CREATE OR REPLACE VIEW P1VTXEDW.VUL_QUOTATIONACCT_01 (
  ACCOUNT_NUM,
  ACCOUNT_MODIFIER_NUM,
  QUOTATION_ID,
  ACCOUNT_QUOTE_ROLE_CD)
AS SELECT
  AGMNT.ACCOUNT_NUM AS ACCOUNT_NUM,
  AGMNT.ACCOUNT_MODIFIER_NUM AS ACCOUNT_MODIFIER_NUM,
  --     ,CAST(BKEY_QUO.EDW_KEY AS INTEGER) AS QUOTATION_ID << mig orig--
  CAST(BKEY_QUO.EDW_KEY AS INT) AS QUOTATION_ID,
  CAST(M00650.EDW_CODE AS SMALLINT) AS ACCOUNT_QUOTE_ROLE_CD
FROM
  P1VSTEDW.LEAD_UL_LN_1_0 AS LOAN
  INNER JOIN P1VSTEDW.LEAD_UL_APPLICATION_1_0 AS APP ON APP.PZINSKEY = LOAN.PZINSKEY
  INNER JOIN P1VTTEDW.AGREEMENT AS AGMNT ON LOAN.CONTRACTNO = AGMNT.ACCOUNT_NUM
  AND Agmnt.Account_Modifier_Num = 'B2K01'
  AND Agmnt.RECORD_DELETED_FLAG = 0 --      AND Agmnt.END_DT = DATE'9999-12-31' << mig orig--
  AND Agmnt.END_DT = '9999-12-31'
  INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC AS AGMTC ON AGMNT.ACCOUNT_NUM = AGMTC.ACCOUNT_NUM
  AND AGMNT.ACCOUNT_MODIFIER_NUM = AGMTC.ACCOUNT_MODIFIER_NUM
  AND AGMTC.AGREEMENT_CLASSIFICATION_CD = 16
  AND AGMTC.AGREEMENT_CLASS_VALUE_CD IN ('1', '2', '3')
  AND AGMTC.RECORD_DELETED_FLAG = 0 --      AND AGMTC.END_DT = DATE'9999-12-31' << mig orig--
  AND AGMTC.END_DT = '9999-12-31'
  LEFT OUTER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY_QUO ON BKEY_QUO.SOURCE_KEY = LOAN.BKEY_QUOTATION_088_001
  CROSS JOIN P1VUTEDW.M00650_ACCT_QUOTE_ROLE AS M00650
WHERE
  M00650.SOURCE_KEY = 'CREDIT CARD ACCOUNT'
  AND M00650.SOURCE_ID = '1'
  AND M00650.SRC_CTL_ID = '024'
  AND COALESCE(APP.ApplicationID, '') <> ''
  AND APP.pyStatusWork <> 'Indexing-Duplicate'
  AND COALESCE(LOAN.ContractNo, '') <> ''
  AND LOAN.ProductGroup IN ('CC', 'SPC')
UNION ALL
  --------------------------------------------------------------------
  -- >> VUL_QUOTATIONACCT_02
  --------------------------------------------------------------------
SELECT
  AGMNT.ACCOUNT_NUM AS ACCOUNT_NUM,
  AGMNT.ACCOUNT_MODIFIER_NUM AS ACCOUNT_MODIFIER_NUM,
  --     ,CAST(BKEY_QUO.EDW_KEY AS INTEGER) AS QUOTATION_ID << mig orig--
  CAST(BKEY_QUO.EDW_KEY AS INT) AS QUOTATION_ID,
  CAST(M00650.EDW_CODE AS SMALLINT) AS ACCOUNT_QUOTE_ROLE_CD
FROM
  P1VSTEDW.LEAD_UL_LN_1_0 AS LOAN
  INNER JOIN P1VSTEDW.LEAD_UL_APPLICATION_1_0 AS APP ON APP.PZINSKEY = LOAN.PZINSKEY
  INNER JOIN P1VTTEDW.AGREEMENT AS AGMNT ON LOAN.CONTRACTNO = AGMNT.BASE_ACCOUNT_NUM
  AND Agmnt.Account_Modifier_Num = 'AM14'
  AND Agmnt.RECORD_DELETED_FLAG = 0 --      AND Agmnt.END_DT = DATE'9999-12-31' << mig orig--
  AND Agmnt.END_DT = '9999-12-31'
  INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC AS AGMTC ON AGMNT.ACCOUNT_NUM = AGMTC.ACCOUNT_NUM
  AND AGMNT.ACCOUNT_MODIFIER_NUM = AGMTC.ACCOUNT_MODIFIER_NUM
  AND AGMTC.AGREEMENT_CLASSIFICATION_CD = 16
  AND AGMTC.AGREEMENT_CLASS_VALUE_CD IN ('1', '2', '3')
  AND AGMTC.RECORD_DELETED_FLAG = 0 --      AND AGMTC.END_DT = DATE'9999-12-31' << mig orig--
  AND AGMTC.END_DT = '9999-12-31'
  LEFT JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY_QUO ON BKEY_QUO.SOURCE_KEY = LOAN.BKEY_QUOTATION_088_001
  CROSS JOIN P1VUTEDW.M00650_ACCT_QUOTE_ROLE AS M00650
WHERE
  M00650.SOURCE_KEY = 'Speedy Loan ACCOUNT'
  AND M00650.SOURCE_ID = '1'
  AND M00650.SRC_CTL_ID = '024'
  AND COALESCE(APP.ApplicationID, '') <> ''
  AND APP.pyStatusWork <> 'Indexing-Duplicate'
  AND COALESCE(LOAN.ContractNo, '') <> ''
  AND LOAN.ProductGroup = 'SPL'
UNION ALL
  --------------------------------------------------------------------
  -- >> VUL_QUOTATIONACCT_03
  --------------------------------------------------------------------

SELECT
  AGMNT.ACCOUNT_NUM AS ACCOUNT_NUM,
  AGMNT.ACCOUNT_MODIFIER_NUM AS ACCOUNT_MODIFIER_NUM,
  --     ,CAST(BKEY_QUO.EDW_KEY AS INTEGER) AS QUOTATION_ID << mig orig--
  CAST(BKEY_QUO.EDW_KEY AS INT) AS QUOTATION_ID,
  CAST(M00650.EDW_CODE AS SMALLINT) AS ACCOUNT_QUOTE_ROLE_CD
FROM
  P1VSTEDW.LEAD_UL_LN_1_0 AS LOAN
  INNER JOIN P1VSTEDW.LEAD_UL_APPLICATION_1_0 AS APP ON APP.PZINSKEY = LOAN.PZINSKEY
  -- INNER JOIN P1VSTEDW.LEAD_UL_LN_BANKACC_1_0 AS BANK ON BANK.PZINSKEY = LOAN.PZINSKEY
  INNER JOIN (SELECT FORMAT_NUMBER_TD(ACCOUNTNUMBER, '####################', 20, 'Y') AS ACCOUNTNUMBER_FORMATTED, * FROM P1VSTEDW.LEAD_UL_LN_BANKACC_1_0) AS BANK ON BANK.PZINSKEY = LOAN.PZINSKEY
  AND BANK.Loans_id = LOAN.Loans_id
  INNER JOIN P1VTTEDW.AGREEMENT AS AGMNT --    ON CAST(CAST(BANK.ACCOUNTNUMBER AS FORMAT 'Z(20)') AS VARCHAR(20)) = AGMNT.BASE_ACCOUNT_NUM << mig orig--
  -- ON CAST(CAST(BANK.ACCOUNTNUMBER AS INT) AS VARCHAR(20)) = AGMNT.BASE_ACCOUNT_NUM
  ON BANK.ACCOUNTNUMBER_FORMATTED = AGMNT.BASE_ACCOUNT_NUM
  AND Agmnt.Account_Modifier_Num IN ('ST14', 'IM14')
  AND Agmnt.RECORD_DELETED_FLAG = 0 --      AND Agmnt.END_DT = DATE'9999-12-31' << mig orig--
  AND Agmnt.END_DT = '9999-12-31'
  INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC AS AGMTC ON AGMNT.ACCOUNT_NUM = AGMTC.ACCOUNT_NUM
  AND AGMNT.ACCOUNT_MODIFIER_NUM = AGMTC.ACCOUNT_MODIFIER_NUM
  AND AGMTC.AGREEMENT_CLASSIFICATION_CD = 16
  AND AGMTC.AGREEMENT_CLASS_VALUE_CD IN ('1', '2', '3')
  AND AGMTC.RECORD_DELETED_FLAG = 0 --      AND AGMTC.END_DT = DATE'9999-12-31' << mig orig--
  AND AGMTC.END_DT = '9999-12-31'
  LEFT JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY_QUO ON BKEY_QUO.SOURCE_KEY = LOAN.BKEY_QUOTATION_088_001
  CROSS JOIN P1VUTEDW.M00650_ACCT_QUOTE_ROLE AS M00650
WHERE
  M00650.SOURCE_KEY = 'Payment Deposit Account'
  AND M00650.SOURCE_ID = '1'
  AND M00650.SRC_CTL_ID = '024'
  AND COALESCE(APP.ApplicationID, '') <> ''
  AND APP.pyStatusWork <> 'Indexing-Duplicate'
  AND COALESCE(BANK.ACCOUNTNUMBER, '') <> ''
  AND BANK.Category = 'DirectDebit'
