CREATE OR REPLACE VIEW P1VSGMF.GN_BPTRN_1_0 (
  EDW_RECORD_NO,
  BP_TO_ACCOUNT_NUMBER,
  BP_TRAN_DATE,
  BP_TRAN_TIME,
  BP_REFERENCE_1,
  BP_CUST_NO_REF_2,
  BP_TERM_ID,
  BP_CHANNEL_CODE,
  BP_CONTROL_ID,
  BP_TRAN_SERIAL,
  BP_WORK_ID,
  BP_TRAN_CODE,
  BP_TELLER_ID,
  BP_AUTH_ID,
  BP_AUTH_LEVEL,
  BP_FLAG,
  BP_PROCESSING_BRANCH,
  BP_BRANCH_CODE,
  BP_CHEQUE_NUMBER,
  BP_BANK_CODE,
  BP_PAYMENT_DATE,
  BP_VALUE_DATE,
  BP_TYPE,
  BP_FROM_ACCOUNT,
  BP_SEQUENCE_NO,
  BP_CUSTOMER_NAME,
  BP_AMOUNT,
  BP_COMMISSION,
  BP_PAYMENT_BY,
  BP_REFERENCE_3,
  BP_CHRG_TYPE,
  BP_SCHEDULE_GEN,
  BP_VENDOR_BUSI_TYPE,
  BP_VENDOR_KEY,
  BP_FROM_AC_BR_CODE,
  BP_REV_DEL_FLAG,
  BP_NEXT_DAY_FLAG,
  BP_RECONCILE_REFID,
  BP_CD_APPV_CODE,
  BP_B2K_TRN_REF_NO,
  BP_B2K_TRN_TRACE_NO,
  BP_ORG_TRAN_DATE,
  BP_ORG_TRAN_TIME,
  START_DT,
  END_DT,
  RECORD_DELETED_FLAG,
  CTL_ID,
  INS_PROC_NAME,
  INS_TXF_BATCHID,
  UPD_PROC_NAME,
  UPD_TXF_BATCHID,
  BP_SENDING_BANK,
  TRANSACTION_DATE)
AS select
STGMERGE.EDW_RECORD_NO
,STGMERGE.BP_TO_ACCOUNT_NUMBER
,COALESCE(CC.DEFAULT_DATE, to_date('1000-01-03' , 'yyyy-MM-dd')) AS BP_TRAN_DATE /*D1*/ /* transaction_date */
,STGMERGE.BP_TRAN_TIME
,STGMERGE.BP_REFERENCE_1
,STGMERGE.BP_CUST_NO_REF_2
,STGMERGE.BP_TERM_ID
,STGMERGE.BP_CHANNEL_CODE
,STGMERGE.BP_CONTROL_ID
,STGMERGE.BP_TRAN_SERIAL
,STGMERGE.BP_WORK_ID
,STGMERGE.BP_TRAN_CODE
,STGMERGE.BP_TELLER_ID
,STGMERGE.BP_AUTH_ID
,STGMERGE.BP_AUTH_LEVEL
,STGMERGE.BP_FLAG
,STGMERGE.BP_PROCESSING_BRANCH
,STGMERGE.BP_BRANCH_CODE
,STGMERGE.BP_CHEQUE_NUMBER
,STGMERGE.BP_BANK_CODE
,STGMERGE.BP_PAYMENT_DATE /*D2*/
,STGMERGE.BP_VALUE_DATE /*D3*/
,STGMERGE.BP_TYPE
,STGMERGE.BP_FROM_ACCOUNT
,STGMERGE.BP_SEQUENCE_NO
,STGMERGE.BP_CUSTOMER_NAME
,STGMERGE.BP_AMOUNT
,STGMERGE.BP_COMMISSION
,STGMERGE.BP_PAYMENT_BY
,STGMERGE.BP_REFERENCE_3
,STGMERGE.BP_CHRG_TYPE
,STGMERGE.BP_SCHEDULE_GEN
,STGMERGE.BP_VENDOR_BUSI_TYPE
,STGMERGE.BP_VENDOR_KEY
,STGMERGE.BP_FROM_AC_BR_CODE
,STGMERGE.BP_REV_DEL_FLAG
,STGMERGE.BP_NEXT_DAY_FLAG
,STGMERGE.BP_RECONCILE_REFID
,STGMERGE.BP_CD_APPV_CODE
,STGMERGE.BP_B2K_TRN_REF_NO
,STGMERGE.BP_B2K_TRN_TRACE_NO
,STGMERGE.BP_ORG_TRAN_DATE
,STGMERGE.BP_ORG_TRAN_TIME
,STGMERGE.START_DT
,STGMERGE.END_DT
,STGMERGE.RECORD_DELETED_FLAG
,STGMERGE.CTL_ID
,STGMERGE.INS_PROC_NAME
,STGMERGE.INS_TXF_BATCHID
,STGMERGE.UPD_PROC_NAME
,STGMERGE.UPD_TXF_BATCHID
,STGMERGE.BP_SENDING_BANK
,COALESCE(DEFAULT_DATE,to_date('1000-01-03' , 'yyyy-MM-DD')) AS TRANSACTION_DATE
FROM p1dutedw.CHAR_CALENDAR as CC

RIGHT OUTER JOIN
(
SELECT EDW_RECORD_NO
,BP_TO_ACCOUNT_NUMBER
,BP_TRAN_DATE /* transaction_date */
,BP_TRAN_TIME
,BP_REFERENCE_1
,BP_CUST_NO_REF_2
,BP_TERM_ID
,BP_CHANNEL_CODE
,BP_CONTROL_ID
,BP_TRAN_SERIAL
,BP_WORK_ID
,BP_TRAN_CODE
,BP_TELLER_ID
,BP_AUTH_ID
,BP_AUTH_LEVEL
,BP_FLAG
,BP_PROCESSING_BRANCH
,BP_BRANCH_CODE
,BP_CHEQUE_NUMBER
,BP_BANK_CODE
,COALESCE(CDT2.DEFAULT_DATE, to_date('1000-01-03' , 'yyyy-MM-dd')) AS BP_PAYMENT_DATE /*D2*/
,COALESCE(CDT3.DEFAULT_DATE, to_date('1000-01-03' , 'yyyy-MM-dd')) AS BP_VALUE_DATE /*D3*/
,BP_TYPE
,BP_FROM_ACCOUNT
,BP_SEQUENCE_NO
,BP_CUSTOMER_NAME
,BP_AMOUNT
,BP_COMMISSION
,BP_PAYMENT_BY
,BP_REFERENCE_3
,BP_CHRG_TYPE
,BP_SCHEDULE_GEN
,BP_VENDOR_BUSI_TYPE
,BP_VENDOR_KEY
,BP_FROM_AC_BR_CODE
,BP_REV_DEL_FLAG
,BP_NEXT_DAY_FLAG
,BP_RECONCILE_REFID
,BP_CD_APPV_CODE
,BP_B2K_TRN_REF_NO
,BP_B2K_TRN_TRACE_NO
,BP_ORG_TRAN_DATE
,BP_ORG_TRAN_TIME
,START_DT
,END_DT
,RECORD_DELETED_FLAG
,CTL_ID
,INS_PROC_NAME
,INS_TXF_BATCHID
,UPD_PROC_NAME
,UPD_TXF_BATCHID
,BP_SENDING_BANK

FROM	P1DSGEDW.GN_BPTRN_1_0_T1 as T1
LEFT OUTER JOIN p1dutedw.CHAR_CALENDAR AS CDT2
ON     COALESCE(T1.BP_PAYMENT_DATE,'NA') = CDT2.CDT_YYMMDD
LEFT OUTER JOIN p1dutedw.CHAR_CALENDAR AS CDT3
ON     COALESCE(T1.BP_VALUE_DATE,'NA') = CDT3.CDT_YYMMDD
) STGMERGE

ON COALESCE(STGMERGE.BP_TRAN_DATE,'NA') = CC.CDT_YYMMDD
