CREATE OR REPLACE VIEW P1VEUIPS.VIPS_CUSTOC (
  CUSTOMERID,
  ACCTID,
  ACCTTYPE,
  CUST_NO_RM,
  OC_CODE)
AS SELECT
CUSTOMERID,
ACCTID,
ACCTTYPE,
CUST_NO_RM,
OC_CODE FROM (
SELECT
CAST(ACT_PROF.CUSTOMERID AS VARCHAR(32)) AS CUSTOMERID,
CAST(ACT_PROF.ACCTID AS VARCHAR(35)) AS ACCTID,
CAST(TRIM(ACT_PROF.ACCTTYPE) AS VARCHAR(10)) AS ACCTTYPE,
CAST(PARTIDEN.PARTY_IDENTIFICATION_NUM AS VARCHAR(30)) AS CUST_NO_RM,
CAST(FININSINTORG_BR.ORGANIZATION_NUM AS VARCHAR(4)) AS OC_CODE
 
FROM P1DPYIPS.S1_ACT_PROF AS ACT_PROF

CROSS JOIN P1VTPIPS.VIPS_BUSINESSDATE_D AS BD

LEFT OUTER JOIN 
(
        SELECT  ESL_AGMT.OC_CODE,
        ESL_AGMT.BASE_ACCT_NUM,
        ESL_AGMT.PRIM_CUST_ID
        FROM P1VTTEDW.EDW_AGREEMENT_INFO AS ESL_AGMT
        
        INNER JOIN P1VTPIPS.VIPS_BUSINESSDATE_D AS BD
        ON ESL_AGMT.AS_OF_DT=BD.BUSINESSDATE
        AND ESL_AGMT.AGMT_CTL_ID IN ('002','003')
        AND ESL_AGMT.AGMT_LEVEL_CD IN (1,2,3)
        AND ESL_AGMT.ACCOUNT_MODIFIER_NUM IN ('ST14','IM14')

) AS ESL_AGMT
ON UPPER(RTRIM(ESL_AGMT.BASE_ACCT_NUM))=UPPER(RTRIM(ACT_PROF.ACCTID))

LEFT OUTER JOIN 
(
        SELECT  PARTIDEN.PARTY_ID,
        PARTIDEN.PARTY_IDENTIFICATION_NUM
        FROM P1VTTEDW.PARTY_IDENTIFICATION AS PARTIDEN
        
        INNER JOIN P1VTPIPS.VIPS_BUSINESSDATE_D AS BD
        ON  PARTIDEN.CTL_ID='001'
        AND PARTIDEN.PARTY_IDENTIFICATION_TYPE_CD=12    -----[CS023900:RM KEY NUM] 
        AND BD.BUSINESSDATE BETWEEN PARTIDEN.START_DT AND PARTIDEN.END_DT
        AND PARTIDEN.RECORD_DELETED_FLAG=0
) AS PARTIDEN
ON PARTIDEN.PARTY_ID=ESL_AGMT.PRIM_CUST_ID

LEFT OUTER JOIN P1VTTEDW.PARTY_PARTY_RELATIONSHIP_HIST AS PARPARRELHST
ON PARPARRELHST.RELATES_PARTY_ID = ESL_AGMT.PRIM_CUST_ID
AND BD.BUSINESSDATE BETWEEN PARPARRELHST.START_DT AND PARPARRELHST.END_DT
AND PARPARRELHST.RECORD_DELETED_FLAG = 0
AND PARPARRELHST.CTL_ID = '001'
AND PARPARRELHST.PARTY_RELATIONSHIP_ROLE_CD = 101   -- [CS024401: OC]

LEFT OUTER JOIN P1VTTEDW.FINANCIAL_INST_INT_ORG AS FININSINTORG_BR
ON FININSINTORG_BR.INTERNAL_ORG_PARTY_ID = PARPARRELHST.RELATED_PARTY_ID
AND BD.BUSINESSDATE BETWEEN FININSINTORG_BR.START_DT AND FININSINTORG_BR.END_DT
AND FININSINTORG_BR.RECORD_DELETED_FLAG = 0
AND FININSINTORG_BR.CTL_ID = '006'
)
GROUP BY CUSTOMERID,ACCTID,ACCTTYPE,CUST_NO_RM,OC_CODE 
QUALIFY RANK() OVER ( 
PARTITION BY 
UPPER(CUSTOMERID),UPPER(ACCTID),UPPER(ACCTTYPE),UPPER(CUST_NO_RM),UPPER(OC_CODE)
ORDER BY
CUSTOMERID,ACCTID,ACCTTYPE,CUST_NO_RM,OC_CODE
) = 1
