CREATE OR REPLACE VIEW P1VSGEDW.ESN_EVENT_LOG_1_0_T3 (
  EDW_RECORD_NO,
  USERID,
  ESN_DATE,
  ESN_TIME,
  CHANNEL,
  IP,
  EVENT_CODE,
  LANG,
  REFERENCE,
  ACC_FROM,
  ACC_TO,
  AMOUNT,
  RUN_NO,
  RESPONSE_CODE,
  FEE_INTER,
  FEE_3RD,
  FEE_CUR,
  FEE4,
  FEE5,
  INFORMATION1,
  INFORMATION2,
  INFORMATION3,
  INFORMATION4,
  INFORMATION5,
  RUN_ID,
  CARD_NO,
  START_DT,
  END_DT,
  RECORD_DELETED_FLAG,
  CTL_ID,
  INS_PROC_NAME,
  INS_TXF_BATCHID,
  UPD_PROC_NAME,
  UPD_TXF_BATCHID)
AS SELECT
EDW_RECORD_NO
,USERID
,ESN_DATE
, ESN_TIME
,CHANNEL
,IP
,EVENT_CODE
,LANG
,REFERENCE
,ACC_FROM
,ACC_TO
,AMOUNT
,RUN_NO
,RESPONSE_CODE
,FEE_INTER
,FEE_3RD
,FEE_CUR
,FEE4
,FEE5
,INFORMATION1
,INFORMATION2
,INFORMATION3
,INFORMATION4
,INFORMATION5
,RUN_ID
,CARD_NO
,START_DT
,END_DT
,RECORD_DELETED_FLAG
,CTL_ID
,INS_PROC_NAME
,INS_TXF_BATCHID
,UPD_PROC_NAME
,UPD_TXF_BATCHID
 FROM (
SELECT 
EDW_RECORD_NO
,USERID
,ESN_DATE
,CAST(  (CASE WHEN SUBSTR(ESN_T1,1,2) BETWEEN '00' AND '23' THEN SUBSTR(ESN_T1,1,2) ELSE '23' END)||':'
                 ||(CASE WHEN SUBSTR(ESN_T1,4,2) BETWEEN '00' AND '59' THEN SUBSTR(ESN_T1,4,2) ELSE '59' END)||':'
                 ||(CASE WHEN SUBSTR(ESN_T1,7,2) BETWEEN '00' AND '59' THEN SUBSTR(ESN_T1,7,2) ELSE '59' END)  AS TIMESTAMP)
ESN_TIME
,CHANNEL
,IP
,EVENT_CODE
,LANG
,REFERENCE
,ACC_FROM
,ACC_TO
,AMOUNT
,RUN_NO
,RESPONSE_CODE
,FEE_INTER
,FEE_3RD
,FEE_CUR
,FEE4
,FEE5
,INFORMATION1
,INFORMATION2
,INFORMATION3
,INFORMATION4
,INFORMATION5
,RUN_ID
,CARD_NO
,START_DT
,END_DT
,RECORD_DELETED_FLAG
,CTL_ID
,INS_PROC_NAME
,INS_TXF_BATCHID
,UPD_PROC_NAME
,UPD_TXF_BATCHID

FROM
(SELECT
A.EDW_RECORD_NO
,A.USERID
,A.ESN_DATE
, CAST (CASE WHEN (TRIM(A.esn_time)) = '' THEN '00:00:00'
           ELSE 
                       CASE WHEN CHAR_LENGTH(A.esn_time) = 5 THEN '0'||SUBSTR(A.esn_time,1,1)||':'||SUBSTR(A.esn_time,2,2)||':'||(CASE WHEN SUBSTR(A.esn_time,4,2) > '59' THEN '59' ELSE SUBSTR(A.esn_time,4,2) END) 
                       ELSE 
                                  CASE WHEN CHAR_LENGTH(A.esn_time) = 4 THEN SUBSTR(A.esn_time,1,2)||':'||SUBSTR(A.esn_time,3,2)||':00' 
                                  ELSE  CASE WHEN SUBSTR(A.esn_time,2,1) = ':' THEN '0' || SUBSTR(A.esn_time,1,1) || ':0' || SUBSTR(A.esn_time,3,1) || ':' || (CASE WHEN SUBSTR(A.esn_time,5,2) > '59' THEN '59' ELSE SUBSTR(A.esn_time,5,2) END) 
                                                 ELSE CASE WHEN CHAR_LENGTH(A.esn_time) = 6 THEN SUBSTR(A.esn_time,1,2) ||':'||SUBSTR(A.esn_time,3,2)||':'||(CASE WHEN SUBSTR(A.esn_time,5,2) > '59' THEN '59' ELSE SUBSTR(A.esn_time,5,2) END) 
                                                               ELSE '00:00:00' END
                                                 END
                                   END
                        END
            END  AS VARCHAR(8) ) AS ESN_T1
,A.CHANNEL
,A.IP
,A.EVENT_CODE
,A.LANG
,A.REFERENCE
,A.ACC_FROM
,A.ACC_TO
,A.AMOUNT
,A.RUN_NO
,A.RESPONSE_CODE
,A.FEE_INTER
,A.FEE_3RD
,A.FEE_CUR
,A.FEE4
,A.FEE5
,A.INFORMATION1
,A.INFORMATION2
,A.INFORMATION3
,A.INFORMATION4
,A.INFORMATION5
,A.RUN_ID
,A.CARD_NO
,A.START_DT
,A.END_DT
,A.RECORD_DELETED_FLAG
,A.CTL_ID
,A.INS_PROC_NAME
,A.INS_TXF_BATCHID
,A.UPD_PROC_NAME
,A.UPD_TXF_BATCHID
FROM P1VSGEDW.ESN_EVENT_LOG_1_0_T1 A

INNER JOIN P1VSGEDW.ESN_EVENT_CODE_1_0 B
ON A.EVENT_CODE = B.EVENT_CODE

WHERE B.Transaction_Type = 'FINANCIAL'
) AS SRC
) C
