CREATE OR REPLACE VIEW P1VTPBIT.VBI_DIM_DATE (
  Dt_Id,
  CAL_YEAR,
  CAL_HALF_YEAR,
  CAL_QUARTER,
  CAL_MONTH,
  CAL_WEEK,
  CAL_DT,
  DAY_OF_WEEK,
  MONTH_EN,
  MONTH_TH,
  MONTH_EN_ABV,
  MONTH_TH_ABV,
  QR_YEAR,
  WEEK_IN_MONTH,
  WEEK_NAME,
  YEAR_SEQ,
  HALF_YEAR_SEQ,
  QUARTER_SEQ,
  MONTH_SEQ,
  WEEK_SEQ,
  DAY_SEQ,
  WORKING_DAY_SEQ,
  LAST_DAY_OF_YEAR,
  LAST_DAY_OF_HALF_YEAR,
  LAST_DAY_OF_QUARTER,
  LAST_DAY_OF_MONTH,
  LAST_DAY_OF_WEEK,
  WORKING_DAY_FLAG,
  LAST_WORKING_DAY_OF_MONTH,
  START_MONTH_DT_ID,
  END_MONTH_DT_ID,
  START_MONTH_DT,
  END_MONTH_DT,
  START_QUARTER_DT_ID,
  END_QUARTER_DT_ID,
  START_QUARTER_DT,
  END_QUARTER_DT)
AS SELECT       
      CAST(CAST(DATE_FORMAT(CALENDAR_DATE , 'yyyyMMdd') AS CHAR(8)) AS INT) AS Dt_Id
      ,CAST(YEAR_OF_CALENDAR AS SMALLINT) AS CAL_YEAR
      ,CAST((CAST((MONTH_OF_YEAR + 5) AS DECIMAL(38,18))/6) AS SMALLINT) AS CAL_HALF_YEAR
      ,CAST(QUARTER_OF_YEAR AS SMALLINT) AS CAL_QUARTER
      ,CAST(MONTH_OF_YEAR AS SMALLINT) AS CAL_MONTH
      ,CAST(WEEK_OF_YEAR+1 AS SMALLINT) AS CAL_WEEK
      ,CALENDAR_DATE AS CAL_DT
      ,DAY_OF_WEEK AS DAY_OF_WEEK 
      ,CAST(CAST(DATE_FORMAT(CALENDAR_DATE , 'MMMM') AS CHAR(9)) AS VARCHAR(20)) AS MONTH_EN
      ,CAST(
                        CASE    WHEN MONTH_OF_YEAR = 1  THEN 'มกราคม' --_UNICODE '0E210E010E230E320E040E21'XCV
                                WHEN    MONTH_OF_YEAR = 2  THEN 'กุมภาพันธ์' --_UNICODE '0E010E380E210E200E320E1E0E310E190E180E4C'XCV
                                WHEN    MONTH_OF_YEAR = 3  THEN 'มีนาคม'  --_UNICODE '0E210E350E190E320E040E21'XCV
                                WHEN    MONTH_OF_YEAR = 4  THEN 'เมษายน' --_UNICODE '0E400E210E290E320E220E19'XCV
                                WHEN    MONTH_OF_YEAR = 5  THEN 'พฤษภาคม' --_UNICODE '0E1E0E240E290E200E320E040E21'XCV
                                WHEN    MONTH_OF_YEAR = 6  THEN 'มิถุนายน' --_UNICODE '0E210E340E160E380E190E320E220E19'XCV
                                WHEN    MONTH_OF_YEAR = 7  THEN 'กรกฏาคม'--_UNICODE '0E010E230E010E0F0E320E040E21'XCV
                                WHEN    MONTH_OF_YEAR = 8  THEN 'สิงหาคม' --_UNICODE '0E2A0E340E070E2B0E320E040E21'XCV
                                WHEN    MONTH_OF_YEAR = 9  THEN 'กันยายน' --_UNICODE '0E010E310E190E220E320E220E19'XCV
                                WHEN    MONTH_OF_YEAR = 10 THEN 'ตุลาคม' --_UNICODE '0E150E380E250E320E040E21'XCV
                                WHEN    MONTH_OF_YEAR = 11 THEN 'พฤศจิกายน'--_UNICODE '0E1E0E240E280E080E340E010E320E220E19'XCV
                                WHEN    MONTH_OF_YEAR = 12 THEN 'ธันวาคม'--_UNICODE '0E180E310E190E270E320E040E21'XCV
                        END     AS VARCHAR(20)) AS MONTH_TH
      ,CAST(CAST(DATE_FORMAT(CALENDAR_DATE ,'MMM') AS CHAR(3)) AS VARCHAR(20)) AS MONTH_EN_ABV
      ,CAST(
                        CASE    WHEN MONTH_OF_YEAR = 1  THEN 'ม.ค.' --_UNICODE '0E21002E0E04002E'XCV
                                WHEN    MONTH_OF_YEAR = 2  THEN 'ก.พ.' --_UNICODE '0E01002E0E1E002E'XCV
                                WHEN    MONTH_OF_YEAR = 3  THEN 'มี.ค.' --_UNICODE '0E210E35002E0E04002E'XCV
                                WHEN    MONTH_OF_YEAR = 4  THEN 'เม.ย.'--_UNICODE '0E400E21002E0E22002E'XCV
                                WHEN    MONTH_OF_YEAR = 5  THEN 'พ.ค.'--_UNICODE '0E1E002E0E04002E'XCV
                                WHEN    MONTH_OF_YEAR = 6  THEN 'มิ.ย.'--_UNICODE '0E210E34002E0E22002E'XCV
                                WHEN    MONTH_OF_YEAR = 7  THEN 'ก.ค.'--_UNICODE '0E01002E0E04002E'XCV
                                WHEN    MONTH_OF_YEAR = 8  THEN 'ส.ค.'--_UNICODE '0E2A002E0E04002E'XCV
                                WHEN    MONTH_OF_YEAR = 9  THEN 'ก.ย'--_UNICODE '0E01002E0E22'XCV
                                WHEN    MONTH_OF_YEAR = 10 THEN 'ต.ค.'--_UNICODE '0E15002E0E04002E'XCV
                                WHEN    MONTH_OF_YEAR = 11 THEN 'พ.ย.'--_UNICODE '0E1E002E0E22002E'XCV
                                WHEN    MONTH_OF_YEAR = 12 THEN 'ธ.ค.'--_UNICODE '0E18002E0E04002E'XCV
                        END     AS VARCHAR(20)) AS MONTH_TH_ABV
      ,CAST('Q'||TRIM(QUARTER_OF_YEAR)||'/'||TRIM(YEAR_OF_CALENDAR) AS VARCHAR(20)) AS QR_YEAR
      ,WEEK_OF_MONTH+1 AS WEEK_IN_MONTH
      ,CAST('WEEK 0'||TRIM(WEEK_OF_MONTH+1) AS VARCHAR(20)) AS WEEK_NAME
      ,YEAR_OF_CALENDAR-1899 AS YEAR_SEQ
    --   ,((CALENDAR_DATE % 10000)/100 + 5) / 6 + 2 * CALENDAR_DATE/10000 AS HALF_YEAR_SEQ
          ,CAST(CAST((MONTH(CALENDAR_DATE) + 5) AS DECIMAL(38,18)) / 6 + 2 * CAST((YEAR(CALENDAR_DATE)-1900) AS DECIMAL(38,18)) AS INT) AS HALF_YEAR_SEQ
      ,QUARTER_OF_CALENDAR AS QUARTER_SEQ
      ,MONTH_OF_CALENDAR AS MONTH_SEQ 
      ,WEEK_OF_CALENDAR+1 AS WEEK_SEQ
      ,DAY_OF_CALENDAR AS DAY_SEQ
      ,
CASE    WHEN (CAST(
CASE    WHEN HOLIDAY_DT IS NOT NULL THEN 'N'
                
        WHEN    DAY_OF_WEEK NOT IN (7,1) THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1))) = 'N' THEN NULL
                
ELSE    ROW_NUMBER() OVER(PARTITION BY (CAST(
CASE    WHEN HOLIDAY_DT IS NOT NULL THEN 'N'
                
        WHEN    DAY_OF_WEEK NOT IN (7,1) THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1))) 
ORDER   BY CALENDAR_DATE ASC) 
       
END     AS WORKING_DAY_SEQ
      ,CAST(
CASE    WHEN CALENDAR_DATE = TRIM(YEAR_OF_CALENDAR)||'-12-31' THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1)) AS LAST_DAY_OF_YEAR
      ,CAST(
CASE    WHEN TRIM(EXTRACT(MONTH FROM CALENDAR_DATE))||TRIM(EXTRACT(DAY FROM CALENDAR_DATE)) IN ('630',
                '1231') THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1)) AS LAST_DAY_OF_HALF_YEAR
      ,CAST(
CASE    WHEN CALENDAR_DATE = (ADD_MONTHS(TO_DATE(TRIM(YEAR_OF_CALENDAR)||'-'||
          LPAD(CAST(TRIM(((QUARTER_OF_YEAR - 1) * 3) + 3)AS INT), 2, '0')
          ||'-01'  ,'yyyy-MM-dd'),
                1)-1) THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1)) AS LAST_DAY_OF_QUARTER
      ,CAST(
CASE    WHEN CALENDAR_DATE = (ADD_MONTHS((CALENDAR_DATE - EXTRACT(DAY FROM CALENDAR_DATE)+1),
                1)-1) THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1)) AS LAST_DAY_OF_MONTH
      ,CAST(
CASE    WHEN DAY_OF_WEEK = 7 THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1)) AS LAST_DAY_OF_WEEK
      ,CAST(
CASE    WHEN HOLIDAY_DT IS NOT NULL THEN 'N'
                
        WHEN    DAY_OF_WEEK NOT IN (7,1) THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1))  AS WORKING_DAY_FLAG
      ,CAST(
CASE    WHEN LTWKDY.LAST_WK_DAY IS NOT NULL THEN 'Y' 
ELSE    'N' 
END     AS CHAR(1)) AS LAST_WORKING_DAY_OF_MONTH
       ,CAST(CAST(DATE_FORMAT((CALENDAR_DATE - EXTRACT(DAY FROM CALENDAR_DATE) + 1) , 'yyyyMMdd') AS CHAR(8)) AS INT) AS START_MONTH_DT_ID
       ,CAST(CAST(DATE_FORMAT((ADD_MONTHS((CALENDAR_DATE - EXTRACT(DAY FROM CALENDAR_DATE)+1),
                1)-1) , 'yyyyMMdd') AS CHAR(8)) AS INT) AS END_MONTH_DT_ID
      ,CALENDAR_DATE - EXTRACT(DAY FROM CALENDAR_DATE) + 1 AS START_MONTH_DT
      ,ADD_MONTHS((CALENDAR_DATE - EXTRACT(DAY FROM CALENDAR_DATE)+1),
                1)-1 AS END_MONTH_DT
       ,CAST(CAST(DATE_FORMAT((TO_DATE(TRIM(YEAR_OF_CALENDAR)||'-'||
                LPAD(CAST(TRIM(((QUARTER_OF_YEAR - 1) * 3) + 1) AS INT), 2, '0')
                ||'-01' ,'yyyy-MM-dd')) , 'yyyyMMdd') AS CHAR(8)) AS INT) AS START_QUARTER_DT_ID
       ,CAST(CAST(DATE_FORMAT((ADD_MONTHS(TO_DATE(TRIM(YEAR_OF_CALENDAR)||'-'||
          LPAD(CAST(TRIM(((QUARTER_OF_YEAR - 1) * 3) + 3)AS INT), 2, '0')
          ||'-01'  ,'yyyy-MM-dd'),
                1)-1) , 'yyyyMMdd') AS CHAR(8)) AS INT) AS END_QUARTER_DT_ID
      ,TO_DATE(TRIM(YEAR_OF_CALENDAR)||'-'||
                LPAD(CAST(TRIM(((QUARTER_OF_YEAR - 1) * 3) + 1) AS INT), 2, '0')
                ||'-01' ,'yyyy-MM-dd') AS START_QUARTER_DT
      ,ADD_MONTHS(TO_DATE(TRIM(YEAR_OF_CALENDAR)||'-'||
          LPAD(CAST(TRIM(((QUARTER_OF_YEAR - 1) * 3) + 3)AS INT), 2, '0')
          ||'-01'  ,'yyyy-MM-dd'),
                1)-1 AS END_QUARTER_DT
    
        FROM SYS_CALENDAR.CALENDAR AS CALENDAR

        INNER JOIN P1VTPBIT.VBI_BUSINESSDATE_P AS BD
        ON CALENDAR.CALENDAR_DATE BETWEEN ADD_MONTHS(BD.BUSINESSDATE ,-36) AND ADD_MONTHS(BD.BUSINESSDATE ,18) 
    
    LEFT JOIN P1DPYBIT.BI_SCB_HOLIDY
        ON      CALENDAR_DATE = HOLIDAY_DT
    
    LEFT OUTER JOIN
     (
                SELECT  MAX(CALENDAR_DATE) LAST_WK_DAY  
                FROM    SYS_CALENDAR.CALENDAR LEFT OUTER JOIN P1DPYBIT.BI_SCB_HOLIDY 
                ON      CALENDAR_DATE = HOLIDAY_DT
      
                WHERE   DAY_OF_WEEK NOT IN (7,1)
                AND     HOLIDAY_DT IS NULL
        
                GROUP   BY MONTH_OF_YEAR,YEAR_OF_CALENDAR
        ) LTWKDY 
        ON      CALENDAR_DATE = LAST_WK_DAY
