CREATE OR REPLACE VIEW P1VSGEDW.ESN_SMS_NOTIFICATION_1_0_T1 (
  EDW_RECORD_NO,
  USERID,
  ESN_DATE,
  ESN_TIME,
  ESN_TYPE,
  MOBILE_NO,
  LANG,
  START_DT,
  END_DT,
  RECORD_DELETED_FLAG,
  CTL_ID,
  INS_PROC_NAME,
  INS_TXF_BATCHID,
  UPD_PROC_NAME,
  UPD_TXF_BATCHID)
AS SELECT * FROM P1DSGEDW.ESN_SMS_NOTIFICATION_1_0_T1
