CREATE OR REPLACE VIEW P1VSGEDW.ESN_HISTORY_1_0_T1 (
  EDW_RECORD_NO,
  CUST_ID,
  TRX_STATUS,
  TRX_DATE,
  USERID,
  INFORMATION,
  START_DT,
  END_DT,
  RECORD_DELETED_FLAG,
  CTL_ID,
  INS_PROC_NAME,
  INS_TXF_BATCHID,
  UPD_PROC_NAME,
  UPD_TXF_BATCHID)
AS SELECT * FROM P1DSGEDW.ESN_HISTORY_1_0_T1
