CREATE OR REPLACE VIEW P1VTXEDW.VIM_IMACTM10_ACCOPRODHIST_01 (
  ACCOUNT_NUM,
  ACCOUNT_MODIFIER_NUM,
  PRODUCT_ID,
  AGREEMENT_PRODUCT_ROLE_CD,
  ACCT_PRODUCT_ASSOC_START_DT,
  ACCT_PRODUCT_ASSOC_END_DT)
AS SELECT 
       (TRIM(COALESCE(IMACTM1.WMS_CONTROL_1,'')) ||  TRIM(COALESCE(IMACTM1.WMS_CONTROL_2,'')) ||
       TRIM(COALESCE(IMACTM1.WMS_CONTROL_3,'')) || TRIM(COALESCE(IMACTM1.WMS_CONTROL_4,'')) ||
       TRIM(COALESCE(IMACTM1.WMS_ACCT_NO,''))) AS ACCOUNT_NUM ,
       'IM' ||TRIM(COALESCE(IMACTM1.WMS_CONTROL_1,'')) AS ACCOUNT_MODIFIER_NUM,
       BKEY.EDW_KEY AS PRODUCT_ID,
       BMAP.EDW_CODE AS AGREEMENT_PRODUCT_ROLE_CD,
       TO_DATE('10000101' ,'yyyyMMdd') AS ACCT_PRODUCT_ASSOC_START_DT,
       TO_DATE('99991231' ,'yyyyMMdd') AS ACCT_PRODUCT_ASSOC_END_DT
   
FROM    P1VSTEDW.IM_IMACTM_1_0 AS IMACTM1
       INNER JOIN   P1VUTEDW.BKEY_PRODUCT AS BKEY
    
 ON      (TRIM(COALESCE(IMACTM1.WMS_CONTROL_1,'')) || '_' ||  TRIM(COALESCE(IMACTM1.WMS_CONTROL_2,'')) || '_' || 
       TRIM(COALESCE(IMACTM1.WMS_ACCT_TYPE,''))) || '_' ||  (
     
CASE 
      
 WHEN  
        IMACTM1.WMS_OD_LIMIT = '0'
    
 AND  cast(IMACTM1.WMS_OD_LIMIT_AMT as decimal(15,2)) > 0 THEN 'OD'
      
 ELSE  'CA'  
       
END ) = BKEY.SOURCE_KEY
       CROSS JOIN   P1VUTEDW.M02050_AGREE_PROD_ROLE AS BMAP
       
   
WHERE  
        UPPER(RTRIM(BMAP.SOURCE_KEY)) = UPPER(RTRIM('PRODUCT AGREEMENT'))
    
 AND 
         BMAP.SOURCE_ID = '1'
    
 AND  BMAP.SRC_CTL_ID = '003'
