CREATE OR REPLACE VIEW P1VTXEDW.VLOS_PR10_QUOPROFEATUR_01 (
  QUOTATION_ID,
  PRODUCT_GROUP_ID,
  PRODUCT_GROUP_SEQUENCE_ID,
  QUOTATION_PROD_GRP_START_DT,
  FEATURE_ID,
  QUOTE_PROD_GRP_FEAT_START_DT,
  QUOTE_PROD_GRP_FEAT_CURR_CD,
  QUOTE_PROD_GRP_FEATURE_NUM,
  QUOTE_PROD_GRP_FEATURE_RATE,
  QUOTE_PROD_GRP_FEATURE_AMT,
  QUOTE_PROD_GRP_FEAT_UOM_CD,
  QUOTE_PROD_GRP_FEATURE_TXT)
AS SELECT
         CAST(BKEY.EDW_KEY  AS INT)  AS QUOTATION_ID,
         CAST(BKEY1.EDW_KEY AS INT)  AS PRODUCT_GROUP_ID,
         CAST(PR.ID AS VARCHAR(50)) AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         CAST(BKEY3.EDW_KEY AS INT) AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(
         (CASE 
          WHEN RVWCYCL.USERCODE = 'RC_0001'   THEN '3' 
          WHEN RVWCYCL.USERCODE = 'RC_0002'   THEN '6'
          WHEN RVWCYCL.USERCODE = 'RC_0003'   THEN '1'
          WHEN RVWCYCL.USERCODE = 'RC_0004'   THEN '2'
          WHEN RVWCYCL.USERCODE = 'RC_0005'   THEN '3'      ELSE   '99999'
          END) AS VARCHAR(100)) AS QUOTE_PROD_GRP_FEATURE_NUM,
          FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE,
          CAST(NULL AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         M34400.EDW_CODE AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
      
      
         
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN  P1VSTEDW.LOS_PLPR_TMP_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        LEFT OUTER JOIN P1VSTEDW.LOS_RVWCYCL_1_0 AS RVWCYCL
         ON PR.REVIEWCYCLE_ID = RVWCYCL.ID
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS  BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
         
        LEFT OUTER JOIN P1VUTEDW.BKEY_FEATURE AS BKEY3
         ON BKEY3.SOURCE_KEY = '5_1_Review Cycle_'
     
       CROSS JOIN P1VUTEDW.M34400_UNIT_OF_MEASR AS M34400
       /*
        LEFT OUTER JOIN
        (
         SELECT EDW_CODE,SOURCE_KEY,SRC_CTL_ID,SOURCE_ID
         FROM P1VUTEDW.M34400_UNIT_OF_MEASR
         WHERE  SOURCE_ID = '1'
         AND SRC_CTL_ID = '021'
         ) M34400
         ON M34400.SOURCE_KEY = (CASE WHEN RVWCYCL.USERCODE = 'RC_0001' THEN 'M'
                         WHEN RVWCYCL.USERCODE = 'RC_0002' THEN 'M'
                         ELSE   'Y'
                    END)
        */            
          
        WHERE  COALESCE(PR.REVIEWCYCLE_ID,'') <> '' 
        AND M34400.SOURCE_ID = '1'
        AND M34400.SRC_CTL_ID = '021'
        AND ( (M34400.SOURCE_KEY = 'M' AND RVWCYCL.USERCODE = 'RC_0001')
           OR (M34400.SOURCE_KEY = 'M' AND RVWCYCL.USERCODE = 'RC_0002')
           OR (M34400.SOURCE_KEY = 'Y' AND RVWCYCL.USERCODE NOT IN ('RC_0001','RC_0002')) ) --> PERFORMANCE TUNING
        /*AND M34400.SOURCE_KEY = CASE WHEN RVWCYCL.USERCODE = 'RC_0001' THEN 'M'
                              WHEN RVWCYCL.USERCODE = 'RC_0002' THEN 'M'
                              ELSE   'Y'
                           END*/
        
        UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_02
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         CASE WHEN COALESCE(CURRENCY.USERCODE,'') = ''
            THEN M09700_01.EDW_CODE
            ELSE M09700_02.EDW_CODE
          END AS QUOTE_PROD_GRP_FEAT_CURR_CD,  --> PERFORMANCE TUNING
         CAST(NULL AS VARCHAR(100)) AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE,
         CAST(PR.COMMITMENTAMOUNT AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_TMP_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        LEFT OUTER JOIN P1VSTEDW.LOS_CURRENCY_1_0 AS CURRENCY
         ON PR.CURRENCY_ID = CURRENCY.ID
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_FEATURE AS BKEY3
         ON BKEY3.SOURCE_KEY = '2_1_Credit Limit_'
        
        /*LEFT OUTER JOIN P1VUTEDW.M09700_CRNCY M09700
        ON M09700.SOURCE_KEY =
        CASE WHEN COALESCE(CURRENCY.USERCODE,'') = ''
         THEN '764'
         ELSE CURRENCY.USERCODE
        END
        AND M09700.SOURCE_ID = '1'
        AND M09700.SRC_CTL_ID = '021'*/
        
        CROSS JOIN P1VUTEDW.M09700_CRNCY M09700_01 --> PERFORMANCE TUNING
          
        LEFT OUTER JOIN P1VUTEDW.M09700_CRNCY M09700_02  --> PERFORMANCE TUNING
          ON M09700_02.SOURCE_KEY = CURRENCY.USERCODE
          AND M09700_02.SOURCE_ID = '1'
          AND M09700_02.SRC_CTL_ID = '021'
         
        WHERE  COALESCE(PR.COMMITMENTAMOUNT,'') <> '' 
          AND M09700_01.SOURCE_KEY = '764'
          AND M09700_01.SOURCE_ID = '1'
          AND M09700_01.SRC_CTL_ID = '021'
        
        UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_03
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(REPLACE(PR.PERCENTFEEONUNUSEDPORTION,'%','') AS DECIMAL(18,10)), '0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(REPLACE(PR.PERCENTFEEONUNUSEDPORTION,',','') AS DECIMAL(38,18)), '#.000000000000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(NULL AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_TMP_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        LEFT OUTER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '1_1_Unused Credit Fee_'
         
        WHERE COALESCE(PR.PERCENTFEEONUNUSEDPORTION,'') <> '' 
        
        UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_05
        --------------------------------------------------------------------------
      
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(PR.TERM AS VARCHAR(100)) AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(NULL AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
      
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_TMP_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        LEFT OUTER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY  = '5_1_Maturity Term_'
         
         CROSS JOIN  P1VUTEDW.M34400_UNIT_OF_MEASR AS M34400
         /*
        LEFT OUTER JOIN
        (
         SELECT EDW_CODE,SOURCE_KEY,SRC_CTL_ID,SOURCE_ID
         FROM P1VUTEDW.M34400_UNIT_OF_MEASR
         WHERE  SOURCE_ID = '1'
         AND SRC_CTL_ID = '021'
        )M34400
         ON 'M' = M34400.SOURCE_KEY
         */
         
        WHERE  COALESCE( PR.TERM,'') <> ''
        AND M34400.SOURCE_ID = '1'
        AND M34400.SRC_CTL_ID = '021'
        AND M34400.SOURCE_KEY = 'M'
        
        UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_04
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100)) AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(REPLACE(LEQFT.USERCODE,'%','') AS DECIMAL(18,10)),'0.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(REPLACE(LEQFT.USERCODE,',','') AS DECIMAL(18,10)),'#.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(NULL AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_TMP_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        LEFT OUTER JOIN P1VSTEDW.LOS_LEQFT_1_0 AS LEQFT
         ON PR.LEQFTYPE_ID = LEQFT.ID
        
        LEFT OUTER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
         
        LEFT OUTER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        LEFT OUTER JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON BKEY3.SOURCE_KEY ='1_1_LEQ Factor_'
        
         WHERE  COALESCE(PR.LEQFTYPE_ID,'') <> ''
         
         --BOOKMARK1
         
         /* Khet S. change join to BKEY  to INNER JOIN   -- follow to mapping 2012-03-05 */
  UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_08
        --------------------------------------------------------------------------
        SELECT       
         QUOTATION_ID,
         PRODUCT_GROUP_ID,
         PRODUCT_GROUP_SEQUENCE_ID,
         QUOTATION_PROD_GRP_START_DT,
         FEATURE_ID,
         QUOTE_PROD_GRP_FEAT_START_DT,
         QUOTE_PROD_GRP_FEAT_CURR_CD,
         QUOTE_PROD_GRP_FEATURE_NUM,
         QUOTE_PROD_GRP_FEATURE_RATE,
         QUOTE_PROD_GRP_FEATURE_AMT,
         QUOTE_PROD_GRP_FEAT_UOM_CD,
         QUOTE_PROD_GRP_FEATURE_TXT

        FROM(

        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(PLPR.EXISTINGBALANCE AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
           , RANK( ) OVER (PARTITION BY BKEY.EDW_KEY,BKEY1.EDW_KEY,PR.ID,BKEY3.EDW_KEY
        ORDER  BY PLPR.EXISTINGBALANCE ) AS R 
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        --- Change Condition : Duplicate record source
        INNER JOIN P1VSTEDW.LOS_DL_1_0 AS DL
        ON PLPR.DEAL_ID = DL.ID
        
        INNER JOIN P1VSTEDW.LOS_PRST_1_0 AS PRST
        ON DL.PRODUCTSTATUS_ID = PRST.ID
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '2_1_Existing Balance_'
         
        WHERE COALESCE(PLPR.EXISTINGBALANCE,'') <> ''
        --- Change Condition : Duplicate record source
        AND PRST.USERCODE NOT IN ('WITHDRAW','CANCELLED')
        
        --ORDER BY PR.COMMITMENTAMOUNT DESC  GET record NUMBER 1
        ) AS TMP
        WHERE TMP.R = 1
   
     

  UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_09
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(PR.INSURANCEPREMIUM AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '2_1_Insurance Premium_'
         
        WHERE COALESCE(PR.INSURANCEPREMIUM,'') <> ''


  UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_10
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(PR.COURTFEE AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '2_1_Court Fee_'
         
        WHERE COALESCE(PR.COURTFEE,'') <> ''

  UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_11
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(PR.LAWYERFEE AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '2_1_Lawyer Fee_'
         
        WHERE COALESCE(PR.LAWYERFEE,'') <> ''

  UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_12
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(PR.MISCELLANEOUSEXPENSE AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '2_1_Miscellanous Expenses_'
         
        WHERE COALESCE(PR.MISCELLANEOUSEXPENSE,'') <> ''

  UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_13
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(PR.DEBTORINTEREST AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '2_1_Debtor Interest_'
         
        WHERE COALESCE(PR.DEBTORINTEREST,'') <> ''


  UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_14
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(PR.DEBTORBALANCEOUTSTANDING AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '2_1_Debtor Balance_'
         
        WHERE COALESCE(PR.DEBTORBALANCEOUTSTANDING,'') <> ''


         UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_15
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(PR.DEDUCTIONAMOUNT AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '2_1_Deduction Amount_'
         
        WHERE COALESCE(PR.DEDUCTIONAMOUNT,'') <> ''
         
         
         UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_16
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(NULL AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         CAST(PR.PROJECTNAME AS VARCHAR(250)) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '3_1_Project Name_'
         
        WHERE COALESCE(PR.PROJECTNAME,'') <> ''
        
        UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_17
        --------------------------------------------------------------------------
        
        SELECT
         BKEY.EDW_KEY AS QUOTATION_ID,
         BKEY1.EDW_KEY AS PRODUCT_GROUP_ID,
         PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
         BKEY3.EDW_KEY AS FEATURE_ID,
/*         CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
         TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
         NULL AS QUOTE_PROD_GRP_FEAT_CURR_CD,
         CAST(NULL AS VARCHAR(100))  AS QUOTE_PROD_GRP_FEATURE_NUM,
         FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000')  AS QUOTE_PROD_GRP_FEATURE_RATE
         CAST(NULL AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
         NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
         CAST(date_format(PR.DATECURRENTMATURITY, 'yyyy-MM-dd HH:mm:ss.SSSSSS') as VARCHAR(250)) AS QUOTE_PROD_GRP_FEATURE_TXT -- Change from CAST(PR.DATECURRENTMATURITY AS VARCHAR(250)) AS QUOTE_PROD_GRP_FEATURE_TXT
        
        FROM P1VSTEDW.LOS_PR_1_0 AS PR
        
        INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
         ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
        
        INNER JOIN P1VUTEDW.BKEY_QUOTATION AS BKEY
         ON PLPR.BK_QUOTATION_074_001 = BKEY.SOURCE_KEY
        
        INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKEY1
         ON PR.BK_PRODUCTGROUP_033_001 = BKEY1.SOURCE_KEY
        
        
        INNER  JOIN
        (
         SELECT EDW_KEY,SOURCE_KEY
         FROM P1VUTEDW.BKEY_FEATURE
        )BKEY3
         ON
         BKEY3.SOURCE_KEY = '3_1_Product Maturity Date_'
         
        WHERE PR.DATECURRENTMATURITY  IS NOT NULL OR  PR.DATECURRENTMATURITY  <> ''
  
  -- START COMMENT --> UR : OP63050003
        UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_18
        --------------------------------------------------------------------------
  
  SELECT
  BKDEAL.EDW_KEY AS QUOTATION_ID,
  BKPGPRT.EDW_KEY AS PRODUCT_GROUP_ID,
  PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*  CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
  TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
  BKQUOFEA.EDW_KEY AS FEATURE_ID,
/*  CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
  TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
        CASE WHEN COALESCE(CURRENCY.USERCODE,'') = ''
           THEN M09700_01.EDW_CODE
           ELSE M09700_02.EDW_CODE
         END AS QUOTE_PROD_GRP_FEAT_CURR_CD,  --> PERFORMANCE TUNING
  CAST(NULL AS VARCHAR(100)) AS QUOTE_PROD_GRP_FEATURE_NUM,
  FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE
  CAST(PR.APPLICATIONAMOUNT AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
  NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
  CAST(date_format(PR.APPLICATIONDATE, 'yyyy-MM-dd HH:mm:ss.SSSSSS') as VARCHAR(250)) AS QUOTE_PROD_GRP_FEATURE_TXT -- Change from (CAST(PR.APPLICATIONDATE AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT

  FROM P1VSTEDW.LOS_PR_1_0 AS PR
  
  INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
  ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
  
  LEFT OUTER JOIN P1VSTEDW.LOS_CURRENCY_1_0 AS CURRENCY
        ON PR.APPLICATIONCURRENCY_ID = CURRENCY.ID
  
  LEFT OUTER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKPGPRT
  ON PR.BK_PRODUCTGROUP_033_001 = BKPGPRT.SOURCE_KEY
  
  LEFT OUTER JOIN P1VUTEDW.BKEY_QUOTATION AS BKDEAL
  ON PLPR.BK_QUOTATION_074_001 = BKDEAL.SOURCE_KEY
  
  LEFT OUTER JOIN P1VUTEDW.BKEY_FEATURE AS BKQUOFEA
  ON BKQUOFEA.SOURCE_KEY = '2_1_Application Amount_'
  
        /*LEFT OUTER JOIN P1VUTEDW.M09700_CRNCY M09700
        ON M09700.SOURCE_KEY =
        CASE WHEN COALESCE(CURRENCY.USERCODE,'') = ''
         THEN '764'
         ELSE CURRENCY.USERCODE
        END
        AND M09700.SOURCE_ID = '1'
        AND M09700.SRC_CTL_ID = '021'*/
  
  CROSS JOIN P1VUTEDW.M09700_CRNCY AS M09700_01 --> PERFORMANCE TUNING
          
        LEFT OUTER JOIN P1VUTEDW.M09700_CRNCY AS M09700_02  --> PERFORMANCE TUNING
          ON M09700_02.SOURCE_KEY = CURRENCY.USERCODE
          AND M09700_02.SOURCE_ID = '1'
          AND M09700_02.SRC_CTL_ID = '021'
         
        WHERE COALESCE(PR.APPLICATIONAMOUNT,'') <> '' 
  AND M09700_01.SOURCE_KEY = '764'
  AND M09700_01.SOURCE_ID = '1'
  AND M09700_01.SRC_CTL_ID = '021'
  
  UNION ALL
        
        --------------------------------------------------------------------------
        -- > > VLOS_PR10_QUOPROFEATUR_19
        --------------------------------------------------------------------------
  SELECT
  BKDEAL.EDW_KEY AS QUOTATION_ID,
  BKPGPRT.EDW_KEY AS PRODUCT_GROUP_ID,
  PR.ID AS PRODUCT_GROUP_SEQUENCE_ID,
/*  CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTATION_PROD_GRP_START_DT, << mig orig*/
  TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTATION_PROD_GRP_START_DT,
  BKQUOFEA.EDW_KEY AS FEATURE_ID,
/*  CAST('1000-01-01' AS DATE FORMAT 'YYYY-MM-DD') AS QUOTE_PROD_GRP_FEAT_START_DT, << mig orig*/
  TO_DATE('1000-01-01' ,'yyyy-MM-dd') AS QUOTE_PROD_GRP_FEAT_START_DT,
        CASE WHEN COALESCE(CURRENCY.USERCODE,'') = ''
           THEN M09700_01.EDW_CODE
           ELSE M09700_02.EDW_CODE
         END AS QUOTE_PROD_GRP_FEAT_CURR_CD,  --> PERFORMANCE TUNING
  CAST(PR.ORDERHOUSELOANCONTRACT AS VARCHAR(100)) AS QUOTE_PROD_GRP_FEATURE_NUM,
  FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'0.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE, -- Change from FORMAT_NUMBER(Cast(NULL AS DECIMAL(18,10)),'#.0000000000') AS QUOTE_PROD_GRP_FEATURE_RATE
  CAST(PR.ARRANGEMENTAMOUNT AS DECIMAL(38,12)) AS QUOTE_PROD_GRP_FEATURE_AMT,
  NULL AS QUOTE_PROD_GRP_FEAT_UOM_CD,
  (CAST( NULL AS VARCHAR(250))) AS QUOTE_PROD_GRP_FEATURE_TXT

  
  FROM P1VSTEDW.LOS_PR_1_0 AS PR
  
  INNER JOIN P1VSTEDW.LOS_PLPR_1_0 AS PLPR
  ON PR.ID = CASE WHEN COALESCE(PLPR.FROMPRODUCT_ID,'') = '' 
        THEN PLPR.TOPRODUCT_ID 
        ELSE PLPR.FROMPRODUCT_ID END
    
  LEFT OUTER JOIN P1VSTEDW.LOS_CURRENCY_1_0 AS CURRENCY
        ON PR.ARRANGEMENTCURRENCY_ID = CURRENCY.ID
  
  LEFT OUTER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BKPGPRT
  ON PR.BK_PRODUCTGROUP_033_001 = BKPGPRT.SOURCE_KEY
  
  LEFT OUTER JOIN P1VUTEDW.BKEY_QUOTATION AS BKDEAL
  ON PLPR.BK_QUOTATION_074_001 = BKDEAL.SOURCE_KEY
  
  LEFT OUTER JOIN P1VUTEDW.BKEY_FEATURE AS BKQUOFEA
  ON BKQUOFEA.SOURCE_KEY = '3_1_Arrangement Orderhouseloan_'
  
  /*LEFT OUTER JOIN P1VUTEDW.M09700_CRNCY M09700
        ON M09700.SOURCE_KEY =
        CASE WHEN COALESCE(CURRENCY.USERCODE,'') = ''
         THEN '764'
         ELSE CURRENCY.USERCODE
        END
        AND M09700.SOURCE_ID = '1'
        AND M09700.SRC_CTL_ID = '021'*/
  
  CROSS JOIN P1VUTEDW.M09700_CRNCY AS M09700_01 --> PERFORMANCE TUNING
          
        LEFT OUTER JOIN P1VUTEDW.M09700_CRNCY AS M09700_02  --> PERFORMANCE TUNING
          ON M09700_02.SOURCE_KEY = CURRENCY.USERCODE
          AND M09700_02.SOURCE_ID = '1'
          AND M09700_02.SRC_CTL_ID = '021'
         
        WHERE M09700_01.SOURCE_KEY = '764'
  AND M09700_01.SOURCE_ID = '1'
  AND M09700_01.SRC_CTL_ID = '021'
