CREATE OR REPLACE VIEW P1VTPSL.TVSL_OUTSTANDING (
  ACCOUNT_NUMBER,
  ACCCOUNT_NAME,
  ACCOUNT_TYPE,
  ACCOUNT_PN_NUMBER,
  ACCOUNT_OUTSTANDING,
  ACCOUNT_LIMIT_AMOUNT,
  ACCOUNT_ALS_OC)
COMMENT ' #########################################
 CHANGE DATE 2012-05-30 BY Anongnath A.
 MAPPING BY Ummara T.
 MAPPING VERSION: EDW_DownStream_SoftLoan_Diagram_V1-4.pdf
 R55050007: BOT SoftLoan Phase 3
 CHANGE:
         CONDITION ACCOUNT_OUTSTANDING
 --------------------------------------------------------------------------------------
 CHANGE DATE 2012-03-09 BY Anongnath A.
 MAPPING BY Sujin L.
 MAPPING VERSION: EDW_DownStream_SoftLoan_Diagram_V1-1.vsd
 R55010082:BOT SoftLoan Phase 1
 CHANGE:
         ACCOUNT_NUMBER,FILTER AMMSZ101,CONDITION ACCOUNT_TYPE
 --------------------------------------------------------------------------------------
 CREATE DATE 2012-03-08 BY Anongnath A.
 MAPPING BY Sujin L.
 MAPPING VERSION: EDW_DownStream_SoftLoan_Diagram_V1-0.vsd
 R55010082:BOT SoftLoan Phase 1
 #########################################
 
 
'
AS SELECT 
 -- /*
         
/*  
 COALESCE(TRIM(AMMSRT00.AMDWHHD_HDR_CTL1),'') ||
         COALESCE(TRIM(AMMSRT00.AMDWHHD_HDR_CTL2),'') ||
         COALESCE(TRIM(AMMSRT00.AMDWHHD_HDR_CTL3),'') ||
         COALESCE(TRIM(AMMSRT00.AMDWHHD_HDR_CTL4),'') ||
         COALESCE(TRIM(AMMSRT00.AMDWHHD_HDR_ACCT_NUM),'') AS ACCOUNT_NUMBER
 
          
*/
 COALESCE(TRIM(AMMSRT00.AMDWHHD_HDR_SCB_ACCT_NUM),'')  || ' ' || COALESCE(TRIM(AMMSRT00.AMDWHHD_HDR_ACCT_NUM),'') AS ACCOUNT_NUMBER 
,CASE
        WHEN  AMMSCI01.AMMSCI01_CF_LINE_TYPE_1 = '1'
        AND   AMMSCI01.AMMSCI01_CF_LINE_TYPE_2 <> '1'
                THEN  AMMSCI01.AMMSCI01_CF_LINE_DATA_1 
        WHEN   AMMSCI01.AMMSCI01_CF_LINE_TYPE_1 = '1'
        AND   AMMSCI01.AMMSCI01_CF_LINE_TYPE_2 = '1'
        AND   AMMSCI01.AMMSCI01_CF_LINE_TYPE_3 <> '1'
                THEN  rpad( CAST((COALESCE(AMMSCI01.AMMSCI01_CF_LINE_DATA_1,'')) AS CHAR(40)), 40, ' ') || CAST((COALESCE(AMMSCI01.AMMSCI01_CF_LINE_DATA_2,''))  AS CHAR(40))
        WHEN   AMMSCI01.AMMSCI01_CF_LINE_TYPE_1 = '1'
        AND   AMMSCI01.AMMSCI01_CF_LINE_TYPE_2 = '1'
        AND   AMMSCI01.AMMSCI01_CF_LINE_TYPE_3 = '1' 
        AND   AMMSCI01.AMMSCI01_CF_LINE_TYPE_4 <> '1'
                THEN  rpad( CAST((COALESCE(AMMSCI01.AMMSCI01_CF_LINE_DATA_1,'')) AS CHAR(40)), 40, ' ') || CAST((COALESCE(AMMSCI01.AMMSCI01_CF_LINE_DATA_2,''))  AS CHAR(40)) || 
                CAST((COALESCE(AMMSCI01.AMMSCI01_CF_LINE_DATA_3,''))  AS CHAR(40))
END AS ACCOUNT_NAME
,CASE
        WHEN AMMSZ101.AMDWHHD_HDR_CTL3 = '478' THEN 'Mortgage'
        WHEN AMMSZ101.AMDWHHD_HDR_CTL3 = '497' THEN 'Hire Purchase'
        WHEN AMMSZ101.AMDWHHD_HDR_CTL3 IN ( '496','485') THEN 'SSME / SME'
END AS ACCOUNT_TYPE
,SUBSTR(AMMSZ101.AMMSZ101_ZM_NOTES_4,13,11) AS ACCOUNT_PN_NUMBER
,CAST(CASE
        WHEN AMMSZ101.AMDWHHD_HDR_CTL3 = '497'   /*  [Hire Purchase] IF HP THEN - COMMIT FEE */ -- [Hire Purchase] IF HP THEN - COMMIT FEE
        THEN COALESCE(AMMSBA01_OS.AMMSBA01_BA_CURR_BAL, 0) - COALESCE(AMMSZ101.AMMSZ101_ZM_AMT_2, 0)
        ELSE COALESCE(AMMSBA01_OS.AMMSBA01_BA_CURR_BAL, 0)
        END AS DECIMAL(18,2)) AS ACCOUNT_OUTSTANDING
,CAST(CASE
        WHEN AMMSZ101.AMDWHHD_HDR_CTL3 = '497' 
        THEN AMMSRT00.AMMSRT00_RT_ORIG_LOAN_AMT
        ELSE AMMSBA01_LIMIT.AMMSBA01_BA_CURR_BAL 
END AS DECIMAL(18,2)) AS ACCOUNT_LIMIT_AMOUNT
,AMMSRT00.AMMSRT00_CF_PRIM_BR AS ACCOUNT_ALS_OC        

FROM P1VSTEDW.AM_AMMSZ101_1_0 AS AMMSZ101

INNER JOIN P1VSTEDW.AM_AMMSRT00_1_0 AS AMMSRT00
ON  AMMSRT00.AMDWHHD_HDR_CTL1 = AMMSZ101.AMDWHHD_HDR_CTL1
AND AMMSRT00.AMDWHHD_HDR_CTL2 = AMMSZ101.AMDWHHD_HDR_CTL2
AND AMMSRT00.AMDWHHD_HDR_CTL3 = AMMSZ101.AMDWHHD_HDR_CTL3
AND AMMSRT00.AMDWHHD_HDR_CTL4 = AMMSZ101.AMDWHHD_HDR_CTL4
AND AMMSRT00.AMDWHHD_HDR_ACCT_NUM = AMMSZ101.AMDWHHD_HDR_ACCT_NUM
AND AMMSZ101.AMDWHHD_HDR_CTL3 IN ('478','485','496','497')
AND COALESCE(AMMSZ101.AMMSZ101_ZM_NOTES_2,'') LIKE 'BOTSLF%'

LEFT OUTER JOIN P1VSTEDW.AM_AMMSCI01_1_0 AS AMMSCI01
ON AMMSCI01.AMDWHHD_HDR_CTL1 = AMMSZ101.AMDWHHD_HDR_CTL1
AND AMMSCI01.AMDWHHD_HDR_CTL2 = AMMSZ101.AMDWHHD_HDR_CTL2
AND AMMSCI01.AMDWHHD_HDR_CTL3 = AMMSZ101.AMDWHHD_HDR_CTL3
AND AMMSCI01.AMDWHHD_HDR_CTL4 = AMMSZ101.AMDWHHD_HDR_CTL4
AND AMMSCI01.AMDWHHD_HDR_ACCT_NUM = AMMSZ101.AMDWHHD_HDR_ACCT_NUM

LEFT OUTER JOIN P1VSTEDW.AM_AMMSBA01_1_0 AS AMMSBA01_LIMIT
 -- /*
 
/*  
 ON AMMSBA01_LIMIT.AMDWHHD_HDR_CTL1 = AMMSZ101.AMDWHHD_HDR_CTL1
 AND AMMSBA01_LIMIT.AMDWHHD_HDR_CTL2 = AMMSZ101.AMDWHHD_HDR_CTL2
 AND AMMSBA01_LIMIT.AMDWHHD_HDR_CTL3 = AMMSZ101.AMDWHHD_HDR_CTL3
 AND AMMSBA01_LIMIT.AMDWHHD_HDR_CTL4 = AMMSZ101.AMDWHHD_HDR_CTL4
 AND AMMSBA01_LIMIT.AMDWHHD_HDR_ACCT_NUM = AMMSZ101.AMDWHHD_HDR_ACCT_NUM
 
  
*/
 ON AMMSBA01_LIMIT.AMDWHHD_HDR_SCB_ACCT_NUM = AMMSZ101.AMDWHHD_HDR_SCB_ACCT_NUM
AND AMMSBA01_LIMIT.AMDWHHD2_HD2_FIN_KEY LIKE 'C%'

LEFT OUTER JOIN(
        SELECT
        AMMSBA01.AMDWHHD_HDR_CTL1
        ,AMMSBA01.AMDWHHD_HDR_CTL2
        ,AMMSBA01.AMDWHHD_HDR_CTL3
        ,AMMSBA01.AMDWHHD_HDR_CTL4
        ,AMMSBA01.AMDWHHD_HDR_ACCT_NUM
        ,SUM(AMMSBA01.AMMSBA01_BA_CURR_BAL) AS AMMSBA01_BA_CURR_BAL
         FROM P1VSTEDW.AM_AMMSBA01_1_0 AS AMMSBA01
         WHERE AMMSBA01.AMDWHHD_HDR_CTL3 IN ('478','485','496','497')
         AND AMMSBA01.AMDWHHD2_HD2_FIN_KEY LIKE 'P%'
         GROUP BY 1,2,3,4,5
 )AS AMMSBA01_OS
ON AMMSBA01_OS.AMDWHHD_HDR_CTL1 = AMMSZ101.AMDWHHD_HDR_CTL1
AND AMMSBA01_OS.AMDWHHD_HDR_CTL2 = AMMSZ101.AMDWHHD_HDR_CTL2
AND AMMSBA01_OS.AMDWHHD_HDR_CTL3 = AMMSZ101.AMDWHHD_HDR_CTL3
AND AMMSBA01_OS.AMDWHHD_HDR_CTL4 = AMMSZ101.AMDWHHD_HDR_CTL4
AND AMMSBA01_OS.AMDWHHD_HDR_ACCT_NUM = AMMSZ101.AMDWHHD_HDR_ACCT_NUM
