CREATE OR REPLACE VIEW P1VEUODS.VODS_CBS_LAST_TRANS_DT (
  EVENT_START_DT,
  EVENT_START_TM)
AS SELECT COALESCE(LEFT(LAST_TRANS.MAX_EVENT_DATETIME,10),BD.BUSINESSDATE) AS EVENT_START_DT
 --CAST(TO_DATE(COALESCE(LAST_TRANS.MAX_EVENT_DATETIME,BD.BUSINESSDATE) ,'yyyy-MM-dd') AS CHAR(10)) AS EVENT_START_DT
 --------CAST(COALESCE(CAST(LAST_TRANS.MAX_EVENT_DATETIME AS TIME), CAST('00:00:00' AS TIME)) AS CHAR(8)) AS EVENT_START_TM
 --, CAST(COALESCE(date_format(LAST_TRANS.MAX_EVENT_DATETIME, 'HH:mm:ss'), '00:00:00') AS CHAR(8)) AS EVENT_START_TM
 , COALESCE(RIGHT(LAST_TRANS.MAX_EVENT_DATETIME,8),'00:00:00') AS EVENT_START_TM
 
FROM (
 SELECT MAX(date_format(to_timestamp(CAST(EV.EVENT_START_DT AS CHAR(10)) || CAST(EV.EVENT_START_TM AS CHAR(8)), 'yyyy-MM-ddHH:mm:ss'),'yyyy-MM-ddHH:mm:ss')) AS MAX_EVENT_DATETIME
 FROM P1VTTEDW.EVENT AS EV

 INNER JOIN P1VTPODS.VODS_BUSINESSDATE_D AS BD
  ON EV.START_DT = BD.BUSINESSDATE 
  AND EV.EVENT_START_DT BETWEEN BD.FIRST_DAY_OF_MONTH AND BD.LAST_DAY_OF_MONTH
  --ON EV.EVENT_START_DT = BD.BUSINESSDATE
  AND EV.CTL_ID = '002' --002: ST
  
 INNER JOIN P1VTTEDW.FINANCIAL_EVENT AS FE
  ON FE.EVENT_ID = EV.EVENT_ID
  AND FE.EVENT_START_DT = EV.EVENT_START_DT
  AND FE.START_DT = BD.BUSINESSDATE
  AND FE.DEBIT_CREDIT_IND = 'D'  
  AND FE.CTL_ID = '002' --002: ST
  
 --ACCT_SAVING
 INNER JOIN (
  SELECT AE.EVENT_ID, AE.EVENT_START_DT, AG.BASE_ACCOUNT_NUM
  FROM P1VTTEDW.ACCOUNT_EVENT AS AE
  
  INNER JOIN P1VTPODS.VODS_BUSINESSDATE_D AS BD
   ON AE.START_DT = BD.BUSINESSDATE
   AND AE.EVENT_START_DT BETWEEN BD.FIRST_DAY_OF_MONTH AND BD.LAST_DAY_OF_MONTH
   --ON AE.EVENT_START_DT = BD.BUSINESSDATE
   AND AE.Ctl_Id = '002' --002: ST
  --21684
  
  INNER JOIN P1VTTEDW.AGREEMENT AS AG
   ON AE.ACCOUNT_NUM = AG.ACCOUNT_NUM
   AND AE.ACCOUNT_MODIFIER_NUM = AG.ACCOUNT_MODIFIER_NUM
   AND BD.BUSINESSDATE BETWEEN AG.START_DT AND AG.END_DT
   AND AG.RECORD_DELETED_FLAG = 0
   AND AG.CTL_ID = '002' --002: ST
  
  INNER JOIN P1DTPODS.TODS_SAVING_PRODUCT AS SVP
   ON SVP.BASE_ACCOUNT_NUM = AG.BASE_ACCOUNT_NUM
   AND SVP.AS_OF_DT = BD.BUSINESSDATE
 ) AS ACCT_SAVING
  ON ACCT_SAVING.EVENT_ID = EV.EVENT_ID
  AND ACCT_SAVING.EVENT_START_DT = EV.EVENT_START_DT
 
 --CBS (Core Bank)
 LEFT JOIN (
  SELECT CE.EVENT_ID, CE.EVENT_START_DT, ES.EVENT_SOURCE_TYPE_CD, PARAM.Result_Value1_Desc
  
  FROM P1VTTEDW.CONTACT_EVENT AS CE
  
  INNER JOIN P1VTPODS.VODS_BUSINESSDATE_D AS BD
   ON CE.START_DT = BD.BUSINESSDATE
   AND CE.EVENT_START_DT BETWEEN BD.FIRST_DAY_OF_MONTH AND BD.LAST_DAY_OF_MONTH
   --ON CE.EVENT_START_DT = BD.BUSINESSDATE
   AND CE.CTL_ID = '002'
   
  INNER JOIN P1VTTEDW.EVENT_SOURCE AS ES
   ON CE.EVENT_SOURCE_ID = ES.EVENT_SOURCE_ID
   AND BD.BUSINESSDATE BETWEEN ES.START_DT AND ES.END_DT
   AND ES.RECORD_DELETED_FLAG = 0
   AND ES.CTL_ID = '002'
   
  LEFT JOIN P1DPYODS.ODS_PARAM_PRODUCT AS PARAM
  ON (
   PARAM.Compare_Attribute1 = 'EVENT_SOURCE_TYPE_CD'  --ATR_01
   AND (
    (PARAM.Compare_Operater1 = '=' AND CAST(ES.EVENT_SOURCE_TYPE_CD AS VARCHAR(6)) = PARAM.Compare_Value1_Val)
    OR (PARAM.Compare_Operater1 = '<>' AND CAST(ES.EVENT_SOURCE_TYPE_CD AS VARCHAR(6)) <> PARAM.Compare_Value1_Val)
    OR (PARAM.Compare_Operater1 = 'LIKE' AND CAST(ES.EVENT_SOURCE_TYPE_CD AS VARCHAR(6)) LIKE PARAM.Compare_Value1_Val)
    --OR (PARAM.Compare_Value1_Val = '')
   )
  )
 ) CBS_SOURCE
  ON CBS_SOURCE.EVENT_ID = EV.EVENT_ID
  AND CBS_SOURCE.EVENT_START_DT = EV.EVENT_START_DT
  
 WHERE COALESCE(CBS_SOURCE.EVENT_SOURCE_TYPE_CD, '') <> ''
 
) AS LAST_TRANS

CROSS JOIN P1VTPODS.VODS_BUSINESSDATE_D AS BD
