CREATE OR REPLACE VIEW P1VEUODS.VODS_CC_LAST_TRANS_DT (
  EVENT_START_DT,
  EVENT_START_TM)
AS SELECT LEFT(LAST_TRANS.MAX_EVENT_DATETIME,10) AS EVENT_START_DT
	--CAST(CAST(LAST_TRANS.MAX_EVENT_DATETIME AS TIME) AS CHAR(8)) AS EVENT_START_TM
 --, CAST(date_format(LAST_TRANS.MAX_EVENT_DATETIME, 'HH:mm:ss') AS CHAR(8)) AS EVENT_START_TM
 , RIGHT(LAST_TRANS.MAX_EVENT_DATETIME,8) AS EVENT_START_TM
FROM (
 SELECT --MAX(date_format(to_timestamp(CAST(EV.EVENT_START_DT AS CHAR(10)) || CAST(COALESCE(EV.EVENT_START_TM, CAST('00:00:00' AS TIMESTAMP)) AS CHAR(8)), 'yyyy-MM-ddHH:mm:ss'),'yyyy-MM-ddHH:mm:ss')) AS MAX_EVENT_DATETIME
   MAX(CAST(EV.EVENT_START_DT AS CHAR(10)) || CAST(COALESCE(EV.EVENT_START_TM, CAST('00:00:00' AS TIMESTAMP)) AS CHAR(8))) AS MAX_EVENT_DATETIME
 FROM (
  SELECT EV.EVENT_ID, EV.EVENT_START_DT, EV.EVENT_START_TM
  FROM P1VTTEDW.EVENT AS EV
  INNER JOIN P1VTPODS.VODS_BUSINESSDATE_D AS BD
   ON BD.BUSINESSDATE = EV.START_DT
   AND EV.CTL_ID = '005' --B2K
   AND EV.EVENT_START_DT BETWEEN BD.FIRST_DAY_OF_LASTMONTH AND BD.LAST_DAY_OF_MONTH
   AND SUBSTR(EV.TRANSACTION_ID,INSTR(EV.TRANSACTION_ID,'_')+1,6) <> '777777'
   AND (
     --B2K / FIS
     (
      SUBSTR(EV.HOST_TRANSACTION_CODE_NUM,1,2) IN ( '05',  '06',  '07',  '25',  '26',  '27')
      OR SUBSTR(EV.HOST_TRANSACTION_CODE_NUM,1,5) = '69_90'
     )
     --B2K <>JCB
    OR  (
      SUBSTR(EV.TRANSACTION_ID,INSTR(EV.TRANSACTION_ID,'_')+1,6) <> '356518' -- <> JCB
           AND SUBSTR(EV.HOST_TRANSACTION_CODE_NUM,1,5) IN ( '69_92', '69_97' ) --B2K 
       )
       --FIS JCB
    OR  (
      SUBSTR(TRANSACTION_ID,INSTR(EV.TRANSACTION_ID,'_')+1,6) = '356518' -- = JCB
               AND SUBSTR(EV.HOST_TRANSACTION_CODE_NUM,1,5) = '69_93' --FIS 
      )
   )
 ) AS EV
 CROSS JOIN P1VTPODS.VODS_BUSINESSDATE_D AS BD
 INNER JOIN P1VTTEDW.FINANCIAL_EVENT AS FV
  ON FV.EVENT_ID = EV.EVENT_ID
  AND FV.EVENT_START_DT = EV.EVENT_START_DT
  AND FV.START_DT = BD.BUSINESSDATE
  AND FV.CTL_ID = '005' --B2K
 INNER JOIN (
  SELECT AE.EVENT_ID
   , AE.EVENT_START_DT
   , AG.ACCOUNT_NUM
  FROM P1VTTEDW.ACCOUNT_EVENT AS AE
  INNER JOIN P1VTPODS.VODS_BUSINESSDATE_D AS BD
   ON AE.START_DT = BD.BUSINESSDATE
   AND AE.CTL_ID = '005' --B2K
  INNER JOIN P1VTTEDW.AGREEMENT AS AG
   ON AG.ACCOUNT_NUM = AE.ACCOUNT_NUM
   AND AG.ACCOUNT_MODIFIER_NUM = AE.ACCOUNT_MODIFIER_NUM
   AND BD.BUSINESSDATE BETWEEN AG.START_DT AND AG.END_DT
   AND AG.RECORD_DELETED_FLAG = 0
   AND AG.CTL_ID = '005' --B2K
   AND AG.ACCOUNT_MODIFIER_NUM = 'B2K01' --Filter only CREDIT_CARD ( Filter out: DEBIT and PREPAID CARD)
 ) AS AE
  ON AE.EVENT_ID = EV.EVENT_ID
  AND AE.EVENT_START_DT = EV.EVENT_START_DT
) AS LAST_TRANS
