CREATE OR REPLACE VIEW P1VTPBCM.TVBCM_PAYROLL_PA_ATS_CN (
  AS_OF_DT,
  SEQ_NO,
  COMP_NAME,
  CORPID_COMPCODE,
  VALUE_DATE,
  TO_ACCOUNT_NUM,
  ACCOUNT_NAME,
  EMPID_CITIZEN_PASSPORT,
  BIRTH_DT,
  GENDER_TYPE,
  INSURANCE_COMPANY,
  INSURANCE_PLAN)
COMMENT '/*############################################################
  MODELER NAME: JAYANTA DAS
  DEVELOP BY: SMITA PATEL
  VIEW NAME: VTPBCM.TVBCM_PAYROLL_PA_ATS_CN
  CREATE DATE: 2016-12-12
  DESCRIPTION : UR59080013 - SCB Payroll with PA Payroll
  ------------------------------------------------------------
  UPDATE DATE : 2017-10-11
  CHANGE DESCRIPTION : 1) Changed INNER JOIN TO LEFT JOIN for M13400_EVENT_STS table and changed Joining Condition 
                          from EVENT.EVENT_STATUS_CD to E_R.EVENT_STATUS_CD
                       2) Added QUALIFY ROW_NUMBER() clause in CN subview to get only latest Transaction.
  ##############################################################		
  UR NAME : P590019-10 - STB Payroll & PA 	
  MODELER NAME : BISHWAJEET
  DEVELOP BY : ARISA P.
  VIEW NAME : VTPBCM.TVBCM_PAYROLL_PA_ATS_CN
  UPDATE DATE : 2019-08-26
  DESCRIPTION : Added new sub view  
  MAPPING DOCUMENT : EDW_DownStream_BCM_Payroll_PA_Transaction_to_Insurance_Diagram_V1.2.vsd
                                           EDW_DownStream_BCM_Payroll_PA_Transaction_to_Insurance_Specification_V1-1.ods
  ##############################################################		
  UR NAME : CB62110020 Add Biz Anywhere channel into Payroll report for Insurance Company 	
  MODELER NAME : PAWARIT N.
  DEVELOP BY : WANUTPORN RK.
  VIEW NAME : VTPBCM.TVBCM_PAYROLL_PA_ATS_CN
  UPDATE DATE : 2020-04-16
  MAPPING DOCUMENT : EDW_DownStream_BCM_Payroll_PA_Transaction_to_Insurance_Diagram_V1.3.vsd
                                           EDW_DownStream_BCM_Payroll_PA_Transaction_to_Insurance_Specification_V1-2.ods
  ##############################################################		
  UR NAME : CB63110008 (Payroll PA-PA Profile and Support New insurance company)
  MODELER NAME : PAWARIT N.
  DEVELOP BY : Ratchata L
  VIEW NAME : VTPBCM.TVBCM_PAYROLL_PA_ATS_CN
  UPDATE DATE : 2021-06-25
  MAPPING DOCUMENT : EDW_DownStream_BCM_Payroll_PA_Transaction_to_Insurance_Diagram_V1.5.vsd
                                           EDW_DownStream_BCM_Payroll_PA_Transaction_to_Insurance_Specification_V1-5.ods
  ############################################################*/'
AS SELECT
    CAST(BD.BUSINESSDATE AS DATE ) AS AS_OF_DT
   ,CAST(COM.SEQ_NO AS INTEGER) AS SEQ_NO
   ,CAST(COM.COMP_NAME AS VARCHAR(200)) AS COMP_NAME
   ,CAST(COM.CORPID_COMPCD AS VARCHAR(20)) AS CORPID_COMPCODE
   ,CAST(FAE.EVENT_VALUE_DTTM AS DATE ) AS VALUE_DATE
   ,CAST(FTE.TO_ACCOUNT_NUM AS VARCHAR(10)) AS TO_ACCOUNT_NUM
   ,CAST(COALESCE(AGMT.CONTRACT_NAME, AGMT.THAI_CONTRACT_NAME) AS VARCHAR(300)) AS ACCOUNT_NAME

  /* START Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */
   ,CAST(NULL AS VARCHAR(100)) AS EMPID_CITIZEN_PASSPORT
   ,CAST(NULL AS DATE ) AS BIRTH_DT
   ,CAST(NULL AS VARCHAR(10)) AS GENDER_TYPE
   ,CAST(COM.INSURANCE_COMPANY AS VARCHAR(50)) AS INSURANCE_COMPANY
   ,CAST(COM.INSURANCE_PLAN AS VARCHAR(50)) AS INSURANCE_PLAN
   /* END Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */


  /*FROM ( SELECT  ACC_EVT.EVENT_VALUE_DTTM
                ,ACC_EVT.EVENT_ID
                ,ACC_EVT.EVENT_START_DT
          FROM P1VTTEDW.FINANCIAL_ACCOUNT_EVENT AS ACC_EVT
          WHERE ACC_EVT.CTL_ID ='041' ---[ATS] 
      ) AS FAE*/
  FROM P1VTTEDW.FINANCIAL_ACCOUNT_EVENT AS FAE 
  INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
  ON CAST(FAE.EVENT_VALUE_DTTM AS DATE ) BETWEEN BD.FIRST_DAY_OF_MONTH AND BD.LAST_DAY_OF_MONTH
  AND FAE.CTL_ID ='041' ---[ATS] 



  /*INNER JOIN (SELECT 
                      E.EVENT_ID
                     ,E.EVENT_START_DT
                     ,E.TRANSACTION_ID
              FROM P1VTTEDW.EVENT AS E
              WHERE E.CTL_ID ='041' ---[ATS]
              AND E.EVENT_STATUS_CD = 1 ---[CS013400 : 1 = COMPLETED]
  ) 
  AS EVENT */
  INNER JOIN  P1VTTEDW.EVENT AS EVENT
  ON FAE.EVENT_ID = EVENT.EVENT_ID
  AND FAE.EVENT_START_DT = EVENT.EVENT_START_DT
  AND EVENT.CTL_ID ='041' ---[ATS]
  AND EVENT.EVENT_STATUS_CD = 1 ---[CS013400 : 1 = COMPLETED]



  INNER JOIN P1DPYBCM.BCM_PAYROLL_PA AS COM
  ON UPPER(RTRIM(COM.CORPID_COMPCD)) = UPPER(RTRIM(EVENT.TRANSACTION_ID))
  AND COM.AS_OF_DT = BD.BUSINESSDATE
  /* START Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */
  AND UPPER(COM.TYPE1) = 'COMP_CD' -->Add condition
  /* END Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */         

  LEFT JOIN ( SELECT 
       AGMT.ACCOUNT_NUM
       ,AGMT.CONTRACT_NAME
       ,AGMT.THAI_CONTRACT_NAME

     FROM P1VTTEDW.AGREEMENT AS AGMT
     WHERE AGMT.CTL_ID ='041' ---[ATS]
     AND AGMT.RECORD_DELETED_FLAG = 0
     AND AGMT.END_DT = '9999-12-31' 
  ) AS AGMT
  ON UPPER(RTRIM(EVENT.TRANSACTION_ID)) = UPPER(RTRIM(AGMT.ACCOUNT_NUM))

  /*INNER JOIN (SELECT 
                      FTE_01.EVENT_ID
                     ,FTE_01.EVENT_START_DT
                     ,FTE_01.TO_ACCOUNT_NUM
              FROM P1VTTEDW.FUNDS_TRANSFER_EVENT AS FTE_01
              WHERE FTE_01.CTL_ID ='041' ---[ATS]
      ) AS FTE*/
  INNER JOIN P1VTTEDW.FUNDS_TRANSFER_EVENT AS FTE
  ON FTE.EVENT_ID = FAE.EVENT_ID
  AND FTE.EVENT_START_DT = FAE.EVENT_START_DT
  AND FTE.CTL_ID ='041' ---[ATS]


  INNER JOIN P1VTTEDW.CONTACT_EVENT AS CE
  ON FTE.EVENT_ID = CE.EVENT_ID
  AND FTE.EVENT_START_DT = CE.EVENT_START_DT
  AND CE.CTL_ID ='041' ---[ATS]
  AND CE.TERMINAL_ID = '0800' --[0800 = PAYROLL]

  WHERE COALESCE(FTE.TO_ACCOUNT_NUM,'') <> ''

  UNION ALL
  SELECT AS_OF_DT,SEQ_NO,COMP_NAME,CORPID_COMPCODE,VALUE_DATE,TO_ACCOUNT_NUM,Account_Name,EMPID_CITIZEN_PASSPORT,BIRTH_DATE,GENDER_TYPE,INSURANCE_COMPANY,INSURANCE_PLAN 
  FROM(
  SELECT
    Cast(BD.BUSINESSDATE AS DATE ) AS AS_OF_DT
   ,Cast(COM.SEQ_NO AS INTEGER) AS SEQ_NO
   ,Cast(COM.COMP_NAME AS VARCHAR(200)) AS COMP_NAME
   ,Cast(COM.CorpID_CompCode AS VARCHAR(20)) AS CORPID_COMPCODE
   ,Cast(FAE.EVENT_VALUE_DTTM AS DATE ) AS VALUE_DATE
   ,Cast(FTE_C.TO_ACCOUNT_NUM AS VARCHAR(10)) AS TO_ACCOUNT_NUM

   /*
   ,CAST(TRIM(CASE WHEN FTE_C.BENEF_THAI_NAME = ' ' OR FTE_C.BENEF_THAI_NAME IS NULL
      THEN FTE_C.BENEFICIARY_LINE_1_NAME
    ELSE FTE_C.BENEF_THAI_NAME END ) AS VARCHAR(300))AS ACCOUNT_NAME */ --Change

   /* START Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */
   --,Cast(Coalesce(FTE_C.CONTRACT_NAME, FTE_C.THAI_CONTRACT_NAME) AS VARCHAR(300))  AS Account_Name
   ,Cast(CASE WHEN COM.Insurance_Company='FWD' THEN
            Coalesce(FTE_C_DET.CONTRACT_NAME, FTE_C_DET.THAI_CONTRACT_NAME)
    ELSE
           Trim(CASE WHEN FTE_C.BENEF_THAI_NAME = ' ' OR FTE_C.BENEF_THAI_NAME IS NULL THEN FTE_C.BENEFICIARY_LINE_1_NAME ELSE FTE_C.BENEF_THAI_NAME END)
    END AS VARCHAR(300)) AS Account_Name
   ,Cast(Coalesce(FTE_C_DET.CID_PARTY_IDENTIFICATION_NUM, FTE_C_DET.PPORT_PARTY_IDENTIFICATION_NUM) AS VARCHAR(100)) AS EMPID_CITIZEN_PASSPORT
   ,Cast(FTE_C_DET.BIRTH_DT AS DATE ) AS BIRTH_DATE
   ,Cast(FTE_C_DET.SOURCE_KEY AS VARCHAR(10)) AS GENDER_TYPE
   ,Cast(COM.INSURANCE_COMPANY AS VARCHAR(50)) AS INSURANCE_COMPANY
   ,Cast(COM.INSURANCE_PLAN AS VARCHAR(50)) AS INSURANCE_PLAN
   ,Row_Number() Over (PARTITION BY Cast(BD.BUSINESSDATE AS DATE ), Cast(COM.SEQ_NO AS INTEGER), Cast(COM.COMP_NAME AS VARCHAR(200)) , Cast(COM.CorpID_CompCode AS VARCHAR(20)),  FTE_C.To_Account_Num, Cast(FAE.EVENT_VALUE_DTTM AS DATE ) ORDER BY EVENT.TRANSACTION_ID DESC) AS R
   /* END Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */


  /*FROM ( SELECT  ACC_EVT.EVENT_VALUE_DTTM
                ,ACC_EVT.EVENT_ID
                ,ACC_EVT.EVENT_START_DT
          FROM P1VTTEDW.FINANCIAL_ACCOUNT_EVENT AS ACC_EVT
          WHERE ACC_EVT.CTL_ID ='052' ---[CN] 
      ) AS FAE*/
  FROM  P1VTTEDW.FINANCIAL_ACCOUNT_EVENT AS FAE
  INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
  ON Cast(FAE.EVENT_VALUE_DTTM AS DATE ) BETWEEN BD.FIRST_DAY_OF_MONTH AND BD.LAST_DAY_OF_MONTH
  AND FAE.CTL_ID ='052' ---[CN] 

  /*INNER JOIN ( SELECT 
                       AE.EVENT_ID
                      ,AE.EVENT_START_DT
                      ,AE.ACCOUNT_NUM
                  FROM P1VTTEDW.ACCOUNT_EVENT AS AE
                  WHERE AE.CTL_ID ='052' ---[CN]
                  AND AE.RECORD_DELETED_FLAG = 0
                  AND AE.ACCOUNT_MODIFIER_NUM = 'S1'
  ) AS ACC_EVENT */
  INNER JOIN  P1VTTEDW.ACCOUNT_EVENT AS ACC_EVENT
  ON FAE.EVENT_ID = ACC_EVENT.EVENT_ID
  AND FAE.EVENT_START_DT = ACC_EVENT.EVENT_START_DT
  AND ACC_EVENT.CTL_ID ='052' ---[CN]
  AND ACC_EVENT.RECORD_DELETED_FLAG = 0
  AND ACC_EVENT.ACCOUNT_MODIFIER_NUM = 'S1'

  INNER JOIN (
     SELECT 
       Cast(EDW_KEY AS VARCHAR(100)) AS EDW_KEY,  --> CB63110008 Fix error bad format character 
       Substr(SOURCE_KEY,1, Char_Length(SOURCE_KEY)-4) COMPANY_ID
              FROM P1VUTEDW.BKEY_AGREEMENTCS
              WHERE RECORD_DELETED_FLAG = 0  ) AS BKEYCS 
  ON UPPER(RTRIM(ACC_EVENT.ACCOUNT_NUM)) = UPPER(RTRIM(BKEYCS.EDW_KEY))

  /*
  INNER JOIN P1DPYBCM.BCM_PAYROLL_PA AS COM
  ON TRIM(COM.CORPID_COMPCD) = EVENT.TRANSACTION_ID
  AND COM.AS_OF_DT = BD.BUSINESSDATE 
  */ --> Change

  /* START Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */

  INNER JOIN 
   ( 
      SELECT
       STB.Seq AS SEQ_NO,
       STB.CUST_NM AS COMP_NAME,
       STB.CORP_ID AS CORPID_COMPCODE,
       'STB' AS INPUT_FLAG,
       STB.INSURANCE_COMPANY,
       STB.INSURANCE_PLAN
      FROM P1DPYSTB.STB_PAYROLL_PA AS STB
      INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
      ON BD.BUSINESSDATE BETWEEN STB.START_DT AND STB.END_DT
      AND STB.RECORD_DELETED_FLAG = 0
      AND STB.CTL_ID = '388' --STARTBIZ
      AND Upper(STB.ID_TP) = 'CORP_ID'

      UNION ALL

      SELECT 
       BCM.SEQ_NO,
       BCM.COMP_NAME,
       BCM.CORPID_COMPCD AS CORPID_COMPCODE,
       'BCM' AS INPUT_FLAG,
       BCM.INSURANCE_COMPANY,
       BCM.INSURANCE_PLAN   
      FROM P1DPYBCM.BCM_PAYROLL_PA AS BCM
      INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
      ON BCM.AS_OF_DT = BD.BUSINESSDATE
      AND BCM.CTL_ID = '090'
      AND Upper(BCM.Type1) = 'CORP_ID'
   ) AS COM
  ON UPPER(RTRIM(BKEYCS.COMPANY_ID)) = UPPER(RTRIM(COM.CorpID_CompCode))
  /* END Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */

  /*INNER JOIN (SELECT 
                      E.EVENT_ID
                     ,E.EVENT_START_DT
                     ,E.TRANSACTION_ID
                     ,E.EVENT_STATUS_CD
                     ,E.EVENT_ACTIVITY_TYPE_CD
              FROM P1VTTEDW.EVENT AS E
              WHERE E.CTL_ID ='052' ---[CN]
              AND E.RECORD_DELETED_FLAG = 0
  ) 
  AS EVENT */
  INNER JOIN  P1VTTEDW.EVENT AS EVENT
  ON FAE.EVENT_ID = EVENT.EVENT_ID
  AND FAE.EVENT_START_DT = EVENT.EVENT_START_DT
  AND EVENT.CTL_ID ='052' ---[CN]
  AND EVENT.RECORD_DELETED_FLAG = 0

  INNER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS MTABLE
  ON MTABLE.EDW_CODE = EVENT.EVENT_ACTIVITY_TYPE_CD
  AND MTABLE.SRC_CTL_ID = 052 --[CN]
  AND MTABLE.SOURCE_KEY = 'PAY'
  AND MTABLE.RECORD_DELETED_FLAG = 0
  AND MTABLE.END_DT = '9999-12-31'

  /*INNER JOIN P1VUTEDW.M13400_EVENT_STS AS STS 
  ON EVENT.EVENT_STATUS_CD  = STS.EDW_CODE
  AND STS.SRC_CTL_ID = '052'
  AND STS.RECORD_DELETED_FLAG = 0
  AND STS.END_DT = '9999-12-31'
  AND STS.SOURCE_KEY = 'I'*/

  /*INNER JOIN ( SELECT  EGA_SUB.EVENT_ID
                      ,EGA_SUB.EVENT_START_DT

              FROM P1VTTEDW.EVENT_GROUP_ASSOC AS EGA_SUB 
              WHERE EGA_SUB.CTL_ID ='052' 
              AND EGA_SUB.RECORD_DELETED_FLAG = 0
              AND EGA_SUB.EVENT_GROUP_ID IN (183,184) --[BATCHTXN,DETAILTXN]
  ) AS EGA*/
  INNER JOIN P1VTTEDW.EVENT_GROUP_ASSOC AS EGA 
  ON EGA.EVENT_ID = EVENT.EVENT_ID
  AND EGA.EVENT_START_DT = EVENT.EVENT_START_DT
  AND EGA.CTL_ID ='052' 
  AND EGA.RECORD_DELETED_FLAG = 0
  AND EGA.EVENT_GROUP_ID IN (183,184) --[BATCHTXN,DETAILTXN]

  /*INNER JOIN (SELECT ER_SUB.EVENT_ID
                      ,ER_SUB.EVENT_START_DT
                      ,ER_SUB.RELATED_EVENT_ID
                      ,ER_SUB.RELATED_EVENT_START_DT

              FROM P1VTTEDW.EVENT_RELATIONSHIP AS ER_SUB
              WHERE ER_SUB.CTL_ID ='052' ---[CN]
              AND ER_SUB.RECORD_DELETED_FLAG = 0
              AND ER_SUB.EVENT_RELATIONSHIP_TYPE_CD = 1 --[MAIN-SUB]
  ) AS ER */
  INNER JOIN  P1VTTEDW.EVENT_RELATIONSHIP AS ER
  ON ER.EVENT_ID = EGA.EVENT_ID
  AND ER.EVENT_START_DT = EGA.EVENT_START_DT
  AND ER.CTL_ID ='052' ---[CN]
  AND ER.RECORD_DELETED_FLAG = 0
  AND ER.EVENT_RELATIONSHIP_TYPE_CD = 1 --[MAIN-SUB]

  /*INNER JOIN (SELECT 
                      FTE_01.EVENT_ID
                     ,FTE_01.EVENT_START_DT
                     ,FTE_01.TO_ACCOUNT_NUM
              FROM P1VTTEDW.FUNDS_TRANSFER_EVENT AS FTE_01
              WHERE FTE_01.CTL_ID ='052' ---[CN]
              AND FTE_01.RECORD_DELETED_FLAG = 0
      ) AS FTE*/
  INNER JOIN P1VTTEDW.FUNDS_TRANSFER_EVENT AS FTE
  ON FTE.EVENT_ID = ER.EVENT_ID
  AND FTE.EVENT_START_DT = ER.EVENT_START_DT
  AND FTE.CTL_ID ='052' ---[CN]
  AND FTE.RECORD_DELETED_FLAG = 0

  /*
  LEFT OUTER JOIN ( SELECT FE.EVENT_ID
        ,FE.EVENT_START_DT
        ,FE.TO_ACCOUNT_NUM
        ,FE.BENEFICIARY_LINE_1_NAME
        ,FE.BENEF_THAI_NAME

  FROM P1VTTEDW.FUNDS_TRANSFER_EVENT FE  --M Add Alias
  WHERE FE.CTL_ID ='052' --[CN]
  AND FE.RECORD_DELETED_FLAG = 0
  AND FE.END_DT = '9999-12-31'
  ) AS FTE_C
  ON FTE_C.EVENT_ID = ER.RELATED_EVENT_ID
  AND FTE_C.EVENT_START_DT = ER.RELATED_EVENT_START_DT
  */ --> Change 


  /*INNER JOIN 
              (SEL * 
              FROM P1VTTEDW.FINANCIAL_EVENT
              WHERE RECORD_DELETED_FLAG = 0
                     AND END_DT = '9999-12-31'
                     AND CTL_ID = '052'
              ) AS FE_C */
  INNER JOIN P1VTTEDW.FINANCIAL_EVENT AS FE_C
  ON   ER.RELATED_EVENT_ID = FE_C.EVENT_ID
  AND ER.RELATED_EVENT_START_DT = FE_C.EVENT_START_DT
  AND FE_C.RECORD_DELETED_FLAG = 0
  AND FE_C.END_DT = '9999-12-31'
  AND FE_C.CTL_ID = '052'



  /*INNER JOIN 
              (SEL * 
              FROM P1VTTEDW.EVENT
              WHERE RECORD_DELETED_FLAG = 0
                     AND CTL_ID = '052' 
              ) AS E_R */
  INNER JOIN P1VTTEDW.EVENT E_R
  ON ER.RELATED_EVENT_ID = E_R.EVENT_ID
  AND ER.RELATED_EVENT_START_DT = E_R.EVENT_START_DT
  AND E_R.RECORD_DELETED_FLAG = 0
  AND E_R.CTL_ID = '052' 


  INNER JOIN P1VUTEDW.M13400_EVENT_STS AS STS 
  ON E_R.EVENT_STATUS_CD  = STS.EDW_CODE
  AND STS.SRC_CTL_ID = '052'
  AND STS.RECORD_DELETED_FLAG = 0
  AND STS.END_DT = '9999-12-31'
  AND STS.SOURCE_KEY = 'I'

  /* START Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */
   LEFT JOIN
   ( SELECT 
      EVENT_ID,
      EVENT_START_DT,
      TO_ACCOUNT_NUM,
      BENEFICIARY_LINE_1_NAME,
      BENEF_THAI_NAME
      FROM P1VTTEDW.FUNDS_TRANSFER_EVENT
      WHERE CTL_ID ='052' --[CN]
      AND RECORD_DELETED_FLAG = 0
      AND END_DT = '9999-12-31'
      AND SETTLEMENT_STATUS_TYPE_CD IN (1,2) --[CS044311:1:FD, CS044311:2:FR]
    ) AS FTE_C
  ON ER.RELATED_EVENT_ID = FTE_C.EVENT_ID  
  AND ER.RELATED_EVENT_START_DT = FTE_C.EVENT_START_DT 

  LEFT OUTER JOIN 
  (SELECT
    AG.CONTRACT_NAME AS CONTRACT_NAME,
    AG.THAI_CONTRACT_NAME AS THAI_CONTRACT_NAME,
    AG.BASE_ACCOUNT_NUM AS BASE_ACCOUNT_NUM,
    CID.PARTY_IDENTIFICATION_NUM AS CID_PARTY_IDENTIFICATION_NUM,
    PPORT.PARTY_IDENTIFICATION_NUM AS PPORT_PARTY_IDENTIFICATION_NUM,
    IDV.BIRTH_DT AS BIRTH_DT,
    SX.SOURCE_KEY AS SOURCE_KEY
    FROM
    (
     SELECT
       AG.CONTRACT_NAME
      ,AG.THAI_CONTRACT_NAME
      ,AG.BASE_ACCOUNT_NUM
      ,AG.ACCOUNT_NUM
      ,AG.ACCOUNT_MODIFIER_NUM
     FROM P1VTTEDW.AGREEMENT AS AG
     INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
     ON BD.BUSINESSDATE BETWEEN AG.START_DT AND AG.END_DT
     AND AG.RECORD_DELETED_FLAG = 0
      AND AG.ACCOUNT_MODIFIER_NUM IN ('ST14','IM14') 
     AND AG.CTL_ID IN ('002','003')   ---[ST, IM]
    ) AS AG

    INNER JOIN 
     (
     SELECT
      AACS.ACCOUNT_NUM,
      AACS.ACCOUNT_MODIFIER_NUM

     FROM P1VTTEDW.AGMT_AGMT_CLASS_ASSOC AS AACS
     INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
     ON BD.BUSINESSDATE BETWEEN AACS.START_DT AND AACS.END_DT
      AND AACS.RECORD_DELETED_FLAG = 0
      AND AACS.ACCOUNT_MODIFIER_NUM IN ('ST14','IM14') 
      AND AACS.CTL_ID IN ('002','003')   ---[ST, IM]
      AND AACS.AGREEMENT_CLASSIFICATION_CD = 16  ---[AGMT LEVEL]
      AND AACS.AGREEMENT_CLASS_VALUE_CD IN (1,2,3)  ---[PARENT ACCT]
     ) AS AACS
    ON UPPER(RTRIM(AACS.ACCOUNT_NUM)) = UPPER(RTRIM(AG.ACCOUNT_NUM))
    AND UPPER(RTRIM(AACS.ACCOUNT_MODIFIER_NUM)) = UPPER(RTRIM(AG.ACCOUNT_MODIFIER_NUM))


    INNER JOIN 
     (
       SELECT AP.PARTY_ID,AP.ACCOUNT_NUM,AP.ACCOUNT_MODIFIER_NUM  
       FROM P1VTTEDW.ACCOUNT_PARTY AS AP
       INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
       ON BD.BUSINESSDATE BETWEEN AP.START_DT AND AP.END_DT
      AND AP.RECORD_DELETED_FLAG = 0
      AND AP.ACCOUNT_MODIFIER_NUM IN ('ST14','IM14') 
      AND AP.CTL_ID = '001'   ---[RM]
     ) AS AP
    ON UPPER(RTRIM(AACS.ACCOUNT_NUM)) = UPPER(RTRIM(AP.ACCOUNT_NUM))
    AND UPPER(RTRIM(AACS.ACCOUNT_MODIFIER_NUM)) = UPPER(RTRIM(AP.ACCOUNT_MODIFIER_NUM))

    LEFT OUTER JOIN
     ( 
       SELECT IDV.BIRTH_DT,IDV.INDIVIDUAL_PARTY_ID,IDV.GENDER_TYPE_CD
       FROM P1VTTEDW.INDIVIDUAL AS IDV
       INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
       ON BD.BUSINESSDATE BETWEEN IDV.START_DT AND IDV.END_DT
      AND IDV.RECORD_DELETED_FLAG = 0
      AND IDV.CTL_ID= '001' ---[RM] 
     ) AS IDV
     ON IDV.INDIVIDUAL_PARTY_ID = AP.PARTY_ID

    LEFT OUTER JOIN 
     (
       SELECT CID.PARTY_IDENTIFICATION_NUM,CID.PARTY_ID,CID.CTL_ID,CID.PARTY_IDENTIFICATION_TYPE_CD
       FROM P1VTTEDW.PARTY_IDENTIFICATION AS CID
       INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
       ON BD.BUSINESSDATE BETWEEN CID.START_DT AND CID.END_DT
      AND CID.RECORD_DELETED_FLAG = 0
      AND CID.CTL_ID = '001'   ---[RM] 
      AND CID.PARTY_IDENTIFICATION_TYPE_CD = 7    ---[CITIZNE ID]
     ) AS CID
    ON CID.PARTY_ID = AP.PARTY_ID

    LEFT OUTER JOIN   
     (
       SELECT PPORT.PARTY_IDENTIFICATION_NUM,PPORT.PARTY_ID,PPORT.CTL_ID,PPORT.PARTY_IDENTIFICATION_TYPE_CD
       FROM P1VTTEDW.PARTY_IDENTIFICATION AS PPORT
       INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
       ON BD.BUSINESSDATE BETWEEN PPORT.START_DT AND PPORT.END_DT
      AND PPORT.RECORD_DELETED_FLAG = 0
      AND PPORT.CTL_ID = '001'   ---[RM] 
      AND PPORT.PARTY_IDENTIFICATION_TYPE_CD = 9    ---[PASSPORT]
     ) AS PPORT
    ON PPORT.PARTY_ID = AP.PARTY_ID

    LEFT OUTER JOIN P1VUTEDW.M15350_GENDR_TYPE AS SX
    ON SX.EDW_CODE = IDV.GENDER_TYPE_CD 
    AND SX.SRC_CTL_ID = '001'   ---[RM] 
    AND SX.SOURCE_ID = 1

  ) AS FTE_C_DET
  ON UPPER(RTRIM(FTE_C.TO_ACCOUNT_NUM)) = UPPER(RTRIM(FTE_C_DET.BASE_ACCOUNT_NUM))
  /* END Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */

  WHERE Coalesce(FTE_C.TO_ACCOUNT_NUM,'') <> ''
  ) AS SRC
  Where SRC.R=1

  UNION ALL
  SELECT AS_OF_DT,SEQ_NO,COMP_NAME,CORPID_COMPCODE,VALUE_DATE,TO_ACCOUNT_NUM,Account_Name,EMPID_CITIZEN_PASSPORT,BIRTH_DATE,GENDER_TYPE,INSURANCE_COMPANY,INSURANCE_PLAN
     FROM(
  SELECT
    Cast(BD.BUSINESSDATE AS DATE ) AS AS_OF_DT 
   /*,CAST(SPP.SEQ AS INTEGER) AS SEQ_NO 
   ,CAST(SPP.CUST_NM AS VARCHAR(200)) AS COMP_NAME 
   ,CAST(SUBSTR(SPP.CORP_ID,19,12) AS VARCHAR(20)) AS CORPID_COMPCODE*/ --> Change by Wanutporn for CB62110020
   ,Cast(SPP.SEQ_NO AS INTEGER) AS SEQ_NO 
   ,Cast(SPP.COMP_NAME AS VARCHAR(200)) AS COMP_NAME 
   ,Cast(Substr(SPP.CORPID_COMPCODE,19,12) AS VARCHAR(20)) AS CORPID_COMPCODE
   ,Cast(FAE.EVENT_VALUE_DTTM AS DATE ) AS VALUE_DATE
   ,Cast(FTE_RD.TO_ACCOUNT_NUM AS VARCHAR(10)) AS TO_ACCOUNT_NUM

   /*
   ,CAST(TRIM(CASE WHEN FTE_RD.BENEF_THAI_NAME = '' OR FTE_RD.BENEF_THAI_NAME IS NULL 
           THEN FTE_RD.BENEFICIARY_LINE_1_NAME
           ELSE FTE_RD.BENEF_THAI_NAME END) AS VARCHAR(300)) AS ACCOUNT_NAME */ --Change

  /* START Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */ 
   --,Cast(Coalesce(FTE_RD.CONTRACT_NAME, FTE_RD.THAI_CONTRACT_NAME) AS VARCHAR(300))  AS ACCOUNT_NAME
  ,Cast(CASE WHEN SPP.Insurance_Company='FWD' THEN
           Coalesce(FTE_RD_DET.CONTRACT_NAME, FTE_RD_DET.THAI_CONTRACT_NAME)
    ELSE
          Trim(CASE WHEN FTE_RD.Benef_Thai_Name = ' ' OR FTE_RD.Benef_Thai_Name IS NULL THEN FTE_RD.Beneficiary_Line_1_Name ELSE FTE_RD.Benef_Thai_Name END)
      END AS VARCHAR(300)) AS Account_Name
   ,Cast(Coalesce(FTE_RD_DET.CID_PARTY_IDENTIFICATION_NUM, FTE_RD_DET.PPORT_PARTY_IDENTIFICATION_NUM) AS VARCHAR(100)) AS EMPID_CITIZEN_PASSPORT
   ,Cast(FTE_RD_DET.BIRTH_DT AS DATE ) AS BIRTH_DATE
   ,Cast(FTE_RD_DET.SOURCE_KEY AS VARCHAR(10) ) AS GENDER_TYPE
   ,Cast(SPP.INSURANCE_COMPANY AS VARCHAR(50)) AS INSURANCE_COMPANY
   ,Cast(SPP.INSURANCE_PLAN AS VARCHAR(50)) AS INSURANCE_PLAN
  /* END Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */
   ,Row_Number() Over (PARTITION BY  Cast(BD.BUSINESSDATE AS DATE ), Cast(SPP.SEQ_NO AS INTEGER), Cast(SPP.COMP_NAME AS VARCHAR(200)), Cast(Substr(SPP.CORPID_COMPCODE,19,12) AS VARCHAR(20)), FTE_RD.TO_ACCOUNT_NUM ORDER BY FAE.EVENT_VALUE_DTTM DESC) AS R        
  FROM P1VTTEDW.FINANCIAL_ACCOUNT_EVENT AS FAE

  INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
  ON Cast(FAE.EVENT_VALUE_DTTM AS DATE ) BETWEEN BD.FIRST_DAY_OF_MONTH AND BD.LAST_DAY_OF_MONTH
  AND FAE.CTL_ID ='052' ---[CN] 

  INNER JOIN P1VTTEDW.ACCOUNT_EVENT AS AE 
  ON FAE.EVENT_ID = AE.EVENT_ID
  AND FAE.EVENT_START_DT = AE.EVENT_START_DT
  AND AE.CTL_ID ='052' ---[CN]
  AND AE.RECORD_DELETED_FLAG = 0
  AND AE.ACCOUNT_MODIFIER_NUM = 'TBS'

  /*INNER JOIN P1DPYSTB.STB_PAYROLL_PA AS SPP
  ON TRIM(AE.ACCOUNT_NUM) = TRIM(SPP.CORP_ID)
  AND BD.BUSINESSDATE BETWEEN SPP.START_DT AND SPP.END_DT
  AND SPP.RECORD_DELETED_FLAG = 0
  AND SPP.CTL_ID = '388' --StartBiz*/ --Change

  /* START Modified by Wanutporn for CB62110020 Biz Anywhere Date 2020-04-16 
  INNER JOIN
  (
   SELECT STB.SEQ AS SEQ_NO, STB.CUST_NM AS COMP_NAME, TRIM(STB.CORP_ID) AS CORPID_COMPCODE
   ,'STB' AS INPUT_FLAG ,STB.SUB_DT AS SUB_DT 
   FROM P1DPYSTB.STB_PAYROLL_PA AS STB
   INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY BD
   ON BD.BUSINESSDATE BETWEEN STB.START_DT AND STB.END_DT
   AND STB.RECORD_DELETED_FLAG = 0
   AND STB.CTL_ID = '388' --STARTBIZ

   UNION ALL

   SELECT BCM.SEQ_NO AS SEQ_NO, BCM.COMP_NAME AS COMP_NAME, TRIM(BCM.CORPID_COMPCD) AS CORPID_COMPCODE
   ,'BCM' AS INPUT_FLAG, NULL AS SUB_DT
   FROM P1DPYBCM.BCM_PAYROLL_PA AS BCM
   INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY BD
   ON BD.BUSINESSDATE = BCM.AS_OF_DT
   AND BCM.RECORD_DELETED_FLAG = 0
   AND BCM.CTL_ID = '090'

  ) AS SPP
  ON TRIM(AE.ACCOUNT_NUM) = SPP.CORPID_COMPCODE
  -- END Modified by Wanutporn for CB62110020 Biz Anywhere Date 2020-04-16 */ --> Change

  /* START Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */
  INNER JOIN 
  ( 
   SELECT
    STB.Seq AS SEQ_NO,
    STB.CUST_NM AS COMP_NAME,
    STB.CORP_ID AS CORPID_COMPCODE,
    'STB' AS INPUT_FLAG,
    STB.SUB_DT AS SUB_DT,
    STB.INSURANCE_COMPANY,
    STB.INSURANCE_PLAN
   FROM P1DPYSTB.STB_PAYROLL_PA AS STB
   INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
   ON BD.BUSINESSDATE BETWEEN STB.START_DT AND STB.END_DT
   AND STB.RECORD_DELETED_FLAG = 0
   AND STB.CTL_ID = '388' --STARTBIZ
   AND Upper(STB.ID_TP) = 'RM_ID'

   UNION ALL
  SELECT 
    BCM.SEQ_NO,
    BCM.COMP_NAME,
    BCM.CORPID_COMPCD AS CORPID_COMPCODE,
    'BCM' AS INPUT_FLAG,
    NULL AS SUB_DT,
    BCM.INSURANCE_COMPANY,
    BCM.INSURANCE_PLAN


   FROM P1DPYBCM.BCM_PAYROLL_PA AS BCM
   INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
   ON  BCM.AS_OF_DT = BD.BUSINESSDATE
   AND BCM.CTL_ID = '090'
   AND Upper(BCM.Type1) = 'RM_ID'

  ) AS SPP
  ON UPPER(Trim(AE.ACCOUNT_NUM)) = UPPER(RTRIM(SPP.CORPID_COMPCODE))
  /* END Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */

  INNER JOIN P1VTTEDW.EVENT AS E_R
  ON FAE.EVENT_ID = E_R.EVENT_ID
  AND FAE.EVENT_START_DT = E_R.EVENT_START_DT
  AND E_R.CTL_ID ='052' ---[CN]
  AND E_R.RECORD_DELETED_FLAG = 0
  AND E_R.EVENT_FRONT_OFFICE_STATUS_CD = 7 --[CS044200 PP]

  INNER JOIN P1VTTEDW.EVENT_RELATIONSHIP AS ER
  ON E_R.EVENT_ID = ER.EVENT_ID 
  AND E_R.EVENT_START_DT = ER.EVENT_START_DT
  AND ER.CTL_ID ='052' --[CN]
  AND ER.RECORD_DELETED_FLAG = 0
  AND ER.EVENT_RELATIONSHIP_TYPE_CD = 1 --[Main-Sub]

  INNER JOIN P1VTTEDW.EVENT AS E_RD
  ON ER.RELATED_EVENT_ID = E_RD.EVENT_ID
  AND ER.RELATED_EVENT_START_DT = E_RD.EVENT_START_DT
  AND E_RD.CTL_ID = '052' --[CN]
  AND E_RD.RECORD_DELETED_FLAG = 0
  AND E_RD.EVENT_ACTIVITY_TYPE_CD = 7053 --[CS012950 PAY]

  INNER JOIN P1VTTEDW.CONTACT_EVENT AS CE_R
  ON E_R.EVENT_ID = CE_R.EVENT_ID
  AND E_R.EVENT_START_DT = CE_R.EVENT_START_DT
  AND CE_R.CTL_ID = '052' --[CN]
  AND CE_R.RECORD_DELETED_FLAG = 0
  AND CE_R.END_DT = DATE '9999-12-31'

  INNER JOIN P1VUTEDW.M06150_CHNL_TYPE AS M06150
  ON CE_R.CHANNEL_TYPE_CD = M06150.EDW_CODE
  AND M06150.SRC_CTL_ID = '052' --[CN]
  AND M06150.SOURCE_ID = 1
  AND M06150.SOURCE_KEY IN ('TBS', 'IP2') --[CS006150]

  /*
  INNER JOIN 
  ( SELECT 
     EVENT_ID
    ,EVENT_START_DT
    ,TO_ACCOUNT_NUM 
    ,BENEFICIARY_LINE_1_NAME
    ,BENEF_THAI_NAME
    FROM P1VTTEDW.FUNDS_TRANSFER_EVENT
    WHERE CTL_ID ='052' --[CN]
    AND RECORD_DELETED_FLAG = 0
    AND END_DT = '9999-12-31'
    AND SETTLEMENT_STATUS_TYPE_CD IN (1,2) --[CS044311:1:FD, CS044311:2:FR]
  ) AS FTE_RD
  ON ER.RELATED_EVENT_ID = FTE_RD.EVENT_ID  
  AND ER.RELATED_EVENT_START_DT = FTE_RD.EVENT_START_DT */ --Change for CB63110008 by Ratchata



  /* START Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */
  INNER JOIN
  ( SELECT 
       EVENT_ID
      ,EVENT_START_DT
      ,TO_ACCOUNT_NUM 
      ,BENEFICIARY_LINE_1_NAME
      ,BENEF_THAI_NAME
      FROM P1VTTEDW.FUNDS_TRANSFER_EVENT
      WHERE CTL_ID ='052' --[CN]
      AND RECORD_DELETED_FLAG = 0
      AND END_DT = '9999-12-31'
      AND SETTLEMENT_STATUS_TYPE_CD IN (1,2) --[CS044311:1:FD, CS044311:2:FR]
  ) AS FTE_RD
  ON ER.RELATED_EVENT_ID = FTE_RD.EVENT_ID  
  AND ER.RELATED_EVENT_START_DT = FTE_RD.EVENT_START_DT 

  LEFT OUTER JOIN 
  (
   SELECT
    AG.CONTRACT_NAME AS CONTRACT_NAME,
    AG.THAI_CONTRACT_NAME AS THAI_CONTRACT_NAME,
    AG.BASE_ACCOUNT_NUM AS BASE_ACCOUNT_NUM,
    CID.PARTY_IDENTIFICATION_NUM AS CID_PARTY_IDENTIFICATION_NUM,
    PPORT.PARTY_IDENTIFICATION_NUM AS PPORT_PARTY_IDENTIFICATION_NUM,
    IDV.BIRTH_DT AS BIRTH_DT,
    SX.SOURCE_KEY AS SOURCE_KEY

   FROM
    (
     SELECT
       AG.CONTRACT_NAME
      ,AG.THAI_CONTRACT_NAME
      ,AG.BASE_ACCOUNT_NUM
      ,AG.ACCOUNT_NUM
      ,AG.ACCOUNT_MODIFIER_NUM

     FROM P1VTTEDW.AGREEMENT AS AG
     INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
     ON BD.BUSINESSDATE BETWEEN AG.START_DT AND AG.END_DT
     AND AG.RECORD_DELETED_FLAG = 0
      AND AG.ACCOUNT_MODIFIER_NUM IN ('ST14','IM14') 
     AND AG.CTL_ID IN ('002','003')   ---[ST, IM]
    ) AS AG

    INNER JOIN 
     (
     SELECT
      AACS.ACCOUNT_NUM,
      AACS.ACCOUNT_MODIFIER_NUM

     FROM P1VTTEDW.AGMT_AGMT_CLASS_ASSOC AS AACS
     INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
     ON BD.BUSINESSDATE BETWEEN AACS.START_DT AND AACS.END_DT
      AND AACS.RECORD_DELETED_FLAG = 0
      AND AACS.ACCOUNT_MODIFIER_NUM IN ('ST14','IM14') 
      AND AACS.CTL_ID IN ('002','003')   ---[ST, IM]
      AND AACS.AGREEMENT_CLASSIFICATION_CD = 16  ---[AGMT LEVEL]
      AND AACS.AGREEMENT_CLASS_VALUE_CD IN (1,2,3)  ---[PARENT ACCT]
     ) AS AACS
    ON UPPER(RTRIM(AACS.ACCOUNT_NUM)) = UPPER(RTRIM(AG.ACCOUNT_NUM))
    AND UPPER(RTRIM(AACS.ACCOUNT_MODIFIER_NUM)) = UPPER(RTRIM(AG.ACCOUNT_MODIFIER_NUM))


    INNER JOIN 
     (
       SELECT AP.PARTY_ID,AP.ACCOUNT_NUM,AP.ACCOUNT_MODIFIER_NUM  
       FROM P1VTTEDW.ACCOUNT_PARTY AS AP
       INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
       ON BD.BUSINESSDATE BETWEEN AP.START_DT AND AP.END_DT
      AND AP.RECORD_DELETED_FLAG = 0
      AND AP.ACCOUNT_MODIFIER_NUM IN ('ST14','IM14') 
      AND AP.CTL_ID = '001'   ---[RM]
     ) AS AP
    ON UPPER(RTRIM(AACS.ACCOUNT_NUM)) = UPPER(RTRIM(AP.ACCOUNT_NUM))
    AND UPPER(RTRIM(AACS.ACCOUNT_MODIFIER_NUM)) = UPPER(RTRIM(AP.ACCOUNT_MODIFIER_NUM))

    LEFT OUTER JOIN
     ( 
       SELECT IDV.BIRTH_DT,IDV.INDIVIDUAL_PARTY_ID,IDV.GENDER_TYPE_CD
       FROM P1VTTEDW.INDIVIDUAL AS IDV
       INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
       ON BD.BUSINESSDATE BETWEEN IDV.START_DT AND IDV.END_DT
      AND IDV.RECORD_DELETED_FLAG = 0
      AND IDV.CTL_ID= '001' ---[RM] 
     ) AS IDV
     ON IDV.INDIVIDUAL_PARTY_ID = AP.PARTY_ID

    LEFT OUTER JOIN 
     (
       SELECT CID.PARTY_IDENTIFICATION_NUM,CID.PARTY_ID,CID.CTL_ID,CID.PARTY_IDENTIFICATION_TYPE_CD
       FROM P1VTTEDW.PARTY_IDENTIFICATION AS CID
       INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
       ON BD.BUSINESSDATE BETWEEN CID.START_DT AND CID.END_DT
      AND CID.RECORD_DELETED_FLAG = 0
      AND CID.CTL_ID = '001'   ---[RM] 
      AND CID.PARTY_IDENTIFICATION_TYPE_CD = 7    ---[CITIZNE ID]
     ) AS CID
    ON CID.PARTY_ID = AP.PARTY_ID

    LEFT OUTER JOIN   
     (
       SELECT PPORT.PARTY_IDENTIFICATION_NUM,PPORT.PARTY_ID,PPORT.CTL_ID,PPORT.PARTY_IDENTIFICATION_TYPE_CD
       FROM P1VTTEDW.PARTY_IDENTIFICATION AS PPORT
       INNER JOIN P1VTPBCM.VBCM_BDATE_MONTHLY AS BD
       ON BD.BUSINESSDATE BETWEEN PPORT.START_DT AND PPORT.END_DT
      AND PPORT.RECORD_DELETED_FLAG = 0
      AND PPORT.CTL_ID = '001'   ---[RM] 
      AND PPORT.PARTY_IDENTIFICATION_TYPE_CD = 9    ---[PASSPORT]
     ) AS PPORT
    ON PPORT.PARTY_ID = AP.PARTY_ID

    LEFT OUTER JOIN P1VUTEDW.M15350_GENDR_TYPE AS SX
    ON SX.EDW_CODE = IDV.GENDER_TYPE_CD 
    AND SX.SRC_CTL_ID = '001'   ---[RM] 
    AND SX.SOURCE_ID = 1

  ) AS FTE_RD_DET
  ON UPPER(RTRIM(FTE_RD.TO_ACCOUNT_NUM)) = UPPER(RTRIM(FTE_RD_DET.BASE_ACCOUNT_NUM))
  /* END Modified by Ratchata for CB63110008 PA Profile and Support New insurance company Date 2021-06-25 */

  /*WHERE FAE.EVENT_VALUE_DTTM >= SPP.SUB_DT
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SPP.CORP_ID, FTE_RD.TO_ACCOUNT_NUM ORDER BY FAE.EVENT_VALUE_DTTM DESC) = 1*/ --> Change
  /* START Modified by Wanutporn for CB62110020 Biz Anywhere Date 2020-04-16 */
  --WHERE (SPP.Input_Flag = 'BCM') OR (SPP.Input_Flag = 'STB' AND FAE.EVENT_VALUE_DTTM >= SPP.SUB_DT) << mig ori.
  WHERE (SPP.Input_Flag = 'BCM') OR (SPP.Input_Flag = 'STB' AND CAST(FAE.EVENT_VALUE_DTTM AS DATE) >= SPP.SUB_DT)  
  ) AS SRC
  Where SRC.R=1
