CREATE OR REPLACE VIEW P1VTXEDW.VESN_EVENT_01 (
  Event_Id,
  Event_Start_Dt,
  Event_Activity_TYPE_CD,
  Event_Reason_CD,
  Event_Status_CD,
  Event_Status_Reason_CD,
  TRANSACTION_Id,
  Event_Start_Tm,
  Event_END_Dt,
  Event_END_Tm,
  ACCOUNT_Ind,
  Financial_Ind,
  Contact_Ind,
  Incident_Ind,
  ACCOUNT_GROUP_Ind,
  Consent_Ind,
  Financial_ACCOUNT_Event_Ind,
  Internal_Investment_Event_Ind,
  EXTERNAL_Investment_Event_Ind,
  Customer_Portfolio_Ind,
  Event_GMT_Start_Dt,
  Event_GMT_Start_Tm,
  STATEMENT_Event_Ind,
  Card_Event_Ind,
  Swap_Leg_Event_Ind,
  Brokerage_TYPE_CD,
  ATM_SYSTEM_Event_Ind,
  Event_Amount_Ind,
  Host_TRANSACTION_Code_Num,
  FOREIGN_Remittance_Ind,
  Non_Financial_Event_Ind)
COMMENT '/*#####################################################################################
 Change Log :
	 >> Changed Date : 2013-06-22
	    Changed By   : Nattharut S.
	    Changed Desc : Add Single Code for Condition  Event_Code <> 408
   ------------------------------------------------------------------------------
   Target Table    : Event 
   Mapping Version : EDW_Source_ESN_MapXFormBusRule_Specification_V1-3.xls
   Generated By    : Teeranai Sriparkdee
   Generated Date  : 2008-06-20
   ------------------------------------------------------------------------------
   Change Log :
    >> Changed Date : 
       Changed By   : 
       Changed Desc : 
    >> Changed Date : 
       Changed By   : 
       Changed Desc : 
       Change Date : 2009-05-01 
       Change by : Kao
        Detail :  Change condition to fix error Invalid Time on  Part 4 
     -------------------------------------------------------------------------------
  TARGET TABLE    :    EVENT
  MAPPING VERSION : EDW_Source_ESN_MapXFormBusRule_Specification_V 2-8Part2)
  GENERATED BY    :  DURGA
  GENERATED DATE  : 2015-03-19
       -------------------------------------------------------------------------------
  TARGET TABLE    :    EVENT
  MAPPING VERSION : EDW_Source_ESN_MapXFormBusRule_Specification_V 2-9
  GENERATED BY    :  DURGA
  GENERATED DATE  : 2015-03-19
           ------------------------------------------------------------------------------
  TARGET TABLE    :    EVENT
  MAPPING VERSION : EDW_Source_ESN_MapXFormBusRule_Specification_V 3-3
  GENERATED BY    :  PARKAVI
  GENERATED DATE  : 2016-08-08
  Added view id VESN_AnyID_Trans_Event_01  for UR59020090: AnyID Project Phase2
    ------------------------------------------------------------------------------------
    TARGET TABLE    :   EVENT
    MAPPING VERSION : -
    UPDATED BY    :  TALILTIP T.
    UPDATED DATE  : 2017-08-09
    DESCRIPTION : Update data type of EVENT_ID from INTEGER to BIGINT
    ------------------------------------------------------------------------------------
    TARGET TABLE    : EVENT
    MAPPING VERSION : EDW_Source_ESN_MapXFormBusRule_Specification_V 4-2.ods
    UR NUMBER 		 : PF61040002-Enhance EDW to keep insurance payment history transaction
    UPDATED BY      : SMITA PATEL
    UPDATED DATE    : 2018-05-14
    DESCRIPTION     : Added VESN_InsurPaymtHist_Event_01 subview 
######################################################################################*/'
AS SELECT
    -----------------------------------------------------------------------------
   /*
   Part 1 
   View Name     : 1.VESN_event_log_Event_01
   Staging Table : 1.ESN_EVENT_LOG_1_0  
   */
   -----------------------------------------------------------------------------
   /*VESN_event_log_Event_01*/
    CAST(EVENT_LOG.EDW_RECORD_NO AS BIGINT)  AS Event_Id,
    EVENT_LOG.ESN_DATE  AS Event_Start_Dt,
    -- CAST(M12950.EDW_CODE AS SMALLINT)AS Event_Activity_TYPE_CD,
    coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_TYPE_CD,
    NULL AS Event_Reason_CD,
    CAST(M13400.EDW_CODE AS SMALLINT)AS  Event_Status_CD,
    NULL AS Event_Status_Reason_CD,
    CAST (EVENT_LOG.RUN_ID AS VARCHAR(100)) AS TRANSACTION_Id,
   DATE_FORMAT(EVENT_LOG.ESN_TIME ,'HH:mm:ss') AS Event_Start_Tm,
    TO_DATE ('1000-01-04','yyyy-MM-dd') AS Event_END_Dt,
    DATE_FORMAT(NULL,'HH:mm:ss')  AS Event_END_Tm,
    CAST ('YES' AS CHAR(3)) AS ACCOUNT_Ind,
    CAST (NULL AS CHAR(3)) AS Financial_Ind,
    CAST ('YSE' AS CHAR(3)) AS Contact_Ind,
    NULL AS Incident_Ind,
    NULL AS ACCOUNT_GROUP_Ind,
    NULL AS Consent_Ind,
    CAST (NULL AS CHAR(3)) AS Financial_ACCOUNT_Event_Ind,
    CAST (NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
    NULL AS EXTERNAL_Investment_Event_Ind,
    CAST (NULL AS CHAR(3)) AS Customer_Portfolio_Ind,
    NULL AS Event_GMT_Start_Dt,
    NULL AS Event_GMT_Start_Tm,
    NULL AS STATEMENT_Event_Ind,
    CASE 
     WHEN EVENT_LOG.CARD_NO IS NOT NULL THEN CAST('YES' AS CHAR(3))
     ELSE CAST( NULL AS CHAR(3))
    END  AS Card_Event_Ind,
    NULL AS Swap_Leg_Event_Ind,
     NULL  AS Brokerage_TYPE_CD,
     CAST (NULL AS CHAR(3)) AS ATM_SYSTEM_Event_Ind,
     CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
     CAST (NULL AS VARCHAR(50)) AS Host_TRANSACTION_Code_Num,
     NULL AS FOREIGN_Remittance_Ind,
     CASE 
     WHEN EVENT_LOG.Acc_From IS NOT NULL THEN CAST('YES' AS CHAR(3))
     ELSE CAST (NULL AS CHAR(3))
    END AS Non_Financial_Event_Ind
  
  
   FROM  P1VSTEDW.ESN_EVENT_LOG_1_0 AS EVENT_LOG
   
   LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
   ON M12950.Source_Key =  EVENT_LOG.EVENT_CODE
   AND M12950.Src_Ctl_Id = '044'
   AND M12950.Source_Id = 1
   
   LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
   ON M13400.Source_Key = EVENT_LOG.RESPONSE_CODE
   AND M13400.Src_Ctl_Id = '044'
   AND M13400.Source_Id = 1
  
  /*For Fix Job fail in case have Charactor on 2013-06-22
    WHERE EVENT_LOG.Event_Code <> 408
    WHERE EVENT_LOG.Event_Code <> '408' -- 2015-06-20 Remove from R56030131
  */
   
 
   
/*--UNION ALL ----REMOVED  FOR R56030131
  
   
    Part 2
    View Name     : 1.VESN_Event_log_fin_Event_01
         2. VESN_Event_log_fin_Event_02 (Fee Amount)
    Staging Table : 1.ESN_EVENT_FINANCIAL_1_0  
   
   
  SELECT 
    CAST(CASE 
     EVENT
     --WHEN TMP.SEQ = 1 THEN EVENT_FIN.EDW_RECORD_NO 
     EVENT(FEE AMOUNT )
     WHEN TMP.SEQ = 2 THEN EVENT_FIN.EDW_RECORD_NO + 1
     ELSE NULL
    END AS BIGINT)AS Event_Id,
    EVENT_FIN.ESN_DATE AS Event_Start_Dt,
    CAST(M12950.EDW_CODE AS SMALLINT) AS Event_Activity_TYPE_CD,
    NULL AS Event_Reason_CD,
    CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_CD,
    NULL AS Event_Status_Reason_CD,
   CAST (EVENT_FIN.RUN_ID AS VARCHAR(100))  AS TRANSACTION_Id,
   CAST (EVENT_FIN.ESN_TIME AS TIME(6) )  AS Event_Start_Tm,
    DATE_FORMAT ('1000-01-04','yyyy-MM-dd') AS Event_END_Dt,
    CAST(NULL AS TIME(6)) AS Event_END_Tm,
    CASE 
    
     WHEN TMP.SEQ = 1 THEN CAST ('YES' AS CHAR(3))
     ELSE NULL
    END AS ACCOUNT_Ind,
    CAST('YES' AS CHAR(3)) AS Financial_Ind,
    CASE 
   
     WHEN TMP.SEQ = 1 THEN CAST('YES' AS CHAR(3))
     ELSE NULL
    END AS Contact_Ind,
    NULL AS Incident_Ind,
    NULL AS ACCOUNT_GROUP_Ind,
    NULL AS Consent_Ind,
    CAST (NULL AS CHAR(3)) AS Financial_ACCOUNT_Event_Ind,
    CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
    NULL AS EXTERNAL_Investment_Event_Ind,
    CAST (NULL AS CHAR(3)) AS Customer_Portfolio_Ind,
    NULL AS Event_GMT_Start_Dt,
    NULL AS Event_GMT_Start_Tm,
    NULL AS STATEMENT_Event_Ind,
    CASE
     WHEN TMP.SEQ = 1 
      THEN 
       CASE 
        WHEN EVENT_FIN.Card_NO IS NOT NULL THEN CAST ('Y' AS CHAR(3))
         ELSE CAST(NULL AS CHAR(3)) 
        END
      ELSE   CAST(NULL AS CHAR(3))
    END AS Card_Event_Ind,
    NULL AS Swap_Leg_Event_Ind,
     NULL AS Brokerage_TYPE_CD,
     CAST(NULL AS CHAR(3)) AS ATM_SYSTEM_Event_Ind,
     NULL AS Event_Amount_Ind,
     CAST (EVENT_FIN.EVENT_CODE AS VARCHAR(50)) AS Host_TRANSACTION_Code_Num,
     NULL AS FOREIGN_Remittance_Ind,
     CAST (NULL AS CHAR(3)) AS Non_Financial_Event_Ind
    
  
    FROM   P1VSTEDW.ESN_EVENT_FINANCIAL_1_0 AS EVENT_FIN
    
     CROSS JOIN 
      (
       SELECT ((CURRENT_DATE - CDT.DEFAULT_DATE) + 1 )(INTEGER) AS MSEQ
       FROM P1VUTEDW.Char_Calendar AS CDT
       WHERE DEFAULT_DATE BETWEEN (CURRENT_DATE - 1 ) AND CURRENT_DATE
      ) TMP(SEQ) 
  
    LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
    ON M12950.Source_Key = EVENT_FIN.EVENT_CODE
    AND M12950.Src_Ctl_Id = '044'
    AND M12950.Source_Id = 1
   
    LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
    ON M13400.Source_Key = EVENT_FIN.RESPONSE_CODE 
    AND M13400.Src_Ctl_Id = '044'
    AND M13400.Source_Id = 1*/
    
UNION ALL
    
    	  
  /* -- Part 3
    View Name     : 1. VESN_online_Hist_Event_01
    Staging Table : 1.ESN_Online_history_1_0
   */
    SELECT 
     CAST( ONLINE_HIST.EDW_RECORD_NO   AS BIGINT)AS Event_Id,
    TO_DATE(ONLINE_HIST.TRX_DATE ,'yyyy-MM-dd') AS Event_Start_Dt,
    -- CAST(M12950.EDW_CODE AS SMALLINT) AS Event_Activity_TYPE_CD,
    coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_TYPE_CD,
    NULL AS Event_Reason_CD,
    CAST(M13400.EDW_CODE AS SMALLINT )AS Event_Status_CD,
    NULL AS Event_Status_Reason_CD,
    CAST ( ONLINE_HIST.PAYMENT_ID AS VARCHAR(100)) AS TRANSACTION_Id,
    DATE_FORMAT(ONLINE_HIST.TRX_TIME,'HH:mm:ss')AS Event_Start_Tm,
    TO_DATE('1000-01-04','yyyy-MM-dd') AS Event_END_Dt,
    DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
   /* CASE 
     WHEN  TMP.SEQ = 1 THEN CAST ('YES' AS CHAR(3))
     ELSE NULL
    END AS ACCOUNT_Ind,*/--REMOVED  FOR R56030131
    CAST('YES' AS CHAR(3))AS ACCOUNT_Ind,
    CAST ('YES' AS CHAR(3)) AS Financial_Ind,
    CAST(NULL AS CHAR(3)) AS Contact_Ind,
    NULL AS Incident_Ind,
    NULL AS ACCOUNT_GROUP_Ind,
    NULL AS Consent_Ind,
    CAST(NULL AS CHAR(3)) AS Financial_ACCOUNT_Event_Ind,
    CAST (NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
    NULL AS EXTERNAL_Investment_Event_Ind,
    CAST(NULL AS CHAR(3)) AS Customer_Portfolio_Ind,
    NULL AS Event_GMT_Start_Dt,
    NULL AS Event_GMT_Start_Tm,
    NULL AS STATEMENT_Event_Ind,
    /*CASE 
     WHEN TMP.SEQ = 1 THEN */--REMOVED  FOR R56030131
       CASE 
        WHEN  ONLINE_HIST.Card_NO IS NOT NULL THEN CAST('YES' AS CHAR(3))
        ELSE NULL
       END 
  AS Card_Event_Ind,
    NULL AS Swap_Leg_Event_Ind,
     NULL AS Brokerage_TYPE_CD,
    CAST( NULL AS CHAR(3)) AS ATM_SYSTEM_Event_Ind,
     CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
     CAST(ONLINE_HIST.EVENT_CODE AS VARCHAR(50))  AS Host_TRANSACTION_Code_Num,
     NULL AS FOREIGN_Remittance_Ind,
     CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind
     
   
    FROM P1VSTEDW.ESN_ONLINE_HISTORY_1_0 AS ONLINE_HIST
    
    /*CROSS JOIN 
      (
       SELECT ((CURRENT_DATE - CDT.DEFAULT_DATE) + 1 )(INTEGER) AS MSEQ
       FROM P1VUTEDW.Char_Calendar AS CDT
       WHERE DEFAULT_DATE BETWEEN (CURRENT_DATE - 1 ) AND CURRENT_DATE
      ) TMP(SEQ) */--REMOVED  FOR R56030131
      
      
  
    LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
    ON M12950.Source_Key = ONLINE_HIST.Event_Code
    AND M12950.Src_Ctl_id = '044'
    AND M12950.Source_id = 1
    
    LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
    ON M13400.Source_Key = ONLINE_HIST.REC_STATUS
    AND M13400.Source_id = 1
    
    UNION ALL 


   /*-- Part 4
   View Name     : 1.VESN_PYMT_Hist_Event_01
  Staging Table : 1.ESN_payment_history_1_0  
   */
  SELECT
    CAST(PAY_HIST.EDW_RECORD_NO AS BIGINT ) AS  Event_Id ,
    TO_DATE(PAY_HIST.TRX_Date,'yyyy-MM-dd') AS Event_Start_Dt,
    -- CAST(M12950.EDW_CODE AS  SMALLINT)AS Event_Activity_TYPE_CD,
    coalesce(CAST(M12950.EDW_CODE AS  SMALLINT),0) AS Event_Activity_TYPE_CD,
    NULL AS Event_Reason_CD,
   CAST( M13400.EDW_CODE AS SMALLINT) AS Event_Status_CD,
    NULL AS Event_Status_Reason_CD,
    CAST (PAY_HIST.Payment_Id AS VARCHAR(100)) AS TRANSACTION_Id,
    DATE_FORMAT(TRIM(SUBSTR(PAY_HIST.TRX_Time,1,2))||':'||TRIM(SUBSTR(PAY_HIST.TRX_Time,3,2))||':'||
    /*---TRIM(SUBSTR(PAY_HIST.TRX_Time,5,2)) */
   /* ----  change this to solve some records  > 59    change date 2009-05-01 */
	    CASE WHEN 
    TRIM(SUBSTR(PAY_HIST.TRX_Time,5,2) )
    NOT BETWEEN '00' AND '59' THEN '59' 
    ELSE 
    TRIM(SUBSTR(PAY_HIST.TRX_Time,5,2)) 
    END  
    ,'HH:mm:ss') AS Event_Start_Tm,
    NULL AS Event_END_Dt,
    DATE_FORMAT(NULL ,'HH:mm:ss') AS Event_END_Tm,
   /* CASE
     WHEN TMP.SEQ = 1 THEN CAST('YES' AS CHAR(3))
     ELSE NULL
    END AS ACCOUNT_Ind,*/----REMOVED  FOR R56030131
    CAST('YES' AS CHAR(3))AS ACCOUNT_Ind,
    CAST('YES' AS CHAR(3)) AS Financial_Ind,
    CAST(NULL AS CHAR(3)) AS Contact_Ind,
    NULL AS Incident_Ind,
    NULL AS ACCOUNT_GROUP_Ind,
    NULL AS Consent_Ind,
    CAST(NULL AS CHAR(3)) AS Financial_ACCOUNT_Event_Ind,
    CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
  NULL AS EXTERNAL_Investment_Event_Ind,
   CAST(NULL AS CHAR(3)) AS Customer_Portfolio_Ind,
    NULL AS Event_GMT_Start_Dt,
    NULL AS Event_GMT_Start_Tm,
    NULL AS STATEMENT_Event_Ind,
      /*CASE 
        WHEN  TMP.SEQ = 1 AND (PAY_HIST.CARD_NO IS NOT NULL) THEN CAST( 'YES' AS CHAR(3))
        ELSE  CAST(NULL AS CHAR(3)) 
       END AS Card_Event_Ind,*/----REMOVED  FOR R56030131
       CASE WHEN  (PAY_HIST.CARD_NO IS NOT NULL) THEN CAST( 'YES' AS CHAR(3))
        ELSE  CAST(NULL AS CHAR(3)) 
       END AS Card_Event_Ind,
       
    NULL AS Swap_Leg_Event_Ind,
     NULL AS Brokerage_TYPE_CD,
     CAST(NULL AS CHAR(3)) AS ATM_SYSTEM_Event_Ind,
     CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
     CAST(PAY_HIST.Event_Code AS CHAR(3))  AS Host_TRANSACTION_Code_Num,
     NULL AS FOREIGN_Remittance_Ind,
      CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind
    /*-- FROM P1VSTEDW.ESN_payment_history_1_0 AS PAY_HIST*/
    /*------------ change this  view name   : 2009-05-01 -----------------*/
     FROM P1VSTEDW.ESN_payment_history_1_0_DD AS PAY_HIST
    
   /* CROSS JOIN 
      (
       SELECT ((CURRENT_DATE - CDT.DEFAULT_DATE) + 1 )(INTEGER) AS MSEQ
       FROM P1VUTEDW.Char_Calendar AS CDT
       WHERE DEFAULT_DATE BETWEEN (CURRENT_DATE - 1 ) AND CURRENT_DATE
      ) TMP(SEQ) */
     
     LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
     ON M12950.Source_Key = PAY_HIST.Event_Code
     AND M12950.Src_Ctl_Id ='044'
     AND M12950.Source_id = 1
     
     LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
     ON M13400.Source_Key = Pay_Hist.Rec_Status 
     AND M13400.Src_Ctl_Id ='044'
     AND M13400.Source_Id = 1
    
    
   UNION ALL

    /*
   Part 5
   View Name     : 1.VESN_other_bank_trans_Event_01
         2.VESN_other_bank_trans_Event_02
         3.VESN_other_bank_trans_Event_03
         4. VESN_other_bank_trans_Event_04
   Staging Table : 1.ESN_Other_Bank_transfer_1_0
   */
   SELECT 
   CAST(CASE 
 WHEN TMP.SEQ = 1 THEN OTHER_BANK.EDW_RECORD_NO
 WHEN TMP.SEQ = 2 THEN OTHER_BANK.EDW_RECORD_NO + 1
 WHEN TMP.SEQ = 3 THEN OTHER_BANK.EDW_RECORD_NO + 2
 WHEN TMP.SEQ = 4 THEN OTHER_BANK.EDW_RECORD_NO + 3
END  AS BIGINT)  AS Event_Id,
TO_DATE(OTHER_BANK.TRANS_DATE,'yyyy-MM-dd') AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_TYPE_CD,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT) AS Event_Status_CD,
M13350.EDW_CODE AS Event_Status_Reason_CD,
CAST(OTHER_BANK.TRANS_ID AS VARCHAR(100)) AS TRANSACTION_Id,
DATE_FORMAT(OTHER_BANK.TRANS_TIME,'HH:mm:ss') AS Event_Start_Tm,
TO_DATE('1000-01-04','yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CASE 
 WHEN TMP.SEQ = 1 THEN CAST('YES' AS CHAR(3))
 ELSE NULL
END AS ACCOUNT_Ind,
CAST('YES' AS CHAR(3)) AS Financial_Ind,
CAST( NULL AS CHAR(3)) AS Contact_Ind,
NULL AS Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS Consent_Ind,
CAST( NULL AS CHAR(3)) AS Financial_ACCOUNT_Event_Ind,
  CAST( NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS EXTERNAL_Investment_Event_Ind,
  CAST( NULL AS CHAR(3)) AS Customer_Portfolio_Ind,
NULL AS Event_GMT_Start_Dt,
NULL AS Event_GMT_Start_Tm,
NULL AS STATEMENT_Event_Ind,
CASE 
 WHEN TMP.SEQ = 1 THEN CAST('YES' AS CHAR(3))
 ELSE NULL
END AS Card_Event_Ind,
NULL AS Swap_Leg_Event_Ind,
 NULL AS Brokerage_TYPE_CD,
   CAST( NULL AS CHAR(3)) AS ATM_SYSTEM_Event_Ind,
 CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
   CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
 NULL AS FOREIGN_Remittance_Ind,
   CAST( NULL AS CHAR(3)) AS Non_Financial_Event_Ind

  FROM P1VSTEDW.ESN_TRANS_OTHER_BANK_1_0 AS OTHER_BANK
   
   CROSS JOIN 
      (
       SELECT (datediff(CURRENT_DATE,CDT.DEFAULT_DATE) + 1 ) AS SEQ
       FROM P1VUTEDW.Char_Calendar AS CDT
       WHERE DEFAULT_DATE BETWEEN (CURRENT_DATE - 3 ) AND CURRENT_DATE
      ) TMP 
   
   LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
   ON  M12950.Source_Key =OTHER_BANK.TRN_TYPE
	 AND  M12950.Src_Ctl_Id = '044'
   AND M12950.Source_Id = 2
   
   LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
   ON M13400.Source_Key = OTHER_BANK.Status
   AND M13400.Src_Ctl_Id = '044'
   AND M13400.Source_Id = 1
   
   LEFT OUTER JOIN P1VUTEDW.M13350_EVENT_STS_REASN AS M13350
   ON M13350.Source_Key = OTHER_BANK.REJECT_REASON
   AND M13350.Src_Ctl_Id = '044'
   AND M13350.Source_Id = 1
   
   UNION ALL 
   
    /*
      Part 6
      View Name     : 1.VESN_ESN_HISTORY_1_0_Event
     Staging Table : 1.ESN_HISTORY_1_0  
   */

SELECT
CAST(HIST.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(HIST.TRX_DATE ,'yyyy-MM-dd') AS Event_Start_Dt,
coalesce(CAST(BMAP2.EDW_CODE AS SMALLINT),0) AS Event_Activity_TYPE_CD,
NULL AS Event_Reason_CD,
CAST(BMAP.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL AS VARCHAR(100)) AS TRANSACTION_Id,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_Start_Tm,
TO_DATE('1000-01-04' ,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL ,'HH:mm:ss') AS Event_END_Tm,
CAST('Y' AS CHAR(3)) AS ACCOUNT_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_Ind,
CAST(NULL AS CHAR(3)) AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS CHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
HIST.TRX_STATUS AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM P1VSTEDW.ESN_HISTORY_1_0 AS HIST

LEFT JOIN  P1VUTEDW.M13400_EVENT_STS AS BMAP 
ON BMAP.SOURCE_KEY = HIST.TRX_STATUS 
AND BMAP.SRC_CTL_ID = '044'
AND BMAP.SOURCE_ID = 2

LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS BMAP2
ON BMAP2.SOURCE_KEY = 'Admin Transactions' 
AND BMAP2.SRC_CTL_ID = '044'
AND BMAP2.SOURCE_ID = 1 

UNION ALL

/*
 VIEW NAME     : .VESN_INS_HIST_EVENT_01
 STAGING TABLE : VSTEDW.ESN_INSURANCE_HISTORY_1_0
*/
SELECT
CAST(INSURANCE_HISTORY.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(INSURANCE_HISTORY.TRX_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(INSURANCE_HISTORY.PAYMENT_ID AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(INSURANCE_HISTORY.TRX_TIME ,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE('1000-01-04','yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL ,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS CHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(CASE WHEN INSURANCE_HISTORY.Card_no IS NOT NULL
THEN 'YES'
ELSE NULL 
End AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_INSURANCE_HIST_1_0 AS INSURANCE_HISTORY

LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400 
ON   M13400.SOURCE_KEY = INSURANCE_HISTORY.REC_STATUS
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1

CROSS JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
WHERE M12950.SOURCE_KEY = '201'-- (PAYBILL)
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1 


UNION ALL 

/*
 VIEW NAME     : .VESN_DEEJUNGTRANSFER_EVENT_01
STAGING TABLE : VSTEDW.ESN_DEEJUNG_TRANSFER_1_0
*/
SELECT
CAST(DEEJUNG_TRANSFER.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(DEEJUNG_TRANSFER.TRX_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(DEEJUNG_TRANSFER.TRANS_ID AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(DEEJUNG_TRANSFER.TRX_TIME ,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL ,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS CHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(CASE WHEN DEEJUNG_TRANSFER.Card_no IS NOT NULL
THEN 'YES'
ELSE NULL 
End AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
 CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind
FROM  P1VSTEDW.ESN_DEEJUNG_TRANSFER_1_0 AS DEEJUNG_TRANSFER

LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON   M13400.SOURCE_KEY = DEEJUNG_TRANSFER.STATUS
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1 

CROSS JOIN  P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
WHERE  M12950.SOURCE_KEY =  'DJ1'-- (Dee Jung Transfer)
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1 



UNION ALL

/*
 VIEW NAME     : .VESN_CLICKFORDEEJUNG_EVENT_01
 STAGING TABLE : VSTEDW.ESN_CLICK_FOR_DEEJUNG_1_0
*/
SELECT
CAST(CLICK_FOR_DEEJUNG.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(CLICK_FOR_DEEJUNG.TRX_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(CLICK_FOR_DEEJUNG.TRANS_ID AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(CLICK_FOR_DEEJUNG.TRX_TIME,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS CHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(CASE WHEN CLICK_FOR_DEEJUNG.Card_no IS NOT NULL
THEN 'YES'
ELSE NULL 
End AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_CLICKFOR_DEEJUNG_1_0 AS CLICK_FOR_DEEJUNG

LEFT OUTER  JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON  M13400.SOURCE_KEY = CLICK_FOR_DEEJUNG.STATUS
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1 

CROSS JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
WHERE M12950.SOURCE_KEY =  'DJ2' --(Call for Dee Jung)
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1 

UNION ALL 

/*
VIEW NAME     : .VESN_STT_PAYMENT_Event_01
 STAGING TABLE : VSTEDW.ESN_STT_PAYMENT_1_0
*/
SELECT
CAST(STT_PAYMENT.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(STT_PAYMENT.TRX_DATE,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(STT_PAYMENT.PAYMENT_ID AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(STT_PAYMENT.TRX_TIME,'HH:mm:ss') AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL ,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS CHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_STT_PAYMENT_1_0 AS STT_PAYMENT

LEFT OUTER  JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON  M12950.SOURCE_KEY =  STT_PAYMENT.STATUS
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 4

LEFT  OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON  M13400.SOURCE_KEY = STT_PAYMENT.STATUS
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1 

UNION ALL 
/*
 VIEW NAME     : .VESN_TEMPLINE_Event_01
 STAGING TABLE : VSTEDW.ESN_TEMPLINE_1_0
*/
SELECT
CAST(ESN_TEMPLINE.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_TEMPLINE.TxnDateTime ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL  AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_TEMPLINE.TxnDateTime,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL ,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(CASE WHEN ESN_TEMPLINE.AccountNo IS NOT NULL
THEN 'YES'
ELSE NULL 
End AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind


FROM  P1VSTEDW.ESN_TEMPLINE_1_0 AS ESN_TEMPLINE

LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON M12950.SOURCE_KEY = ESN_TEMPLINE.TxnType
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1 

LEFT OUTER  JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON M13400.SOURCE_KEY=CAST(ESN_TEMPLINE.StatusCode AS VARCHAR(100))
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1 

UNION ALL 

/*
 VIEW NAME     : .VESN_OnlineRedeem_Event_01
 STAGING TABLE : VSTEDW.ESN_OnlineRedeem_1_0
*/
SELECT
CAST(ESN_ONLINEREDEEM.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_ONLINEREDEEM.TxnDateTime,'yyyy-MM-dd HH:mm:ss') AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL  AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_ONLINEREDEEM.TxnDateTime,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(CASE WHEN ESN_ONLINEREDEEM.AccountNo IS NOT NULL
THEN 'YES'
ELSE NULL 
End AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_ONLINEREDEEM_1_0 AS ESN_ONLINEREDEEM

LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON M12950.SOURCE_KEY = ESN_ONLINEREDEEM.TxnType
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1 

LEFT OUTER  JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON M13400.SOURCE_KEY=CAST(ESN_ONLINEREDEEM.StatusCode AS VARCHAR(100))
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1 


UNION ALL

/*
 VIEW NAME     : .VESN_REQUEST_OTP_Event_01
 STAGING TABLE : VSTEDW.ESN_REQUEST_OTP_1_0
*/
SELECT
CAST(ESN_REQUEST_OTP.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_REQUEST_OTP.CREATE_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL  AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_REQUEST_OTP.CREATE_TIME,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS CHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_REQUEST_OTP_1_0 AS ESN_REQUEST_OTP

LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON M12950.SOURCE_KEY=ESN_REQUEST_OTP.FUNCTION_NAME
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1  

LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON   M13400.SOURCE_KEY = ESN_REQUEST_OTP.OTP_STATUS
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 2 

UNION ALL 
/*
 VIEW NAME     : .VESN_SMS_NOTIFICATION_Event_01
STAGING TABLE : VSTEDW.ESN_SMS_NOTIFICATION_1_0
*/
SELECT
CAST(ESN_SMS_NOTIFICATION.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_SMS_NOTIFICATION.ESN_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL  AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_SMS_NOTIFICATION.ESN_TIME,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL ,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS CHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_SMS_NOTIFICATION_1_0 AS ESN_SMS_NOTIFICATION

LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON M12950.SOURCE_KEY=ESN_SMS_NOTIFICATION.ESN_TYPE
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1

CROSS JOIN  P1VUTEDW.M13400_EVENT_STS AS M13400
WHERE M13400.SOURCE_KEY = 'S'   --SUCCESS
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1  



UNION ALL 

/*EMOVED FOR EDW_Source_ESN_MapXFormBusRule_Specification_V 2-9
 VIEW NAME     : .VESN_TRANS_SEND_SMS_Event_01
 STAGING TABLE : VSTEDW.ESN_TRANS_SEND_SMS_1_0

SELECT
CAST(ESN_TRANS_SEND_SMS.EDW_RECORD_NO AS BIGINT) AS Event_Id,
DATE_FORMAT(ESN_TRANS_SEND_SMS.TRANSFER_DATE,'yyyy-MM-dd')AS Event_Start_Dt,
CAST(M12950.EDW_CODE AS SMALLINT)AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(NULL  AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL  AS  VARCHAR(100))AS Transaction_Id,
CAST(ESN_TRANS_SEND_SMS.TRANSFER_TIME AS TIME(6))AS Event_Start_Tm,
DATE_FORMAT(NULL,'yyyy-MM-dd') AS Event_END_Dt,
CAST(NULL AS TIME(6)) AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
NULL AS Event_Amount_Ind,
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_TRANS_SEND_SMS_1_0 AS ESN_TRANS_SEND_SMS

LEFT OUTER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON M12950.SOURCE_KEY =  ESN_TRANS_SEND_SMS.TRANSFER_TYPE
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1 


UNION ALL */
/*
  --------------------------------------------------------------------------
  VIEW NAME     : .VESN_Vircard_Fund_Trans_Event_01
  STAGING TABLE : VSTEDW.ESN_VCARD_FUND_TRANS_1_0
  --------------------------------------------------------------------
*/
SELECT
CAST(ESN_VCARD_FUND_TRANS.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_VCARD_FUND_TRANS.TRANS_DATE,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(ESN_VCARD_FUND_TRANS.TRANS_ID  AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_VCARD_FUND_TRANS.TRANS_TIME,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL ,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(CASE WHEN ESN_VCARD_FUND_TRANS.Card_no IS NOT NULL
THEN 'YES'
ELSE NULL 
End AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_VCARD_FUND_TRANS_1_0 AS ESN_VCARD_FUND_TRANS

LEFT OUTER  JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON M12950.SOURCE_KEY =  ESN_VCARD_FUND_TRANS.TRANS_TYPE
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 3 

CROSS JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
WHERE   M13400.SOURCE_KEY  ='S'   --Success
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1 

UNION ALL 


/*
 VIEW NAME     : .VESN_LOGIN_Event_01
 STAGING TABLE : VSTEDW.ESN_LOGIN_1_0
*/
SELECT
CAST(ESN_LOGIN.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_LOGIN.LOGIN_DATE,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_LOGIN.LOGIN_TIME,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL ,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST(NULL AS CHAR(3))AS  Account_Ind,
CAST(NULL AS CHAR(3))AS Financial_Ind,
CAST(NULL AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL  AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_LOGIN_1_0 AS ESN_LOGIN

LEFT OUTER  JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON   M13400.SOURCE_KEY =ESN_LOGIN.LOGIN_STATUS
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 2 

CROSS JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
WHERE M12950.SOURCE_KEY =  'EASYNET LOGIN'
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1

UNION ALL 


/*
 VIEW NAME     : .VESN_Trans_Event_01
 STAGING TABLE : VSTEDW.ESN_TRANSFER_1_0
*/
SELECT
CAST(ESN_TRANSFER.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_TRANSFER.TRX_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(ESN_TRANSFER.TRANS_ID AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_TRANSFER.TRX_TIME,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL ,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES' AS CHAR(3))AS Financial_Ind,
CAST('YES' AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL  AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_TRANSFER_1_0 AS ESN_TRANSFER

LEFT OUTER  JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON   M13400.SOURCE_KEY =ESN_TRANSFER.REC_STATUS
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1 

LEFT OUTER  JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON  M12950.SOURCE_KEY =  ESN_TRANSFER.TRANSFER_TYPE
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 5

UNION ALL 

/*
 VIEW NAME     : .VESN_Regist_Event_01
 STAGING TABLE : VSTEDW.ESN_REGISTRATION_1_0
*/
SELECT
CAST(ESN_REGISTRATION.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_REGISTRATION.ESN_DATE,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(NULL,'HH:mm:ss')AS Event_Start_Tm,
DATE_FORMAT(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST(NULL AS CHAR(3))AS Financial_Ind,
CAST(NULL AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL  AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,  --Modified for UR59020090: AnyID Project Phase2
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_REGISTRATION_1_0 AS ESN_REGISTRATION

CROSS JOIN  P1VUTEDW.M13400_EVENT_STS AS M13400

CROSS    JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
WHERE    M12950.SOURCE_KEY ='EASYNET REGISTRAION PROFILE'
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1 
AND  M13400.SOURCE_KEY = 'S'   --Success
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1
AND  ESN_REGISTRATION.TRX_STATUS <> 110
UNION ALL 
/*
 VIEW NAME     : .VESN_Cancel_Event_01
STAGING TABLE : VSTEDW.ESN_CANCELLATION_1_0
*/
SELECT
CAST(ESN_CANCELLATION.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_CANCELLATION.ESN_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(NULL AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(NULL,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST(NULL AS CHAR(3))AS Financial_Ind,
CAST(NULL AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST(NULL AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL  AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST(NULL AS CHAR(3)) AS Event_Amount_Ind,
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_CANCELLATION_1_0 AS ESN_CANCELLATION

CROSS JOIN  P1VUTEDW.M13400_EVENT_STS AS M13400

CROSS    JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
WHERE    M12950.SOURCE_KEY ='EASYNET CANCELLATION PROFILE'
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1 
AND  M13400.SOURCE_KEY = 'S'   --Success
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1
AND  ESN_CANCELLATION.TRX_STATUS <> 202

UNION ALL 

/*
 VIEW NAME     : VESN_AnyID_Trans_Event_01
STAGING TABLE : VSTEDW.ESN_AnyID_TRANSFER_1_0
 Code Added for UR59020090: AnyID Project Phase2
*/

SELECT
CAST(ESN_ANYID_TRANS.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_ANYID_TRANS.TRX_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
CAST(M13350.EDW_CODE AS SMALLINT) AS Event_Status_Reason_CD,
CAST(ESN_ANYID_TRANS.TRANS_ID AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_ANYID_TRANS.TRX_TIME,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES'  AS CHAR(3))AS Financial_Ind,
CAST('YES'  AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST('YES'  AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL  AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST('YES' AS  CHAR(3)) AS Event_Amount_Ind,
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_ANY_ID_TRANSFER_1_0 AS ESN_ANYID_TRANS
              
LEFT OUTER JOIN  P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON M12950.SOURCE_KEY   =  ESN_ANYID_TRANS.TRANSFER_TYPE 
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 5

LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON M13400.SOURCE_KEY   =  ESN_ANYID_TRANS.STATUS 
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1

LEFT OUTER JOIN P1VUTEDW.M13350_EVENT_STS_REASN AS M13350
ON M13350.SOURCE_KEY   =  ESN_ANYID_TRANS.REJECT_REASON 
AND  M13350.SRC_CTL_ID = '044'
AND  M13350.SOURCE_ID  = 1
/*CODE ADD END FOR UR59020090  by PARKAVI*/

UNION ALL 

/*
 VIEW NAME     : ESN_CLOSEAC_INFO_1_0
 STAGING TABLE : VSTEDW.ESN_CLOSEAC_INFO_1_0
 Code Added for DT61030001 Convert Flag from EK to NK for eKYC project
*/

SELECT
CAST(ESN_CLOSEAC.EDW_RECORD_NO AS BIGINT) AS Event_Id,
TO_DATE(ESN_CLOSEAC.CLOSE_DATE ,'yyyy-MM-dd')AS Event_Start_Dt,
coalesce(CAST(M12950.EDW_CODE AS SMALLINT),0) AS Event_Activity_Type_Cd,
NULL AS Event_Reason_CD,
CAST(M13400.EDW_CODE AS SMALLINT)AS Event_Status_Cd,
NULL AS Event_Status_Reason_CD,
CAST(ESN_CLOSEAC.TRANS_ID AS  VARCHAR(100))AS Transaction_Id,
DATE_FORMAT(ESN_CLOSEAC.CLOSE_TIME,'HH:mm:ss')AS Event_Start_Tm,
TO_DATE(NULL,'yyyy-MM-dd') AS Event_END_Dt,
DATE_FORMAT(NULL,'HH:mm:ss') AS Event_END_Tm,
CAST('YES' AS CHAR(3))AS  Account_Ind,
CAST('YES'  AS CHAR(3))AS Financial_Ind,
CAST('NO'  AS CHAR(3))AS Contact_Ind,
NULL AS  Incident_Ind,
NULL AS ACCOUNT_GROUP_Ind,
NULL AS  Consent_Ind,
CAST('NO'  AS CHAR(3)) AS  Financial_ACCOUNT_Event_Ind,
CAST(NULL AS CHAR(3)) AS Internal_Investment_Event_Ind,
NULL AS  EXTERNAL_Investment_Event_Ind,
CAST(NULL AS VARCHAR(3)) AS   Customer_Portfolio_Ind,
NULL AS  Event_GMT_Start_Dt,
NULL AS  Event_GMT_Start_Tm,
NULL AS  STATEMENT_Event_Ind,
CAST(NULL  AS CHAR(3))AS Card_Event_Ind,
NULL AS  Swap_Leg_Event_Ind,
NULL AS  Brokerage_TYPE_CD,
CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_Event_Ind,
CAST('YES' AS  CHAR(3)) AS Event_Amount_Ind,
CAST( NULL AS CHAR(50)) AS Host_TRANSACTION_Code_Num,
NULL AS  FOREIGN_Remittance_Ind,
CAST(NULL AS CHAR(3)) AS Non_Financial_Event_Ind

FROM  P1VSTEDW.ESN_CLOSEAC_INFO_1_0  AS ESN_CLOSEAC
              
LEFT OUTER JOIN  P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON M12950.SOURCE_KEY   =  'CLOSED ONLINE ACCOUNT'
AND  M12950.SRC_CTL_ID = '044'
AND  M12950.SOURCE_ID  = 1

LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
ON M13400.SOURCE_KEY   =  ESN_CLOSEAC.STATUS 
AND  M13400.SRC_CTL_ID = '044'
AND  M13400.SOURCE_ID  = 1

UNION ALL 

/*
VIEW NAME     : VESN_INSURPAYMTHIST_EVENT_01
 STAGING TABLE : VSTEDW.ESN_INSUR_PAYMT_HIST_1_0
 Code Added for PF61040002-Enhance EDW to keep insurance payment history transaction
*/

SELECT 
		 INSUR_PAYMENT.EDW_RECORD_NO AS EVENT_ID
		,TO_DATE(INSUR_PAYMENT.TRX_DATE,'yyyy-MM-dd') AS EVENT_START_DT
		-- ,M12950.EDW_CODE AS EVENT_ACTIVITY_TYPE_CD
		,coalesce(M12950.EDW_CODE,0) AS EVENT_ACTIVITY_TYPE_CD
		,NULL AS EVENT_REASON_CD
		,M13400.EDW_CODE AS EVENT_STATUS_CD
		,NULL AS EVENT_STATUS_REASON_CD
		,INSUR_PAYMENT.PAYMENT_ID AS TRANSACTION_ID
		,DATE_FORMAT(INSUR_PAYMENT.TRX_TIME,'HH:mm:ss') AS EVENT_START_TM
		,TO_DATE(NULL,'yyyy-MM-dd') AS EVENT_END_DT
		,DATE_FORMAT(NULL ,'HH:mm:ss') AS EVENT_END_TM
		,CAST('YES' AS CHAR(3)) AS ACCOUNT_IND
		,CAST('YES' AS CHAR(3)) AS FINANCIAL_IND
		,CAST('YES' AS CHAR(3)) AS CONTACT_IND
		,NULL AS INCIDENT_IND
		,NULL AS ACCOUNT_GROUP_Ind
		,NULL AS CONSENT_IND
		,CAST(CASE WHEN (COALESCE(CAST(EFFECT_DATE AS VARCHAR(10)),'') <> '' OR EFFECT_DATE <> DATE '1000-01-03')
					THEN 'YES' ELSE 'NO' END AS CHAR(3)) AS FINANCIAL_ACCOUNT_EVENT_IND
		,CAST(NULL AS CHAR(3)) AS INTERNAL_INVESTMENT_EVENT_IND
		,NULL AS  EXTERNAL_INVESTMENT_EVENT_IND
		,CAST(NULL AS VARCHAR(3)) AS   CUSTOMER_PORTFOLIO_IND
		,NULL AS  EVENT_GMT_START_DT
		,NULL AS  EVENT_GMT_START_TM
		,NULL AS  STATEMENT_EVENT_IND
		,CAST(NULL  AS CHAR(3))AS CARD_EVENT_IND
		,NULL AS  SWAP_LEG_EVENT_IND
		,NULL AS  BROKERAGE_TYPE_CD
		,CAST(NULL AS CHAR(3)) AS  ATM_SYSTEM_EVENT_IND
		,CAST(CASE WHEN (COALESCE(FEE,'')<>'' OR COALESCE(BALANCE,'')<>'' OR COALESCE(OLDBALANCE,'')<>'') 
								THEN 'YES' ELSE 'NO' END AS CHAR(3)) AS EVENT_AMOUNT_IND
		,CAST( NULL AS CHAR(50)) AS HOST_TRANSACTION_CODE_NUM
		,NULL AS  FOREIGN_REMITTANCE_IND
		,CAST(NULL AS CHAR(3)) AS NON_FINANCIAL_EVENT_IND

FROM P1VSTEDW.ESN_INSUR_PAYMT_HIST_1_0 AS INSUR_PAYMENT

    CROSS JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
        
    LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
    ON M13400.SOURCE_KEY = INSUR_PAYMENT.REC_STATUS
    AND M13400.SOURCE_ID = 1
    AND M13400.SRC_CTL_ID ='044' 
	
	WHERE M12950.SOURCE_KEY = 'Insurance Payment'
    AND M12950.SOURCE_ID = 1
    AND M12950.SRC_CTL_ID = '044'
