CREATE OR REPLACE VIEW P1VEUATM.VATM_PAYROLL_ACCT (
  CARD_NO,
  ID_NUMBER,
  ACCOUNT_NO,
  TITLE_THAI,
  TFIRST_NAME,
  TLAST_NAME,
  TITLE_ENG,
  EFIRST_NAME,
  ELAST_NAME,
  TITLE_THAI_RM,
  TFIRST_NAME_RM,
  TLAST_NAME_RM,
  UNIVERSITY_NAME,
  FACULTY_NAME,
  MAJOR,
  STUDENT_ID,
  BLOOD_GROUP,
  BIRTH_DATE,
  HOME_NUMBER,
  HOME_NAME,
  FLOOR,
  ROOM_NUMBER,
  MOO,
  SOI,
  STREET,
  TUMBON,
  AUMPHER,
  ZIPCODE,
  PHONE,
  TELTO,
  TELEXT,
  MOBILE,
  EMAIL,
  ISSUE_DATE,
  EXPIRE_DATE,
  EASYNET_REF,
  PROVINCE,
  COMPANY_CODE,
  COMPANY_NAME,
  ACCOUNT_NO_FULL,
  PIN_REF,
  FILLER)
AS SELECT
CAST('' AS CHAR(19))  AS CARD_NO
, CAST(COALESCE(PART.PARTY_IDENTIFICATION_NUM,'') AS CHAR(13))  AS ID_NUMBER
, CAST(COALESCE(ATS.ACCOUNT_NO,'') AS CHAR(13)) AS ACCOUNT_NO
, CAST(COALESCE(PART.INDV_NAME_PREFIX_DESC_TH,'') AS CHAR(20)) AS TITLE_THAI
, CAST(COALESCE(PART.INDV_GIVEN_NAME_TH,'') AS CHAR(50)) AS TFIRST_NAME
, CAST(COALESCE(PART.INDV_FAMILY_NAME_TH,'') AS CHAR(50)) AS TLAST_NAME
, CAST(COALESCE(PART.INDV_NAME_PREFIX_DESC_EN,'') AS CHAR(20)) AS TITLE_ENG
, CAST(COALESCE(PART.INDV_GIVEN_NAME_EN,'') AS CHAR(50)) AS EFIRST_NAME
, CAST(COALESCE(PART.INDV_FAMILY_NAME_EN,'') AS CHAR(50)) AS ELAST_NAME
, CAST('' AS CHAR(50)) AS TITLE_THAI_RM
, CAST(SUBSTR(COALESCE(AGMT.THAI_CONTRACT_NAME,''),1,50) AS CHAR(50)) AS TFIRST_NAME_RM
, CAST(SUBSTR(COALESCE(AGMT.THAI_CONTRACT_NAME,''),51,50) AS CHAR(50)) AS TLAST_NAME_RM
, CAST('' AS CHAR(50)) AS UNIVERSITY_NAME
, CAST('' AS CHAR(50)) AS FACULTY_NAME
, CAST('' AS CHAR(50)) AS MAJOR
, CAST('' AS CHAR(15)) AS STUDENT_ID
, CAST('' AS CHAR(2)) AS BLOOD_GROUP
, CAST(COALESCE(PART.BIRTH_DT,'') AS CHAR(8)) AS BIRTH_DATE
, CAST(COALESCE(ADDR.HOUSE_NUM,'') AS CHAR(100)) AS HOME_NUMBER
, CAST(COALESCE(ADDR.BUILDING_NUM,'') AS CHAR(100)) AS HOME_NAME
, CAST(COALESCE(ADDR.FLOOR_NUM,'') AS CHAR(100)) AS FLOOR
, CAST(COALESCE(ADDR.UNIT_NUM,'') AS CHAR(100)) AS ROOM_NUMBER
, CAST(COALESCE(ADDR.MOO_NAME,'') AS CHAR(100))  AS MOO
, CAST(COALESCE(ADDR.SOI,'') AS CHAR(100)) AS SOI
, CAST(COALESCE(ADDR.STREET_NAME,'') AS CHAR(100))  AS STREET
, CAST(COALESCE(ADDR.DISTRICT_NAME,'') AS CHAR(100)) AS TUMBON
, CAST(COALESCE(ADDR.DIVISION,'') AS CHAR(100)) AS AUMPHER
, CAST(COALESCE(ADDR.POSTAL_CODE,'') AS CHAR(5)) AS ZIPCODE
, CAST(COALESCE(TEL.HOME_1_NUM_DD,'') AS CHAR(10)) AS PHONE
, CAST(COALESCE(TEL.HOME_TO_1_NUM,'') AS CHAR(7)) AS TELTO
, CAST(COALESCE(TEL.HOME_EXTENSION_1_NUM,'') AS CHAR(7)) AS TELEXT
, CAST(COALESCE(TEL.MOBILE_1_NUM_DD,'') AS CHAR(10)) AS MOBILE
, CAST(COALESCE(EMAIL.ELECTRONIC_ADDRESS_TXT,'') AS CHAR(50)) AS EMAIL
, CAST('' AS CHAR(8)) AS ISSUE_DATE
, CAST('' AS CHAR(8)) AS EXPIRE_DATE
, CAST('' AS CHAR(20)) AS EASYNET_REF
, CAST(COALESCE(ADDR.TERRITORY,'') AS CHAR(100)) AS PROVINCE
, CAST(COALESCE(ATS.COM_CODE,'') AS CHAR(20)) AS COMPANY_CODE
, CAST(COALESCE(ATS.COM_NAME,'') AS CHAR(50)) AS COMPANY_NAME
, CAST(COALESCE(ATS.STAFF_BASE_ACCOUNT_NUM,'') AS CHAR(10)) AS ACCOUNT_NO_FULL
, CAST('' AS CHAR(12)) AS PIN_REF
, CAST('' AS CHAR(173)) AS FILLER


FROM (
        SELECT 
        TPAYROLL.COM_CODE
        ,TPAYROLL.COM_NAME
        ,TPAYROLL.STAFF_BASE_ACCOUNT_NUM
        ,SUBSTR(TPAYROLL.STAFF_BASE_ACCOUNT_NUM,1,3) 
                || '-' || SUBSTR(TPAYROLL.STAFF_BASE_ACCOUNT_NUM,4,1)
                || '-' || SUBSTR(TPAYROLL.STAFF_BASE_ACCOUNT_NUM,5,5)
                || '-' || SUBSTR(TPAYROLL.STAFF_BASE_ACCOUNT_NUM,10,1) AS ACCOUNT_NO
        ,TPAYROLL.FROM_SYSTEM
        FROM P1DTPATM.TATM_PAYROLL_ACCT AS TPAYROLL
) AS ATS

CROSS JOIN P1VTPATM.VATM_DSF_BUSINESSDATE_M AS BD

LEFT JOIN (
        SELECT
        ESL.BASE_ACCT_NUM
        ,ESL.PRIM_CUST_ID
        ,ESL.THAI_CONTRACT_NAME
        FROM P1VTTEDW.EDW_AGREEMENT_INFO AS ESL
        
        INNER JOIN P1VTPATM.VATM_DSF_BUSINESSDATE_M AS BD
        ON BD.BUSINESSDATE = ESL.AS_OF_DT
        AND ESL.AGMT_CTL_ID IN ( '002','003' )
        AND ESL.ACCOUNT_MODIFIER_NUM IN ( 'ST14','IM14' )
        AND ESL.ACCOUNT_IND = 'YES'
        AND ESL.ACTIVE_IND = '01'    -- ACTIVE
        AND ESL.PRIM_CUST_ROLE_CD IN (1,2,3)     -- 1 PRIIND, 2 PRIFOR,3 PRIBY
) AS AGMT
ON AGMT.BASE_ACCT_NUM = ATS.STAFF_BASE_ACCOUNT_NUM

LEFT JOIN (
        SELECT 
        ESL.PARTY_ID
        ,CASE
                WHEN ESL.INDV_NAME_PREFIX_CD_TH > 0
                THEN REF_NAME_PREFX_TH.DESCRIPTION 
                ELSE M36000_TH.SOURCE_KEY
                END AS INDV_NAME_PREFIX_DESC_TH
        ,ESL.INDV_GIVEN_NAME_TH
        ,ESL.INDV_FAMILY_NAME_TH
        ,CASE
                WHEN ESL.INDV_NAME_PREFIX_CD_EN > 0
                THEN REF_NAME_PREFX_EN.DESCRIPTION 
                ELSE M36000_EN.SOURCE_KEY
                END AS INDV_NAME_PREFIX_DESC_EN
        ,ESL.INDV_GIVEN_NAME_EN
        ,ESL.INDV_FAMILY_NAME_EN
        ,CAST(DATE_FORMAT(CASE
                WHEN EXTRACT(YEAR FROM ESL.BIRTH_DT) IN (1000,9999)
                THEN NULL
                WHEN EXTRACT(YEAR FROM ESL.BIRTH_DT) < 2020
                THEN ADD_MONTHS(ESL.BIRTH_DT,543*12)
                ELSE ESL.BIRTH_DT
                END ,'ddMMyyyy') AS VARCHAR(10)) AS BIRTH_DT
        ,ESL.PARTY_IDENTIFICATION_NUM
        ,ESL.PARTY_IDENTIFICATION_TYPE_CD
        
        FROM P1VTTEDW.EDW_PARTY_INFO AS ESL

        INNER JOIN P1VTPATM.VATM_DSF_BUSINESSDATE_M AS BD
        ON BD.BUSINESSDATE = ESL.AS_OF_DT
        AND ESL.PARTY_CTL_ID = '001'
                
        LEFT JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_NAME_PREFX_TH
        ON REF_NAME_PREFX_TH.EDW_CODE = ESL.INDV_NAME_PREFIX_CD_TH
        AND REF_NAME_PREFX_TH.CODE_ID = 152
        AND REF_NAME_PREFX_TH.CODE_SET_ID = 'CS036000'
        AND REF_NAME_PREFX_TH.LANGUAGE_ID = 2
        
        LEFT JOIN P1VUTEDW.M36000_NAME_PREFX AS M36000_TH
        ON M36000_TH.EDW_CODE = ESL.INDV_NAME_PREFIX_CD_TH
        AND M36000_TH.SRC_CTL_ID = '001'
        AND M36000_TH.SOURCE_ID = 1
        AND M36000_TH.EDW_CODE < 0
        
        LEFT JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_NAME_PREFX_EN
        ON REF_NAME_PREFX_EN.EDW_CODE = ESL.INDV_NAME_PREFIX_CD_EN
        AND REF_NAME_PREFX_EN.CODE_ID = 152
        AND REF_NAME_PREFX_EN.CODE_SET_ID = 'CS036000'
        AND REF_NAME_PREFX_EN.LANGUAGE_ID = 1
        
        LEFT JOIN P1VUTEDW.M36000_NAME_PREFX AS M36000_EN
        ON M36000_EN.EDW_CODE = ESL.INDV_NAME_PREFIX_CD_EN
        AND M36000_EN.SRC_CTL_ID = '001'
        AND M36000_EN.SOURCE_ID = 1
        AND M36000_EN.EDW_CODE < 0
) AS PART
ON PART.PARTY_ID = AGMT.PRIM_CUST_ID

LEFT JOIN (
        SELECT
        PTLSEQ.PARTY_ID
        ,PTLSEQ.PARTY_LOCATION_ID
        ,STADDRDET.HOUSE_NUM AS HOUSE_NUM
        ,COALESCE(STADDRDET.BUILDING_NUM,'') || ' ' || COALESCE(STADDRDET.VILLAGE_NAME,'') AS BUILDING_NUM
        ,STADDRDET.FLOOR_NUM
        ,STADDRDET.UNIT_NUM
        ,STADDRDET.MOO_NAME
        ,COALESCE(STADDRDET.TROK_NAME,'') || ' ' || COALESCE(STADDRDET.SOI_NAME,'') AS SOI
        ,STADDRDET.STREET_NAME
        ,STADDRDET.DISTRICT_NAME
        ,REF_DIV.DESCRIPTION AS DIVISION
        ,REF_TER.DESCRIPTION AS TERRITORY
        ,CASE 
                WHEN STADDR.POSTAL_CODE_ID < 0
                THEN M35600.SOURCE_KEY
                ELSE CAST(STADDR.POSTAL_CODE_ID AS VARCHAR(10))
                END AS POSTAL_CODE
        
        FROM P1VTTEDW.PARTY_TO_LOCATION_SEQUENCE AS PTLSEQ
        
        INNER JOIN P1VTPATM.VATM_DSF_BUSINESSDATE_M AS BD
        ON BD.BUSINESSDATE BETWEEN PTLSEQ.START_DT AND PTLSEQ.END_DT
        AND PTLSEQ.RECORD_DELETED_FLAG = 0 
        AND PTLSEQ.CTL_ID = '001'
        AND PTLSEQ. PARTY_LOCATION_USAGE_CD IN (1,2,3,4,9,99)
        AND PTLSEQ.PARTY_LOCATION_SEQ_NUM = '000'
   
        INNER JOIN P1VTTEDW.STREET_ADDRESS_DETAIL AS STADDRDET
        ON STADDRDET.STREET_ADDRESS_ID = PTLSEQ.PARTY_LOCATION_ID
        AND BD.BUSINESSDATE BETWEEN STADDRDET.START_DT AND STADDRDET.END_DT
        AND STADDRDET.RECORD_DELETED_FLAG = 0
        
        INNER JOIN P1VTTEDW.STREET_ADDRESS AS STADDR
        ON STADDR.STREET_ADDRESS_ID = PTLSEQ.PARTY_LOCATION_ID
        AND BD.BUSINESSDATE BETWEEN STADDR.START_DT AND STADDR.END_DT
        AND STADDR.RECORD_DELETED_FLAG = 0
        
        LEFT JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_DIV
        ON REF_DIV.EDW_CODE = STADDR.DIVISION_ID
        AND REF_DIV.CODE_ID = 148
        AND REF_DIV.CODE_SET_ID = 'CS035800'
        AND REF_DIV.LANGUAGE_ID = 2
        
        LEFT JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_TER
        ON REF_TER.EDW_CODE = STADDR.TERRITORY_ID
        AND REF_TER.CODE_ID = 146
        AND REF_TER.CODE_SET_ID = 'CS035650'
        AND REF_TER.LANGUAGE_ID = 2

        LEFT JOIN P1VUTEDW.M35600_POSTL_CODE AS M35600
        ON M35600.EDW_CODE = STADDR.POSTAL_CODE_ID
        AND M35600.SRC_CTL_ID = '001'
        AND M35600.SOURCE_ID = 1
        AND M35600.EDW_CODE < 0
) AS ADDR
ON ADDR.PARTY_ID = AGMT.PRIM_CUST_ID

LEFT JOIN P1VTTEDW.T3_PARTY_TELEPHONE AS TEL
ON TEL.PARTY_ID = AGMT.PRIM_CUST_ID
AND TEL.START_DT = BD.BUSINESSDATE

LEFT JOIN (
    SELECT
        PARTY_ID,
        ELECTRONIC_ADDRESS_TXT
    FROM
        (
            SELECT
                PTLSEQ.PARTY_ID,
                EM.ELECTRONIC_ADDRESS_TXT,
                RANK() OVER(
                    PARTITION BY PTLSEQ.PARTY_ID
                    ORDER BY
                        PTLSEQ.PARTY_LOCATION_ID DESC
                ) as R -- Convert from QUALIFY
            FROM
                P1VTTEDW.PARTY_TO_LOCATION_SEQUENCE AS PTLSEQ
                INNER JOIN P1VTPATM.VATM_DSF_BUSINESSDATE_M AS BD ON BD.BUSINESSDATE BETWEEN PTLSEQ.START_DT
                AND PTLSEQ.END_DT
                AND PTLSEQ.RECORD_DELETED_FLAG = 0
                AND PTLSEQ.CTL_ID = '001'
                AND PTLSEQ.PARTY_LOCATION_USAGE_CD = 17 -- EMAIL
                AND PTLSEQ.MAIL_STATUS_CD = 1 -- CURRENT
                INNER JOIN P1VTTEDW.ELECTRONIC_ADDRESS AS EM ON EM.ELECTRONIC_ADDRESS_ID = PTLSEQ.PARTY_LOCATION_ID
                AND BD.BUSINESSDATE BETWEEN EM.START_DT
                AND EM.END_DT
                AND EM.RECORD_DELETED_FLAG = 0 
                --        QUALIFY RANK() OVER( << mig orig--
                --        PARTITION BY PTLSEQ.PARTY_ID
                --        ORDER BY PTLSEQ.PARTY_LOCATION_ID DESC) = 1
        ) AS SRC
    WHERE
        SRC.R = 1
) AS EMAIL
ON EMAIL.PARTY_ID = AGMT.PRIM_CUST_ID
