CREATE OR REPLACE VIEW P1VEUTMS.VTMS_IRORSCG_D (
  AS_OF_DT,
  CUSTOMER_NAME,
  BENE_NAME,
  INVOICE_NO,
  PAYMENT_TYPE,
  BANK_REF,
  CURRENCY,
  INVOICE_AMT,
  RECEIVED_AMT,
  THEIR_REF,
  CUSTOMER_ID)
COMMENT ' ############################################################
 DSF SYSTEM: Teasure Management System
 Create BY: S36710(Yod)
 VERSION MAPPING: EDW_DOWNSTREAM_RISKMART_CAPITAL_INFO_SPECS_V1-1.ODS , EDW_DOWNSTREAM_RISKMART_CAPITAL_INFO_DIAGRAM_V1-1.PDF
 MODELER BY : Nattharut S.
 Create DATE: 2013-07-28
 Description : R56040057  - Treasury Management Outsourcing for SCG Chemical Group
 ############################################################
 "Invoice No"  "Invoice No"
 
'
AS SELECT
 CAST(date_format(AGMT.Contract_Expiration_Dt ,'yyyyMMdd') AS VARCHAR(8)) AS AS_OF_DT
 ,CAST(AGMT.Contract_Name AS VARCHAR(120)) AS CUSTOMER_NAME
 ,CAST(CREDIT_AGMT.Beneficiary_Name AS VARCHAR(100)) AS BENE_NAME
 ,CAST(ACCT_DEMO.Acct_Demographic_Val AS VARCHAR(100)) AS INVOICE_NO
 ,CASE 
  WHEN SUBSTR(AGMT.ACCOUNT_NUM,6,2) = '01'
   THEN 'LC'
  WHEN SUBSTR(AGMT.ACCOUNT_NUM,6,2) = '03'
   THEN 'BC'
  WHEN SUBSTR(AGMT.ACCOUNT_NUM,6,2) = '33'
   THEN 'TR'
 END AS PAYMENT_TYPE
 ,CAST(AGMT.Account_Num AS VARCHAR(100)) AS BANK_REF
 ,REF_CCY_PAY.SHORT_DESCRIPTION AS CURRENCY
 ,NULL AS INVOICE_AMT,
 FORMAT_NUMBER(Cast(REPLACE(COALESCE(ACCT_BAL.Acct_Crncy_Balance_Summary_Amt, 0),',','') AS DECIMAL(38,18)),'#.00') AS RECEIVED_AMT
 ,NULL AS THEIR_REF
 ,CAST(AGMT.Base_Account_Num AS VARCHAR(100)) AS CUSTOMER_ID
  
FROM 
(
/*  SEL AGMT_TF.* << mig orig 
*/
 SELECT AGMT_TF.*
FROM P1VTTEDW.AGREEMENT AS AGMT_TF

INNER JOIN P1VTPTMS.VTMS_BUSINESSDATE_D AS BD
ON AGMT_TF.Contract_Expiration_Dt = BD.NEXTBUSINESSDATE
AND AGMT_TF.CTL_ID = '018'  /* TF */ --TF
/* AND SUBSTR(AGMT_TF.ACCOUNT_NUM,6,2) IN ('01','03','33') --Product (LC, BC, TR) 
*/
AND (
(SUBSTR(AGMT_TF.ACCOUNT_NUM,6,2) = '01' AND AGMT_TF.ACCOUNT_NUM NOT LIKE '%ISS%') /* Product LC */ --Product LC
OR
(SUBSTR(AGMT_TF.ACCOUNT_NUM,6,2) IN ('03','33')) /* Product (BC, TR) */ --Product (BC, TR)
)
) AGMT

CROSS JOIN P1VTPTMS.VTMS_BUSINESSDATE_D AS BD

INNER JOIN P1VTTEDW.ACCOUNT_CURRENCY AS ACCT_CURREN
ON AGMT.ACCOUNT_NUM = ACCT_CURREN.ACCOUNT_NUM
AND AGMT.ACCOUNT_MODIFIER_NUM = ACCT_CURREN.ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE BETWEEN ACCT_CURREN.START_DT AND ACCT_CURREN.END_DT
AND ACCT_CURREN.RECORD_DELETED_FLAG = 0
AND ACCT_CURREN.CTL_ID = '018'
AND ACCT_CURREN.Account_Currency_Cd <> 155  /* THB */ --THB

INNER JOIN P1VTTEDW.ACCOUNT_BALANCE_SUMMARY_DD AS ACCT_BAL
ON AGMT.ACCOUNT_NUM = ACCT_BAL.ACCOUNT_NUM
AND AGMT.ACCOUNT_MODIFIER_NUM = ACCT_BAL.ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE BETWEEN ACCT_BAL.START_DT AND ACCT_BAL.END_DT
AND ACCT_BAL.RECORD_DELETED_FLAG = 0
AND ACCT_BAL.CTL_ID = '018'
AND ACCT_BAL.Balance_Category_Type_Cd = 1
AND ACCT_BAL.Account_Metric_Type_Cd = 1
AND COALESCE(ACCT_BAL.Acct_Crncy_Balance_Summary_Amt,0) > 0

LEFT OUTER JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_CCY_PAY
ON ACCT_CURREN.Account_Currency_Cd = REF_CCY_PAY.EDW_CODE
AND REF_CCY_PAY.LANGUAGE_ID = 1
AND REF_CCY_PAY.CODE_SET_ID = 'CS009700'
AND REF_CCY_PAY.CODE_ID = 55

LEFT OUTER JOIN P1VTTEDW.CREDIT_AGREEMENT AS CREDIT_AGMT
ON AGMT.ACCOUNT_NUM = CREDIT_AGMT.ACCOUNT_NUM
AND AGMT.ACCOUNT_MODIFIER_NUM = CREDIT_AGMT.ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE BETWEEN CREDIT_AGMT.START_DT AND CREDIT_AGMT.END_DT
AND CREDIT_AGMT.RECORD_DELETED_FLAG = 0
AND CREDIT_AGMT.CTL_ID = '018'

LEFT OUTER JOIN P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS ACCT_DEMO
ON AGMT.ACCOUNT_NUM = ACCT_DEMO.ACCOUNT_NUM
AND AGMT.ACCOUNT_MODIFIER_NUM = ACCT_DEMO.ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE BETWEEN ACCT_DEMO.START_DT AND ACCT_DEMO.END_DT
AND ACCT_DEMO.RECORD_DELETED_FLAG = 0
AND ACCT_DEMO.CTL_ID = '018'
AND ACCT_DEMO.Demog_Cd = 4328
