CREATE OR REPLACE VIEW P1VEUCCP.VCCP_TXN_M (
  TRANDATE,
  POSTDATE,
  CARD_NUM,
  TRANCODE,
  REASONCODE,
  BAHT,
  NOTBAHT,
  CURRENCY,
  CORP_NO,
  MER_NO,
  MICRO_REF,
  REIMB_ATTR,
  DESCCODE,
  TERM_ID,
  MAIL_PHONE,
  INTERNET,
  CARDTYPE,
  ISSUECARD,
  REGION)
AS SELECT
CAST(DATE_FORMAT(EVNT.EVENT_START_DT, 'yyyyMMdd') AS CHAR(8)) AS TRANDATE -- change from CAST(EVNT.EVENT_START_DT AS CHAR(8)) AS TRANDATE
,CAST(DATE_FORMAT(EVNT.START_DT, 'yyyyMMdd') AS CHAR(8)) AS POSTDATE -- change from CAST(EVNT.START_DT AS CHAR(8)) AS POSTDATE
,CAST(ACCTACCTRELA.RELATED_ACCOUNT_NUM AS CHAR(16)) AS CARD_NUM
,CAST(TXNALSB2K.B2K_TC AS CHAR(2)) AS TRANCODE
,CAST(TXNALSB2K.B2K_RC AS CHAR(2)) AS REASONCODE
,CAST(FINAN_EVT.EVENT_AMT AS DECIMAL(14,2)) AS BAHT
,CAST(0 AS DECIMAL(14,2)) AS NOTBAHT
,CAST('764' AS CHAR(3)) AS CURRENCY
,CAST('00' AS CHAR(2)) AS CORP_NO
,CAST('' AS CHAR(16)) AS MER_NO
,CAST('' AS CHAR(23)) AS MICRO_REF
,CAST('0' AS CHAR(1)) AS REIMB_ATTR
,CAST('' AS CHAR(2)) AS DESCCODE
,CAST('' AS CHAR(8)) AS TERM_ID
,CAST('' AS CHAR(1)) AS MAIL_PHONE
,CAST('P' AS CHAR(1)) AS INTERNET
,CAST('AY' AS CHAR(2)) AS CARDTYPE
,CAST('M' AS CHAR(1)) AS ISSUECARD
,CAST('E' AS CHAR(1)) AS REGION

FROM P1VTTEDW.ACCT_ACCT_RELATIONSHIP AS ACCTACCTRELA

INNER JOIN P1VTPCCP.VCCP_BUSINESSDATE_M AS BD
ON ACCTACCTRELA.ACCOUNT_MODIFIER_NUM = 'AM14'
AND ACCTACCTRELA.ACCOUNT_NUM LIKE '_____470%'
AND ACCTACCTRELA.ACCT_RELATIONSHIP_TYPE_CD = 95      -- B2K ACCOUNT LQD
AND BD.BUSINESSDATE BETWEEN ACCTACCTRELA.START_DT AND ACCTACCTRELA.END_DT
AND ACCTACCTRELA.RECORD_DELETED_FLAG = 0
AND ACCTACCTRELA.CTL_ID = '004'

INNER JOIN P1VTTEDW.ACCOUNT_EVENT AS ACCT_EVT
ON ACCTACCTRELA.ACCOUNT_NUM = ACCT_EVT.ACCOUNT_NUM
AND ACCTACCTRELA.ACCOUNT_MODIFIER_NUM = ACCT_EVT.ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE  BETWEEN ACCT_EVT.START_DT AND ACCT_EVT.END_DT
AND ACCT_EVT.RECORD_DELETED_FLAG = 0
AND ACCT_EVT.CTL_ID = '004'

INNER JOIN P1VTTEDW.EVENT AS EVNT
ON ACCT_EVT.EVENT_ID = EVNT.EVENT_ID
AND ACCT_EVT.EVENT_START_DT = EVNT.EVENT_START_DT
AND BD.BUSINESSDATE = EVNT.EVENT_START_DT
AND EVNT.CTL_ID = '004'

INNER JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
ON EVNT.EVENT_ACTIVITY_TYPE_CD = M12950.EDW_CODE
AND M12950.SRC_CTL_ID = '004'
AND M12950.SOURCE_ID = 1

INNER JOIN P1DPYCCP.CCP_TXNALSB2K AS TXNALSB2K
ON M12950.SOURCE_KEY = TXNALSB2K.ALS_TC  
AND BD.BUSINESSDATE BETWEEN TXNALSB2K.START_DT AND TXNALSB2K.END_DT
AND TXNALSB2K.RECORD_DELETED_FLAG = 0

INNER JOIN P1VTTEDW.FINANCIAL_EVENT AS FINAN_EVT
ON ACCT_EVT.EVENT_ID = FINAN_EVT.EVENT_ID
AND ACCT_EVT.EVENT_START_DT = FINAN_EVT.EVENT_START_DT
AND BD.BUSINESSDATE = FINAN_EVT.EVENT_START_DT
AND FINAN_EVT.CTL_ID = '004'
