CREATE OR REPLACE VIEW P1VTXEDW.VRBF_SDL20_PTPA_01 (
  PARTY_ID,
  PARTY_ASSET_ID,
  ASSET_ROLE_CD,
  ASSET_ROLE_DT,
  OWNERSHIP_PCT,
  OWNERSHIP_SEQUENCE_NUM)
AS SELECT PARTY_ID,PARTY_ASSET_ID,ASSET_ROLE_CD,ASSET_ROLE_DT,OWNERSHIP_PCT,OWNERSHIP_SEQUENCE_NUM
FROM(

SELECT
        CAST(PARTY_IDENTIFICATION.PARTY_ID  AS INT) AS PARTY_ID,
        CAST(BKEY_PARTY_ASSET.EDW_KEY  AS INT) AS PARTY_ASSET_ID,
        CAST(M03450.EDW_CODE AS SMALLINT) AS  ASSET_ROLE_CD,
/*        CAST(RBF_SDL_2_0.OPEN_DATE AS DATE FORMAT 'YYYY-MM-DD') AS ASSET_ROLE_DT, << mig orig*/
        TO_DATE(RBF_SDL_2_0.OPEN_DATE ,'yyyy-MM-dd') AS ASSET_ROLE_DT,
        CAST(NULL AS DECIMAL(9,4)) AS OWNERSHIP_PCT,
        CAST(NULL AS SMALLINT) AS  OWNERSHIP_SEQUENCE_NUM

,RANK() OVER( PARTITION BY 
RBF_SDL_2_0.DOCUMENT_NO , 
RBF_SDL_2_0.BRANCH_ID, 
RBF_SDL_2_0.LOCKER_ID 
ORDER BY RBF_SDL_2_0. OPEN_DATE DESC) AS R

FROM P1VSTEDW.RBF_SDL_2_0 AS RBF_SDL_2_0

INNER JOIN  P1VTTEDW.PARTY_IDENTIFICATION AS PARTY_IDENTIFICATION
ON PARTY_IDENTIFICATION.PARTY_IDENTIFICATION_NUM = RBF_SDL_2_0.DOCUMENT_NO 
AND PARTY_IDENTIFICATION.PARTY_IDENTIFICATION_TYPE_CD IN (1,2,3,4,5,6,7,8,9,10,11,12) 
AND PARTY_IDENTIFICATION.CTL_ID = '001' 
AND PARTY_IDENTIFICATION.END_DT = DATE '9999-12-31' 
AND PARTY_IDENTIFICATION.RECORD_DELETED_FLAG = 0

LEFT OUTER JOIN  P1VUTEDW.BKEY_PARTY_ASSET AS BKEY_PARTY_ASSET
ON BKEY_PARTY_ASSET.SOURCE_KEY = RBF_SDL_2_0. BK_PARTYASSET_210_001

CROSS JOIN   P1VUTEDW.M03450_ASSET_ROLE AS M03450

WHERE M03450.SOURCE_KEY ='ASSET OWNER'
AND M03450.SOURCE_ID =1
AND M03450.SRC_CTL_ID = '035'

) AS SRC 
WHERE SRC.R = 1


UNION ALL


SELECT PARTY_ID,PARTY_ASSET_ID,ASSET_ROLE_CD,ASSET_ROLE_DT,OWNERSHIP_PCT,OWNERSHIP_SEQUENCE_NUM
FROM(

SELECT
        CAST(BKEY_PARTY.EDW_KEY AS INT) AS PARTY_ID,
        CAST(BKEY_PARTY_ASSET.EDW_KEY  AS INT) AS PARTY_ASSET_ID,
        CAST(M03450.EDW_CODE AS SMALLINT) AS  ASSET_ROLE_CD,
        TO_DATE(RBF_SDL_2_0.OPEN_DATE ,'yyyy-MM-dd') AS ASSET_ROLE_DT,
        CAST(NULL AS DECIMAL(9,4)) AS OWNERSHIP_PCT,
        CAST(NULL AS SMALLINT) AS  OWNERSHIP_SEQUENCE_NUM

,RANK() OVER( PARTITION BY 
RBF_SDL_2_0.DOCUMENT_NO , 
RBF_SDL_2_0.BRANCH_ID, 
RBF_SDL_2_0.LOCKER_ID 
ORDER BY RBF_SDL_2_0. OPEN_DATE DESC) AS R

FROM P1VSTEDW.RBF_SDL_2_0 AS RBF_SDL_2_0

INNER JOIN  P1VTXEDW.VGL_GLSETBK10_01 AS VGL_GLSETBK10_01
ON VGL_GLSETBK10_01.BRANCH_CD = RBF_SDL_2_0.BRANCH_ID 
AND VGL_GLSETBK10_01.BANK_CODE = '14'

LEFT OUTER JOIN  P1VUTEDW.BKEY_PARTY AS BKEY_PARTY
ON BKEY_PARTY.SOURCE_KEY =VGL_GLSETBK10_01.VALUE_SET_RC || '_' || VGL_GLSETBK10_01.BRANCH_CD

LEFT OUTER JOIN  P1VUTEDW.BKEY_PARTY_ASSET AS BKEY_PARTY_ASSET
ON BKEY_PARTY_ASSET.SOURCE_KEY =RBF_SDL_2_0. BK_PARTYASSET_210_001

CROSS JOIN   P1VUTEDW.M03450_ASSET_ROLE AS M03450

WHERE M03450.SOURCE_KEY='ASSET BRANCH'
AND M03450.SOURCE_ID=1
AND M03450.SRC_CTL_ID='035'

) AS SRC
WHERE SRC.R = 1
