CREATE OR REPLACE VIEW p1VSGMF.B2MTX_PCOEC_T_1_0_T1 (
  EDW_RECORD_NO,
  PCOLE_REC_TYPE,
  PCOLE_CORP,
  PCOLE_BATCH_NUMBER,
  PCOLE_SEQUENCE,
  PCOLE_TRAN_ACCOUNT,
  PCOLE_ACNO_EXTENSION,
  PCOLE_TRAN_EXPIRY_DATE,
  PCOLE_TRAN_DATE,
  FILLER_1,
  PCOLE_TRAN_AUTH_NUMBER,
  PCOLE_TRAN_AMOUNT,
  PCOLE_TRAN_FILM_SEQ,
  PCOLE_TRAN_INSTLM_NUMBER,
  PCOLE_TRAN_ORIG_POST_DATE,
  FILLER_2,
  PCOLE_TRAN_DISPOSITION,
  PCOLE_TRAN_OPER,
  PCOLE_TRAN_TERM,
  PCOLE_TRAN_TIME,
  FILLER_3,
  BK_PARTY_002_002,
  BM_M42850_002,
  BM_M09700_001,
  dl_data_dt)
AS select
0 as EDW_RECORD_NO ,
COALESCE(TRIM(PCOLE_REC_TYPE),' ') as PCOLE_REC_TYPE,
COALESCE(TRIM(PCOLE_CORP),' ') as PCOLE_CORP,
PCOLE_BATCH_NUMBER,
PCOLE_SEQUENCE,
COALESCE(TRIM(PCOLE_TRAN_ACCOUNT),' ') as PCOLE_TRAN_ACCOUNT,
null as PCOLE_ACNO_EXTENSION, /*COALESCE(TRIM(PCOLE_ACNO_EXTENSION),' ')*/
COALESCE(TRIM(PCOLE_TRAN_EXPIRY_DATE),' ') as PCOLE_TRAN_EXPIRY_DATE,
right('000000000'||replace(PCOLE_TRAN_DATE,'-',''),9) as PCOLE_TRAN_DATE, /*PCOLE_TRAN_DATE (FORMAT '9(9)')*/ -- change from right('000000000'||PCOLE_TRAN_DATE,9)
COALESCE(TRIM(FILLER_1),' ') as FILLER_1,
COALESCE(TRIM(PCOLE_TRAN_AUTH_NUMBER),' ') as PCOLE_TRAN_AUTH_NUMBER,
replace(FORMAT_NUMBER_TD(PCOLE_TRAN_AMOUNT,'0000000000.00',14,'Y'), '.', '') as PCOLE_TRAN_AMOUNT, -- PCOLE_TRAN_AMOUNT
COALESCE(TRIM(PCOLE_TRAN_FILM_SEQ),' ') as PCOLE_TRAN_FILM_SEQ,
COALESCE(TRIM(PCOLE_TRAN_INSTLM_NUMBER),' ') as PCOLE_TRAN_INSTLM_NUMBER,
right('000000000'||PCOLE_TRAN_ORIG_POST_DATE,9) as PCOLE_TRAN_ORIG_POST_DATE, /*PCOLE_TRAN_ORIG_POST_DATE (FORMAT '9(9)')*/
COALESCE(TRIM(FILLER_2),' ') as FILLER_2,
COALESCE(TRIM(PCOLE_TRAN_DISPOSITION),' ') as PCOLE_TRAN_DISPOSITION,
COALESCE(TRIM(PCOLE_TRAN_OPER),' ') as PCOLE_TRAN_OPER,
COALESCE(TRIM(PCOLE_TRAN_TERM),' ') as PCOLE_TRAN_TERM,
null as PCOLE_TRAN_TIME, /*COALESCE(TRIM(PCOLE_TRAN_TIME),' ')*/
COALESCE(TRIM(FILLER_3),' ') as FILLER_3,
null as BK_PARTY_002_002, 
null as BM_M42850_002, 
null as BM_M09700_001, 
dl_data_dt

from p1dlprst.b2k_pcoec_trn_1_0
