CREATE OR REPLACE VIEW P1VEULQ.VLQ_06_GL_PROD_SEGMENT (
  PROD_CODE,
  NAME_ENG,
  NAME_TH,
  lst_datetime)
AS SELECT CAST(PG.HOST_PRODUCT_GROUP_VAL AS CHAR (4)) PROD_CODE
,CAST(MAX(GL_REP_PROD.GL_REPORTING_PRODUCT_NAME) AS CHAR(180)) NAME_ENG
,CAST(MAX(GL_REP_PROD.GL_REPORTING_PRODUCT_THAI_NAME) AS CHAR(180)) NAME_TH
,MIN( DATE_FORMAT(GL_REP_PROD.START_DT , 'yyyy-MM-dd')) AS lst_datetime

FROM P1VTTEDW.GL_REPORTING_PRODUCT AS GL_REP_PROD

CROSS JOIN P1VTPLQ.VLQ_BUSINESSDATE_D AS CB

INNER JOIN P1VTTEDW.PRODUCT_GROUP AS PG
ON GL_REP_PROD.PRODUCT_GROUP_ID = PG.PRODUCT_GROUP_ID
 --2019-11-22 add filter active record
 AND PG.RECORD_DELETED_FLAG = 0
 AND CB.BUSINESSDATE BETWEEN PG.START_DT AND PG.END_DT
 --> Add 2010-06-18 : UR no.R53040049-01 [EDW Performance Tuning -Set #11 (for LQ)]
 AND PG.CTL_ID ='006'
 
INNER JOIN P1VUTEDW.BKEY_PRODUCTGROUP AS BK_PG
ON PG.PRODUCT_GROUP_ID = BK_PG.EDW_KEY
AND   SUBSTR(BK_PG.SOURCE_KEY,0,INSTR(BK_PG.SOURCE_KEY,'_')-1) IN ('0000000000000000062016','0001007718') --Product SCB in CSFMS_GLSEG_1_0     -- Updated by TMA-Huong         


WHERE GL_REP_PROD.RECORD_DELETED_FLAG = 0
  AND CB.BUSINESSDATE BETWEEN GL_REP_PROD.START_DT AND GL_REP_PROD.END_DT
  --> Add 2010-06-18 : UR no.R53040049-01 [EDW Performance Tuning -Set #11 (for LQ)]
  AND GL_REP_PROD.CTL_ID ='006'
  --> Add 2010-06-18 : UR no.R53040049-01 [EDW Performance Tuning -Set #11 (for LQ)]

GROUP BY 1
