CREATE OR REPLACE VIEW P1VSGMF.GN_MTLOG_1_0_T1 (
  EDW_RECORD_NO,
  GN_REC_SYS_DATE,
  GN_REC_SYS_TIME,
  GN_REC_TASKNO,
  GN_CHANNEL_CODE,
  GN_REC_RECTYPE,
  GN_TS_EXT_TRAN_CODE,
  GN_TRAN_TYPE,
  GN_REC_STATUS,
  GN_ATM_CARDNUMBER,
  GN_TERMINAL_ID,
  GN_TERMINAL_RECNO,
  GN_TS_TELLER_ID,
  GN_TS_TRAN_SERNO,
  GN_TS_PROC_DATE,
  GN_EIB_TRANID,
  GN_EIB_TERMID,
  MIT_MQ_RQUID,
  MIT_ACCT1_ACCTNUM,
  MIT_ACCT2_ACCTNUM,
  MIT_DRCR_IND,
  MIT_FINANCIAL_TYPE,
  MIT_CHEQUE_NUMBER,
  MIT_CHEQUE_CLRG_TYPE,
  MIT_DR_TRAN_AMOUNT,
  MIT_DR_TRAN_CCY,
  MIT_CR_TRAN_AMOUNT,
  MIT_CR_TRAN_CCY,
  MIT_FEE_PROCESS_IND,
  MIT_FEE_TYPE_01,
  MIT_FEE_AMOUNT_01,
  MIT_FEE_TYPE_02,
  MIT_FEE_AMOUNT_02,
  MIT_FEE_TYPE_03,
  MIT_FEE_AMOUNT_03,
  MIT_FEE_TYPE_04,
  MIT_FEE_AMOUNT_04,
  MIT_FEE_TYPE_05,
  MIT_FEE_AMOUNT_05,
  MIT_FEE_TYPE_06,
  MIT_FEE_AMOUNT_06,
  MIT_FEE_TYPE_07,
  MIT_FEE_AMOUNT_07,
  MIT_FEE_TYPE_08,
  MIT_FEE_AMOUNT_08,
  MIT_FEE_TYPE_09,
  MIT_FEE_AMOUNT_09,
  MIT_FEE_TYPE_10,
  MIT_FEE_AMOUNT_10,
  dl_data_dt)
AS SELECT
row_number() over (order by 1) AS EDW_RECORD_NO
,date_format(COALESCE(milog_rec_sys_date,''),'yyyyMMdd') AS GN_REC_SYS_DATE
,replace(COALESCE(milog_rec_sys_time,''),':','') AS GN_REC_SYS_TIME
,COALESCE(milog_rec_taskno,'') AS GN_REC_TASKNO
,COALESCE(milog_channel_code,'') AS GN_CHANNEL_CODE
,COALESCE(milog_rec_rectype,'') AS GN_REC_RECTYPE
,COALESCE(milog_ts_ext_tran_code,'') AS GN_TS_EXT_TRAN_CODE
,COALESCE(milog_tran_type,'') AS GN_TRAN_TYPE
,COALESCE(milog_record_status,'') AS GN_REC_STATUS
,COALESCE(milog_atm_cardnumber,'') AS GN_ATM_CARDNUMBER
,COALESCE(milog_terminal_id,'') AS GN_TERMINAL_ID
,COALESCE(milog_terminal_recno,'') AS GN_TERMINAL_RECNO
,COALESCE(milog_ts_teller_id,'') AS GN_TS_TELLER_ID
,COALESCE(milog_ts_tran_serno,'') AS GN_TS_TRAN_SERNO
,date_format(COALESCE(milog_ts_proc_date,''),'yyyyMMdd') AS GN_TS_PROC_DATE
,COALESCE(milog_eib_tranid,'') AS GN_EIB_TRANID
,COALESCE(milog_eib_termid,'') AS GN_EIB_TERMID
,COALESCE(mit_mq_rquid,'') AS MIT_MQ_RQUID
,COALESCE(MIT_ACCT1_ACCTNUM,'') AS MIT_ACCT1_ACCTNUM
,COALESCE(MIT_ACCT2_ACCTNUM,'') AS MIT_ACCT2_ACCTNUM
,COALESCE(MIT_DRCR_IND,'') AS MIT_DRCR_IND
,COALESCE(MIT_FINANCIAL_TYPE,'') AS MIT_FINANCIAL_TYPE
,COALESCE(MIT_CHEQUE_NUMBER,'') AS MIT_CHEQUE_NUMBER
,COALESCE(MIT_CHEQUE_CLRG_TYPE,'') AS MIT_CHEQUE_CLRG_TYPE
,format_number(mit_dr_tran_amount,'0000000000000.00') AS MIT_DR_TRAN_AMOUNT
,COALESCE(MIT_DR_TRAN_CCY,'') AS MIT_DR_TRAN_CCY
,format_number(mit_cr_tran_amount,'0000000000000.00') AS MIT_CR_TRAN_AMOUNT
,COALESCE(MIT_CR_TRAN_CCY,'') AS MIT_CR_TRAN_CCY
,COALESCE(MIT_FEE_PROCESS_IND,'') AS MIT_FEE_PROCESS_IND
,COALESCE(MIT_FEE_TYPE_01,'') AS MIT_FEE_TYPE_01
,format_number(mit_fee_amount_01,'0000000000000.00') AS MIT_FEE_AMOUNT_01
,COALESCE(MIT_FEE_TYPE_02,'') AS MIT_FEE_TYPE_02
,format_number(mit_fee_amount_02,'0000000000000.00') AS MIT_FEE_AMOUNT_02
,COALESCE(MIT_FEE_TYPE_03,'') AS MIT_FEE_TYPE_03
,format_number(mit_fee_amount_03,'0000000000000.00') AS MIT_FEE_AMOUNT_03
,COALESCE(MIT_FEE_TYPE_04,'') AS MIT_FEE_TYPE_04
,format_number(mit_fee_amount_04,'0000000000000.00') AS MIT_FEE_AMOUNT_04
,COALESCE(MIT_FEE_TYPE_05,'') AS MIT_FEE_TYPE_05
,format_number(mit_fee_amount_05,'0000000000000.00') AS MIT_FEE_AMOUNT_05
,COALESCE(MIT_FEE_TYPE_06,'') AS MIT_FEE_TYPE_06
,format_number(mit_fee_amount_06,'0000000000000.00') AS MIT_FEE_AMOUNT_06
,COALESCE(MIT_FEE_TYPE_07,'') AS MIT_FEE_TYPE_07
,format_number(mit_fee_amount_07,'0000000000000.00') AS MIT_FEE_AMOUNT_07
,COALESCE(MIT_FEE_TYPE_08,'') AS MIT_FEE_TYPE_08
,format_number(mit_fee_amount_08,'0000000000000.00') AS MIT_FEE_AMOUNT_08
,COALESCE(MIT_FEE_TYPE_09,'') AS MIT_FEE_TYPE_09
,format_number(mit_fee_amount_09,'0000000000000.00') AS MIT_FEE_AMOUNT_09
,COALESCE(MIT_FEE_TYPE_10,'') AS MIT_FEE_TYPE_10
,format_number(mit_fee_amount_10,'0000000000000.00') AS MIT_FEE_AMOUNT_10
,dl_data_dt

from p1dlprst.gn_mtlog_2_0
