CREATE OR REPLACE VIEW P1VEULQ.VLQ_10_SUM_DEP_WD_MON_BASIS (
  MONTHENDDATE,
  AC_CODE,
  PROD_CODE,
  CURR_CODE,
  WITHDRAWN_EQUIVALENT_BAHT_AMT,
  WITHDRAWN_CURRENCY_AMT)
AS SELECT 
( DATE_FORMAT(CB.BUSINESSDATE , 'yyyy-MM-dd')) AS MONTHENDDATE
,trim(CAST(COA.ACCOUNT_VAL  AS CHAR(5))) AS AC_CODE
,trim(CAST(COA.PRODUCT_VAL AS CHAR(4))) AS PROD_CODE
,trim(CAST(CURR.SOURCE_KEY AS CHAR(3))) AS CURR_CODE
,SUM(CAST(JEL.JOURNAL_ENTRY_LINE_GLOBAL_AMT AS DECIMAL(18,2))) AS WITHDRAWN_EQUIVALENT_BATH_AMT
,SUM(CAST(JEL.JOURNAL_ENTRY_LINE_TRANS_AMT AS DECIMAL(18,2))) AS WITHDRAWN_CURRENCY_AMT

FROM  P1VTTEDW.LEDGER_BATCH AS LB

INNER JOIN P1VTPLQ.VLQ_BUSINESSDATE_M AS CB
ON LB.START_DT BETWEEN CB.PREVBUSINESSDATE + 1 AND CB.BUSINESSDATE
    AND LB.RECORD_DELETED_FLAG = 0
    AND LB.CTL_ID = '006'
     AND LB.LEDGER_BATCH_DESC LIKE '%SCBFNF%'


INNER JOIN P1VTTEDW.JOURNAL_ENTRY_HEADER JEH
ON LB.LEDGER_BATCH_ID = JEH.JE_HEADER_LEDGER_BATCH_ID
 AND JEH.SET_OF_BOOKS_CD = 1
  --2019-11-29 add filter active record
 AND JEH.START_DT BETWEEN CB.PREVBUSINESSDATE + 1 AND CB.BUSINESSDATE
 AND JEH.RECORD_DELETED_FLAG = 0
 AND JEH.CTL_ID = '006'


INNER JOIN P1VTTEDW.JOURNAL_ENTRY_LINE JEL
ON JEH.JE_HEADER_ID = JEL.JE_HEADER_ID
 AND JEL.JOURNAL_ENTRY_LINE_CREDIT_IND = 'D' 
 --2019-11-29 add filter active record
 AND JEL.START_DT BETWEEN CB.PREVBUSINESSDATE + 1 AND CB.BUSINESSDATE
 AND JEL.RECORD_DELETED_FLAG = 0
 AND JEL.CTL_ID = '006'


INNER JOIN P1VTTEDW.CHART_OF_ACCOUNT COA
ON JEL.JOURNAL_ENTRY_LINE_COA_ID = COA.CHART_OF_ACCOUNT_ID
 AND COA.ACCOUNT_VAL <> '12001' 
 --2019-11-29 add filter active record
 AND CB.BUSINESSDATE BETWEEN COA.START_DT AND COA.END_DT
 AND COA.RECORD_DELETED_FLAG = 0
 AND  COA.COMPANY_VAL = '01'  

INNER JOIN P1VUTEDW.M09700_CRNCY CURR
ON CURR.EDW_CODE = JEL.JOURNL_ENTRY_LN_TRANS_CRNCY_CD
 AND CURR.SRC_CTL_ID = '006'
 --2019-11-29 add filter
 AND CURR.SOURCE_ID = 1

 -- /*

GROUP BY 1 ,2,3,4

UNION ALL

SELECT 
( DATE_FORMAT(CB.BUSINESSDATE , 'yyyy-MM-dd')) AS MONTHENDDATE
,CAST(COA.ACCOUNT_VAL  AS CHAR(5)) AS AC_CODE
,CAST(COA.PRODUCT_VAL AS CHAR(4)) AS PROD_CODE
,CAST(CURR.SOURCE_KEY AS CHAR(3)) AS CURR_CODE
,SUM(CAST(JEL.JOURNAL_ENTRY_LINE_GLOBAL_AMT AS DECIMAL(18,2))) AS WITHDRAWN_EQUIVALENT_BATH_AMT
,SUM(CAST(JEL.JOURNAL_ENTRY_LINE_TRANS_AMT AS DECIMAL(18,2))) AS WITHDRAWN_CURRENCY_AMT

FROM  P1VTTEDW.LEDGER_BATCH AS LB

INNER JOIN P1VTPLQ.VLQ_BUSINESSDATE_M AS CB
ON LB.START_DT BETWEEN CB.PREVBUSINESSDATE + 1 AND CB.BUSINESSDATE
    AND LB.RECORD_DELETED_FLAG = 0
    AND LB.CTL_ID = '006'
    AND LB.LEDGER_BATCH_DESC LIKE '%SCBFNF%'


INNER JOIN P1VTTEDW.JOURNAL_ENTRY_HEADER JEH
ON LB.LEDGER_BATCH_ID = JEH.JE_HEADER_LEDGER_BATCH_ID
 AND JEH.SET_OF_BOOKS_CD = 1
 --2019-11-29 add filter active record
 AND JEH.START_DT BETWEEN CB.PREVBUSINESSDATE + 1 AND CB.BUSINESSDATE
 AND JEH.RECORD_DELETED_FLAG = 0
 AND JEH.CTL_ID = '006'


INNER JOIN P1VTTEDW.JOURNAL_ENTRY_LINE JEL
ON JEH.JE_HEADER_ID = JEL.JE_HEADER_ID
 AND JEL.JOURNAL_ENTRY_LINE_CREDIT_IND = 'C' 
 --2019-11-29 add filter active record
 AND JEL.START_DT BETWEEN CB.PREVBUSINESSDATE + 1 AND CB.BUSINESSDATE
 AND JEL.RECORD_DELETED_FLAG = 0
 AND JEL.CTL_ID = '006'


INNER JOIN P1VTTEDW.CHART_OF_ACCOUNT COA
ON JEL.JOURNAL_ENTRY_LINE_COA_ID = COA.CHART_OF_ACCOUNT_ID
 AND COA.ACCOUNT_VAL = '12001' 
 --2019-11-29 add filter active record
 AND CB.BUSINESSDATE BETWEEN COA.START_DT AND COA.END_DT
 AND COA.RECORD_DELETED_FLAG = 0
  AND  COA.COMPANY_VAL = '01'  

INNER JOIN P1VUTEDW.M09700_CRNCY CURR
ON CURR.EDW_CODE = JEL.JOURNL_ENTRY_LN_TRANS_CRNCY_CD
 AND CURR.SRC_CTL_ID = '006'
 --2019-11-29 add filter
 AND CURR.SOURCE_ID = 1

 -- /*

GROUP BY 1 ,2,3,4
