CREATE OR REPLACE VIEW P1VTXEDW.VUL_CCACSEQ_01 (
  REFER_ID,
  NAMESEQID,
  ACCOUNTSEQNO,
  ENQUIRYMEMBER,
  ACCOUNTTYPE,
  OWNERSHIP,
  CURRENCYCODE,
  ACCOUNTOPENEDDATE,
  LASTPAYDATE,
  ACCOUNTCLOSEDDATE,
  ASOFDATE,
  CREDITLIMIT,
  OWEDAMOUNT,
  PASTDUEAMOUNT,
  DEFAULTDATE,
  TERMFREQUENCY,
  TERMAMOUNT,
  TERMNUMBER,
  PAYHISTORY1,
  PAYHISTORY2,
  PAYHISTORYSTART,
  PAYHISTORYEND,
  ACCOUNTSTATUS,
  LOANCLASS,
  LOANOBJECTIVE,
  COLLATERAL1,
  COLLATERAL2,
  COLLATERAL3,
  DATELASTDEBT,
  PERCENTPAYMENT,
  TYPEOFCREDITCARD,
  NUMOFCOBORROW,
  UNITMAKE,
  UNITMODEL,
  CREDITTYPEFLAG,
  TOT_INSTALLMENT,
  TOT_INSTALLMENT_CURRENT,
  TOT_INSTALLMENT_HISTORY,
  REMAIN_TERM,
  FIELD_DESCRIPTION,
  PZINSKEY,
  BORROWERINFO_ID)
COMMENT ' #####################################################################################
 SYSTEM       : Legacy Impact for LEADs project Phase-Unsecured Product
 UR         : R59050023
 MODELER NAME   : PAWARIT N.
 CREATED BY      : CHANDRAIAH P.
 CREATE DATE    : 2017-02-01
 VIEW NAME     : VTXEDW.VUL_CCACSEQ_01
 MAPPING DOCUMENT : EDW_Mapping_Source_Revenue Score_MapXFormBusRule_Diagram_V3.1.vsd
 #####################################################################################
 
 SEL  << mig orig
'
AS SELECT 
CAST(SUB_UL_CUST_LOAN.APPLICATIONID||'_'||CAST(CAST(SUB_UL_CUST_LOAN.LOANS_ID AS BIGINT) AS VARCHAR(18) ) AS VARCHAR(18)) AS REFER_ID,
CAST(CAST(CAST(LEAD.NAMESEGID AS BIGINT) AS VARCHAR(5) )||'_'||CAST(CAST(LEAD.IDSEQNO AS BIGINT) AS VARCHAR(5) ) AS VARCHAR(10)) AS NAMESEQID,
CAST(CAST(CAST(LEAD.SEQTL AS BIGINT) AS VARCHAR(4) ) AS VARCHAR(10)) AS ACCOUNTSEQNO,
CAST(LEAD.MEMBERNAME AS VARCHAR(32)) AS ENQUIRYMEMBER,
CAST(LEAD.ACCTTYPE AS VARCHAR(2)) AS ACCOUNTTYPE,
CAST(LEAD.OWNIND AS VARCHAR(1)) AS OWNERSHIP,
CAST(LEAD.CURRCODE AS VARCHAR(3)) AS CURRENCYCODE,
CASE WHEN COALESCE(LEAD.DATEOPEN,'') ='' THEN DATE'1000-01-03'
     ELSE TO_DATE(TO_DATE(
  CAST(SUBSTR(LEAD.DATEOPEN,1,4) AS SMALLINT)  || SUBSTR(LEAD.DATEOPEN,5,4) /* delete -543 */
  ,'yyyyMMdd') ,'yyyy-MM-dd') END AS ACCOUNTOPENEDDATE,
CASE WHEN COALESCE(LEAD.DATELASTPAY,'') ='' THEN DATE'1000-01-03'
     ELSE TO_DATE(TO_DATE(
  CAST(SUBSTR(LEAD.DATELASTPAY,1,4) AS SMALLINT)  || SUBSTR(LEAD.DATELASTPAY,5,4) /* delete -543 */
  ,'yyyyMMdd') ,'yyyy-MM-dd') END AS LASTPAYDATE,
CASE WHEN COALESCE(LEAD.DATECLOSE,'') ='' THEN DATE'1000-01-03'
     ELSE TO_DATE(TO_DATE(
  CAST(SUBSTR(LEAD.DATECLOSE,1,4) AS SMALLINT)  || SUBSTR(LEAD.DATECLOSE,5,4) /* delete -543 */
  ,'yyyyMMdd') ,'yyyy-MM-dd') END AS ACCOUNTCLOSEDDATE,
CASE WHEN COALESCE(LEAD.ASDATE,'') ='' THEN DATE'1000-01-03'
     ELSE TO_DATE(TO_DATE(
  CAST(SUBSTR(LEAD.ASDATE,1,4) AS SMALLINT)  || SUBSTR(LEAD.ASDATE,5,4) /* delete -543 */
  ,'yyyyMMdd') ,'yyyy-MM-dd') END AS ASOFDATE,
CAST(LEAD.CREDITLIMIT AS DECIMAL(18,2)) AS CREDITLIMIT,
CAST(LEAD.AMTOWNED AS DECIMAL(18,2)) AS OWEDAMOUNT,
CAST(LEAD.AMTPASTDUE AS DECIMAL(18,2)) AS PASTDUEAMOUNT,
CAST(LEAD.DEFAULTDATE AS DECIMAL(10,2)) AS DEFAULTDATE,
CAST(LEAD.INSTALLFREQ AS CHAR(1)) AS TERMFREQUENCY,
CAST(LEAD.INSTALLAMT AS DECIMAL(12,2)) AS TERMAMOUNT,
CAST(LEAD.INSTALLNO AS VARCHAR(4)) AS TERMNUMBER,
CAST(LEAD.PAYHIST1 AS VARCHAR(54)) AS PAYHISTORY1,
CAST(LEAD.PAYHIST2 AS VARCHAR(54)) AS PAYHISTORY2,
CASE WHEN COALESCE(LEAD.PAYHISTSDATE,'') ='' THEN DATE'1000-01-03'
     ELSE TO_DATE(TO_DATE(
  CAST(SUBSTR(LEAD.PAYHISTSDATE,1,4) AS SMALLINT)  || SUBSTR(LEAD.PAYHISTSDATE,5,4) /* delete -543 */
  ,'yyyyMMdd') ,'yyyy-MM-dd') END AS PAYHISTORYSTART,
CASE WHEN COALESCE(LEAD.PAYHISTEDATE,'') ='' THEN DATE'1000-01-03'
     ELSE TO_DATE(TO_DATE(
  CAST(SUBSTR(LEAD.PAYHISTEDATE,1,4) AS SMALLINT)  || SUBSTR(LEAD.PAYHISTEDATE,5,4) /* delete -543 */
  ,'yyyyMMdd') ,'yyyy-MM-dd') END AS PAYHISTORYEND,
CAST(LEAD.ACCTSTATUS AS VARCHAR(2)) AS ACCOUNTSTATUS,
CAST(LEAD.LOANCLASS AS VARCHAR(2)) AS LOANCLASS,
CAST(LEAD.LOANOBJ AS VARCHAR(5)) AS LOANOBJECTIVE,
CAST(LEAD.COLL1 AS VARCHAR(3)) AS COLLATERAL1,
CAST(LEAD.COLL2 AS VARCHAR(3)) AS COLLATERAL2,
CAST(LEAD.COLL3 AS VARCHAR(3)) AS COLLATERAL3,
CAST(LEAD.LDATEDEBT AS VARCHAR(8)) AS DATELASTDEBT,
CAST(LEAD.PERCENTPAY AS DECIMAL(5,2)) AS PERCENTPAYMENT,
CAST(LEAD.TYPECARD AS VARCHAR(2)) AS TYPEOFCREDITCARD,
CAST(LEAD.NOCOBORROW AS VARCHAR(2)) AS NUMOFCOBORROW,
CAST(LEAD.UNITMAKE AS VARCHAR(15)) AS UNITMAKE,
CAST(LEAD.UNITMODEL AS VARCHAR(15)) AS UNITMODEL,
CAST(LEAD.CREDITTYPEFG AS VARCHAR(3)) AS CREDITTYPEFLAG,
CAST(NULL AS DECIMAL(15,2)) AS TOT_INSTALLMENT,
CAST(NULL AS DECIMAL(15,2)) AS TOT_INSTALLMENT_CURRENT,
CAST(NULL AS DECIMAL(15,2)) AS TOT_INSTALLMENT_HISTORY,
CAST(NULL AS INT) AS REMAIN_TERM,
CAST(NULL  AS VARCHAR(100)) AS FIELD_DESCRIPTION,
CAST(LEAD.PZINSKEY AS  VARCHAR(128)) PZINSKEY,
CAST(LEAD.BORROWERINFO_ID AS DECIMAL(18,0))  AS BORROWERINFO_ID
FROM

/*  (SEL  << mig orig 
*/
 (SELECT 
NAMESEGID,
IDSEQNO,
SEQTL,
MEMBERNAME,
ACCTTYPE,
OWNIND,
CURRCODE,
DATEOPEN,
DATELASTPAY,
DATECLOSE,
ASDATE,
CREDITLIMIT,
AMTOWNED,
AMTPASTDUE,
DEFAULTDATE,
INSTALLFREQ,
INSTALLAMT,
INSTALLNO,
PAYHIST1,
PAYHIST2,
PAYHISTSDATE,
PAYHISTEDATE,
ACCTSTATUS,
LOANCLASS,
LOANOBJ,
COLL1,
COLL2,
COLL3,
LDATEDEBT,
PERCENTPAY,
TYPECARD,
NOCOBORROW,
UNITMAKE,
UNITMODEL,
CREDITTYPEFG,
PZINSKEY,
BORROWERINFO_ID
FROM P1VSTEDW.LEAD_UL_APL_PTYBU_PN_TL_1_0) AS LEAD

INNER JOIN 
(
/*   SEL << mig orig 
*/
  SELECT  APP.PZINSKEY,
 BORW.BORROWERINFO_ID,
 APP.APPLICATIONID,
 LOAN.LOANS_ID
 FROM 
 
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 APPLICATIONID,
 PYSTATUSWORK
 FROM P1VSTEDW.LEAD_UL_APPLICATION_1_0
 ) AS APP
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  BORROWERINFO_ID,
 PZINSKEY
 FROM P1VSTEDW.LEAD_UL_BORW_1_0
 ) AS BORW
 ON BORW.PZINSKEY = APP.PZINSKEY
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 BORROWERINFO_ID,
 REFERENCENO,
 DOCUMENTTYPE
 FROM P1VSTEDW.LEAD_UL_BORW_REF_1_0
 ) AS BORW_REF
 ON BORW_REF.PZINSKEY = BORW.PZINSKEY
 AND BORW_REF.BORROWERINFO_ID = BORW.BORROWERINFO_ID
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 REFERENCENO,
 DOCUMENTTYPE,
 LOANS_ID,
 ACCOUNTOWNER_ID
 FROM P1VSTEDW.LEAD_UL_LN_ACCOWN_REF_1_0
 ) AS ACCOWN_REF
 ON ACCOWN_REF.PZINSKEY = BORW_REF.PZINSKEY
 AND ACCOWN_REF.REFERENCENO = BORW_REF.REFERENCENO
 AND ACCOWN_REF.DOCUMENTTYPE = BORW_REF.DOCUMENTTYPE
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 LOANS_ID,
 ACCOUNTOWNER_ID
 FROM P1VSTEDW.LEAD_UL_LN_ACCOWN_1_0
 ) AS ACCOWN
 ON ACCOWN.PZINSKEY = ACCOWN_REF.PZINSKEY
 AND ACCOWN.LOANS_ID = ACCOWN_REF.LOANS_ID
 AND ACCOWN.ACCOUNTOWNER_ID = ACCOWN_REF.ACCOUNTOWNER_ID
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 LOANS_ID
 FROM P1VSTEDW.LEAD_UL_LN_1_0
 ) AS LOAN
 ON LOAN.PZINSKEY = APP.PZINSKEY
 AND LOAN.PZINSKEY = ACCOWN.PZINSKEY
 AND LOAN.LOANS_ID = ACCOWN.LOANS_ID 
 
 WHERE COALESCE(APP.APPLICATIONID,'') <> '' 
 AND APP.PYSTATUSWORK <> 'INDEXING-DUPLICATE'
) AS SUB_UL_CUST_LOAN
ON SUB_UL_CUST_LOAN.PZINSKEY = LEAD.PZINSKEY
AND SUB_UL_CUST_LOAN.BORROWERINFO_ID = LEAD.BORROWERINFO_ID
