CREATE OR REPLACE VIEW P1VTXEDW.VUL_CCENSEQ_01 (
  REFER_ID,
  NAMESEQID,
  ENQUIRYSEQNO,
  ENQUIRYDATE,
  ENQUIRYMEMBER,
  ENQUIRYPURPOSE,
  CREDITLIMIT,
  CURRENCYCODE,
  ENQUIRYTIME,
  ENQUIRYAMOUNT,
  PZINSKEY,
  BORROWERINFO_ID)
COMMENT '----------------------------------------------------------
 #####################################################################################
 SYSTEM       : Legacy Impact for LEADs project Phase-Unsecured Product
 UR         : R59050023
 MODELER NAME   : PAWARIT N.
 CREATED BY      : CHANDRAIAH P.
 CREATE DATE    : 2017-02-01
 VIEW NAME     : VTXEDW.VUL_CCENSEQ_01
 MAPPING DOCUMENT : EDW_Mapping_Source_Revenue Score_MapXFormBusRule_Diagram_V3.1.vsd
 #####################################################################################
 
 SEL << mig orig
'
AS SELECT CAST(SUB_UL_CUST_LOAN.APPLICATIONID||'_'||CAST(CAST(SUB_UL_CUST_LOAN.LOANS_ID AS BIGINT) AS VARCHAR(18) ) AS VARCHAR(18)) AS REFER_ID, 
CAST(CAST(CAST(NAMESEGID AS BIGINT) AS VARCHAR(5) )||'_'||CAST(CAST(IDSEQNO AS BIGINT) AS VARCHAR(5) ) AS VARCHAR(10)) AS NAMESEQID,
CAST(CAST(CAST(ENQUIRYSEQNO AS BIGINT) AS VARCHAR(5) ) AS VARCHAR(10)) AS ENQUIRYSEQNO,
CASE WHEN COALESCE(LEAD.DATEENQ,'') ='' THEN DATE'1000-01-03'
     ELSE TO_DATE(TO_DATE(
  CAST(SUBSTR(LEAD.DATEENQ,1,4) AS SMALLINT)  || SUBSTR(LEAD.DATEENQ,5,4) /* delete -543 */
  ,'yyyyMMdd') ,'yyyy-MM-dd') END AS ENQUIRYDATE,  /* SUBSTR(LEAD.ASDATE,1,4)||SUBSTR(LEAD.ASDATE,5,2)||SUBSTR(LEAD.ASDATE,7,2) */ --SUBSTR(LEAD.ASDATE,1,4)||SUBSTR(LEAD.ASDATE,5,2)||SUBSTR(LEAD.ASDATE,7,2)
CAST(LEAD.MEMBERNAME AS VARCHAR(32)) AS ENQUIRYMEMBER,
CAST(LEAD.ENQPURPOSE  AS VARCHAR(32)) AS ENQUIRYPURPOSE,
CAST(NULL AS DECIMAL(18,2)) AS CREDITLIMIT,
CAST(LEAD.CURRCODE AS VARCHAR(3)) AS CURRENCYCODE,
CAST(LEAD.TIMEENQ AS VARCHAR(10)) AS ENQUIRYTIME,
CAST(LEAD.ENQUIRYAMOUNT AS VARCHAR(11)) AS ENQUIRYAMOUNT,
CAST(SUB_UL_CUST_LOAN.PZINSKEY AS VARCHAR(128)) AS PZINSKEY,
CAST(SUB_UL_CUST_LOAN.BORROWERINFO_ID AS DECIMAL(18,0)) AS BORROWERINFO_ID
FROM

/*  (SEL << mig orig 
*/
 (SELECT NAMESEGID,
IDSEQNO,
ENQUIRYSEQNO,
DATEENQ,
MEMBERNAME,
ENQPURPOSE,
CURRCODE,
TIMEENQ,
ENQUIRYAMOUNT,
PZINSKEY,
BORROWERINFO_ID
FROM P1VSTEDW.LEAD_UL_APL_PTYBU_PN_IQ_1_0) AS LEAD

INNER JOIN 
(
/*  SEL << mig orig 
*/
 SELECT APP.PZINSKEY,
BORW.BORROWERINFO_ID,
APP.APPLICATIONID,
LOAN.LOANS_ID
FROM 

/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 APPLICATIONID,
 PYSTATUSWORK
 FROM P1VSTEDW.LEAD_UL_APPLICATION_1_0
 ) AS APP
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  BORROWERINFO_ID,
 PZINSKEY
 FROM P1VSTEDW.LEAD_UL_BORW_1_0
 ) AS BORW
 ON BORW.PZINSKEY = APP.PZINSKEY
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 BORROWERINFO_ID,
 REFERENCENO,
 DOCUMENTTYPE
 FROM P1VSTEDW.LEAD_UL_BORW_REF_1_0
 ) AS BORW_REF
 ON BORW_REF.PZINSKEY = BORW.PZINSKEY
 AND BORW_REF.BORROWERINFO_ID = BORW.BORROWERINFO_ID
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 REFERENCENO,
 DOCUMENTTYPE,
 LOANS_ID,
 ACCOUNTOWNER_ID
 FROM P1VSTEDW.LEAD_UL_LN_ACCOWN_REF_1_0
 ) AS ACCOWN_REF
 ON ACCOWN_REF.PZINSKEY = BORW_REF.PZINSKEY
 AND ACCOWN_REF.REFERENCENO = BORW_REF.REFERENCENO
 AND ACCOWN_REF.DOCUMENTTYPE = BORW_REF.DOCUMENTTYPE
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 LOANS_ID,
 ACCOUNTOWNER_ID
 FROM P1VSTEDW.LEAD_UL_LN_ACCOWN_1_0
 ) AS ACCOWN
 ON ACCOWN.PZINSKEY = ACCOWN_REF.PZINSKEY
 AND ACCOWN.LOANS_ID = ACCOWN_REF.LOANS_ID
 AND ACCOWN.ACCOUNTOWNER_ID = ACCOWN_REF.ACCOUNTOWNER_ID
 
 INNER JOIN
/*   (SEL << mig orig 
*/
  (SELECT  PZINSKEY,
 LOANS_ID
 FROM P1VSTEDW.LEAD_UL_LN_1_0
 ) AS LOAN
 ON LOAN.PZINSKEY = APP.PZINSKEY
 AND LOAN.PZINSKEY = ACCOWN.PZINSKEY
 AND LOAN.LOANS_ID = ACCOWN.LOANS_ID 
 
 WHERE COALESCE(APP.APPLICATIONID,'') <> '' 
 AND APP.PYSTATUSWORK <> 'INDEXING-DUPLICATE'
) AS SUB_UL_CUST_LOAN
ON SUB_UL_CUST_LOAN.PZINSKEY = LEAD.PZINSKEY
AND SUB_UL_CUST_LOAN.BORROWERINFO_ID = LEAD.BORROWERINFO_ID
