CREATE OR REPLACE VIEW P1VTXEDW.VB2K_DBLOG_01 (
  EDW_RECORD_NO,
  WK_DEBIT_CARD_REF_NO,
  WK_SENDER_FNAME,
  WK_SENDER_LNAME,
  WK_SENDER_ACCT_NO,
  WK_SENDER_STREET,
  WK_SENDER_CITY,
  WK_SENDER_STATE,
  WK_SENDER_POSTAL_CD,
  WK_SENDER_COUNTRY,
  WK_RECEIVER_FNAME,
  WK_RECEIVER_LNAME,
  WK_TRANS_REF_NO,
  WK_ORIG_TRANS_AMT,
  WK_ORIG_CURRENCY_CODE,
  WK_TRANS_AMT_BAHT,
  WK_TRANS_DATE,
  WK_TRANS_TIME,
  WK_SENDER_BANK_NAME,
  WK_SENDER_ACQUIRER_ID,
  WK_SENDER_ACQUIRER_COUNTRY_CD,
  WK_TRANS_STATUS,
  WK_TRANS_TYPE,
  WK_TRACE_NO_AUTH,
  WK_TRACE_NO_REVERSAL,
  WK_APPROVAL_CODE)
AS SELECT
      EDW_RECORD_NO
      ,WK_DEBIT_CARD_REF_NO
      ,WK_SENDER_FNAME
      ,WK_SENDER_LNAME
      ,WK_SENDER_ACCT_NO
      ,WK_SENDER_STREET
      ,WK_SENDER_CITY
      ,WK_SENDER_STATE
      ,WK_SENDER_POSTAL_CD
      ,WK_SENDER_COUNTRY
      ,WK_RECEIVER_FNAME
      ,WK_RECEIVER_LNAME
      ,WK_TRANS_REF_NO
      ,CAST(CAST(WK_ORIG_TRANS_AMT AS DECIMAL(13,0)) / CAST(100 AS DECIMAL(5,2)) AS DECIMAL(13,2)) AS WK_ORIG_TRANS_AMT
      ,WK_ORIG_CURRENCY_CODE
      ,CAST(CAST(WK_TRANS_AMT_BAHT AS DECIMAL(13,2)) / CAST(100 AS DECIMAL(5,2)) AS DECIMAL(13,2)) AS WK_TRANS_AMT_BAHT
      ,TO_DATE(SUBSTR(WK_TRANS_DATE,1,4)||'-'||SUBSTR(WK_TRANS_DATE,5,2)||'-'||SUBSTR(WK_TRANS_DATE,7,2) ,'yyyy-MM-dd') AS WK_TRANS_DATE
      ,CAST(substring(WK_TRANS_TIME,0,2) || ':' || substring(WK_TRANS_TIME,3,2) || ':' || substring(WK_TRANS_TIME,5,2) AS TIMESTAMP ) AS WK_TRANS_TIME
      ,WK_SENDER_BANK_NAME
      ,WK_SENDER_ACQUIRER_ID
      ,WK_SENDER_ACQUIRER_COUNTRY_CD
      ,WK_TRANS_STATUS
      ,WK_TRANS_TYPE
      ,WK_TRACE_NO_AUTH
   ,WK_TRACE_NO_REVERSAL
   ,WK_APPROVAL_CODE
    FROM P1VSTEDW.B2K_DBLOG_1_0
