CREATE OR REPLACE VIEW P1VTXEDW.VEPP_B2B_EVENT_01 (
  EVENT_ID,
  EVENT_START_DT,
  EVENT_ACTIVITY_TYPE_CD,
  EVENT_STATUS_CD,
  TRANSACTION_ID,
  EVENT_START_TM,
  ACCOUNT_IND,
  FINANCIAL_IND,
  FINANCIAL_ACCOUNT_EVENT_IND,
  EVENT_AMOUNT_IND)
AS SELECT 
 
  PAYMENT.EDW_RECORD_NO AS EVENT_ID,
  TO_DATE(PAYMENT.CREATEDATE  ,'yyyy-MM-dd') AS EVENT_START_DT,
  M12950.EDW_CODE AS EVENT_ACTIVITY_TYPE_CD,
  M13400.EDW_CODE AS EVENT_STATUS_CD,
  PAYMENT.ID AS TRANSACTION_ID,
  CAST(PAYMENT.CREATETIME AS TIMESTAMP) AS EVENT_START_TM,
  CAST(NULL AS CHAR(3)) AS ACCOUNT_IND,
  CAST('YES' AS CHAR(3)) AS FINANCIAL_IND,
  CAST(CASE
     WHEN (PAYMENT.LASTMODIFYDATE IS NOT NULL ) AND (PAYMENT.LASTMODIFYTIME IS NOT NULL )
     THEN 'YES'
     ELSE 'NO'
  END AS CHAR(3)) AS FINANCIAL_ACCOUNT_EVENT_IND,
  CAST(CASE
     WHEN (PAYMENT.PAYABLEAMOUNT IS NOT NULL )
     THEN 'YES'
     ELSE 'NO'
  END AS CHAR(3)) AS EVENT_AMOUNT_IND
   
   FROM P1VSTEDW.EPP_PAYMENT_1_0 AS PAYMENT
   
   CROSS JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
  
  LEFT OUTER JOIN P1VUTEDW.M13400_EVENT_STS AS M13400
  ON M13400.SOURCE_KEY = PAYMENT.STATECODE
  AND M13400.SRC_CTL_ID = '054'
  AND M13400.SOURCE_ID = 1  
  
  WHERE M12950.SOURCE_KEY = 'Payable'
  AND M12950.SRC_CTL_ID = '054'
  AND M12950.SOURCE_ID = 1  
  
  UNION ALL
 
   ------------------------------------------------------------------------------------------------
 --VEPP_MFEE10_Event_01
 -- Staging Table : 1.EPP_MFEE_1_0 (Transaction)
   ------------------------------------------------------------------------------------------------
 SELECT 
 
  MFEE.EDW_RECORD_NO AS EVENT_ID,
  TO_DATE(MFEE.CREATEDATE  ,'yyyy-MM-dd') AS EVENT_START_DT,
  M12950.EDW_CODE AS EVENT_ACTIVITY_TYPE_CD,
  NULL AS EVENT_STATUS_CD,
  MFEE.BILLERCODE  AS TRANSACTION_ID,
  CAST(NULL AS TIMESTAMP)  AS EVENT_START_TM,
  CAST(CASE
     --WHEN( MFEE.FEEACCOUNT IS NULL  OR  MFEE.FEEACCOUNT ='' )<< mig ori.
     WHEN( MFEE.FEEACCOUNT IS NULL  OR  MFEE.FEEACCOUNT = '' )
     THEN 'NO'
     ELSE 'YES' 
  END AS CHAR(3)) AS ACCOUNT_IND,
  CAST(CASE
     --WHEN( MFEE.TOTAL_FEE IS NULL  OR  MFEE.TOTAL_FEE ='' )<< mig ori.
	 WHEN( MFEE.TOTAL_FEE IS NULL  OR  MFEE.TOTAL_FEE =0 )
     THEN 'NO'
     ELSE 'YES' 
  END AS CHAR(3)) AS FINANCIAL_IND,
  CAST(NULL AS CHAR(3)) AS FINANCIAL_ACCOUNT_EVENT_IND,
  CAST('YES' AS CHAR(3)) AS EVENT_AMOUNT_IND
   
   FROM P1VSTEDW.EPP_MFEE_1_0 AS MFEE
   
   CROSS JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
   
   WHERE M12950.SOURCE_KEY = 'Fee Account'
  AND M12950.SRC_CTL_ID = '054'
  AND M12950.SOURCE_ID = 1  
   
   UNION ALL
  
    ------------------------------------------------------------------------------------------------
 --VEPP_PAYDTAIL10_Event_01
 -- Staging Table : 1.EPP_MFEE_1_0 (Transaction)
   ------------------------------------------------------------------------------------------------
 SELECT 
 
  PAYDTAIL.EDW_RECORD_NO AS EVENT_ID,
  TO_DATE(PAYDTAIL.PAYDATETIME  ,'yyyy-MM-dd') AS EVENT_START_DT,
  M12950.EDW_CODE AS EVENT_ACTIVITY_TYPE_CD,
  NULL AS EVENT_STATUS_CD,
  PAYDTAIL.PAYMENTREF  AS TRANSACTION_ID,
  CAST(NULL AS TIMESTAMP)  AS EVENT_START_TM,
  CAST(NULL AS CHAR(3))  AS ACCOUNT_IND,
  CAST(CASE
     --WHEN( PAYDTAIL.FEEAMT IS NULL  OR  PAYDTAIL.FEEAMT ='' ) << mig ori.
	 WHEN( PAYDTAIL.FEEAMT IS NULL  OR  PAYDTAIL.FEEAMT =0 )
     THEN 'NO'
     ELSE 'YES' 
  END AS CHAR(3)) AS FINANCIAL_IND,
  CAST(NULL AS CHAR(3))  AS FINANCIAL_ACCOUNT_EVENT_IND,
  CAST(CASE
     --WHEN( PAYDTAIL.PAYABLEAMOUNT IS NULL  OR  PAYDTAIL.PAYABLEAMOUNT ='' ) << mig ori.
	 WHEN( PAYDTAIL.PAYABLEAMOUNT IS NULL  OR  PAYDTAIL.PAYABLEAMOUNT =0 )
     THEN 'NO'
     ELSE 'YES' 
  END AS CHAR(3)) AS EVENT_AMOUNT_IND
  
   FROM P1VSTEDW.EPP_PAYDTAIL_1_0 AS PAYDTAIL
   
     CROSS JOIN P1VUTEDW.M12950_EVENT_ACTVY_TYPE AS M12950
   
   WHERE M12950.SOURCE_KEY = 'Payable Detail'
  AND M12950.SRC_CTL_ID = '054'
  AND M12950.SOURCE_ID = 1
