CREATE OR REPLACE VIEW P1VSTEDW.S1_HITCOUNT_1_0 (
  CUSTOMERID,
  FUNCTIONCODE,
  FUNCTIONNAME,
  NUMBERHIT,
  HITDATE,
  START_DT,
  END_DT,
  RECORD_DELETED_FLAG,
  CTL_ID,
  INS_PROC_NAME,
  INS_TXF_BATCHID,
  UPD_PROC_NAME,
  UPD_TXF_BATCHID,
  BK_AGREEMENTCS_154_001)
COMMENT '------------------------------------------------------------------------------


      SEL * FROM  P1DSGEDW.S1_HITCOUNT_1_0  << mig orig
'
AS SELECT rtrim(CUSTOMERID) AS CUSTOMERID,
FUNCTIONCODE AS FUNCTIONCODE,
/* FUNCTIONNAME AS FUNCTIONNAME, >> edited by program */
upper(rtrim(FUNCTIONNAME)) AS FUNCTIONNAME,
NUMBERHIT AS NUMBERHIT,
HITDATE AS HITDATE,
START_DT AS START_DT,
END_DT AS END_DT,
RECORD_DELETED_FLAG AS RECORD_DELETED_FLAG,
/* CTL_ID AS CTL_ID, >> edited by program */
upper(rtrim(CTL_ID)) AS CTL_ID,
/* INS_PROC_NAME AS INS_PROC_NAME, >> edited by program */
upper(rtrim(INS_PROC_NAME)) AS INS_PROC_NAME,
INS_TXF_BATCHID AS INS_TXF_BATCHID,
/* UPD_PROC_NAME AS UPD_PROC_NAME, >> edited by program */
upper(rtrim(UPD_PROC_NAME)) AS UPD_PROC_NAME,
UPD_TXF_BATCHID AS UPD_TXF_BATCHID,
/* BK_AGREEMENTCS_154_001 AS BK_AGREEMENTCS_154_001 FROM  P1DSGEDW.S1_HITCOUNT_1_0  >> edited by program */
rtrim(BK_AGREEMENTCS_154_001) AS BK_AGREEMENTCS_154_001 FROM  P1DSGEDW.S1_HITCOUNT_1_0
