CREATE OR REPLACE VIEW P1VEUOBM.VOBM_18_PART_INFO_NSCB (
  PART_ID,
  PART_SRCH_PNAME,
  PART_LIST_PNAME,
  PART_FST_PNAME,
  PART_MID_PNAME,
  PART_LST_PNAME,
  PART_PTITLE_CD,
  PART_STATUS_CD,
  PART_PB_IND,
  PART_SOURCE_CD,
  PART_OC_CODE,
  PART_CUST_TYP,
  CUST_NO_RM,
  LU_DTE)
COMMENT ' ############################################################
 DSF System: (OBM)
 Modeler name: Tippawan
 Develop BY: xxxx
 Version mapping: V 1-1.1
 CREATE DATE: 10/05/2008
 Update history: 10/05/2008 : Modify by : xxx
  1.) LU_DTE: change from  PAR_IDE.Party_Identification_Start_Dt to VOBM_BUSINESSDATE.BUSINESSDATE 22/05/2008 BY THANUT
  Update history: 10/05/2008 : Modify by : xxx
  1.) Change  condition field PART_PB_IND check P and C
  Update history: 04/08/2008 : Modify by : Chaiya
  1.) Change  condition Party_Identification_Num LIKE  ANY ("0080%", "0081%")
 ############################################################
 
 




INDIVIDUAL

'
AS SELECT 
CAST(PARTY.PARTY_ID AS VARCHAR(26) ) AS PART_ID,
/* PARTY.PARTY_TYPE_CD AS PARTY_TYPE_CD, 
*/
CAST( IND_NAM_HIS.Given_Name 
 || ' ' || IND_NAM_HIS.Middle_Name 
 || ' ' || IND_NAM_HIS.Family_Name
 || ' ' || M36000_EN.Source_key 
 AS VARCHAR(100)) AS PART_SRCH_PNAME,

CAST((  M36000_EN.Source_key|| ' ' || 
 IND_NAM_HIS.Given_Name|| ' ' ||
 IND_NAM_HIS.Middle_Name|| ' ' ||
 IND_NAM_HIS.Family_Name) AS CHAR(120)) AS PART_LIST_PNAME,

CAST(IND_NAM_HIS.Given_Name AS VARCHAR(100)) AS PART_FST_PNAME,
CAST(IND_NAM_HIS.Middle_Name AS VARCHAR(30)) AS PART_MID_PNAME,
CAST(IND_NAM_HIS.Family_Name AS VARCHAR(30)) AS PART_LST_PNAME,
CAST(LEFT(M36000_EN.Source_key,15) AS CHAR(15)) AS PART_PTITLE_CD,
CAST(' ' AS CHAR(1)) AS PART_STATUS_CD,
CAST('P' AS CHAR(1)) AS PART_PB_IND,
CAST('CBS' AS CHAR(4)) AS PART_SOURCE_CD,
CAST(LEFT(FIN_INS_INT_ORG.Organization_Num,8) AS CHAR(8)) AS PART_OC_CODE,
CAST(M23401.Source_key AS CHAR(2)) AS PART_CUST_TYP,
CAST(PAR_IDE.Party_Identification_Num AS CHAR(30)) AS CUST_NO_RM,
/*  (VOBM_BUSINESSDATE.BUSINESSDATE (FORMAT 'YYYY-MM-DD') (CHAR(10)))   AS LU_DTE  << mig orig 
*/
 ( CAST(DATE_FORMAT(VOBM_BUSINESSDATE.BUSINESSDATE , 'yyyy-MM-dd') AS CHAR(10)))   AS LU_DTE 

/* SELECT COUNT(*) 
*/
FROM  P1VTTEDW.PARTY PARTY   /* 14,879,945 */ --14,879,945
INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D VOBM_BUSINESSDATE
ON  VOBM_BUSINESSDATE.BUSINESSDATE   BETWEEN PARTY.START_DT AND PARTY.END_DT

INNER JOIN P1VTTEDW.PARTY_IDENTIFICATION PAR_IDE
ON PAR_IDE.PARTY_ID = PARTY.PARTY_ID
AND  VOBM_BUSINESSDATE.BUSINESSDATE   BETWEEN PAR_IDE.START_DT AND PAR_IDE.END_DT
AND   PAR_IDE.RECORD_DELETED_FLAG = 0
AND  PAR_IDE.PARTY_IDENTIFICATION_TYPE_CD =12
AND  PARTY.CTL_ID = PAR_IDE.CTL_ID
/* AND  SUBSTR(PAR_IDE.PARTY_IDENTIFICATION_NUM,1,4) IN ('0080', '0081') --91 
*/
AND PAR_IDE.Party_Identification_Num LIKE  ANY ('0080%', '0081%')

LEFT OUTER JOIN P1VTTEDW.INDIVIDUAL_NAME_HIST IND_NAM_HIS
ON PARTY.PARTY_ID = IND_NAM_HIS.INDIVIDUAL_PARTY_ID
AND  VOBM_BUSINESSDATE.BUSINESSDATE   BETWEEN IND_NAM_HIS.START_DT AND IND_NAM_HIS.END_DT
AND   IND_NAM_HIS.RECORD_DELETED_FLAG = 0
AND  IND_NAM_HIS.LANGUAGE_CD =2

LEFT OUTER JOIN P1VTTEDW.PARTY_PARTY_CLASS_ASSOC PAR_PAR_CLA_ASS
ON PARTY.PARTY_ID = PAR_PAR_CLA_ASS.PARTY_ID
AND  VOBM_BUSINESSDATE.BUSINESSDATE   BETWEEN PAR_PAR_CLA_ASS.START_DT AND PAR_PAR_CLA_ASS.END_DT
AND   PAR_PAR_CLA_ASS.RECORD_DELETED_FLAG = 0
AND  PAR_PAR_CLA_ASS.PARTY_CLASSIFICATION_CD =1

LEFT OUTER JOIN
(
 P1VTTEDW.PARTY_PARTY_RELATIONSHIP_HIST PAR_PAR_REL_HIS
 INNER JOIN  P1VTTEDW.FINANCIAL_INST_INT_ORG FIN_INS_INT_ORG
 ON PAR_PAR_REL_HIS.RELATED_PARTY_ID = FIN_INS_INT_ORG.INTERNAL_ORG_PARTY_ID
 AND  PAR_PAR_REL_HIS.Party_Relationship_Role_Cd=101
)
ON PARTY.PARTY_ID = PAR_PAR_REL_HIS.RELATES_PARTY_ID
AND  VOBM_BUSINESSDATE.BUSINESSDATE   BETWEEN PAR_PAR_REL_HIS.START_DT AND PAR_PAR_REL_HIS.END_DT
AND   PAR_PAR_REL_HIS.RECORD_DELETED_FLAG = 0


/* LEFT OUTER JOIN P1VUTEDW.M36000_NAME_PREFX  AS M36000
ON  IND_NAM_HIS.Name_Prefix_Cd = M36000.EDW_CODE
AND  IND_NAM_HIS.CTL_ID = M36000.SRC_CTL_ID
AND  M36000.SOURCE_ID = 1
 
*/
LEFT OUTER JOIN P1VUTEDW.M23401_PARTY_CLASS_VAL  AS M23401
ON  PAR_PAR_CLA_ASS.Party_Class_Value_Cd = M23401.EDW_CODE
AND  PAR_PAR_CLA_ASS.CTL_ID = M23401.SRC_CTL_ID
AND  M23401.SOURCE_ID = 1

LEFT OUTER JOIN 
(SELECT edw_code,
source_key
 FROM (
    SELECT edw_code,source_key  
    ,RANK() OVER 
(PARTITION BY edw_code
ORDER BY base64(source_key) DESC)  AS R 
    FROM P1VUTEDW.M36000_NAME_PREFX
WHERE SRC_CTL_ID = '001' 
) AS SRC
    WHERE SRC.R = 1 
    ) AS M36000_EN
ON IND_NAM_HIS.Name_Prefix_Cd   = M36000_EN.EDW_CODE

WHERE   PARTY.RECORD_DELETED_FLAG = 0  
AND  PARTY.PARTY_TYPE_CD = 1 
AND  PARTY.CTL_ID = '001'

UNION  ALL


/* ----------------------------------------------------------------
Organization
 
*/
SELECT 
CAST(PARTY.PARTY_ID AS VARCHAR(26)) AS PART_ID,
/* PARTY.PARTY_TYPE_CD AS PARTY_TYPE_CD, 
*/
CAST( ORG_NAM_HIS.Org_Name || ' ' || M35850_EN.Source_key 
 AS VARCHAR(100)) AS PART_SRCH_PNAME,

CAST( M35850_EN.Source_key||  ' ' || ORG_NAM_HIS.Org_Name
 AS CHAR(120)) AS PART_LIST_PNAME,

CAST(ORG_NAM_HIS.Org_Name AS VARCHAR(100)) AS PART_FST_PNAME,
CAST(' ' AS VARCHAR(30)) AS PART_MID_PNAME,
CAST(' ' AS VARCHAR(30)) AS PART_LST_PNAME,
CAST(LEFT(M35850_EN.Source_key,15) AS CHAR(15)) AS PART_PTITLE_CD,
CAST(' ' AS CHAR(1)) AS PART_STATUS_CD,
CAST('C' AS CHAR(1)) AS PART_PB_IND,
CAST('CBS' AS CHAR(4)) AS PART_SOURCE_CD,
CAST(LEFT(FIN_INS_INT_ORG.Organization_Num,8) AS CHAR(8)) AS PART_OC_CODE,
CAST(M23401.Source_key AS CHAR(2)) AS PART_CUST_TYP,
CAST(PAR_IDE.Party_Identification_Num AS CHAR(30)) AS CUST_NO_RM,
/*  (VOBM_BUSINESSDATE.BUSINESSDATE (FORMAT 'YYYY-MM-DD') (CHAR(10)))   AS LU_DTE   --CHANGE DATE TYPE << mig orig 
*/
 ( CAST(DATE_FORMAT(VOBM_BUSINESSDATE.BUSINESSDATE , 'yyyy-MM-dd') AS CHAR(10)))   AS LU_DTE   /* CHANGE DATE TYPE */ --CHANGE DATE TYPE

/* SELECT COUNT(*) 
*/
FROM  P1VTTEDW.PARTY PARTY   /* 14,879,945 */ --14,879,945
INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D VOBM_BUSINESSDATE
ON  VOBM_BUSINESSDATE.BUSINESSDATE   BETWEEN PARTY.START_DT AND PARTY.END_DT

INNER JOIN P1VTTEDW.PARTY_IDENTIFICATION PAR_IDE
ON PAR_IDE.PARTY_ID = PARTY.PARTY_ID
AND  VOBM_BUSINESSDATE.BUSINESSDATE   BETWEEN PAR_IDE.START_DT AND PAR_IDE.END_DT
AND   PAR_IDE.RECORD_DELETED_FLAG = 0
AND  PAR_IDE.PARTY_IDENTIFICATION_TYPE_CD =12
AND  PARTY.CTL_ID = PAR_IDE.CTL_ID
/* AND  SUBSTR(PAR_IDE.PARTY_IDENTIFICATION_NUM,1,4) IN ('0080', '0081') --91 
*/
AND PAR_IDE.Party_Identification_Num LIKE  ANY ('0080%', '0081%')

LEFT OUTER JOIN P1VTTEDW.ORGANIZATION_NAME_HIST ORG_NAM_HIS
ON PARTY.PARTY_ID = ORG_NAM_HIS.ORG_PARTY_ID
AND  VOBM_BUSINESSDATE.BUSINESSDATE  BETWEEN ORG_NAM_HIS.START_DT AND ORG_NAM_HIS.END_DT
AND   ORG_NAM_HIS.RECORD_DELETED_FLAG = 0
AND  ORG_NAM_HIS.LANGUAGE_CD =2

LEFT OUTER JOIN P1VTTEDW.PARTY_PARTY_CLASS_ASSOC PAR_PAR_CLA_ASS
ON PARTY.PARTY_ID = PAR_PAR_CLA_ASS.PARTY_ID
AND  VOBM_BUSINESSDATE.BUSINESSDATE 
  BETWEEN PAR_PAR_CLA_ASS.START_DT AND PAR_PAR_CLA_ASS.END_DT
AND   PAR_PAR_CLA_ASS.RECORD_DELETED_FLAG = 0
AND  PAR_PAR_CLA_ASS.PARTY_CLASSIFICATION_CD =8

LEFT OUTER JOIN
(
 P1VTTEDW.PARTY_PARTY_RELATIONSHIP_HIST PAR_PAR_REL_HIS
 INNER JOIN  P1VTTEDW.FINANCIAL_INST_INT_ORG FIN_INS_INT_ORG
 ON PAR_PAR_REL_HIS.RELATED_PARTY_ID = FIN_INS_INT_ORG.INTERNAL_ORG_PARTY_ID
 AND  PAR_PAR_REL_HIS.Party_Relationship_Role_Cd=101
)
ON PARTY.PARTY_ID = PAR_PAR_REL_HIS.RELATES_PARTY_ID
AND  VOBM_BUSINESSDATE.BUSINESSDATE   BETWEEN PAR_PAR_REL_HIS.START_DT AND PAR_PAR_REL_HIS.END_DT
AND   PAR_PAR_REL_HIS.RECORD_DELETED_FLAG = 0


/* LEFT OUTER JOIN P1VUTEDW.M35850_CMRCL_TITLE  AS M35850
ON  ORG_NAM_HIS.Commercial_Title_Cd = M35850.EDW_CODE
AND  ORG_NAM_HIS.CTL_ID = M35850.SRC_CTL_ID
AND  M35850.SOURCE_ID = 1
 
*/
LEFT OUTER JOIN 
(SELECT edw_code,
source_key
 FROM (
    SELECT edw_code,source_key  
    ,RANK() OVER 
(PARTITION BY edw_code
ORDER BY base64(source_key) DESC)  AS R 
    FROM P1VUTEDW.M35850_CMRCL_TITLE
WHERE SRC_CTL_ID = '001' 
) AS SRC
    WHERE SRC.R = 1 
    ) AS M35850_EN
ON ORG_NAM_HIS.Commercial_Title_Cd   = M35850_EN.EDW_CODE

LEFT OUTER JOIN P1VUTEDW.M23401_PARTY_CLASS_VAL  AS M23401
ON  PAR_PAR_CLA_ASS.Party_Class_Value_Cd = M23401.EDW_CODE
AND  PAR_PAR_CLA_ASS.CTL_ID = M23401.SRC_CTL_ID
AND  M23401.SOURCE_ID = 1

WHERE   PARTY.RECORD_DELETED_FLAG = 0  
AND  PARTY.PARTY_TYPE_CD = 2
AND  PARTY.CTL_ID = '001'
