CREATE OR REPLACE VIEW P1VEUDMS.VDMS_ESL_DAILY_NOTIONAL (
  AS_OF_DT,
  TRANS_NUM,
  SUB_NUM,
  CURRENT_NOTIONAL_BUY_AMT,
  CURRENT_NOTIONAL_BUY_CUR,
  CURRENT_NOTIONAL_SELL_AMT,
  CURRENT_NOTIONAL_SELL_CUR,
  MARK_TO_MARKET,
  ROOT_CNT)
COMMENT '/*############################################################
DSF SYSTEM: (DMS)
CREATE BY: NARESH KUMAR G
CREATE DATE: 2013-11-22
MAPPING:  EDW_DOWNSTREAM_DMS_ESL_TREASURY_MAPXFORMBUSRULE_SPECIFICATION_V0-6
                   DMS_ESL_TREASUTY_V0-6.VSD
			
Date: 2019-09-05
CB62050010  HCMC
change by Siriwat S.
Detail : change amt field from DECIMAL(35,20) to DECIMAL(35,2)
############################################################*/'
AS SELECT
 CAST(TO_DATE(BD.BUSINESSDATE ,'yyyy-MM-dd') AS CHAR(10)) AS AS_OF_DT
,CAST(rtrim(MX_NOTIONAL.TRANS_NUM) AS CHAR(10)) AS TRANS_NUM /* edit */
,CAST(rtrim(MX_NOTIONAL.SUB_NUM) AS CHAR(2)) AS SUB_NUM /* edit */
,CAST(FORMAT_NUMBER(MX_NOTIONAL.CURRENT_NOTIONAL_BUY_AMT, '#.00') AS VARCHAR(38) ) AS CURRENT_NOTIONAL_BUY_AMT /* edit */
,CAST(MX_NOTIONAL.CURRENT_NOTIONAL_BUY_CUR AS VARCHAR(7)) AS CURRENT_NOTIONAL_BUY_CUR
,CAST(CAST(MX_NOTIONAL.CURRENT_NOTIONAL_SELL_AMT AS DECIMAL(35,2)) AS VARCHAR(38)) AS CURRENT_NOTIONAL_SELL_AMT /*CB62050010  HCMC*/
,CAST(MX_NOTIONAL.CURRENT_NOTIONAL_SELL_CUR AS VARCHAR(7)) AS CURRENT_NOTIONAL_SELL_CUR
,CAST(FORMAT_NUMBER(MX_NOTIONAL.MARK_TO_MARKET, '#.00') AS VARCHAR(38) ) AS MARK_TO_MARKET /* edit */
,CAST(MX_NOTIONAL.ROOT_CNT AS CHAR(10)) AS ROOT_CNT
FROM P1VTTEDW.PMS_MX_DAILYCURNOTIONAL AS MX_NOTIONAL
INNER JOIN P1VTPDMS.VDMS_BUSINESSDATE_D AS BD
   ON BD.BUSINESSDATE BETWEEN MX_NOTIONAL.START_DT AND MX_NOTIONAL.END_DT
AND MX_NOTIONAL.RECORD_DELETED_FLAG = 0
AND MX_NOTIONAL.CTL_ID='305'
