CREATE OR REPLACE VIEW P1VSGMF.ST_STACTM_2_0 (
  ST_CONTROL_1,
  ST_CONTROL_2,
  ST_CONTROL_3,
  ST_CONTROL_4,
  ST_ACCOUNT_NO,
  ST_NA_COUNTRY,
  ST_NAME_LINE_1,
  ST_NAME_LINE_2,
  ST_NAME_LINE_3,
  ST_ADDRESS_LINE_1,
  ST_ADDRESS_LINE_2,
  ST_ADDRESS_LINE_3,
  ST_ADDRESS_LINE_4,
  ST_ADDRESS_LINE_5,
  ST_CITY_STATE,
  ST_ZIP_CODE,
  dl_data_dt)
AS select
  COALESCE(TRIM(PRST.ST_CONTROL_1), '') AS ST_CONTROL_1,
  COALESCE(TRIM(PRST.ST_CONTROL_2), '') AS ST_CONTROL_2,
  COALESCE(TRIM(PRST.ST_CONTROL_3), '') AS ST_CONTROL_3,
  COALESCE(TRIM(PRST.ST_CONTROL_4), '') AS ST_CONTROL_4,
  COALESCE(TRIM(PRST.ST_ACCOUNT_NO), '') AS ST_ACCOUNT_NO,
  COALESCE(TRIM(RAW.ST_NA_COUNTRY), '') AS ST_NA_COUNTRY,
  COALESCE(RAW.ST_NAME_LINE_1, '') AS ST_NAME_LINE_1,
  COALESCE(RAW.ST_NAME_LINE_2, '') AS ST_NAME_LINE_2,
  COALESCE(RAW.ST_NAME_LINE_3, '') AS ST_NAME_LINE_3,
  COALESCE(TRIM(RAW.ST_ADDRESS_LINE_1), '') AS ST_ADDRESS_LINE_1,
  COALESCE(TRIM(RAW.ST_ADDRESS_LINE_2), '') AS ST_ADDRESS_LINE_2,
  COALESCE(TRIM(RAW.ST_ADDRESS_LINE_3), '') AS ST_ADDRESS_LINE_3,
  COALESCE(TRIM(RAW.ST_ADDRESS_LINE_4), '') AS ST_ADDRESS_LINE_4,
  COALESCE(TRIM(RAW.ST_ADDRESS_LINE_5), '') AS ST_ADDRESS_LINE_5,
  COALESCE(TRIM(RAW.ST_CITY_STATE), '') AS ST_CITY_STATE,
  COALESCE(TRIM(RAW.ST_ZIP_CODE), '') AS ST_ZIP_CODE,
  prst.dl_data_dt

FROM
  P1DLPRST.ST_STACTM_2_0 PRST
  INNER JOIN P1DLRAW.ST_STACTM_2_0 RAW ON TRIM(PRST.ST_CONTROL_1) = TRIM(RAW.ST_CONTROL_1)
  AND TRIM(PRST.ST_CONTROL_2) = TRIM(RAW.ST_CONTROL_2)
  AND TRIM(PRST.ST_CONTROL_3) = TRIM(RAW.ST_CONTROL_3)
  AND TRIM(PRST.ST_CONTROL_4) = TRIM(RAW.ST_CONTROL_4)
  AND TRIM(PRST.ST_ACCOUNT_NO) = TRIM(RAW.ST_ACCOUNT_NO)
  AND TRIM(PRST.DL_DATA_DT) = TRIM(RAW.DL_DATA_DT)
