CREATE OR REPLACE VIEW P1VEUOBM.VOBM_PLAN_RATE_HS (
  AS_OF_DT,
  SAGMNT_ID,
  ITEM_NO,
  ACCT_INTEREST_FEAT_START_DT,
  ACCT_INTEREST_FEAT_END_DT,
  TIER_NUM,
  SUB_TIER_NUM,
  ACCT_INTEREST_FEAT_FROM_AMT,
  ACCT_INTEREST_FEAT_TO_AMT,
  ACCT_INTEREST_FEAT_RATE,
  ACCT_INTEREST_FEAT_FINAL_RATE,
  ACCT_INTEREST_FEAT_QTY,
  ACCT_INTEREST_FEAT_NUM,
  ACCT_INTEREST_FEAT_UOM_CD,
  ACCT_INTEREST_FEAT_TXT,
  ACCT_INTEREST_SPREAD_RATE,
  INTEREST_INDEX_CD,
  FIXED_VARIABLE_IND,
  TIER_TYPE_CD_VAL)
COMMENT ' ############################################################
 DSF SYSTEM: (OBM)
 MODELER NAME: SUTIDA T.
 DEVELOP BY: Chaiya B.
 VERSION MAPPING: EDW_DownStream_OBM_MapXFormBusRule_Specification_v2-1.xls
 CREATE DATE: 2010-11-24
 ----------------------------------
 Modify By: Chaiya B.
 VERSION MAPPING: Flow_OBM_BILL_SCH_DETAIL,DEF_DETAIL,PLAN_RATEV1-3.vsd
 Modify Date: 2010-12-01
 ----------------------------------
 Modify By: Chaiya B.
 VERSION MAPPING: Flow_OBM_BILL_SCH_DETAIL,DEF_DETAIL,PLAN_RATEV1-3.vsd
 Modify Date: 2010-12-07
 DESCRIPTION : ADD field AS_OF_DT
 ----------------------------------
 MODIFY BY: Chaiya B.
 VERSION MAPPING: Flow_OBM_BILL_SCH_DETAIL,DEF_DETAIL,PLAN_RATEV1-4.vsd
 MODIFY DATE: 2010-12-09
 DESCRIPTION : Change business rule ITEM_NO
 ----------------------------------
 Modify By: Chaiya B.
 MODIFY DATE: 2010-12-15
 DESCRIPTION : Add condition filter active and closed at businessdate day
 ----------------------------------
 MODIFY BY: Chaiya B.
 MODIFY DATE: 2011-01-22
 DESCRIPTION :  change script call table _HS for SLA
 ########################################################### 
 
'
AS SELECT
/*  (BD.BUSINESSDATE (FORMAT 'YYYY-MM-DD') (CHAR(10))) AS AS_OF_DT << mig orig 
*/
 ( CAST(DATE_FORMAT(BD.BUSINESSDATE , 'yyyy-MM-dd') AS CHAR(10))) AS AS_OF_DT
,CAST(AGREMT.BASE_ACCOUNT_NUM AS CHAR(26)) AS SAGMNT_ID
/* >2010-12-09<--
,CAST(AGREMT.ACCOUNT_NUM AS CHAR(45)) AS ITEM_NO 
*/
,CAST(CASE
    WHEN  SUBSTR(AGREMT.ACCOUNT_MODIFIER_NUM,1,2)  = 'AM' AND       SUBSTR(AGREMT.Account_Num,27,1)  = '0'
     THEN     '00' || SUBSTR(AGREMT.Account_Num,1,2) || '0' || SUBSTR(AGREMT.Account_Num,3,3) ||  SUBSTR(AGREMT.Account_Num,9,4) || '0034000000000' ||  SUBSTR(AGREMT.Account_Num,13,20)
  
    WHEN  SUBSTR(AGREMT.ACCOUNT_MODIFIER_NUM,1,2)  = 'AM' AND       SUBSTR(AGREMT.Account_Num,27,1)  = ''
     THEN     SUBSTR(AGREMT.Account_Num,1,5) || 
           (CASE  
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '470' THEN SUBSTR(AGREMT.Account_Num,10,3) || '0099' 
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '473' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0035'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '478' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0031'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '479' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0479'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '496' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0030'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '497' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0497'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '498' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0498'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '485' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0032'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '487' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0034'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '489' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0036'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '491' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0063'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '493' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0064'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '475' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0060'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '481' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0061'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '483' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0062'
                    WHEN SUBSTR(AGREMT.Account_Num,6,3) = '495' THEN SUBSTR(AGREMT.Account_Num,10,3) ||'0088'                  
           ELSE  SUBSTR(AGREMT.Account_Num,6,7)   
       END)
     || SUBSTR(AGREMT.Account_Num,13,14)
  
    ELSE     AGREMT.ACCOUNT_NUM
END AS CHAR(45)) AS ITEM_NO
,CASE
 WHEN ABSF_BKEY.ACCT_INTEREST_FEAT_START_DT IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN CAST(NULL AS CHAR(10))
/*   ELSE (ABSF_BKEY.ACCT_INTEREST_FEAT_START_DT (FORMAT 'YYYY-MM-DD') (CHAR(10))) << mig orig 
*/
  ELSE ( CAST(DATE_FORMAT(ABSF_BKEY.ACCT_INTEREST_FEAT_START_DT , 'yyyy-MM-dd') AS CHAR(10)))
END AS ACCT_INTEREST_FEAT_START_DT
,CASE
 WHEN ABSF_BKEY.ACCT_INTEREST_FEAT_END_DT IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN CAST(NULL AS CHAR(10))
/*   ELSE (ABSF_BKEY.ACCT_INTEREST_FEAT_END_DT (FORMAT 'YYYY-MM-DD') (CHAR(10)))  << mig orig 
*/
  ELSE ( CAST(DATE_FORMAT(ABSF_BKEY.ACCT_INTEREST_FEAT_END_DT , 'yyyy-MM-dd') AS CHAR(10))) 
END AS ACCT_INTEREST_FEAT_END_DT
,CAST(ABSF_BKEY.TIER_NUM AS CHAR(5)) AS TIER_NUM
,CAST(ABSF_BKEY.SUB_TIER_NUM AS CHAR(2)) AS SUB_TIER_NUM
,CAST(CAST(COALESCE(ABSF_BKEY.ACCT_INTEREST_FEAT_FROM_AMT, 0) AS DECIMAL(15,2)) AS CHAR(17))  AS ACCT_INTEREST_FEAT_FROM_AMT
,CAST(CAST(COALESCE(ABSF_BKEY.ACCT_INTEREST_FEAT_TO_AMT, 0) AS DECIMAL(15,2)) AS CHAR(17)) AS ACCT_INTEREST_FEAT_TO_AMT
,CAST(format_number(CAST(COALESCE(ABSF_BKEY.ACCT_INTEREST_FEAT_RATE, 0) AS DECIMAL(12,7)), "0.0000000") AS CHAR(14)) AS ACCT_INTEREST_FEAT_RATE
,CAST(format_number(CAST(COALESCE(ABSF_BKEY.ACCT_INTEREST_FEAT_FINAL_RATE, 0) AS DECIMAL(12,7)), "0.0000000") AS CHAR(14)) AS ACCT_INTEREST_FEAT_FINAL_RATE
,CAST(TRIM(ABSF_BKEY.ACCT_INTEREST_FEAT_QTY) AS CHAR(3)) AS ACCT_INTEREST_FEAT_QTY
/* >2010-12-01 add field ACCT_INTEREST_FEAT_NUM <-- 
*/
,CAST(COALESCE(TRIM(ABSF_BKEY.ACCT_INTEREST_FEAT_NUM),'') AS CHAR(2)) AS ACCT_INTEREST_FEAT_NUM 
,CAST(COALESCE(TRIM(ABSF_BKEY.ACCT_INTEREST_FEAT_UOM_CD),'') AS CHAR(1)) AS ACCT_INTEREST_FEAT_UOM_CD
/* >2010-12-01 add field ACCT_INTEREST_FEAT_TXT <-- 
*/
,CAST(COALESCE(ABSF_BKEY.ACCT_INTEREST_FEAT_TXT,'') AS CHAR(10)) AS ACCT_INTEREST_FEAT_TXT
,CAST(format_number(CAST(COALESCE(ABSF_BKEY.ACCT_INTEREST_SPREAD_RATE, 0) AS DECIMAL(12,7)), "0.0000000") AS CHAR(14)) AS ACCT_INTEREST_SPREAD_RATE
,CAST(COALESCE(ABSF_BKEY.M17850_SOURCE_KEY,'') AS CHAR(3)) AS INTEREST_INDEX_CD
,CAST(COALESCE(ABSF_BKEY.FIXED_VARIABLE_IND,'') AS CHAR(3)) AS FIXED_VARIABLE_IND
,CAST(COALESCE(ABSF_BKEY.M00075_SOURCE_KEY,'') AS CHAR(1)) AS TIER_TYPE_CD_VAL

FROM P1VTTEDW.AGREEMENT_HS AS AGREMT

INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
ON BD.BUSINESSDATE BETWEEN AGREMT.START_DT AND AGREMT.END_DT
 AND AGREMT.RECORD_DELETED_FLAG = 0
 AND AGREMT.CTL_ID = '004'
 AND AGREMT.ACCOUNT_MODIFIER_NUM IN ('AM80','AM81')
 -->2010-12-15 add filter condition active and  closed at businessdate day<--
/* >2010-12-15 add filter condition active and  closed at businessdate day<-- 
*/
    AND (AGREMT.Acct_Current_Status_Type_Cd NOT IN (4,122,123)
  OR (AGREMT.Acct_Current_Status_Type_Cd  IN (4,122,123) AND AGREMT.ACCOUNT_CLOSE_DT = BD.BUSINESSDATE)) 
 

/* >2010-11-29 add join condition for filter level<--
 
*/
INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC_HS AS AGMT_AGMT_CL_AS
ON AGREMT.ACCOUNT_NUM = AGMT_AGMT_CL_AS.ACCOUNT_NUM
 AND AGREMT.ACCOUNT_MODIFIER_NUM = AGMT_AGMT_CL_AS.ACCOUNT_MODIFIER_NUM
 AND BD.BUSINESSDATE BETWEEN AGMT_AGMT_CL_AS.START_DT AND AGMT_AGMT_CL_AS.END_DT
 AND AGMT_AGMT_CL_AS.RECORD_DELETED_FLAG = 0
 AND AGMT_AGMT_CL_AS.AGREEMENT_CLASSIFICATION_CD = 16
 AND AGMT_AGMT_CL_AS.AGREEMENT_CLASS_VALUE_CD IN (1,5,6)
 AND AGMT_AGMT_CL_AS.CTL_ID = '004'
 
INNER JOIN 
(
SELECT
ACCINTERFEA.ACCOUNT_NUM
,ACCINTERFEA.ACCOUNT_MODIFIER_NUM
,ACCINTERFEA.ACCT_INTEREST_FEAT_START_DT
,ACCINTERFEA.ACCT_INTEREST_FEAT_END_DT
,ACCINTERFEA.TIER_NUM
,ACCINTERFEA.SUB_TIER_NUM
,ACCINTERFEA.ACCT_INTEREST_FEAT_FROM_AMT
,ACCINTERFEA.ACCT_INTEREST_FEAT_TO_AMT
,ACCINTERFEA.ACCT_INTEREST_FEAT_RATE
,ACCINTERFEA.ACCT_INTEREST_FEAT_FINAL_RATE
,ACCINTERFEA.ACCT_INTEREST_FEAT_QTY
,ACCINTERFEA.ACCT_INTEREST_FEAT_UOM_CD
,ACCINTERFEA.ACCT_INTEREST_SPREAD_RATE
,M17850.SOURCE_KEY AS M17850_SOURCE_KEY
,ACCINTERFEA.FIXED_VARIABLE_IND
,M00075.SOURCE_KEY AS M00075_SOURCE_KEY
,ACCINTERFEA.ACCT_INTEREST_FEAT_NUM
,ACCINTERFEA.ACCT_INTEREST_FEAT_TXT

FROM P1VTTEDW.ACCOUNT_INTEREST_FEATURE_HS AS ACCINTERFEA

INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
ON BD.BUSINESSDATE BETWEEN ACCINTERFEA.START_DT AND ACCINTERFEA.END_DT
 AND ACCINTERFEA.RECORD_DELETED_FLAG = 0
 AND ACCINTERFEA.CTL_ID = '004'
 AND ACCINTERFEA.ACCOUNT_MODIFIER_NUM IN ('AM80','AM81')
 
INNER JOIN P1VUTEDW.BKEY_FEATURE AS BKFEATURE
ON ACCINTERFEA.FEATURE_ID = BKFEATURE.EDW_KEY
 AND BKFEATURE.SOURCE_KEY = '3_1_Plan Rate_'
 
LEFT OUTER JOIN P1VUTEDW.M17850_INTST_INDEX AS M17850
ON ACCINTERFEA.INTEREST_INDEX_CD = M17850.EDW_CODE
 AND M17850.SOURCE_ID = 1
 AND M17850.SRC_CTL_ID = '004'
 
LEFT OUTER JOIN P1VUTEDW.M00075_TIER_TYPE AS M00075
ON ACCINTERFEA.TIER_TYPE_CD = M00075.EDW_CODE
 AND M00075.SOURCE_ID = 1
 AND M00075.SRC_CTL_ID = '004'
  
) AS ABSF_BKEY
ON AGREMT.ACCOUNT_NUM = ABSF_BKEY.ACCOUNT_NUM
 AND AGREMT.ACCOUNT_MODIFIER_NUM = ABSF_BKEY.ACCOUNT_MODIFIER_NUM
