CREATE OR REPLACE VIEW P1VSGMF.B2K_BCMSTAUX_1_0 (
  BCM_AUX_CORPORATION_NUMBER,
  BCM_AUX_ACCOUNT_NO1,
  BCM_AUX_NEW_ACCT_BIN,
  BCM_AUX_NEW_ACCT_SEQUENCE,
  BCM_PREV_ACCT_NUMBER,
  BCM_AUXUD_THAI_NAME,
  BCM_AUXUD_CREDIT_ALLOW,
  BCM_AUXUD_OCCUPATION,
  BCM_AUXUD_PERSONAL_ID,
  BCM_AUXUD_DEPT_ID,
  BCM_AUXUD_EMPLOYEE_ID,
  BCM_AUXUD_RECOMM_BY,
  BCM_AUXUD_OTH_ID_TYPE,
  BCM_AUXUD_OTH_ID,
  BCM_AUXUD_COMPANY_CODE,
  BCM_AUXUD_PROSPECT_INFO,
  BCM_AUXUD_START_PRIV_DT,
  BCM_AUXUD_END_PRIV_DT,
  BCM_AUXUD_CUST_SEGMENT,
  dl_data_dt)
AS SELECT
COALESCE(TRIM(PRST.BCM_AUX_CORPORATION_NUMBER),'') as BCM_AUX_CORPORATION_NUMBER ,
COALESCE(TRIM(PRST.BCM_AUX_ACCOUNT_NO1),'') as BCM_AUX_ACCOUNT_NO1 ,
COALESCE(TRIM(PRST.BCM_AUX_NEW_ACCT_BIN),'') as BCM_AUX_NEW_ACCT_BIN ,
COALESCE(TRIM(PRST.BCM_AUX_NEW_ACCT_SEQUENCE),'') as BCM_AUX_NEW_ACCT_SEQUENCE ,
COALESCE(TRIM(PRST.BCM_PREV_ACCT_NUMBER),'') as BCM_PREV_ACCT_NUMBER ,
COALESCE(TRIM(PRST.BCM_AUXUD_THAI_NAME),'') as BCM_AUXUD_THAI_NAME ,
right('00000'||PRST.BCM_AUXUD_CREDIT_ALLOW,5) as BCM_AUXUD_CREDIT_ALLOW /*BCM_AUXUD_CREDIT_ALLOW (FORMAT '9(5)')*/ ,
COALESCE(TRIM(PRST.BCM_AUXUD_OCCUPATION),'') as BCM_AUXUD_OCCUPATION ,
RAW.BCM_AUXUD_PERSONAL_ID ,
right('00000'||PRST.BCM_AUXUD_DEPT_ID,5) as BCM_AUXUD_DEPT_ID /*BCM_AUXUD_DEPT_ID (FORMAT '9(5)')*/ ,
PRST.BCM_AUXUD_EMPLOYEE_ID ,
COALESCE(TRIM(PRST.BCM_AUXUD_RECOMM_BY),'') as BCM_AUXUD_RECOMM_BY ,
COALESCE(TRIM(PRST.BCM_AUXUD_OTH_ID_TYPE),'') as BCM_AUXUD_OTH_ID_TYPE ,
COALESCE(TRIM(PRST.BCM_AUXUD_OTH_ID),'') as BCM_AUXUD_OTH_ID ,
right('00000'||PRST.BCM_AUXUD_COMPANY_CODE,5) as BCM_AUXUD_COMPANY_CODE /*BCM_AUXUD_COMPANY_CODE (FORMAT '9(5)')*/ ,
COALESCE(TRIM(PRST.BCM_AUXUD_PROSPECT_INFO),'') as BCM_AUXUD_PROSPECT_INFO ,
right('000000000'||PRST.BCM_AUXUD_START_PRIV_DT,9) as BCM_AUXUD_START_PRIV_DT /*BCM_AUXUD_START_PRIV_DT (FORMAT '9(9)')*/ ,
right('000000000'||PRST.BCM_AUXUD_END_PRIV_DT,9) as BCM_AUXUD_END_PRIV_DT /*BCM_AUXUD_END_PRIV_DT (FORMAT '9(9)')*/ ,
COALESCE(TRIM(PRST.BCM_AUXUD_CUST_SEGMENT),'') as BCM_AUXUD_CUST_SEGMENT ,
prst.dl_data_dt

from p1dlprst.b2k_bcmstaux_1_0 prst
left join p1dlraw.b2k_bcmstaux_1_0 raw
  on trim(prst.BCM_AUX_CORPORATION_NUMBER) = trim(raw.BCM_AUX_CORPORATION_NUMBER)
  and trim(prst.BCM_AUX_ACCOUNT_NO1) = trim(raw.BCM_AUX_ACCOUNT_NO1)
  and prst.dl_data_dt = raw.dl_data_dt
