CREATE OR REPLACE VIEW P1VEUOBM.VOBM_27_ITEM_ORIG_MAP_HS (
  AS_OF_DT,
  APPL_CODE,
  ITEM_NO,
  ORG_CNT_NO,
  ROOT_CNT_NO,
  TRAN_STATUS)
COMMENT ' ############################################################
 DSF SYSTEM: (OBM)
 MODELER NAME: Vijaykumar Jangamashetti (VJ)
 DEVELOP BY: Tanaporn W. (IBM)
 VERSION MAPPING: EDW_DownStream_OBM_MapXFormBusRule_Specification_v3-1.ods
 VERSION VISIO: EDW_DownStream_OBM_MapXFormBusRule_Specification_v3-1.vsd
 CREATE DATE: 2017-07-04
 ########################################################### 
 
 [CS000750:4 = CLOSE],
 [CS000700:100 = CANCELED] 
'
AS SELECT
/*  (BD.BUSINESSDATE (FORMAT 'YYYY-MM-DD') (CHAR(10))) AS AS_OF_DT << mig orig 
*/
 ( CAST(DATE_FORMAT(BD.BUSINESSDATE , 'yyyy-MM-dd') AS CHAR(10))) AS AS_OF_DT
,CAST(CASE
     WHEN ACCOUNT_ACCOUNT_GROUP_J01.ACCT_TO_ACCT_GROUP_RELAT_CD = 1 THEN  CAST('TR80' AS CHAR(4))
     WHEN ACCOUNT_ACCOUNT_GROUP_J01.ACCT_TO_ACCT_GROUP_RELAT_CD = 2 THEN  CAST('TR81' AS CHAR(4))
    END AS CHAR(4) 
   ) AS APPL_CODE
,RPAD(AGREEMENT_J01.ACCOUNT_NUM ||' '|| AGREEMENT_J01.ACCOUNT_MODIFIER_NUM, 45, ' ') AS ITEM_NO
,CAST(AG10.ACCOUNT_GROUP_NUM AS CHAR(45)) AS ORG_CNT_NO
,CAST(AG9.ACCOUNT_GROUP_NUM AS CHAR(45)) AS ROOT_CNT_NO
,CAST(CASE 
   WHEN  AGREEMENT_J01.ACCT_CURRENT_STATUS_TYPE_CD = 4 THEN CAST('C' AS CHAR(1))
   ELSE CAST('O' AS CHAR(1))
    END AS CHAR(1)
   ) AS TRAN_STATUS

FROM P1VTTEDW.AGREEMENT AS AGREEMENT_J01

INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
ON BD.BUSINESSDATE BETWEEN AGREEMENT_J01.START_DT AND AGREEMENT_J01.END_DT
AND AGREEMENT_J01.RECORD_DELETED_FLAG = 0
AND AGREEMENT_J01.CTL_ID = '017'
AND AGREEMENT_J01.ACCT_CURRENT_STATUS_TYPE_CD  NOT IN (4,122,123) 
OR (AGREEMENT_J01.ACCT_CURRENT_STATUS_TYPE_CD  IN (4,122,123) AND AGREEMENT_J01.ACCOUNT_CLOSE_DT = BD.BUSINESSDATE) /* [CS000750:4 = CLOSE] */ --[CS000750:4 = CLOSE]
AND AGREEMENT_J01.ACCOUNT_MODIFIER_NUM <> 'PR'

INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC AS AGMT_AGMT_CLASS_ASSOC_J01
ON AGMT_AGMT_CLASS_ASSOC_J01.ACCOUNT_NUM = AGREEMENT_J01.ACCOUNT_NUM
AND AGMT_AGMT_CLASS_ASSOC_J01.ACCOUNT_MODIFIER_NUM = AGREEMENT_J01.ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE BETWEEN AGMT_AGMT_CLASS_ASSOC_J01.START_DT AND AGMT_AGMT_CLASS_ASSOC_J01.END_DT
AND AGMT_AGMT_CLASS_ASSOC_J01.RECORD_DELETED_FLAG = 0
AND AGMT_AGMT_CLASS_ASSOC_J01.CTL_ID = '017'
AND AGMT_AGMT_CLASS_ASSOC_J01.AGREEMENT_CLASSIFICATION_CD = 27 /* [CS002000:27 = INTERNAL FLAG] */ --[CS002000:27 = INTERNAL FLAG]
AND AGMT_AGMT_CLASS_ASSOC_J01.AGREEMENT_CLASS_VALUE_CD = 2 /* [CS001987:2 = EXTERNAL TRANSACTION] */ --[CS001987:2 = EXTERNAL TRANSACTION]

INNER JOIN P1VTTEDW.ACCOUNT_ACCOUNT_GROUP AS ACCOUNT_ACCOUNT_GROUP_J01
ON ACCOUNT_ACCOUNT_GROUP_J01.ACCOUNT_NUM = AGREEMENT_J01.ACCOUNT_NUM
AND ACCOUNT_ACCOUNT_GROUP_J01.ACCOUNT_MODIFIER_NUM = AGREEMENT_J01. ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE BETWEEN ACCOUNT_ACCOUNT_GROUP_J01.START_DT AND ACCOUNT_ACCOUNT_GROUP_J01.END_DT
AND ACCOUNT_ACCOUNT_GROUP_J01.RECORD_DELETED_FLAG = 0
AND ACCOUNT_ACCOUNT_GROUP_J01.CTL_ID = '017' /* [TR] */ --[TR]
AND ACCOUNT_ACCOUNT_GROUP_J01.ACCT_TO_ACCT_GROUP_RELAT_CD IN (1,2)

LEFT JOIN P1VTTEDW.ACCOUNT_ACCOUNT_GROUP AS AAG11
ON AAG11.ACCOUNT_NUM = AGREEMENT_J01.ACCOUNT_NUM
AND AAG11.ACCOUNT_MODIFIER_NUM = AGREEMENT_J01.ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE BETWEEN AAG11.START_DT AND AAG11.END_DT
AND AAG11.RECORD_DELETED_FLAG = 0
AND AAG11.Ctl_ID = '017' /* [TR] */ --[TR]
AND AAG11.ACCT_TO_ACCT_GROUP_RELAT_CD = 11   /*  CS001150 : 11- Deal-Root Contract */ -- CS001150 : 11- Deal-Root Contract

LEFT JOIN P1VTTEDW.ACCOUNT_GROUP AS AG9 
ON AG9.ACCOUNT_GROUP_ID = AAG11.ACCOUNT_GROUP_ID
AND BD.BUSINESSDATE BETWEEN AG9.START_DT AND AG9.END_DT
AND AG9.RECORD_DELETED_FLAG = 0
AND AG9.CTL_ID = '017' /* [TR] */ --[TR]
AND AG9.ACCOUNT_GROUP_REASON_TYPE_CD = 9 /* CS000300: 9 ROOT CONTRACT NUM */ --CS000300: 9 ROOT CONTRACT NUM

LEFT JOIN P1VTTEDW.ACCOUNT_ACCOUNT_GROUP AS AAG12
ON AAG12.ACCOUNT_NUM = AGREEMENT_J01.ACCOUNT_NUM
AND AAG12.ACCOUNT_MODIFIER_NUM = AGREEMENT_J01.ACCOUNT_MODIFIER_NUM
AND BD.BUSINESSDATE BETWEEN AAG12.START_DT AND AAG12.END_DT
AND AAG12.RECORD_DELETED_FLAG = 0
AND AAG12.Ctl_ID = '017' /* [TR] */ --[TR]
AND AAG12.ACCT_TO_ACCT_GROUP_RELAT_CD = 12 /*  CS001150 : 12- DEAL-ORIGINAL CONTRACT    */ -- CS001150 : 12- DEAL-ORIGINAL CONTRACT   

LEFT JOIN P1VTTEDW.ACCOUNT_GROUP AS AG10
ON AG10.ACCOUNT_GROUP_ID = AAG12.ACCOUNT_GROUP_ID
AND BD.BUSINESSDATE BETWEEN AG10.START_DT AND AG10.END_DT
AND AG10.RECORD_DELETED_FLAG = 0
AND AG10.CTL_ID = '017' /* [TR] */ --[TR]
AND AG10.ACCOUNT_GROUP_REASON_TYPE_CD = 10 /* CS000300: 10  ORIGINAL CONTRACT NUM */ --CS000300: 10  ORIGINAL CONTRACT NUM

LEFT JOIN
(
/*  SEL << mig orig 
*/
 SELECT   ACCOUNT_NUM
  ,ACCOUNT_MODIFIER_NUM
  ,HOST_PRODUCT_GROUP_VAL 
  ,PRODUCT_NAME 
FROM P1VTTEDW.ACCOUNT_PRODUCT_HISTORY AS ACCOUNT_PRODUCT_HISTORY_J01

INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
ON BD.BUSINESSDATE BETWEEN ACCOUNT_PRODUCT_HISTORY_J01.START_DT AND ACCOUNT_PRODUCT_HISTORY_J01.END_DT
AND ACCOUNT_PRODUCT_HISTORY_J01.RECORD_DELETED_FLAG = 0
AND ACCOUNT_PRODUCT_HISTORY_J01.CTL_ID = '017' /* [TR] */ --[TR]

LEFT JOIN P1VTTEDW.PROD_GROUP_ASSOCIATION AS PROD_GROUP_ASSOCIATION_J01
ON PROD_GROUP_ASSOCIATION_J01.PRODUCT_ID = ACCOUNT_PRODUCT_HISTORY_J01.PRODUCT_ID
AND BD.BUSINESSDATE BETWEEN PROD_GROUP_ASSOCIATION_J01.START_DT AND PROD_GROUP_ASSOCIATION_J01.END_DT
AND PROD_GROUP_ASSOCIATION_J01.RECORD_DELETED_FLAG = 0
AND PROD_GROUP_ASSOCIATION_J01.CTL_ID = '017' /* [TR] */ --[TR]

LEFT JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP_J01
ON PRODUCT_GROUP_J01.PRODUCT_GROUP_ID = PROD_GROUP_ASSOCIATION_J01.PRODUCT_GROUP_ID
AND BD.BUSINESSDATE BETWEEN PRODUCT_GROUP_J01.START_DT AND PRODUCT_GROUP_J01.END_DT
AND PRODUCT_GROUP_J01.RECORD_DELETED_FLAG = 0
AND PRODUCT_GROUP_J01.CTL_ID = '017' /* [TR] */ --[TR]
AND PRODUCT_GROUP_J01.HOST_PRODUCT_GROUP_VAL <> 'FI'

LEFT JOIN P1VTTEDW.PRODUCT AS PRODUCT_J01
ON PRODUCT_J01.PRODUCT_ID = ACCOUNT_PRODUCT_HISTORY_J01.PRODUCT_ID
AND BD.BUSINESSDATE BETWEEN PRODUCT_J01.START_DT AND PRODUCT_J01.END_DT
AND PRODUCT_J01.RECORD_DELETED_FLAG = 0
AND PRODUCT_J01.CTL_ID = '017' /* [TR] */ --[TR]

) AS PRODUCT_GROUP_J01
ON PRODUCT_GROUP_J01.ACCOUNT_NUM = AGREEMENT_J01.ACCOUNT_NUM
AND PRODUCT_GROUP_J01.ACCOUNT_MODIFIER_NUM = AGREEMENT_J01.ACCOUNT_MODIFIER_NUM

WHERE NOT(PRODUCT_GROUP_J01.HOST_PRODUCT_GROUP_VAL = 'FX' AND  AGREEMENT_J01.ACCT_CURRENT_STATUS_TYPE_CD = 4 AND AGREEMENT_J01.ACCT_STATUS_REASON_CD = 100)
