CREATE OR REPLACE VIEW P1VEUOBM.VOBM_02_BALANCE_INFO_HS (
  AS_OF_DT,
  APPL_CODE,
  ITEM_NO,
  SAGMNT_ID,
  LIMIT_NO,
  LIMIT_SEQ,
  GL_PROD_CODE,
  PROD_CODE,
  FIS_CODE,
  BAL_CURR_CODE,
  BAL_AMT,
  RC_CODE,
  OC_CODE,
  STATUS,
  CLOSE_DT,
  CONTRACT_DT,
  EFFECT_DT,
  MATURITY_DT,
  PASTDUE_DT,
  STOPCAL_DT,
  FUND_FLAG,
  PENALTY_DT,
  STATUS_TDR,
  EXPRY_DT)
COMMENT ' ############################################################
  DSF SYSTEM: (OBM)
  MODELER NAME: xxx
  DEVELOP BY: Chaiya
  VERSION MAPPING: v1-1.10
  CREATE DATE: 18/03/2009
  -->Change Version : 1.1 <--
  -->Change Date : 2009-03-26 <--
  --------------------------------  by  : Kao ------------------------------------------------------
  Change  Get DATA FROM NEW TABLE ( use FOR OBM ONLY ---------------------------------
  - AGREEMENT --> AGREEMENT_HS 
  - ACCOUNT_INTEREST_FEATURE  --> ACCOUNT_INTEREST_FEATURE_HS 
  - AGMT_AGMT_CLASS_ASSOC  ---> AGMT_AGMT_CLASS_ASSOC_HS
  
  UPDATE HISTORY: 09/04/2009 : MODIFY BY : Chaiya
  1.) Change TABLE ACCOUNT_PARTY_HS, ACCOUNT_PRODUCT_HISTORY_HS
  2.) No change this condition in TR account_party (RM)when get RC_CODE, OC_CODE,BRANCH
  
     change   Date   28-04-2010    By   T. Sutida
  - change  for  fillter  Internal Deal (27,2) 
    
  Change date 2-11-2010 ADD  by T.Sutida
  Filter FX cancel TRANSACTION  OF TR OUT FROM file AS FOLLOWING:-
  UR53080007 MAS 610 APP 2 RETURN OF Monthly FOREIGN Exchange Business Transacted -REQUEST TO exclude FX Cancelled deals
  Mapping :EDW_DownStream_OBM_MapXFormBusRule_Specification_v2-3.ods
  ------------------------------------------------------------
  Modify date: 2010-11-26
  Modify By: Chaiya B.
  Mapping Version: EDW_DownStream_OBM_MapXFormBusRule_Specification_v2-1.ods 
  Description : R53040063 - ECET Project - Daily P&L of FX Option Premium
      1.) TR80,TR81 add filter account_modifier_num <> ""PR""
  ------------------------------------------------------------
  Modify date: 2011-06-21
  Modify By: Nattharut
  Mapping Version: EDW_DownStream_OBM_MapXFormBusRule_Specification_v2-4.ods 
  Description : UR R54040017 - Short term loan and loan & Deposit Products used for generating Regulatory report of SG
    Add New Field 
    1.EXPRY_DT (ALS)
  ############################################################ 
 
'
AS SELECT 
  ( CAST(DATE_FORMAT(VOBM_BUSINESSDATE.BUSINESSDATE , 'yyyy-MM-dd') AS CHAR(10)))  AS AS_OF_DT, CAST(AGREEMENT.ACCOUNT_MODIFIER_NUM AS CHAR(4)) AS APPL_CODE,
  RPAD(AGREEMENT.ACCOUNT_NUM, 45, ' ') AS ITEM_NO, 
  CAST(SUBSTR(AGREEMENT.Base_Account_Num,1,3) || '0' || SUBSTR(AGREEMENT.Base_Account_Num,4,7) AS CHAR(26)) AS SAGMNT_ID, (CASE 
   WHEN ACCOUNT_CREDIT_LIMIT.Account_Num IS NULL AND ACCOUNT_CREDIT_LIMIT.Account_Modifier_Num IS NULL
    THEN CAST( 0 AS CHAR(20))
    ELSE CAST('13' AS CHAR(20))
  END) AS LIMIT_NO, (CASE 
   WHEN CAST(OBM_TIER.LIMIT_SEQ AS DECIMAL(9,0)) = OBM_TIER.LIMIT_SEQ
               THEN CAST(CAST(OBM_TIER.LIMIT_SEQ AS DECIMAL(9,0)) AS VARCHAR(9))
               ELSE TRIM(TRAILING '0' FROM CAST(CAST(OBM_TIER.LIMIT_SEQ AS DECIMAL(9,0)) AS VARCHAR(9)))
  END) AS LIMIT_SEQ, CAST(ACCOUNT_BALANCE_SUMMARY_DD.GL_Product_Code_Val AS CHAR(4)) AS GL_PROD_CODE,
  CAST('CURR' AS CHAR(4))AS PROD_CODE, CAST(ACCOUNT_BALANCE_SUMMARY_DD.GL_Account_Code_Val AS CHAR(6)) AS FIS_CODE,
  CAST(REF_CS009700.SHORT_DESCRIPTION AS CHAR(3)) AS BAL_CURR_CODE,
  (CASE
    WHEN ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt < 0 THEN 
     CASE
     WHEN CAST(ABS(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt)  AS DECIMAL(18,2)) = ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt
           THEN CAST(CAST(ABS(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt)  AS DECIMAL(18,2)) AS VARCHAR(21))
           ELSE TRIM(TRAILING '0' FROM CAST(CAST(ABS(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt)  AS DECIMAL(18,2)) AS VARCHAR(21)))
    END
    ELSE 
     CASE
     WHEN CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt AS DECIMAL(18,2)) = ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt
           THEN CAST(CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt AS DECIMAL(18,2)) AS VARCHAR(21))
           ELSE TRIM(TRAILING '0' FROM CAST(CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt AS DECIMAL(18,2)) AS VARCHAR(21)))
    END
  END)  AS BAL_AMT, CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_21 AS CHAR(4)) AS RC_CODE,
  CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_22 AS CHAR(4)) AS OC_CODE,
  CAST(REF_CS000750.SHORT_DESCRIPTION AS CHAR(2)) AS STATUS, 
  (CASE
   WHEN AGREEMENT.Account_Close_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-10-04') THEN  CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(AGREEMENT.Account_Close_Dt  , 'yyyy-MM-dd') AS CHAR(10)))  
  END) AS CLOSE_DT,
  ( CAST(DATE_FORMAT(AGREEMENT.Account_Open_Dt   , 'yyyy-MM-dd') AS CHAR(10)))  AS CONTRACT_DT,
  (CASE 
  WHEN ACCOUNT_CREDIT_LIMIT.Account_Num IS NULL AND ACCOUNT_CREDIT_LIMIT.Account_Modifier_Num IS NULL
   THEN ( CAST(DATE_FORMAT(AGREEMENT.Account_Open_Dt , 'yyyy-MM-dd') AS CHAR(10)))
   ELSE ( CAST(DATE_FORMAT(ACCOUNT_CREDIT_LIMIT.Credit_Limit_Start_Dttm  , 'yyyy-MM-dd') AS CHAR(10)))
  END) AS EFFECT_DT, ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd')  , 'yyyy-MM-dd') AS CHAR(10)))  AS MATURITY_DT, (CASE
   WHEN ACCOUNT_COLLECTION_STATUS.Collection_Status_Start_Dttm IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCOUNT_COLLECTION_STATUS.Collection_Status_Start_Dttm,DATE '9999-12-31')  , 'yyyy-MM-dd') AS CHAR(10)))  
  END) AS PASTDUE_DT,
  (CASE
   WHEN ACCOUNT_SUMMARY_DD.Non_Accrue_Int_Start_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE'1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCOUNT_SUMMARY_DD.Non_Accrue_Int_Start_Dt,DATE '9999-12-31') , 'yyyy-MM-dd') AS CHAR(10)))  
  END) AS STOPCAL_DT,
  (CASE WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1
  THEN  CAST('F' AS CHAR(1))
  ELSE  CAST('N' AS CHAR(1))
  END)  AS FUND_FLAG, ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))   AS PENALTY_DT,
  RPAD(' ', 2 , ' ') AS STATUS_TDR,
  ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10))) AS EXPRY_DT

  FROM  P1VTTEDW.AGREEMENT_HS AS AGREEMENT
  
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS VOBM_BUSINESSDATE
  ON  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGREEMENT.START_DT 
   AND  AGREEMENT.END_DT
   AND  AGREEMENT.RECORD_DELETED_FLAG = 0
   AND  AGREEMENT.ACCOUNT_Modifier_Num IN ('IM80','IM81')
   AND (AGREEMENT.Acct_Current_Status_Type_Cd NOT IN (4,122,123) 
    OR (AGREEMENT.Acct_Current_Status_Type_Cd  IN (4,122,123) AND AGREEMENT.ACCOUNT_CLOSE_DT = VOBM_BUSINESSDATE.BUSINESSDATE))
   
  INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC_HS AS AGMT_AGMT_CLASS_ASSOC
  ON AGREEMENT.ACCOUNT_NUM = AGMT_AGMT_CLASS_ASSOC.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = AGMT_AGMT_CLASS_ASSOC.ACCOUNT_MODIFIER_NUM
   AND AGMT_AGMT_CLASS_ASSOC.Agreement_Classification_CD = 16
   AND AGMT_AGMT_CLASS_ASSOC.Agreement_CLASS_Value_CD = 1
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGMT_AGMT_CLASS_ASSOC.START_DT 
   AND AGMT_AGMT_CLASS_ASSOC.END_DT
   AND AGMT_AGMT_CLASS_ASSOC.RECORD_DELETED_FLAG = 0
   AND AGMT_AGMT_CLASS_ASSOC.CTL_ID = '003'
  
  LEFT OUTER JOIN 
  (
  SELECT
  ACCPAR.ACCOUNT_NUM,
  ACCPAR.ACCOUNT_MODIFIER_NUM,
  MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 21 
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_21, MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 22
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_22 
  FROM P1VTTEDW.ACCOUNT_PARTY_HS AS ACCPAR
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
  ON  BD.BUSINESSDATE BETWEEN ACCPAR.START_DT 
   AND ACCPAR.END_DT  AND ACCPAR.RECORD_DELETED_FLAG = 0
   AND ACCPAR.ACCOUNT_Modifier_Num IN ('IM80','IM81')
   AND ACCPAR.Account_Party_Role_Cd IN(21, 22)
  
  LEFT OUTER JOIN P1VTTEDW.FINANCIAL_INST_INT_ORG AS FINANCIAL_INST_INT_ORG
  ON ACCPAR.PARTY_ID = FINANCIAL_INST_INT_ORG.Internal_Org_Party_Id    
   AND BD.BUSINESSDATE BETWEEN FINANCIAL_INST_INT_ORG.START_DT 
    AND FINANCIAL_INST_INT_ORG.END_DT  AND FINANCIAL_INST_INT_ORG.RECORD_DELETED_FLAG = 0
  
  GROUP BY 1,2
  ) AS ACCOUNT_PARTY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PARTY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PARTY.ACCOUNT_MODIFIER_NUM
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_BALANCE_SUMMARY_DD_HS AS ACCOUNT_BALANCE_SUMMARY_DD
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_MODIFIER_NUM
   AND ACCOUNT_BALANCE_SUMMARY_DD.Balance_Category_TYPE_CD = 1  AND ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_Metric_TYPE_CD = 1 
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_BALANCE_SUMMARY_DD.START_DT 
   AND ACCOUNT_BALANCE_SUMMARY_DD.END_DT
   AND ACCOUNT_BALANCE_SUMMARY_DD.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_BALANCE_SUMMARY_DD.CTL_ID = '003'
  
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CURRENCY AS ACCOUNT_CURRENCY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CURRENCY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CURRENCY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CURRENCY.START_DT 
   AND ACCOUNT_CURRENCY.END_DT
   AND ACCOUNT_CURRENCY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_CURRENCY.CTL_ID = '003'
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_SUMMARY_DD AS ACCOUNT_SUMMARY_DD
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_SUMMARY_DD.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_SUMMARY_DD.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_SUMMARY_DD.START_DT 
   AND ACCOUNT_SUMMARY_DD.END_DT
   AND ACCOUNT_SUMMARY_DD.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_SUMMARY_DD.CTL_ID = '003'
   
  
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_COLLECTION_STATUS_HS  AS ACCOUNT_COLLECTION_STATUS
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_COLLECTION_STATUS.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_COLLECTION_STATUS.ACCOUNT_MODIFIER_NUM
   AND ACCOUNT_COLLECTION_STATUS.Past_Due_Amount_TYPE_CD = 1
   AND ACCOUNT_COLLECTION_STATUS.Collection_Status_TYPE_CD = 3
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_COLLECTION_STATUS.START_DT 
   AND ACCOUNT_COLLECTION_STATUS.END_DT
   AND ACCOUNT_COLLECTION_STATUS.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_COLLECTION_STATUS.CTL_ID = '003'
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CREDIT_LIMIT AS ACCOUNT_CREDIT_LIMIT
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CREDIT_LIMIT.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CREDIT_LIMIT.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CREDIT_LIMIT.START_DT 
   AND ACCOUNT_CREDIT_LIMIT.END_DT
   AND ACCOUNT_CREDIT_LIMIT.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_CREDIT_LIMIT.CTL_ID = '003'
   
  LEFT OUTER JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_CS009700
  ON ACCOUNT_CURRENCY.Account_Currency_Cd = REF_CS009700.EDW_CODE
   AND  REF_CS009700.CODE_ID = 55
   AND REF_CS009700.CODE_SET_ID = 'CS009700'
   AND  REF_CS009700.LANGUAGE_ID = 1 
  
  LEFT OUTER JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_CS000750
   ON  AGREEMENT.Acct_Current_Status_Type_Cd = REF_CS000750.EDW_CODE
   AND  REF_CS000750.CODE_ID = 7
   AND REF_CS000750.CODE_SET_ID = 'CS000750'
   AND  REF_CS000750.LANGUAGE_ID = 3
   
  LEFT OUTER JOIN 
  (SELECT 
     ABSD.ACCOUNT_NUM
     ,ABSD.ACCOUNT_MODIFIER_NUM
     ,MAX(CASE WHEN AIF.TIER_NUM IS NOT NULL THEN AIF.TIER_NUM ELSE 0 END)  AS LIMIT_SEQ
             
  FROM P1VTTEDW.ACCOUNT_BALANCE_SUMMARY_DD_HS AS ABSD
  
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
  ON BD.BUSINESSDATE BETWEEN ABSD.START_DT AND ABSD.END_DT
  AND ABSD.RECORD_DELETED_FLAG = 0
  AND (ABSD.ACCOUNT_MODIFIER_NUM = 'IM80' OR ABSD.ACCOUNT_Modifier_Num = 'IM81')
  AND ABSD.Balance_Category_Type_Cd = 1
  AND ABSD.Account_Metric_Type_Cd = 1
  
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_INTEREST_FEATURE_HS AS AIF
  ON ABSD.ACCOUNT_NUM = AIF.ACCOUNT_NUM
  AND ABSD.ACCOUNT_MODIFIER_NUM = AIF.ACCOUNT_MODIFIER_NUM
  AND ABSD.Acct_Crncy_Balance_Summary_Amt <= AIF.Acct_Interest_Feat_To_Amt 
  AND AIF.Acct_Interest_Feat_Role_Cd = 424
  AND BD.BUSINESSDATE BETWEEN AIF.START_DT AND AIF.END_DT
  AND AIF.RECORD_DELETED_FLAG = 0
  
  WHERE ABSD.ACCOUNT_Modifier_Num IN ('IM80','IM81')
  
  GROUP BY 1,2
  
  ) AS OBM_TIER
  ON AGREEMENT.Account_Num = OBM_TIER.Account_Num
  AND AGREEMENT.Account_Modifier_Num = OBM_TIER.Account_Modifier_Num
  
  UNION ALL
   
  SELECT
  ( CAST(DATE_FORMAT(VOBM_BUSINESSDATE.BUSINESSDATE , 'yyyy-MM-dd') AS CHAR(10)))    AS AS_OF_DT,
  CAST(AGREEMENT.Account_Modifier_Num AS CHAR(4)) AS APPL_CODE,
  RPAD(AGREEMENT.Account_Num, 45, ' ') AS ITEM_NO, 
  CAST(SUBSTR(AGREEMENT.Base_Account_Num,1,3) || '0' || SUBSTR(AGREEMENT.Base_Account_Num,4,7) AS CHAR(26)) AS SAGMNT_ID, CAST(0 AS CHAR(20)) AS LIMIT_NO, (CASE 
   WHEN CAST(0 AS DECIMAL(9,0)) = 0
               THEN CAST(CAST(0 AS DECIMAL(9,0)) AS VARCHAR(9))
               ELSE TRIM(TRAILING '0' FROM CAST(CAST(0 AS DECIMAL(9,0)) AS VARCHAR(9)))
  END) AS LIMIT_SEQ,
  CAST(ACCOUNT_BALANCE_SUMMARY_DD.GL_Product_Code_Val AS CHAR(4)) AS GL_PROD_CODE,
  CAST(SUBSTR(PRODUCT_GROUP4.Host_Product_Group_Val,1,CHARACTER_LENGTH(TRIM(PRODUCT_GROUP4.Host_Product_Group_Val))-3) AS CHAR(4))
   AS PROD_CODE, CAST(ACCOUNT_BALANCE_SUMMARY_DD.GL_Account_Code_Val AS CHAR(6)) AS FIS_CODE, 
  CAST(REF_CS009700.SHORT_DESCRIPTION AS CHAR(3)) AS BAL_CURR_CODE,
  (CASE
   WHEN CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt AS DECIMAL(18,2))  = ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt
   THEN CAST(CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt  AS DECIMAL(18,2)) AS VARCHAR(21))
    ELSE TRIM(TRAILING '0' FROM CAST(CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt  AS DECIMAL(18,2)) AS VARCHAR(21)))
  END) AS BAL_AMT,
  CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_21 AS CHAR(4)) AS RC_CODE,
  CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_22 AS CHAR(4)) AS OC_CODE,
  CAST(REF_CS000750.SHORT_DESCRIPTION AS CHAR(2)) AS STATUS, 
  (CASE
   WHEN AGREEMENT.Account_Close_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE'1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(AGREEMENT.Account_Close_Dt , 'yyyy-MM-dd') AS CHAR(10)))
  END) AS CLOSE_DT,
  ( CAST(DATE_FORMAT(AGREEMENT.Account_Open_Dt   , 'yyyy-MM-dd') AS CHAR(10)))  AS CONTRACT_DT,
  (CASE 
   WHEN SUBSTR(PRODUCT_GROUP3.Host_Product_Group_Val,1,CHARACTER_LENGTH(TRIM(PRODUCT_GROUP3.Host_Product_Group_Val))-3)  = 'FXTM'
    THEN (  CAST(DATE_FORMAT( ACCOUNT_CONTRACT_HISTORY.Contract_Start_Dttm , 'yyyy-MM-dd') AS CHAR(10)))
    ELSE ( CAST(DATE_FORMAT(Agreement.ACCOUNT_OPEN_dt  , 'yyyy-MM-dd') AS CHAR(10)))
  END)
   AS EFFECT_DT, (CASE
   WHEN AGREEMENT.Contract_Expiration_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(AGREEMENT.Contract_Expiration_Dt  , 'yyyy-MM-dd') AS CHAR(10)))  
  END) AS MATURITY_DT,
  ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))  AS PASTDUE_DT, ( CAST(DATE_FORMAT(TO_DATE('9999-12-31'  ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))  AS STOPCAL_DT, (CASE WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1
  THEN  CAST('F' AS CHAR(1))
  ELSE  CAST('N' AS CHAR(1))
  END)  AS FUND_FLAG, ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))  AS PENALTY_DT, 
  RPAD(' ', 2 , ' ') AS STATUS_TDR,
  ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))  AS EXPRY_DT

  FROM  P1VTTEDW.AGREEMENT_HS AS AGREEMENT
  
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS VOBM_BUSINESSDATE
  ON  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGREEMENT.START_DT 
   AND  AGREEMENT.END_DT
   AND  AGREEMENT.RECORD_DELETED_FLAG = 0
   AND  AGREEMENT.ACCOUNT_Modifier_Num IN ('ST80','ST81')
    AND (AGREEMENT.Acct_Current_Status_Type_Cd NOT IN (4,122,123) 
    OR (AGREEMENT.Acct_Current_Status_Type_Cd  IN (4,122,123) AND AGREEMENT.ACCOUNT_CLOSE_DT = VOBM_BUSINESSDATE.BUSINESSDATE))
   
   
  INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC_HS  AS AGMT_AGMT_CLASS_ASSOC
  ON AGREEMENT.ACCOUNT_NUM = AGMT_AGMT_CLASS_ASSOC.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = AGMT_AGMT_CLASS_ASSOC.ACCOUNT_MODIFIER_NUM
   AND AGMT_AGMT_CLASS_ASSOC.Agreement_Classification_CD = 16 
   AND AGMT_AGMT_CLASS_ASSOC.Agreement_CLASS_Value_CD IN (1,6)
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGMT_AGMT_CLASS_ASSOC.START_DT 
   AND AGMT_AGMT_CLASS_ASSOC.END_DT
   AND AGMT_AGMT_CLASS_ASSOC.RECORD_DELETED_FLAG = 0
   AND AGMT_AGMT_CLASS_ASSOC.CTL_ID = '002'
   
  LEFT OUTER JOIN 
  (
  SELECT
  ACCPAR.ACCOUNT_NUM,
  ACCPAR.ACCOUNT_MODIFIER_NUM,
  MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 21 
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_21, MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 22
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_22 
  FROM P1VTTEDW.ACCOUNT_PARTY_HS AS ACCPAR
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
  ON  BD.BUSINESSDATE BETWEEN ACCPAR.START_DT 
   AND ACCPAR.END_DT  AND ACCPAR.RECORD_DELETED_FLAG = 0
   AND ACCPAR.ACCOUNT_Modifier_Num IN ('ST80','ST81')
   AND ACCPAR.Account_Party_Role_Cd IN(21, 22)
  
  
  LEFT OUTER JOIN P1VTTEDW.FINANCIAL_INST_INT_ORG AS FINANCIAL_INST_INT_ORG
  ON ACCPAR.PARTY_ID = FINANCIAL_INST_INT_ORG.Internal_Org_Party_Id    
  AND BD.BUSINESSDATE BETWEEN FINANCIAL_INST_INT_ORG.START_DT 
   AND FINANCIAL_INST_INT_ORG.END_DT  AND FINANCIAL_INST_INT_ORG.RECORD_DELETED_FLAG = 0
  
  GROUP BY 1,2
  ) AS ACCOUNT_PARTY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PARTY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PARTY.ACCOUNT_MODIFIER_NUM
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_BALANCE_SUMMARY_DD_HS AS ACCOUNT_BALANCE_SUMMARY_DD
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_MODIFIER_NUM
   AND ACCOUNT_BALANCE_SUMMARY_DD.Balance_Category_TYPE_CD = 1 
   AND ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_Metric_TYPE_CD = 1 
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_BALANCE_SUMMARY_DD.START_DT 
   AND ACCOUNT_BALANCE_SUMMARY_DD.END_DT
   AND ACCOUNT_BALANCE_SUMMARY_DD.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_BALANCE_SUMMARY_DD.CTL_ID = '002'
  
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CURRENCY AS ACCOUNT_CURRENCY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CURRENCY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CURRENCY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CURRENCY.START_DT 
   AND ACCOUNT_CURRENCY.END_DT
   AND ACCOUNT_CURRENCY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_CURRENCY.CTL_ID = '002'
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CONTRACT_HISTORY AS ACCOUNT_CONTRACT_HISTORY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CONTRACT_HISTORY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CONTRACT_HISTORY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CONTRACT_HISTORY.START_DT 
   AND ACCOUNT_CONTRACT_HISTORY.END_DT
   AND ACCOUNT_CONTRACT_HISTORY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_CONTRACT_HISTORY.CTL_ID = '002'
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_PRODUCT_HISTORY_HS AS ACCOUNT_PRODUCT_HISTORY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PRODUCT_HISTORY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PRODUCT_HISTORY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_PRODUCT_HISTORY.START_DT 
   AND ACCOUNT_PRODUCT_HISTORY.END_DT
   AND ACCOUNT_PRODUCT_HISTORY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_PRODUCT_HISTORY.CTL_ID = '002'
  
  LEFT OUTER JOIN P1VTTEDW.PROD_GROUP_ASSOCIATION AS PROD_GROUP_ASSOCIATION
  ON ACCOUNT_PRODUCT_HISTORY.PRODUCT_ID = PROD_GROUP_ASSOCIATION.PRODUCT_ID
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PROD_GROUP_ASSOCIATION.START_DT 
   AND PROD_GROUP_ASSOCIATION.END_DT
   AND PROD_GROUP_ASSOCIATION.RECORD_DELETED_FLAG = 0
   AND PROD_GROUP_ASSOCIATION.CTL_ID = '002'
   
    LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP4
  ON PROD_GROUP_ASSOCIATION.PRODUCT_GROUP_ID = PRODUCT_GROUP4.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP4.Product_Group_Level_Num = 4  AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP4.START_DT 
   AND PRODUCT_GROUP4.END_DT
   AND PRODUCT_GROUP4.RECORD_DELETED_FLAG = 0
    
  LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP3
  ON PRODUCT_GROUP4.Parent_Prod_Group_Id = PRODUCT_GROUP3.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP3.Product_Group_Level_Num = 3  AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP3.START_DT 
   AND PRODUCT_GROUP3.END_DT
   AND PRODUCT_GROUP3.RECORD_DELETED_FLAG = 0 
  
  LEFT OUTER JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_CS009700
  ON ACCOUNT_CURRENCY.Account_Currency_Cd = REF_CS009700.EDW_CODE
   AND  REF_CS009700.CODE_ID = 55
   AND REF_CS009700.CODE_SET_ID = 'CS009700'
   AND  REF_CS009700.LANGUAGE_ID = 1 
  
  LEFT OUTER JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_CS000750
   ON  AGREEMENT.Acct_Current_Status_Type_Cd = REF_CS000750.EDW_CODE
   AND  REF_CS000750.CODE_ID = 7
   AND REF_CS000750.CODE_SET_ID = 'CS000750'
   AND  REF_CS000750.LANGUAGE_ID = 3
   
/*  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS ACCT_DEMO
   ON AGREEMENT.ACCOUNT_NUM = ACCT_DEMO.ACCOUNT_NUM
    AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCT_DEMO.ACCOUNT_MODIFIER_NUM
    AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCT_DEMO.START_DT 
    AND ACCT_DEMO.END_DT
    AND ACCT_DEMO.RECORD_DELETED_FLAG = 0
    AND ACCT_DEMO.CTL_ID = '002'
    AND ACCT_DEMO.Demog_Cd = 4196  -- ALS USER DATE2
    
*/
  UNION ALL
  
  
  
  SELECT
  ( CAST(DATE_FORMAT(VOBM_BUSINESSDATE.BUSINESSDATE, 'yyyy-MM-dd') AS CHAR(10)))   AS AS_OF_DT,
  (CASE
    WHEN  AGREEMENT.Account_Modifier_Num  = 'AM80' THEN  CAST('AL80' AS CHAR(4))
    WHEN AGREEMENT.Account_Modifier_Num  = 'AM81' THEN  CAST('AL81' AS CHAR(4))
  END)
   AS APPL_CODE, RPAD((CASE  WHEN AGMT_AGMT_CLASS_ASSOC2.Agreement_Classification_Cd = 11  AND AGMT_AGMT_CLASS_ASSOC2.Agreement_Class_Value_Cd IN (153,192)
    THEN 'C' || (CASE 
    WHEN  SUBSTR(AGREEMENT.ACCOUNT_MODIFIER_NUM,1,2)  = 'AM' AND       SUBSTR(AGREEMENT.Account_Num,27,1)  = '0'
     THEN     '00' || SUBSTR(AGREEMENT.Account_Num,1,2) || '0' || SUBSTR(AGREEMENT.Account_Num,3,3) ||  SUBSTR(AGREEMENT.Account_Num,9,4) || '0034000000000' ||  SUBSTR(AGREEMENT.Account_Num,13,20)
  
    WHEN  SUBSTR(AGREEMENT.ACCOUNT_MODIFIER_NUM,1,2)  = 'AM' AND       SUBSTR(AGREEMENT.Account_Num,27,1)  = ''
     THEN     SUBSTR(AGREEMENT.Account_Num,1,5) || 
           (CASE  
                     WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '470' THEN SUBSTR(AGREEMENT.Account_Num,10,3) || '0099' 
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '473' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0035'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '478' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0031'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '479' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0479'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '496' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0030'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '497' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0497'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '498' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0498'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '485' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0032'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '487' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0034'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '489' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0036'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '491' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0063'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '493' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0064'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '475' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0060'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '481' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0061'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '483' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0062'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '495' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0088'                  
           ELSE  SUBSTR(AGREEMENT.Account_Num,6,7)   
       END)
     || SUBSTR(AGREEMENT.Account_Num,13,14)
  
    ELSE     AGREEMENT.ACCOUNT_NUM
    END)
   ELSE (CASE 
    WHEN  SUBSTR(AGREEMENT.ACCOUNT_MODIFIER_NUM,1,2)  = 'AM' AND       SUBSTR(AGREEMENT.Account_Num,27,1)  = '0'
     THEN     '00' || SUBSTR(AGREEMENT.Account_Num,1,2) || '0' || SUBSTR(AGREEMENT.Account_Num,3,3) ||  SUBSTR(AGREEMENT.Account_Num,9,4) || '0034000000000' ||  SUBSTR(AGREEMENT.Account_Num,13,20)
  
    WHEN  SUBSTR(AGREEMENT.ACCOUNT_MODIFIER_NUM,1,2)  = 'AM' AND       SUBSTR(AGREEMENT.Account_Num,27,1)  = ''
     THEN     SUBSTR(AGREEMENT.Account_Num,1,5) || 
           (CASE  
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '470' THEN SUBSTR(AGREEMENT.Account_Num,10,3) || '0099' 
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '473' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0035'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '478' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0031'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '479' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0479'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '496' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0030'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '497' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0497'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '498' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0498'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '485' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0032'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '487' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0034'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '489' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0036'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '491' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0063'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '493' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0064'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '475' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0060'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '481' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0061'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '483' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0062'
                    WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '495' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0088'                  
           ELSE  SUBSTR(AGREEMENT.Account_Num,6,7)   
       END)
     || SUBSTR(AGREEMENT.Account_Num,13,14)
  
    ELSE     AGREEMENT.ACCOUNT_NUM
    END)
  END),45,' ')   AS ITEM_NO,
   CAST(AGREEMENT.BASE_ACCOUNT_NUM AS CHAR(26)) AS SAGMNT_ID,
  (CASE SUBSTR(PRODUCT_GROUP2.Host_Product_Group_Val,1,CHARACTER_LENGTH(TRIM(PRODUCT_GROUP2.Host_Product_Group_Val))-3)
      WHEN  'LN30' THEN CAST('06' AS CHAR(20))
      WHEN 'LN31' THEN CAST('06' AS CHAR(20))
      WHEN 'PN32' THEN CAST('06'  AS CHAR(20))
      WHEN 'CD34' THEN CAST('07' AS CHAR(20))
      WHEN 'LG60' THEN CAST('08' AS CHAR(20))
      WHEN 'AV61' THEN CAST('09' AS CHAR(20))
      WHEN 'AC62' THEN CAST('10' AS CHAR(20))
      WHEN 'DLC' THEN CAST('11' AS CHAR(20))
      WHEN 'LQD' THEN CAST('14' AS CHAR(20))
      WHEN 'FA36' THEN CAST('20' AS CHAR(20))
      WHEN 'LN35' THEN CAST('32' AS CHAR(20))
      WHEN 'HP98' THEN CAST('61' AS CHAR(20))
      WHEN 'LS97' THEN CAST('62' AS CHAR(20))
   ELSE CAST('99' AS CHAR(20))
  END)  AS LIMIT_NO, (CASE 
   WHEN CAST(1 AS DECIMAL(9,0)) = 1
               THEN CAST(CAST(1 AS DECIMAL(9,0)) AS VARCHAR(9))
               ELSE TRIM(TRAILING '0' FROM CAST(CAST(1 AS DECIMAL(9,0)) AS VARCHAR(9)))
  END) AS LIMIT_SEQ,
  CAST(ACCOUNT_BALANCE_SUMMARY_DD.GL_PRODUCT_CODE_VAL AS CHAR(4)) AS GL_PROD_CODE,
  CAST(SUBSTR(PRODUCT_GROUP2.Host_Product_Group_Val,1,CHARACTER_LENGTH(TRIM(PRODUCT_GROUP2.Host_Product_Group_Val))-3) AS CHAR(4))  AS PROD_CODE, CAST(ACCOUNT_BALANCE_SUMMARY_DD.GL_ACCOUNT_CODE_VAL AS CHAR(6)) AS FIS_CODE,
  CAST(REF_CS009700.SHORT_DESCRIPTION AS CHAR(3)) AS BAL_CURR_CODE,
  (CASE
   WHEN (ACCOUNT_BALANCE_SUMMARY_DD.BALAMT) < 0 THEN 
      CASE
     WHEN CAST(ABS(ACCOUNT_BALANCE_SUMMARY_DD.BALAMT)  AS DECIMAL(18,2)) = (ACCOUNT_BALANCE_SUMMARY_DD.BALAMT)
           THEN CAST(CAST(ABS(ACCOUNT_BALANCE_SUMMARY_DD.BALAMT)  AS DECIMAL(18,2)) AS VARCHAR(21))
           ELSE TRIM(TRAILING '0' FROM CAST(CAST(ABS(ACCOUNT_BALANCE_SUMMARY_DD.BALAMT)  AS DECIMAL(18,2)) AS VARCHAR(21)))
    END
    ELSE 
      CASE
     WHEN CAST((ACCOUNT_BALANCE_SUMMARY_DD.BALAMT) AS DECIMAL(18,2)) = (ACCOUNT_BALANCE_SUMMARY_DD.BALAMT)
           THEN CAST(CAST((ACCOUNT_BALANCE_SUMMARY_DD.BALAMT)  AS DECIMAL(18,2)) AS VARCHAR(21))
           ELSE TRIM(TRAILING '0' FROM CAST(CAST((ACCOUNT_BALANCE_SUMMARY_DD.BALAMT)  AS DECIMAL(18,2)) AS VARCHAR(21)))
    END
  END)  AS BAL_AMT, CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_21 AS CHAR(4)) AS RC_CODE,
  CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_22 AS CHAR(4)) AS OC_CODE,
  (CASE 
   WHEN  AGREEMENT.Acct_Current_Status_Type_Cd = 4 THEN CAST('02' AS CHAR(2))
   ELSE CAST('01' AS CHAR(2))
  END)  AS STATUS, (CASE
   WHEN AGREEMENT.Account_Close_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(AGREEMENT.Account_Close_Dt  , 'yyyy-MM-dd') AS CHAR(10))) 
  END) AS CLOSE_DT,
  ( CAST(DATE_FORMAT(AGREEMENT.Account_Signed_Dt , 'yyyy-MM-dd') AS CHAR(10)))  AS CONTRACT_DT,
  ( CAST(DATE_FORMAT(AGREEMENT.Account_Open_Dt , 'yyyy-MM-dd') AS CHAR(10)))  AS EFFECT_DT, 
/*  (CASE
    WHEN AGREEMENT.Contract_Expiration_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
    ELSE (AGREEMENT.Contract_Expiration_Dt (FORMAT 'YYYY-MM-DD') (CHAR(10)))  
   END) AS MATURITY_DT,
  
*/
   (CASE
   WHEN ACCOUNT_CONTRACT_HISTORY.Contract_Term_Expiration_Dttm IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(ACCOUNT_CONTRACT_HISTORY.Contract_Term_Expiration_Dttm , 'yyyy-MM-dd') AS CHAR(10)))  
  END) AS MATURITY_DT,  
  (CASE
   WHEN ACCOUNT_SUMMARY_DD.Oldest_Due_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10)) 
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCOUNT_SUMMARY_DD.Oldest_Due_Dt,DATE '9999-12-31') , 'yyyy-MM-dd') AS CHAR(10))) 
  END) AS PASTDUE_DT,
  (CASE
   WHEN ACCOUNT_SUMMARY_DD.Non_Accrue_Int_Start_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10)) 
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCOUNT_SUMMARY_DD.Non_Accrue_Int_Start_Dt,DATE '9999-12-31') , 'yyyy-MM-dd') AS CHAR(10))) 
  END) AS STOPCAL_DT, 
  (CASE WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1 THEN  CAST('F' AS CHAR(1))
   ELSE  CAST('N' AS CHAR(1))
  END)  AS FUND_FLAG, (CASE
   WHEN ACCOUNT_SUMMARY_DD.Last_Penalty_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCOUNT_SUMMARY_DD.Last_Penalty_Dt,DATE '9999-12-31') , 'yyyy-MM-dd') AS CHAR(10))) 
  END) AS PENALTY_DT,
  (CASE 
   WHEN AGREEMENT.Acct_Current_Status_Type_Cd IN (4,127) AND AGREEMENT.Acct_Status_Reason_Cd = 31 THEN RPAD('1', 2, ' ')
   ELSE  RPAD('0', 2, ' ')
  END)  AS STATUS_TDR ,
  (CASE
   WHEN ACCT_DEMO.Acct_Demographic_Start_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCT_DEMO.Acct_Demographic_Start_Dt,DATE '9999-12-31') , 'yyyy-MM-dd') AS CHAR(10))) 
  END) AS EXPRY_DT

  FROM  P1VTTEDW.AGREEMENT_HS AS AGREEMENT
  
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS VOBM_BUSINESSDATE
  ON  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGREEMENT.START_DT 
   AND  AGREEMENT.END_DT
   AND  AGREEMENT.RECORD_DELETED_FLAG = 0
   AND AGREEMENT.ACCOUNT_Modifier_Num IN ('AM80' ,'AM81')
   AND (AGREEMENT.Acct_Current_Status_Type_Cd NOT IN (4,122,123) 
    OR (AGREEMENT.Acct_Current_Status_Type_Cd  IN (4,122,123) AND AGREEMENT.ACCOUNT_CLOSE_DT = VOBM_BUSINESSDATE.BUSINESSDATE)) 
   
  INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC_HS  AS AGMT_AGMT_CLASS_ASSOC1
  ON AGREEMENT.ACCOUNT_NUM = AGMT_AGMT_CLASS_ASSOC1.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = AGMT_AGMT_CLASS_ASSOC1.ACCOUNT_MODIFIER_NUM
   AND AGMT_AGMT_CLASS_ASSOC1.Agreement_Classification_CD = 16
   AND AGMT_AGMT_CLASS_ASSOC1.Agreement_CLASS_Value_CD IN (1,5,6)
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGMT_AGMT_CLASS_ASSOC1.START_DT 
   AND AGMT_AGMT_CLASS_ASSOC1.END_DT
   AND AGMT_AGMT_CLASS_ASSOC1.RECORD_DELETED_FLAG = 0 
   AND AGMT_AGMT_CLASS_ASSOC1.CTL_ID = '004'
  
  LEFT OUTER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC_HS  AS AGMT_AGMT_CLASS_ASSOC2
  ON AGREEMENT.ACCOUNT_NUM = AGMT_AGMT_CLASS_ASSOC2.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = AGMT_AGMT_CLASS_ASSOC2.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGMT_AGMT_CLASS_ASSOC2.START_DT 
   AND AGMT_AGMT_CLASS_ASSOC2.END_DT
   AND AGMT_AGMT_CLASS_ASSOC2.RECORD_DELETED_FLAG = 0 
   AND AGMT_AGMT_CLASS_ASSOC2.Agreement_Classification_Cd = 11 
   AND AGMT_AGMT_CLASS_ASSOC2.CTL_ID = '004'
  
  LEFT OUTER JOIN 
  (
  SELECT
  ACCPAR.ACCOUNT_NUM,
  ACCPAR.ACCOUNT_MODIFIER_NUM,
  MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 21 
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_21, MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 22
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_22 
  FROM P1VTTEDW.ACCOUNT_PARTY_HS AS ACCPAR
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
  ON  BD.BUSINESSDATE BETWEEN ACCPAR.START_DT 
   AND ACCPAR.END_DT  AND ACCPAR.RECORD_DELETED_FLAG = 0
   AND ACCPAR.ACCOUNT_Modifier_Num IN ('AM80' ,'AM81')
   AND ACCPAR.Account_Party_Role_Cd IN(21, 22)
  
  
  LEFT OUTER JOIN P1VTTEDW.FINANCIAL_INST_INT_ORG AS FINANCIAL_INST_INT_ORG
  ON ACCPAR.PARTY_ID = FINANCIAL_INST_INT_ORG.Internal_Org_Party_Id    
  AND BD.BUSINESSDATE BETWEEN FINANCIAL_INST_INT_ORG.START_DT 
   AND FINANCIAL_INST_INT_ORG.END_DT  AND FINANCIAL_INST_INT_ORG.RECORD_DELETED_FLAG = 0
  
  GROUP BY 1,2
  ) AS ACCOUNT_PARTY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PARTY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PARTY.ACCOUNT_MODIFIER_NUM
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_SUMMARY_DD AS ACCOUNT_SUMMARY_DD
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_SUMMARY_DD.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_SUMMARY_DD.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_SUMMARY_DD.START_DT 
   AND ACCOUNT_SUMMARY_DD.END_DT
   AND ACCOUNT_SUMMARY_DD.RECORD_DELETED_FLAG = 0 
   AND ACCOUNT_SUMMARY_DD.CTL_ID = '004'
   
  LEFT OUTER JOIN 
  (
  SELECT
  ACCBALSUM.ACCOUNT_NUM,
  ACCBALSUM.ACCOUNT_MODIFIER_NUM,
  ACCBALSUM.GL_PRODUCT_CODE_VAL,
  ACCBALSUM.GL_ACCOUNT_CODE_VAL,
  MAX(
  CASE
    WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 1 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1,1359,1360,1361) 
     AND Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1 
     THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
      ELSE
      (CASE
        WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 1 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1300,1301) 
        THEN
        (CASE
          WHEN Agreement.Asset_Liability_Cd <> 1 AND Agreement.Balance_Sheet_Cd = 1
           THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
          WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd <> 1
           THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
          WHEN Agreement.Asset_Liability_Cd <> 1 AND Agreement.Balance_Sheet_Cd <> 1
           THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
        END)
      END)
  END) AS BALAMT
  
  FROM P1VTTEDW.ACCOUNT_BALANCE_SUMMARY_DD_HS AS ACCBALSUM
  
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS VOBM_BUSINESSDATE
  ON  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCBALSUM.START_DT 
   AND  ACCBALSUM.END_DT
   AND  ACCBALSUM.RECORD_DELETED_FLAG = 0
   AND ACCBALSUM.ACCOUNT_Modifier_Num IN ('AM80' ,'AM81')
   AND ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 1 
   AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1,1359,1360,1361,1300,1301)
    
  INNER JOIN P1VTTEDW.AGREEMENT_HS AS AGREEMENT
  ON ACCBALSUM.ACCOUNT_NUM = AGREEMENT.ACCOUNT_NUM
   AND ACCBALSUM.ACCOUNT_MODIFIER_NUM = AGREEMENT.ACCOUNT_MODIFIER_NUM
   AND  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGREEMENT.START_DT 
    AND  AGREEMENT.END_DT  AND  AGREEMENT.RECORD_DELETED_FLAG = 0 
    AND AGREEMENT.CTL_ID = '004'
  
  WHERE ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT 
   = (CASE
      WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 1 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1,1359,1360,1361) 
      AND Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1 
      THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
      ELSE
      (
       CASE
        WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 1 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1300,1301) 
        THEN
        (
         CASE
          WHEN Agreement.Asset_Liability_Cd <> 1 AND Agreement.Balance_Sheet_Cd = 1
          THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
          WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd <> 1
          THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
          WHEN Agreement.Asset_Liability_Cd <> 1 AND Agreement.Balance_Sheet_Cd <> 1
          THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
         END
        )
       END
      )
     END)
  
  
   GROUP BY 1,2,3,4
  ) AS ACCOUNT_BALANCE_SUMMARY_DD
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_MODIFIER_NUM
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CURRENCY AS ACCOUNT_CURRENCY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CURRENCY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CURRENCY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CURRENCY.START_DT 
   AND ACCOUNT_CURRENCY.END_DT
   AND ACCOUNT_CURRENCY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_CURRENCY.CTL_ID = '004'
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_PRODUCT_HISTORY_HS AS ACCOUNT_PRODUCT_HISTORY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PRODUCT_HISTORY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PRODUCT_HISTORY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_PRODUCT_HISTORY.START_DT 
   AND ACCOUNT_PRODUCT_HISTORY.END_DT
   AND ACCOUNT_PRODUCT_HISTORY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_PRODUCT_HISTORY.CTL_ID = '004'
  
  LEFT OUTER JOIN P1VTTEDW.PROD_GROUP_ASSOCIATION AS PROD_GROUP_ASSOCIATION
  ON ACCOUNT_PRODUCT_HISTORY.PRODUCT_ID = PROD_GROUP_ASSOCIATION.PRODUCT_ID
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PROD_GROUP_ASSOCIATION.START_DT 
   AND PROD_GROUP_ASSOCIATION.END_DT
   AND PROD_GROUP_ASSOCIATION.RECORD_DELETED_FLAG = 0
   AND PROD_GROUP_ASSOCIATION.CTL_ID = '004'
  
  LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP4
  ON PROD_GROUP_ASSOCIATION.PRODUCT_GROUP_ID = PRODUCT_GROUP4.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP4.Product_Group_Level_Num = 4
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP4.START_DT 
   AND PRODUCT_GROUP4.END_DT
   AND PRODUCT_GROUP4.RECORD_DELETED_FLAG = 0
    
   LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP3
  ON PRODUCT_GROUP4.Parent_Prod_Group_Id = PRODUCT_GROUP3.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP3.Product_Group_Level_Num = 3
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP3.START_DT 
   AND PRODUCT_GROUP3.END_DT
   AND PRODUCT_GROUP3.RECORD_DELETED_FLAG = 0
    
  LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP2
  ON PRODUCT_GROUP3.Parent_Prod_Group_Id = PRODUCT_GROUP2.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP2.Product_Group_Level_Num = 2 
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP2.START_DT 
   AND PRODUCT_GROUP2.END_DT
   AND PRODUCT_GROUP2.RECORD_DELETED_FLAG = 0
  
  LEFT OUTER JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_CS009700
  ON ACCOUNT_CURRENCY.Account_Currency_Cd = REF_CS009700.EDW_CODE
   AND  REF_CS009700.CODE_ID = 55
   AND REF_CS009700.CODE_SET_ID = 'CS009700'
   AND  REF_CS009700.LANGUAGE_ID = 1 
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS ACCT_DEMO
  ON AGREEMENT.ACCOUNT_NUM = ACCT_DEMO.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCT_DEMO.ACCOUNT_MODIFIER_NUM
   AND ACCT_DEMO.Demog_Cd = 4196   /*  'ALS USER DATE2 */ 
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCT_DEMO.START_DT 
   AND ACCT_DEMO.END_DT
   AND ACCT_DEMO.RECORD_DELETED_FLAG = 0
   AND ACCT_DEMO.CTL_ID = '004'
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CONTRACT_HISTORY AS ACCOUNT_CONTRACT_HISTORY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CONTRACT_HISTORY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CONTRACT_HISTORY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CONTRACT_HISTORY.START_DT 
   AND ACCOUNT_CONTRACT_HISTORY.END_DT
   AND ACCOUNT_CONTRACT_HISTORY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_CONTRACT_HISTORY.CTL_ID = '004'
  
  
  UNION ALL
  
  
  
  SELECT
  ( CAST(DATE_FORMAT(VOBM_BUSINESSDATE.BUSINESSDATE , 'yyyy-MM-dd') AS CHAR(10)))   AS AS_OF_DT,
  (CASE
    WHEN  AGREEMENT.Account_Modifier_Num  = 'AM80' THEN  CAST('AL80' AS CHAR(4))
    WHEN AGREEMENT.Account_Modifier_Num  = 'AM81' THEN  CAST('AL81' AS CHAR(4))
  END) AS APPL_CODE, RPAD(CASE 
    WHEN  SUBSTR(AGREEMENT.ACCOUNT_MODIFIER_NUM,1,2)  = 'AM' AND       SUBSTR(AGREEMENT.Account_Num,27,1)  = '0'
     THEN     '00' || SUBSTR(AGREEMENT.Account_Num,1,2) || '0' || SUBSTR(AGREEMENT.Account_Num,3,3) ||  SUBSTR(AGREEMENT.Account_Num,9,4) || '0034000000000' ||  SUBSTR(AGREEMENT.Account_Num,13,20)
  
    WHEN  SUBSTR(AGREEMENT.ACCOUNT_MODIFIER_NUM,1,2)  = 'AM' AND       SUBSTR(AGREEMENT.Account_Num,27,1)  = ''
     THEN     SUBSTR(AGREEMENT.Account_Num,1,5) || 
           (CASE  
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '470' THEN SUBSTR(AGREEMENT.Account_Num,10,3) || '0099' 
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '473' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0035'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '478' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0031'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '479' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0479'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '496' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0030'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '497' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0497'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '498' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0498'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '485' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0032'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '487' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0034'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '489' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0036'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '491' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0063'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '493' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0064'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '475' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0060'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '481' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0061'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '483' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0062'
           
           WHEN SUBSTR(AGREEMENT.Account_Num,6,3) = '495' THEN SUBSTR(AGREEMENT.Account_Num,10,3) ||'0088'                  
           ELSE  SUBSTR(AGREEMENT.Account_Num,6,7)   
       END)
    || SUBSTR(AGREEMENT.Account_Num,13,14)
  
   ELSE     AGREEMENT.ACCOUNT_NUM
  END,45,' ')  AS ITEM_NO,
  
  CAST(AGREEMENT.BASE_ACCOUNT_NUM AS CHAR(26)) AS SAGMNT_ID,
  (CASE SUBSTR(PRODUCT_GROUP2.Host_Product_Group_Val,1,CHARACTER_LENGTH(TRIM(PRODUCT_GROUP2.Host_Product_Group_Val))-3)
    WHEN  'LN30' THEN CAST('06' AS CHAR(20))
    WHEN 'LN31' THEN CAST('06' AS CHAR(20))
      WHEN 'PN32' THEN CAST('06'  AS CHAR(20))
      WHEN 'CD34' THEN CAST('07' AS CHAR(20))
      WHEN 'LG60' THEN CAST('08' AS CHAR(20))
      WHEN 'AV61' THEN CAST('09' AS CHAR(20))
      WHEN 'AC62' THEN CAST('10' AS CHAR(20))
      WHEN 'DLC' THEN CAST('11' AS CHAR(20))
      WHEN 'LQD' THEN CAST('14' AS CHAR(20))
      WHEN 'FA36' THEN CAST('20' AS CHAR(20))
      WHEN 'LN35' THEN CAST('32' AS CHAR(20))
      WHEN 'HP98' THEN CAST('61' AS CHAR(20))
      WHEN 'LS97' THEN CAST('62' AS CHAR(20))
   ELSE CAST('99' AS CHAR(20))
  END)  AS LIMIT_NO, (CASE 
   WHEN CAST(1 AS DECIMAL(9,0)) = 1
               THEN CAST(CAST(1 AS DECIMAL(9,0)) AS VARCHAR(9))
               ELSE TRIM(TRAILING '0' FROM CAST(CAST(1 AS DECIMAL(9,0)) AS VARCHAR(9)))
  END) AS LIMIT_SEQ,
  CAST(ACCOUNT_BALANCE_SUMMARY_DD.BALAMT AS CHAR(4)) AS GL_PROD_CODE,
  CAST(SUBSTR(PRODUCT_GROUP2.Host_Product_Group_Val,1,CHARACTER_LENGTH(TRIM(PRODUCT_GROUP2.Host_Product_Group_Val))-3) AS CHAR(4))  AS PROD_CODE, CAST(ACCOUNT_BALANCE_SUMMARY_DD.BALAMT AS CHAR(6)) AS FIS_CODE,
  CAST(REF_CS009700.SHORT_DESCRIPTION  AS CHAR(3))AS BAL_CURR_CODE,
  (CASE
   WHEN (ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT) < 0 THEN 
      CASE
     WHEN CAST(ABS (ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT) AS DECIMAL(18,2)) = (ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT)
           THEN CAST(CAST(ABS(ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT)  AS DECIMAL(18,2)) AS VARCHAR(21))
           ELSE TRIM(TRAILING '0' FROM CAST(CAST(ABS(ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT)  AS DECIMAL(18,2)) AS VARCHAR(21)))
    END
    ELSE 
      CASE
     WHEN  CAST((ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT) AS DECIMAL(18,2)) = (ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT)
           THEN CAST(CAST((ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT)  AS DECIMAL(18,2)) AS VARCHAR(21))
           ELSE TRIM(TRAILING '0' FROM CAST(CAST((ACCOUNT_BALANCE_SUMMARY_DD.BALAMT + ACCOUNT_BALANCE_SUMMARY_DD.NONINT + ACCOUNT_BALANCE_SUMMARY_DD.INTAMT)  AS DECIMAL(18,2)) AS VARCHAR(21)))
    END
  END) AS BAL_AMT, CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_21 AS CHAR(4)) AS RC_CODE,
  CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_22 AS CHAR(4)) AS OC_CODE,
  (CASE 
   WHEN  AGREEMENT.Acct_Current_Status_Type_Cd = 4 THEN CAST('02' AS CHAR(2))
   ELSE CAST('01' AS CHAR(2))
  END)  AS STATUS, (CASE
   WHEN AGREEMENT.Account_Close_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(AGREEMENT.Account_Close_Dt , 'yyyy-MM-dd') AS CHAR(10))) 
  END) AS CLOSE_DT,
  ( CAST(DATE_FORMAT(AGREEMENT.Account_Signed_Dt , 'yyyy-MM-dd') AS CHAR(10)))  AS CONTRACT_DT,
  ( CAST(DATE_FORMAT(AGREEMENT.Account_Open_Dt , 'yyyy-MM-dd') AS CHAR(10)))  AS EFFECT_DT,
/*  (CASE
    WHEN AGREEMENT.Contract_Expiration_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
    ELSE (AGREEMENT.Contract_Expiration_Dt (FORMAT 'YYYY-MM-DD') (CHAR(10)))  
   END) AS MATURITY_DT,
  
*/
   (CASE
   WHEN ACCOUNT_CONTRACT_HISTORY.Contract_Term_Expiration_Dttm IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(ACCOUNT_CONTRACT_HISTORY.Contract_Term_Expiration_Dttm , 'yyyy-MM-dd') AS CHAR(10)))  
  END) AS MATURITY_DT,  
  (CASE
   WHEN ACCOUNT_SUMMARY_DD.Oldest_Due_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10)) 
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCOUNT_SUMMARY_DD.Oldest_Due_Dt,DATE '9999-12-31') , 'yyyy-MM-dd') AS CHAR(10))) 
  END) AS PASTDUE_DT,
  (CASE
   WHEN ACCOUNT_SUMMARY_DD.Non_Accrue_Int_Start_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCOUNT_SUMMARY_DD.Non_Accrue_Int_Start_Dt,DATE '9999-12-31') , 'yyyy-MM-dd') AS CHAR(10))) 
  END) AS STOPCAL_DT,
  (CASE WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1
  THEN  CAST('F' AS CHAR(1))
  ELSE  CAST('N' AS CHAR(1))
  END)  AS FUND_FLAG, (CASE
   WHEN ACCOUNT_SUMMARY_DD.Last_Penalty_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE'1000-01-03',DATE '1000-01-04') THEN  CAST('9999-12-31' AS CHAR(10)) 
   ELSE ( CAST(DATE_FORMAT(COALESCE(ACCOUNT_SUMMARY_DD.Last_Penalty_Dt,DATE '9999-12-31') , 'yyyy-MM-dd') AS CHAR(10)))  
  END) AS PENALTY_DT,
  (CASE 
   WHEN AGREEMENT.Acct_Current_Status_Type_Cd IN (4,127) AND AGREEMENT.Acct_Status_Reason_Cd = 31 THEN CAST('1' AS CHAR(2))
   ELSE CAST('0' AS CHAR(2))
  END)
   AS STATUS_TDR ,
  ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))  AS EXPRY_DT

  FROM  P1VTTEDW.AGREEMENT_HS AS AGREEMENT
  
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS VOBM_BUSINESSDATE
  ON  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGREEMENT.START_DT 
   AND  AGREEMENT.END_DT
   AND  AGREEMENT.RECORD_DELETED_FLAG = 0
   AND AGREEMENT.ACCOUNT_Modifier_Num IN ('AM80' ,'AM81')
    AND (AGREEMENT.Acct_Current_Status_Type_Cd NOT IN (4,122,123) 
    OR (AGREEMENT.Acct_Current_Status_Type_Cd  IN (4,122,123) AND AGREEMENT.ACCOUNT_CLOSE_DT = VOBM_BUSINESSDATE.BUSINESSDATE))
   
  INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC_HS  AS AGMT_AGMT_CLASS_ASSOC1
  ON AGREEMENT.ACCOUNT_NUM = AGMT_AGMT_CLASS_ASSOC1.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = AGMT_AGMT_CLASS_ASSOC1.ACCOUNT_MODIFIER_NUM
   AND AGMT_AGMT_CLASS_ASSOC1.Agreement_Classification_CD = 16 
   AND AGMT_AGMT_CLASS_ASSOC1.Agreement_CLASS_Value_CD IN (1,5,6)
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGMT_AGMT_CLASS_ASSOC1.START_DT 
   AND AGMT_AGMT_CLASS_ASSOC1.END_DT
   AND AGMT_AGMT_CLASS_ASSOC1.RECORD_DELETED_FLAG = 0
   AND AGMT_AGMT_CLASS_ASSOC1.CTL_ID = '004'
  
  INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC_HS  AS AGMT_AGMT_CLASS_ASSOC2
  ON AGREEMENT.ACCOUNT_NUM = AGMT_AGMT_CLASS_ASSOC2.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = AGMT_AGMT_CLASS_ASSOC2.ACCOUNT_MODIFIER_NUM
   AND AGMT_AGMT_CLASS_ASSOC2.Agreement_Classification_Cd = 11 
   AND (AGMT_AGMT_CLASS_ASSOC2.Agreement_CLASS_Value_CD = 153 OR AGMT_AGMT_CLASS_ASSOC2.Agreement_CLASS_Value_CD = 192) 
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGMT_AGMT_CLASS_ASSOC2.START_DT 
   AND AGMT_AGMT_CLASS_ASSOC2.END_DT
   AND AGMT_AGMT_CLASS_ASSOC2.RECORD_DELETED_FLAG = 0
   AND AGMT_AGMT_CLASS_ASSOC2.CTL_ID = '004'
   
  
  LEFT OUTER JOIN 
  (
  SELECT
  ACCPAR.ACCOUNT_NUM,
  ACCPAR.ACCOUNT_MODIFIER_NUM,
  MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 21 
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_21, MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 22
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_22 
  FROM P1VTTEDW.ACCOUNT_PARTY_HS AS ACCPAR
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
  ON  BD.BUSINESSDATE BETWEEN ACCPAR.START_DT 
    AND ACCPAR.END_DT  AND ACCPAR.RECORD_DELETED_FLAG = 0
    AND ACCPAR.ACCOUNT_Modifier_Num IN ('AM80' ,'AM81')
    AND ACCPAR.Account_Party_Role_Cd IN(21, 22)
   
  LEFT OUTER JOIN P1VTTEDW.FINANCIAL_INST_INT_ORG AS FINANCIAL_INST_INT_ORG
  ON ACCPAR.PARTY_ID = FINANCIAL_INST_INT_ORG.Internal_Org_Party_Id    
   AND BD.BUSINESSDATE BETWEEN FINANCIAL_INST_INT_ORG.START_DT 
   AND FINANCIAL_INST_INT_ORG.END_DT  AND FINANCIAL_INST_INT_ORG.RECORD_DELETED_FLAG = 0
  
  GROUP BY 1,2
  ) AS ACCOUNT_PARTY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PARTY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PARTY.ACCOUNT_MODIFIER_NUM
  
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_SUMMARY_DD AS ACCOUNT_SUMMARY_DD
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_SUMMARY_DD.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_SUMMARY_DD.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_SUMMARY_DD.START_DT 
   AND ACCOUNT_SUMMARY_DD.END_DT
   AND ACCOUNT_SUMMARY_DD.RECORD_DELETED_FLAG = 0 
   AND ACCOUNT_SUMMARY_DD.CTL_ID = '004'
   
  LEFT OUTER JOIN 
  (
  SELECT
  ACCBALSUM.ACCOUNT_NUM,
  ACCBALSUM.ACCOUNT_MODIFIER_NUM,
  ACCBALSUM.GL_PRODUCT_CODE_VAL,
  ACCBALSUM.GL_ACCOUNT_CODE_VAL,
  MAX(
  CASE
    WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 23 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1,1359,1360,1361) 
     AND Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1 
     THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
      ELSE
      (CASE
        WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 1 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1300,1301) 
        THEN
        (CASE
          WHEN Agreement.Asset_Liability_Cd <> 1 AND Agreement.Balance_Sheet_Cd = 1
           THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
          WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd <> 1
           THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
          WHEN Agreement.Asset_Liability_Cd <> 1 AND Agreement.Balance_Sheet_Cd <> 1
           THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
        END)
      END)
  END) AS BALAMT,
  MAX(
  CASE 
   WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 27
   AND  ACCBALSUM.ACCOUNT_METRIC_TYPE_CD= 700 
   THEN  ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
  END ) AS INTAMT,
  MAX(
  CASE 
   WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 31 
   AND  ACCBALSUM.ACCOUNT_METRIC_TYPE_CD= 700 
   THEN  ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
  END ) AS NONINT
  
  FROM P1VTTEDW.ACCOUNT_BALANCE_SUMMARY_DD_HS AS ACCBALSUM
  
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS VOBM_BUSINESSDATE
  ON  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCBALSUM.START_DT 
   AND  ACCBALSUM.END_DT
   AND  ACCBALSUM.RECORD_DELETED_FLAG = 0
   AND ACCBALSUM.ACCOUNT_Modifier_Num IN ('AM80' ,'AM81')
   AND ACCBALSUM.BALANCE_CATEGORY_TYPE_CD  IN( 23,27,31)
   AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1,1359,1360,1361,1300,1301,700)
    
  INNER JOIN P1VTTEDW.AGREEMENT_HS AS AGREEMENT
  ON ACCBALSUM.ACCOUNT_NUM = AGREEMENT.ACCOUNT_NUM
   AND ACCBALSUM.ACCOUNT_MODIFIER_NUM = AGREEMENT.ACCOUNT_MODIFIER_NUM
   AND  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGREEMENT.START_DT 
    AND  AGREEMENT.END_DT  AND  AGREEMENT.RECORD_DELETED_FLAG = 0 
    AND AGREEMENT.CTL_ID = '004'
  
  WHERE (ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT 
   = (CASE
      WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 23 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1,1359,1360,1361) 
      AND Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1 
      THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
      ELSE
      (
       CASE
        WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 23 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD IN (1300,1301) 
        THEN
        (
         CASE
          WHEN Agreement.Asset_Liability_Cd <> 1 AND Agreement.Balance_Sheet_Cd = 1
          THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
          WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd <> 1
          THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
          WHEN Agreement.Asset_Liability_Cd <> 1 AND Agreement.Balance_Sheet_Cd <> 1
          THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
         END
        )
       END
      )
     END)
     
  OR
  ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT 
   = (CASE
      WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 27 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD = 700 
      THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
    END)
  OR
  ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT 
   = (CASE
      WHEN ACCBALSUM.BALANCE_CATEGORY_TYPE_CD = 31 AND ACCBALSUM.ACCOUNT_METRIC_TYPE_CD = 700 
      THEN ACCBALSUM.ACCT_CRNCY_BALANCE_SUMMARY_AMT
    END)  
    )
  
  
   GROUP BY 1,2,3,4
  ) AS ACCOUNT_BALANCE_SUMMARY_DD
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_MODIFIER_NUM
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CURRENCY AS ACCOUNT_CURRENCY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CURRENCY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CURRENCY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CURRENCY.START_DT 
   AND ACCOUNT_CURRENCY.END_DT
   AND ACCOUNT_CURRENCY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_CURRENCY.CTL_ID = '004'
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_PRODUCT_HISTORY_HS AS ACCOUNT_PRODUCT_HISTORY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PRODUCT_HISTORY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PRODUCT_HISTORY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_PRODUCT_HISTORY.START_DT 
   AND ACCOUNT_PRODUCT_HISTORY.END_DT
   AND ACCOUNT_PRODUCT_HISTORY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_PRODUCT_HISTORY.CTL_ID = '004'
  
  LEFT OUTER JOIN P1VTTEDW.PROD_GROUP_ASSOCIATION AS PROD_GROUP_ASSOCIATION
  ON ACCOUNT_PRODUCT_HISTORY.PRODUCT_ID = PROD_GROUP_ASSOCIATION.PRODUCT_ID
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PROD_GROUP_ASSOCIATION.START_DT 
   AND PROD_GROUP_ASSOCIATION.END_DT
   AND PROD_GROUP_ASSOCIATION.RECORD_DELETED_FLAG = 0
   AND PROD_GROUP_ASSOCIATION.CTL_ID = '004'
   
   LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP4
  ON PROD_GROUP_ASSOCIATION.PRODUCT_GROUP_ID = PRODUCT_GROUP4.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP4.Product_Group_Level_Num = 4
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP4.START_DT 
   AND PRODUCT_GROUP4.END_DT
   AND PRODUCT_GROUP4.RECORD_DELETED_FLAG = 0
    
   LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP3
  ON PRODUCT_GROUP4.Parent_Prod_Group_Id = PRODUCT_GROUP3.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP3.Product_Group_Level_Num = 3
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP3.START_DT 
   AND PRODUCT_GROUP3.END_DT
   AND PRODUCT_GROUP3.RECORD_DELETED_FLAG = 0
    
  LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP2
  ON PRODUCT_GROUP3.Parent_Prod_Group_Id = PRODUCT_GROUP2.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP2.Product_Group_Level_Num = 2 
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP2.START_DT 
   AND PRODUCT_GROUP2.END_DT
   AND PRODUCT_GROUP2.RECORD_DELETED_FLAG = 0
     
  LEFT OUTER JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_CS009700
  ON ACCOUNT_CURRENCY.Account_Currency_Cd = REF_CS009700.EDW_CODE
   AND  REF_CS009700.CODE_ID = 55
   AND REF_CS009700.CODE_SET_ID = 'CS009700'
   AND  REF_CS009700.LANGUAGE_ID = 1 
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CONTRACT_HISTORY AS ACCOUNT_CONTRACT_HISTORY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CONTRACT_HISTORY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CONTRACT_HISTORY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CONTRACT_HISTORY.START_DT 
   AND ACCOUNT_CONTRACT_HISTORY.END_DT
   AND ACCOUNT_CONTRACT_HISTORY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_CONTRACT_HISTORY.CTL_ID = '004'
  
  
  UNION ALL
  
  
  SELECT
  ( CAST(DATE_FORMAT(VOBM_BUSINESSDATE.BUSINESSDATE , 'yyyy-MM-dd') AS CHAR(10)))  AS AS_OF_DT, 
  (CASE
   WHEN ACCOUNT_ACCOUNT_GROUP.Acct_To_Acct_Group_Relat_Cd = 1 THEN  CAST('TR80' AS CHAR(4))
   WHEN ACCOUNT_ACCOUNT_GROUP.Acct_To_Acct_Group_Relat_Cd = 2 THEN  CAST('TR81' AS CHAR(4))
  END)  AS APPL_CODE, 
  RPAD(AGREEMENT.Account_Num||' '||AGREEMENT.Account_Modifier_Num,45,' ') AS ITEM_NO,
  CAST(AGREEMENT.BASE_ACCOUNT_NUM AS CHAR(26)) AS SAGMNT_ID,
  CAST(0 AS CHAR(20)) AS LIMIT_NO, (CASE 
   WHEN CAST(1 AS DECIMAL(9,0)) = 1
               THEN CAST(CAST(1 AS DECIMAL(9,0)) AS VARCHAR(9))
               ELSE TRIM(TRAILING '1' FROM CAST(CAST(1 AS DECIMAL(9,0)) AS VARCHAR(9)))
  END) AS LIMIT_SEQ,
  CAST(ACCOUNT_BALANCE_SUMMARY_DD.GL_Product_Code_Val AS CHAR(4)) AS GL_PROD_CODE, 
  
  CAST(CASE
   WHEN PRODUCT.PRODUCT_NAME LIKE ANY ('MM_LENDING%','LD_LENDING%') THEN
    CASE
     WHEN ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD = 155 THEN 'LDC'
     WHEN DATEDIFF(AGREEMENT.CONTRACT_EXPIRATION_DT , AGREEMENT.ACCOUNT_SIGNED_DT) <= 1
      AND ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD = 155 THEN 'LDO'
     WHEN DATEDIFF(AGREEMENT.CONTRACT_EXPIRATION_DT , AGREEMENT.ACCOUNT_SIGNED_DT) > 1
      AND ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD = 155 THEN 'LDT'    
     WHEN DATEDIFF(AGREEMENT.CONTRACT_EXPIRATION_DT , AGREEMENT.ACCOUNT_SIGNED_DT) > 365
      AND ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD <> 155 THEN 'LFLG'    
     WHEN DATEDIFF(AGREEMENT.CONTRACT_EXPIRATION_DT , AGREEMENT.ACCOUNT_SIGNED_DT) <= 365
      AND ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD <> 155 THEN 'LFSH'
    END
   WHEN PRODUCT.PRODUCT_NAME LIKE ANY ('MM_BORROWING%','LD_BORROWING%') THEN
     CASE
      WHEN ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD = 155 THEN 'BDC'
      WHEN DATEDIFF(AGREEMENT.CONTRACT_EXPIRATION_DT , AGREEMENT.ACCOUNT_SIGNED_DT) <= 1
       AND ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD = 155 THEN 'BDO'
      WHEN DATEDIFF(AGREEMENT.CONTRACT_EXPIRATION_DT , AGREEMENT.ACCOUNT_SIGNED_DT) > 1
       AND ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD = 155 THEN 'BDT'    
      WHEN DATEDIFF(AGREEMENT.CONTRACT_EXPIRATION_DT , AGREEMENT.ACCOUNT_SIGNED_DT) > 365
       AND ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD <> 155 THEN 'BFLG'    
      WHEN DATEDIFF(AGREEMENT.CONTRACT_EXPIRATION_DT , AGREEMENT.ACCOUNT_SIGNED_DT) <= 365
       AND ACCOUNT_CURRENCY.ACCOUNT_CURRENCY_CD <> 155 THEN 'BFSH'        
     END 
   WHEN SUBSTR(PRODUCT.PRODUCT_NAME,1,2) = 'BE' THEN
     CASE
      WHEN AGMT_AGMT_CLASS_ASSOC.AGREEMENT_CLASS_VALUE_CD = 1 THEN 'BDTD'
      ELSE 'BDTI'
     END 
   WHEN  SUBSTR(PRODUCT.PRODUCT_NAME,1,2) = 'FX' THEN
     CASE
      WHEN FOREIGN_EXCHANGE_AGREEMENT.FX_AGREEMENT_TYPE_CD = 1 THEN 'FWX'
      WHEN FOREIGN_EXCHANGE_AGREEMENT.FX_AGREEMENT_TYPE_CD IN (2,3,4) THEN 'SPOT'
      WHEN FOREIGN_EXCHANGE_AGREEMENT.FX_AGREEMENT_TYPE_CD IN (5,7,9) THEN 'NSP'
      WHEN FOREIGN_EXCHANGE_AGREEMENT.FX_AGREEMENT_TYPE_CD = 11 THEN 'NFW'
      WHEN FOREIGN_EXCHANGE_AGREEMENT.FX_AGREEMENT_TYPE_CD IN(6,8,10) THEN 'FSP'
      WHEN FOREIGN_EXCHANGE_AGREEMENT.FX_AGREEMENT_TYPE_CD = 12 THEN 'FFW'
     END 
   WHEN  PRODUCT.PRODUCT_NAME LIKE 'DERIVATIVES%' THEN 'FWX'
   ELSE PRODUCT_GROUP.Host_Product_Group_Val
  END AS CHAR(4)) AS PROD_CODE, CAST(ACCOUNT_BALANCE_SUMMARY_DD.GL_Account_Code_Val AS CHAR(6)) AS FIS_CODE,
  CAST(REF_CS009700.SHORT_DESCRIPTION AS CHAR(3)) AS BAL_CURR_CODE,
  (CASE
   WHEN CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt  AS DECIMAL(18,2))  = ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt
   THEN CAST(CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt  AS DECIMAL(18,2)) AS VARCHAR(21))
    ELSE TRIM(TRAILING '0' FROM CAST(CAST(ACCOUNT_BALANCE_SUMMARY_DD.Acct_Crncy_Balance_Summary_Amt  AS DECIMAL(18,2)) AS VARCHAR(21)))
  END) AS BAL_AMT,
  CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_21 AS CHAR(4)) AS RC_CODE,
  CAST(ACCOUNT_PARTY.ACCPAR_ROLE_CD_22 AS CHAR(4)) AS OC_CODE,
  (CASE 
   WHEN  AGREEMENT.Acct_Current_Status_Type_Cd = 4 THEN CAST('02' AS CHAR(2))
   ELSE CAST('01' AS CHAR(2))
  END)  AS STATUS, (CASE
   WHEN AGREEMENT.Account_Close_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04', DATE '1900-01-01') THEN CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(AGREEMENT.Account_Close_Dt , 'yyyy-MM-dd') AS CHAR(10)))  
  END) AS CLOSE_DT,
  ( CAST(DATE_FORMAT(AGREEMENT.Account_Signed_Dt , 'yyyy-MM-dd') AS CHAR(10)))   AS CONTRACT_DT,
  ( CAST(DATE_FORMAT(AGREEMENT.Account_Open_Dt   , 'yyyy-MM-dd') AS CHAR(10)))  AS EFFECT_DT,
  (CASE
   WHEN AGREEMENT.Contract_Expiration_Dt IN (DATE '1000-01-01', DATE '1000-01-02', DATE '1000-01-03',DATE '1000-01-04') THEN CAST('9999-12-31' AS CHAR(10))
   ELSE ( CAST(DATE_FORMAT(AGREEMENT.Contract_Expiration_Dt , 'yyyy-MM-dd') AS CHAR(10)))
  END) AS MATURITY_DT,
  ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))   AS PASTDUE_DT,
  ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10))) AS STOPCAL_DT,
  (CASE WHEN Agreement.Asset_Liability_Cd = 1 AND Agreement.Balance_Sheet_Cd = 1
  THEN  CAST('F' AS CHAR(1))
  ELSE  CAST('N' AS CHAR(1))
  END)  AS FUND_FLAG, ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))   AS PENALTY_DT, 
    RPAD(' ', 2, ' ') AS STATUS_TDR,
  ( CAST(DATE_FORMAT(TO_DATE('9999-12-31' ,'yyyy-MM-dd') , 'yyyy-MM-dd') AS CHAR(10)))  AS EXPRY_DT
  
  FROM  P1VTTEDW.AGREEMENT  AS AGREEMENT
  
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS VOBM_BUSINESSDATE
  ON  VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGREEMENT.START_DT 
   AND  AGREEMENT.END_DT
   AND  AGREEMENT.RECORD_DELETED_FLAG = 0
  AND AGREEMENT.ctl_id = '017'
  
   AND (AGREEMENT.Acct_Current_Status_Type_Cd NOT IN (4,122,123) 
    OR (AGREEMENT.Acct_Current_Status_Type_Cd  IN (4,122,123) AND AGREEMENT.ACCOUNT_CLOSE_DT = VOBM_BUSINESSDATE.BUSINESSDATE)) 
/* >2010-11-26 R53040063-filter PR<--   
*/
  AND AGREEMENT.ACCOUNT_MODIFIER_NUM <> 'PR'
   
  INNER JOIN P1VTTEDW.ACCOUNT_ACCOUNT_GROUP  AS ACCOUNT_ACCOUNT_GROUP
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_ACCOUNT_GROUP.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_ACCOUNT_GROUP.ACCOUNT_MODIFIER_NUM
   AND ACCOUNT_ACCOUNT_GROUP.Acct_To_Acct_Group_Relat_Cd IN (1,2)
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_ACCOUNT_GROUP.START_DT 
   AND ACCOUNT_ACCOUNT_GROUP.END_DT
   AND ACCOUNT_ACCOUNT_GROUP.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_ACCOUNT_GROUP.CTL_ID = '017'
   
/*  change  for  fillter  Internal Deal (27,2)   28-04-2010  
*/
   INNER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC  AS AGMT_CLASS_ASSOC27
  ON AGREEMENT.ACCOUNT_NUM = AGMT_CLASS_ASSOC27.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = AGMT_CLASS_ASSOC27.ACCOUNT_MODIFIER_NUM
   AND AGMT_CLASS_ASSOC27.AGREEMENT_CLASSIFICATION_CD =27
   AND AGMT_CLASS_ASSOC27.AGREEMENT_CLASS_VALUE_CD =2
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGMT_CLASS_ASSOC27.START_DT 
   AND AGMT_CLASS_ASSOC27.END_DT
   AND AGMT_CLASS_ASSOC27.RECORD_DELETED_FLAG = 0
   AND AGMT_CLASS_ASSOC27.CTL_ID = '017'   
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_BALANCE_SUMMARY_DD38 AS ACCOUNT_BALANCE_SUMMARY_DD
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_MODIFIER_NUM
   AND ACCOUNT_BALANCE_SUMMARY_DD.Balance_Category_TYPE_CD = 1 
   AND ACCOUNT_BALANCE_SUMMARY_DD.ACCOUNT_Metric_TYPE_CD = 1
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_BALANCE_SUMMARY_DD.START_DT 
   AND ACCOUNT_BALANCE_SUMMARY_DD.END_DT
   AND ACCOUNT_BALANCE_SUMMARY_DD.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_BALANCE_SUMMARY_DD.CTL_ID = '017'
   
  LEFT OUTER JOIN 
  (
  SELECT
  ACCPAR.ACCOUNT_NUM,
  ACCPAR.ACCOUNT_MODIFIER_NUM,
  MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 21 
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_21, MAX(
  CASE 
   WHEN ACCPAR.Account_Party_Role_Cd = 22
   THEN  FINANCIAL_INST_INT_ORG.Organization_Num
  END )  AS ACCPAR_ROLE_CD_22 
  FROM P1VTTEDW.ACCOUNT_PARTY AS ACCPAR
  INNER JOIN P1VTPOBM.VOBM_BUSINESSDATE_D AS BD
  ON  BD.BUSINESSDATE BETWEEN ACCPAR.START_DT 
   AND ACCPAR.END_DT  AND ACCPAR.RECORD_DELETED_FLAG = 0
   AND ACCPAR.CTL_ID = '017'
   AND ACCPAR.Account_Party_Role_Cd IN(21, 22)
  
  LEFT OUTER JOIN P1VTTEDW.FINANCIAL_INST_INT_ORG AS FINANCIAL_INST_INT_ORG
  ON ACCPAR.PARTY_ID = FINANCIAL_INST_INT_ORG.Internal_Org_Party_Id 
  AND BD.BUSINESSDATE BETWEEN FINANCIAL_INST_INT_ORG.START_DT 
   AND FINANCIAL_INST_INT_ORG.END_DT  AND FINANCIAL_INST_INT_ORG.RECORD_DELETED_FLAG = 0   
  
  GROUP BY 1,2
  ) AS ACCOUNT_PARTY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PARTY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PARTY.ACCOUNT_MODIFIER_NUM
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_CURRENCY AS ACCOUNT_CURRENCY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_CURRENCY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_CURRENCY.ACCOUNT_MODIFIER_NUM
   AND ACCOUNT_CURRENCY.CURRENCY_USE_CD = 1
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_CURRENCY.START_DT 
   AND ACCOUNT_CURRENCY.END_DT
   AND ACCOUNT_CURRENCY.RECORD_DELETED_FLAG = 0
    AND ACCOUNT_CURRENCY.CTL_ID = '017'
   
  LEFT OUTER JOIN P1VTTEDW.ACCOUNT_PRODUCT_HISTORY AS ACCOUNT_PRODUCT_HISTORY
  ON AGREEMENT.ACCOUNT_NUM = ACCOUNT_PRODUCT_HISTORY.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = ACCOUNT_PRODUCT_HISTORY.ACCOUNT_MODIFIER_NUM
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN ACCOUNT_PRODUCT_HISTORY.START_DT 
   AND ACCOUNT_PRODUCT_HISTORY.END_DT
   AND ACCOUNT_PRODUCT_HISTORY.RECORD_DELETED_FLAG = 0
   AND ACCOUNT_PRODUCT_HISTORY.CTL_ID = '017'
   
  LEFT OUTER JOIN P1VTTEDW.PROD_GROUP_ASSOCIATION AS PROD_GROUP_ASSOCIATION
  ON ACCOUNT_PRODUCT_HISTORY.PRODUCT_ID = PROD_GROUP_ASSOCIATION.PRODUCT_ID
  AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PROD_GROUP_ASSOCIATION.START_DT 
   AND PROD_GROUP_ASSOCIATION.END_DT
   AND PROD_GROUP_ASSOCIATION.RECORD_DELETED_FLAG = 0
  AND PROD_GROUP_ASSOCIATION.CTL_ID = '017'
  
  LEFT OUTER JOIN P1VTTEDW.PRODUCT_GROUP AS PRODUCT_GROUP
  ON PROD_GROUP_ASSOCIATION.PRODUCT_GROUP_ID = PRODUCT_GROUP.PRODUCT_GROUP_ID
   AND PRODUCT_GROUP.Host_Product_Group_Val <> 'FI' 
   AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT_GROUP.START_DT 
   AND PRODUCT_GROUP.END_DT
   AND PRODUCT_GROUP.RECORD_DELETED_FLAG = 0
   AND PRODUCT_GROUP.CTL_ID = '017'
   
    LEFT OUTER JOIN P1VTTEDW.PRODUCT AS PRODUCT
  ON ACCOUNT_PRODUCT_HISTORY.PRODUCT_ID = PRODUCT.PRODUCT_ID
    AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN PRODUCT.START_DT 
    AND PRODUCT.END_DT
    AND PRODUCT.RECORD_DELETED_FLAG = 0
    AND PRODUCT.CTL_ID = '017'
    
  LEFT OUTER JOIN P1VTTEDW.AGMT_AGMT_CLASS_ASSOC   AS AGMT_AGMT_CLASS_ASSOC
  ON AGREEMENT.ACCOUNT_NUM = AGMT_AGMT_CLASS_ASSOC.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = AGMT_AGMT_CLASS_ASSOC.ACCOUNT_MODIFIER_NUM
    AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN AGMT_AGMT_CLASS_ASSOC.START_DT 
    AND AGMT_AGMT_CLASS_ASSOC.END_DT
    AND AGMT_AGMT_CLASS_ASSOC.RECORD_DELETED_FLAG = 0
    AND AGMT_AGMT_CLASS_ASSOC.CTL_ID = '017'
     AND AGMT_AGMT_CLASS_ASSOC.AGREEMENT_CLASSIFICATION_CD = 23 
     
  LEFT OUTER JOIN  P1VTTEDW.FOREIGN_EXCHANGE_AGREEMENT AS FOREIGN_EXCHANGE_AGREEMENT
  ON AGREEMENT.ACCOUNT_NUM = FOREIGN_EXCHANGE_AGREEMENT.ACCOUNT_NUM
   AND AGREEMENT.ACCOUNT_MODIFIER_NUM = FOREIGN_EXCHANGE_AGREEMENT.ACCOUNT_MODIFIER_NUM
    AND VOBM_BUSINESSDATE.BUSINESSDATE BETWEEN FOREIGN_EXCHANGE_AGREEMENT.START_DT 
    AND FOREIGN_EXCHANGE_AGREEMENT.END_DT
    AND FOREIGN_EXCHANGE_AGREEMENT.RECORD_DELETED_FLAG = 0
    AND FOREIGN_EXCHANGE_AGREEMENT.CTL_ID = '017'
  
  LEFT OUTER JOIN P1VUTEDW.REFERENCE_DESCRIPTION AS REF_CS009700
  ON ACCOUNT_CURRENCY.Account_Currency_Cd = REF_CS009700.EDW_CODE
   AND  REF_CS009700.CODE_ID = 55
   AND REF_CS009700.CODE_SET_ID = 'CS009700'
   AND  REF_CS009700.LANGUAGE_ID = 1
/*   2-11-2010 ADD Filter FX cancel TRANSACTION  OF TR OUT FROM file AS FOLLOWING:-
 UR53080007 MAS 610 APP 2 RETURN OF Monthly FOREIGN Exchange Business Transacted -REQUEST TO exclude FX Cancelled deals
*/

WHERE NOT(PRODUCT_GROUP.Host_Product_Group_Val = 'FX' 
AND  AGREEMENT.Acct_Current_Status_Type_Cd = 4 
AND AGREEMENT.Acct_Status_Reason_Cd = 100)
