CREATE OR REPLACE VIEW P1VTPBU.VBU_BusinessDate_M (
  BUSINESSDATE,
  PREVBUSINESSDATE,
  NEXTBUSINESSDATE,
  FIRSTBUSINESSDATE)
COMMENT 'VBU_BUSINESSDATE_M

'
AS SELECT
BDATE.BUSINESSDATE AS BUSINESSDATE,
BDATE.PREVBUSINESSDATE AS PREVBUSINESSDATE,
BDATE.NEXTBUSINESSDATE AS NEXTBUSINESSDATE,
to_date(SUBSTR(CAST(TO_DATE(BDATE.BUSINESSDATE ,'yyyyMMdd') AS CHAR(8)),1,8) || '01') AS FIRSTBUSINESSDATE
FROM P1DCFEDW.CTLFW_BUSINESSDATE AS BDATE
 WHERE BDATE.BUSINESSDATEKEY = 381
