CREATE OR REPLACE VIEW P1VTPBIT.TVBI_BI_ORG_SUB_LEV (
  PARTY_ID,
  ORG_OWNER,
  ORG_OWNER_NAME_EN,
  ORG_OWNER_NAME_TH,
  ORG_OWNER_NAME_DESC_EN,
  ORG_OWNER_NAME_DESC_TH,
  CHILD_SEGMENT_MAX_VALUE,
  CHILD_SEGMENT_MIN_VALUE)
AS SELECT
F.INTERNAL_ORG_PARTY_ID AS Party_Id
,F.ORGANIZATION_NUM  AS ORG_OWNER
, C.ORG_NAME_EN AS ORG_OWNER_NAME_EN
, C.ORG_NAME_TH AS ORG_OWNER_NAME_TH
, C.ORG_NAME_DESC_EN AS ORG_OWNER_NAME_DESC_EN
, C.ORG_NAME_DESC_TH AS ORG_OWNER_NAME_DESC_TH
, CAST(A.CHILD_SEGMENT_MAX_VALUE AS INT) AS CHILD_SEGMENT_MAX_VALUE
, CAST(A.CHILD_SEGMENT_MIN_VALUE AS INT) AS CHILD_SEGMENT_MIN_VALUE

FROM
(
 SELECT
 F.ORGANIZATION_NUM
 ,F.INTERNAL_ORG_PARTY_ID

 FROM P1VTTEDW.FINANCIAL_INST_INT_ORG AS F

 INNER JOIN P1VTPBIT.VBI_BUSINESSDATE_D AS CB_01
  ON CB_01.BUSINESSDATE BETWEEN F.START_DT AND F.END_DT
   AND F.RECORD_DELETED_FLAG = 0

 INNER JOIN P1VUTEDW.BKEY_PARTY P
 ON F.INTERNAL_ORG_PARTY_ID = P.EDW_KEY
  AND SUBSTR(P.SOURCE_KEY,0,INSTR(P.SOURCE_KEY,'_')-1) = '0000000000000000061021'
) AS F

CROSS JOIN P1VTPBIT.VBI_BUSINESSDATE_D AS CB

INNER JOIN
(
 SELECT
   COALESCE(A.ORG_PARTY_ID,B.ORG_PARTY_ID) AS ORG_PARTY_ID
   , A.ORG_NAME AS ORG_NAME_TH
   , B.ORG_NAME AS ORG_NAME_EN
   , A.ORG_NAME_DESC AS ORG_NAME_DESC_TH
   , B.ORG_NAME_DESC AS ORG_NAME_DESC_EN

  FROM
  (
   SELECT
   THAI.ORG_PARTY_ID
   ,THAI.ORG_NAME
   ,THAI.ORG_NAME_DESC
   FROM P1VTTEDW.ORGANIZATION_NAME_HIST AS THAI

   INNER JOIN  P1VTPBIT.VBI_BUSINESSDATE_D AS CB_02
   ON CB_02.BUSINESSDATE BETWEEN THAI.START_DT AND THAI.END_DT
     AND THAI.LANGUAGE_CD = 2
      AND THAI.NAME_TYPE_CD = 7
      AND THAI.RECORD_DELETED_FLAG = 0
   ) AS A

  FULL OUTER JOIN
  (
   SELECT
   ENG.ORG_PARTY_ID
   ,ENG.ORG_NAME
   ,ENG.ORG_NAME_DESC
   FROM P1VTTEDW.ORGANIZATION_NAME_HIST AS ENG

   INNER JOIN  P1VTPBIT.VBI_BUSINESSDATE_D AS CB_03
   ON CB_03.BUSINESSDATE BETWEEN ENG.START_DT AND ENG.END_DT
     AND ENG.LANGUAGE_CD = 1
      AND ENG.NAME_TYPE_CD = 7
      AND ENG.RECORD_DELETED_FLAG = 0
   ) AS B
   ON A.ORG_PARTY_ID = B.ORG_PARTY_ID
) AS C
ON F.INTERNAL_ORG_PARTY_ID = C.ORG_PARTY_ID
 AND C.ORG_NAME_EN NOT LIKE ('DUMMY%')

LEFT OUTER JOIN P1VTTEDW.COA_SEGMENT_CATEGORY_HIERARCHY AS A
ON A.PARENT_SEGMENT_VALUE = F.ORGANIZATION_NUM
  AND CB.BUSINESSDATE BETWEEN A.START_DT AND A.END_DT
  AND A.RECORD_DELETED_FLAG = 0
  AND A.COA_SEGMENT_CATEGORY_CD = 3
