CREATE OR REPLACE VIEW P1VEUCDD.VCDD_PRODUCT (
  PRODUCT_ID,
  PRODUCT_NAME,
  PRODUCT_GROUP,
  PRODUCT_CLASS,
  PRODUCT_LINE)
COMMENT '------------------------------------------------------------------------------

 ############################################################
  MODELER NAME: ANONGNATH A.
  DEVELOP BY: PRAVEEN
  VIEW NAME: VCDD_PRODUCT
  VERSION MAPPING: EDW_DOWNSTREAM_CDD_MAPXFORMBUSRULE_SPECIFICATION V1-4
  CREATE DATE: 2014-10-01
  DESCRIPTION : R55080038-02 - CHANGE PROGRAM KYCCDD -SCORING
 ############################################################
 

'
AS SELECT
CAST( CDD.PRODUCT_SOURCE_TYPE_CODE AS VARCHAR(20)) AS PRODUCT_ID,
CAST(LEFT(CDD.PRODUCT_SOURCE_TYPE_DESC,30) AS  VARCHAR(30)) AS PRODUCT_NAME, --ADD LEFT ON 20230206
CAST(CDD.PRODUCT_GROUP AS VARCHAR(30)) AS   PRODUCT_GROUP,
CAST( CDD.PRODUCT_CLASS AS VARCHAR(30)) AS  PRODUCT_CLASS,
CAST(NULL AS VARCHAR(30)) AS  PRODUCT_LINE
         
FROM P1DPYCDD.TCDD_PRODUCT AS CDD
 
INNER JOIN P1VTPCDD.VCDD_BUSINESSDATE_P AS BD
ON BD.BUSINESSDATE = CDD.START_DT 
AND CDD.RECORD_DELETED_FLAG = 0
