CREATE OR REPLACE VIEW P1VTXEDW.VS1_EVENTGRPASS_01 (
  Event_Group_Id,
  Event_Id,
  Event_Start_Dt)
AS SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_COL_CR.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_COL_CR.CREATEDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_COL_CR_1_0 AS S1_COL_CR

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'ACTLCREDITAMT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL
  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_COL_DB.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_COL_CR.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_COL_DB_1_0 AS S1_COL_DB

INNER JOIN P1VSTEDW.S1_COL_CR_1_0 AS S1_COL_CR
ON UPPER(RTRIM(S1_COL_DB.TRANREF)) = UPPER(RTRIM(S1_COL_CR.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'DEBITAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1



UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_COL_FEE.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_COL_CR.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_COL_FEE_1_0 AS S1_COL_FEE

INNER JOIN P1VSTEDW.S1_COL_CR_1_0 AS S1_COL_CR
ON UPPER(RTRIM(S1_COL_FEE.TRANREF)) = UPPER(RTRIM(S1_COL_CR.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'FEEAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_TRAN_DB.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_TRAN_DB.CREATEDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_TRAN_DB_1_0 AS S1_TRAN_DB

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'INSTRAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL
  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_TRAN_CR.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_TRAN_DB.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_TRAN_CR_1_0 AS S1_TRAN_CR

INNER JOIN P1VSTEDW.S1_TRAN_DB_1_0 AS S1_TRAN_DB
ON UPPER(RTRIM(S1_TRAN_CR.TRANREF)) = UPPER(RTRIM(S1_TRAN_DB.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'CREDITAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL
  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_TRAN_FEE.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_TRAN_DB.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_TRAN_FEE_1_0 AS S1_TRAN_FEE

INNER JOIN P1VSTEDW.S1_TRAN_DB_1_0 AS S1_TRAN_DB
ON UPPER(RTRIM(S1_TRAN_FEE.TRANREF)) = UPPER(RTRIM(S1_TRAN_DB.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'FEEAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_INT_DB.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_INT_DB.CREATEDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_INT_DB_1_0 AS S1_INT_DB

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'INTDEBITAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_INT_CR.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_INT_DB.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_INT_CR_1_0 AS S1_INT_CR

INNER JOIN 
(
 SELECT
  INT_DB.TRANREF,
  INT_DB.SCHDEXECUTIONDATE
 
 FROM P1VSTEDW.S1_INT_DB_1_0 AS INT_DB
 
 GROUP BY 1,2
) AS S1_INT_DB
ON UPPER(RTRIM(S1_INT_CR.TRANREF)) = UPPER(RTRIM(S1_INT_DB.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'INTCREDITAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL
  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_INT_FEE.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_INT_DB.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_INT_FEE_1_0 AS S1_INT_FEE

INNER JOIN 
(
 SELECT
  INT_DB.TRANREF,
  INT_DB.SCHDEXECUTIONDATE
  
 FROM P1VSTEDW.S1_INT_DB_1_0 AS INT_DB
 
 GROUP BY 1,2
 
) AS S1_INT_DB
ON UPPER(RTRIM(S1_INT_FEE.TRANREF)) = UPPER(RTRIM(S1_INT_DB.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'FEEAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1


 --  >> CHANGED DATE :  2012-07-06
 -- CHANGED BY   :  Khet S.

UNION ALL
  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_FCY_DB.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_FCY_DB.CREATEDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_FCY_DB_1_0 AS S1_FCY_DB


LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'DEBITAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL
  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_FCY_CR.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_FCY_DB.SCHDEXECUTIONDTTM ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_FCY_CR_1_0 AS S1_FCY_CR

INNER JOIN P1VSTEDW.S1_FCY_DB_1_0 AS S1_FCY_DB
ON UPPER(RTRIM(S1_FCY_CR.TRANREF)) = UPPER(RTRIM(S1_FCY_DB.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'CREDITAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_FCY_FEE.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_FCY_DB.SCHDEXECUTIONDTTM ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_FCY_FEE_1_0 AS S1_FCY_FEE

INNER JOIN P1VSTEDW.S1_FCY_DB_1_0 AS S1_FCY_DB
ON UPPER(RTRIM(S1_FCY_FEE.TRANREF)) = UPPER(RTRIM(S1_FCY_DB.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'FEEAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_FCY_RATE.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_FCY_DB.SCHDEXECUTIONDTTM ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_FCY_RATE_1_0 AS S1_FCY_RATE

INNER JOIN P1VSTEDW.S1_FCY_DB_1_0 AS S1_FCY_DB
ON UPPER(RTRIM(S1_FCY_RATE.TRANREF)) = UPPER(RTRIM(S1_FCY_DB.TRANREF))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'TRANSRATE'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_BILL_DB_1_0.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_BILL_DB_1_0.CREATEDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_BILL_DB_1_0 AS S1_BILL_DB_1_0

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'INSTRAMOUNT' 
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL
  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_BILL_CR_1_0.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_BILL_DB_1_0.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_BILL_CR_1_0 AS S1_BILL_CR_1_0

INNER JOIN P1VSTEDW.S1_BILL_DB_1_0 AS S1_BILL_DB_1_0
 ON UPPER(RTRIM(S1_BILL_DB_1_0.TRANSACTIONID)) = UPPER(RTRIM(S1_BILL_CR_1_0.TRANSACTIONID))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'CREDITAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_BILL_FEE_1_0.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_BILL_DB_1_0.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_BILL_FEE_1_0 AS S1_BILL_FEE_1_0

INNER JOIN P1VSTEDW.S1_BILL_DB_1_0 AS S1_BILL_DB_1_0
 ON RTRIM(S1_BILL_DB_1_0.TRANSACTIONID) = RTRIM(S1_BILL_FEE_1_0.TRANSACTIONID)

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'FEEAMOUNT' 
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL



SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_BILL_DB_1_0.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_BILL_DB_1_0.CREATEDATE ,'yyyy-MM-dd') AS Event_Start_Dt

FROM P1VSTEDW.S1_BILL_DB_1_0 AS S1_BILL_DB_1_0

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = CAST(S1_BILL_DB_1_0.RECURRINGTYPE AS VARCHAR(100) )
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_XFER_DB_1_0.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_XFER_DB_1_0.CREATEDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_XFER_DB_1_0 AS S1_XFER_DB_1_0

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'INSTRAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_XFER_CR_1_0.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_XFER_DB_1_0.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_XFER_CR_1_0 AS S1_XFER_CR_1_0
INNER JOIN  P1VSTEDW.S1_XFER_DB_1_0 AS S1_XFER_DB_1_0
ON  UPPER(RTRIM(S1_XFER_DB_1_0.TRANSACTIONID)) = UPPER(RTRIM(S1_XFER_CR_1_0.TRANSACTIONID))

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'CREDITAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1

UNION ALL

  -----------------------------------------------------------------------------
SELECT 
CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
,CAST(S1_XFER_FEE_1_0.EDW_RECORD_NO AS BIGINT) AS Event_Id
,TO_DATE(S1_XFER_DB_1_0.SCHDEXECUTIONDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt

FROM P1VSTEDW.S1_XFER_FEE_1_0 AS S1_XFER_FEE_1_0
INNER JOIN  P1VSTEDW.S1_XFER_DB_1_0 AS S1_XFER_DB_1_0
ON  UPPER(RTRIM(S1_XFER_DB_1_0.TRANSACTIONID)) = UPPER(RTRIM(S1_XFER_FEE_1_0.TRANREF))                       

LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
ON M42050.SOURCE_KEY = 'FEEAMOUNT'
AND M42050.SRC_CTL_ID = '051'
AND M42050.SOURCE_ID = 1
/*####### END Change for UR  : CB61020001,CB60120006 - S1&IPS (2018-04-06) ##### */

UNION ALL

  -----------------------------------------------------------------------------
SELECT CAST(M42050.EDW_CODE AS INT) AS Event_Group_Id
  , CAST(S1_TRAN_DB.EDW_RECORD_NO AS BIGINT) AS Event_Id
  , TO_DATE(S1_TRAN_DB.CREATEDATE ,'yyyy-MM-dd' ) AS Event_Start_Dt
FROM P1VSTEDW.S1_TRAN_DB_1_0 AS S1_TRAN_DB
LEFT OUTER JOIN P1VUTEDW.M42050_EVENT_GROUP AS M42050
    ON  UPPER(RTRIM(M42050.SOURCE_KEY)) = UPPER(RTRIM(S1_TRAN_DB.CHANNEL))
        AND M42050.SRC_CTL_ID = '051'
        AND M42050.SOURCE_ID = 2
