CREATE OR REPLACE VIEW P1VSTEDW.S1_USR_PROF_1_0 (
  CUSTOMERID,
  TOTALUSER,
  TOTALACTIVEUSER,
  TOTALACTIVETOKENUSER,
  START_DT,
  END_DT,
  RECORD_DELETED_FLAG,
  CTL_ID,
  INS_PROC_NAME,
  INS_TXF_BATCHID,
  UPD_PROC_NAME,
  UPD_TXF_BATCHID,
  BK_PARTY_133_001)
COMMENT '------------------------------------------------------------------------------




'
AS SELECT
/* S1_USR_PROF.CUSTOMERID >> edited by program */
rtrim(S1_USR_PROF.CUSTOMERID) AS CUSTOMERID
,S1_USR_PROF.TOTALUSER
,S1_USR_PROF.TOTALACTIVEUSER
,S1_USR_PROF.TOTALACTIVETOKENUSER
,S1_USR_PROF.START_DT
,S1_USR_PROF.END_DT
,S1_USR_PROF.RECORD_DELETED_FLAG
/* ,S1_USR_PROF.CTL_ID >> edited by program */
,upper(rtrim(S1_USR_PROF.CTL_ID)) AS CTL_ID
/* ,S1_USR_PROF.INS_PROC_NAME >> edited by program */
,upper(rtrim(S1_USR_PROF.INS_PROC_NAME)) AS INS_PROC_NAME
,S1_USR_PROF.INS_TXF_BATCHID
/* ,S1_USR_PROF.UPD_PROC_NAME >> edited by program */
,upper(rtrim(S1_USR_PROF.UPD_PROC_NAME)) AS UPD_PROC_NAME
,S1_USR_PROF.UPD_TXF_BATCHID
/*  ,CAST( TRIM(COALESCE(BKINV_FOR_S1_PARTY.EDW_KEY,'')) AS VARCHAR(100))||'_133'AS BK_PARTY_133_001 >> edited by program */
 ,CAST( TRIM(COALESCE(BKINV_FOR_S1_PARTY.EDW_KEY,'')) AS VARCHAR(100))||'_133' AS BK_PARTY_133_001
 FROM  P1DSGEDW.S1_USR_PROF_1_0  AS S1_USR_PROF
 
  LEFT OUTER JOIN P1VUTEDW.BKEY_INV_INTERNAL AS BKINV_FOR_S1_PARTY
     ON      rtrim(BKINV_FOR_S1_PARTY.SOURCE_KEY) = rtrim(S1_USR_PROF.BK_PARTY_133_001)
