CREATE OR REPLACE VIEW P1VTPLLFP.TV_LLFP_RL_ACCT_STATUS_FINAL (
  RL_BASE_ACCT_NUM,
  RL_ACCOUNT_NUM,
  RL_ACCOUNT_MOD_NUM,
  RESCHEDULE_DATE,
  BEF_BASE_ACCT_NUM,
  BEF_ACCOUNT_NUM,
  BEF_ACCOUNT_MOD_NUM,
  ALS_CTL3,
  TDR_PDR_FLAG,
  ACTION_CODE)
COMMENT '/*##################################################
CHANGE DATE 2021-04-28
DEVELOPER : VILAVAN NG.
MODELER NAME : KESSANEE P.
MAPPING VERSION : EDW_DownStream_LLFP_TDR_Diagram_V0.3
UR No : OT64010006 - Update logic for RL date and DPD before RL
##################################################*/'
AS SELECT 
FIN_RL.RL_BASE_ACCT_NUM AS RL_BASE_ACCT_NUM
,FIN_RL.RL_ACCOUNT_NUM AS RL_ACCOUNT_NUM
,FIN_RL.RL_ACCOUNT_MOD_NUM AS RL_ACCOUNT_MOD_NUM
,FIN_RL.RESCHEDULE_DATE AS RESCHEDULE_DATE
,FIN_RL.BEF_BASE_ACCT_NUM AS BEF_BASE_ACCT_NUM
,FIN_RL.BEF_ACCOUNT_NUM AS BEF_ACCOUNT_NUM
,FIN_RL.BEF_ACCOUNT_MOD_NUM AS BEF_ACCOUNT_MOD_NUM
,FIN_RL.ALS_CTL3 AS ALS_CTL3
,FIN_RL.TDR_PDR_FLAG AS TDR_PDR_FLAG
,FIN_RL.ACTION_CODE AS ACTION_CODE

FROM 
(
   SELECT
  MAIN_RL.BASE_ACCT_NUM AS RL_BASE_ACCT_NUM
  ,MAIN_RL.RL_CHG_BRANCH AS RL_ACCOUNT_NUM
  ,MAIN_RL.ACCOUNT_MODIFIER_NUM AS RL_ACCOUNT_MOD_NUM
  ,DATE_FORMAT(MAIN_RL.RESCHEDULE_DATE ,'yyyy-MM-dd') AS RESCHEDULE_DATE
  ,SUB_BFR_AGING.BEF_BASE_ACCT_NUM AS BEF_BASE_ACCT_NUM
  ,SUB_BFR_AGING.RL_CHG_BRANCH AS BEF_ACCOUNT_NUM
  ,SUB_BFR_AGING.BEF_ACCOUNT_MOD_NUM AS BEF_ACCOUNT_MOD_NUM
  ,MAIN_RL.ALS_CTL3
  ,MAIN_RL.TDR_PDR_FLAG
  ,MAIN_RL.ACTION_CODE
 FROM
 (
 SELECT
 ACCOUNT_NUM
 ,ACCOUNT_MODIFIER_NUM
 ,RL_CHG_BRANCH --Support branch change case
 ,RESCHEDULE_DATE
 ,BASE_ACCT_NUM
 ,ALS_CTL3
 ,TDR_PDR_FLAG
 ,ACTION_CODE 
 FROM
 (SELECT
     ESL_AGMT.ACCOUNT_NUM AS ACCOUNT_NUM
    ,ESL_AGMT.ACCOUNT_MODIFIER_NUM AS ACCOUNT_MODIFIER_NUM
    ,SUBSTR(ESL_AGMT.ACCOUNT_NUM,1,8)||SUBSTR(ESL_AGMT.ACCOUNT_NUM,13) AS RL_CHG_BRANCH --Support branch change case
    ,DEMOG_RESCHEDULE.RESCHEDULE_DATE AS  RESCHEDULE_DATE
    ,ESL_AGMT.BASE_ACCT_NUM AS  BASE_ACCT_NUM
    ,ACCDEMO_CTL3.ALS_CTL3 AS  ALS_CTL3
 ,DEM_TDR_PDR.TDR_PDR_FLAG AS TDR_PDR_FLAG
 ,CAST(''  AS VARCHAR(20)) AS ACTION_CODE
 ,RANK () OVER (PARTITION BY ESL_AGMT.ACCOUNT_NUM ORDER BY DEMOG_RESCHEDULE.RESCHEDULE_DATE DESC) AS R
 FROM
 (
     SELECT 
  BD.BUSINESSDATE
     ,S_ESL_AGMT.ACCOUNT_NUM
     ,S_ESL_AGMT.ACCOUNT_MODIFIER_NUM
     ,S_ESL_AGMT.BASE_ACCT_NUM
     
     FROM P1VTTEDW.EDW_AGREEMENT_INFO AS S_ESL_AGMT
     
     INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
     ON S_ESL_AGMT.AS_OF_DT = BUSINESSDATE
     AND S_ESL_AGMT.AGMT_CTL_ID ='004'
     AND S_ESL_AGMT.AGMT_LEVEL_CD  IN (1,2,3) /* Consider only Master accounts (Refer CS001966) */
     AND S_ESL_AGMT.ACTIVE_IND = '01' /* Get only Active Account */
          
    ) AS ESL_AGMT

INNER  JOIN 
(
SELECT  ACCDEMO.ACCOUNT_NUM, ACCDEMO.ACCOUNT_MODIFIER_NUM,  ACCDEMO.ACCT_DEMOGRAPHIC_VAL AS ALS_CTL3
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS ACCDEMO
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
 ON BD.BUSINESSDATE BETWEEN ACCDEMO.START_DT AND ACCDEMO.END_DT
 AND ACCDEMO.RECORD_DELETED_FLAG = 0
 AND ACCDEMO.DEMOG_CD = 121 --ALS CTL3
 AND ACCDEMO.DATA_SOURCE_CD = 1357
 AND ACCDEMO.CTL_ID = '004'     
)
AS  ACCDEMO_CTL3
ON ACCDEMO_CTL3.ACCOUNT_NUM = ESL_AGMT.ACCOUNT_NUM
AND ACCDEMO_CTL3.ACCOUNT_MODIFIER_NUM = ESL_AGMT.ACCOUNT_MODIFIER_NUM
 
LEFT  JOIN 
(
SELECT  DEM_TDR_PDR.ACCOUNT_NUM , DEM_TDR_PDR.ACCOUNT_MODIFIER_NUM , M10704_01.SOURCE_KEY AS TDR_PDR_FLAG
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS DEM_TDR_PDR
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
 ON BD.BUSINESSDATE BETWEEN DEM_TDR_PDR.START_DT AND DEM_TDR_PDR.END_DT
 AND DEM_TDR_PDR.RECORD_DELETED_FLAG = 0
 AND DEM_TDR_PDR.DEMOG_CD = 287 --TDR FLAG
 AND DEM_TDR_PDR.CTL_ID = '004'     
  
 LEFT OUTER JOIN P1VUTEDW.M10704_AGREE_DEMOG_VAL AS  M10704_01
 ON DEM_TDR_PDR.DEMOG_VALUE_CD = M10704_01.EDW_CODE
 AND M10704_01.SRC_CTL_ID = '004'
 AND M10704_01.SOURCE_ID = '1'
 
 
 ) AS DEM_TDR_PDR
    ON ESL_AGMT.ACCOUNT_NUM = DEM_TDR_PDR.ACCOUNT_NUM
  AND ESL_AGMT.ACCOUNT_MODIFIER_NUM = DEM_TDR_PDR.ACCOUNT_MODIFIER_NUM
  
LEFT JOIN 
(
SELECT  DEMOG_RESCHEDULE.ACCOUNT_NUM
,DEMOG_RESCHEDULE.ACCOUNT_MODIFIER_NUM
,DATE_FORMAT(DATE_FORMAT(DEMOG_RESCHEDULE.ACCT_DEMOGRAPHIC_VAL ,'yyyyMMdd') ,'yyyy-MM-dd') AS RESCHEDULE_DATE
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS DEMOG_RESCHEDULE
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
ON BD.BUSINESSDATE BETWEEN DEMOG_RESCHEDULE.START_DT AND DEMOG_RESCHEDULE.END_DT
AND DEMOG_RESCHEDULE.RECORD_DELETED_FLAG = 0
AND DEMOG_RESCHEDULE.DEMOG_CD = 4800  --Reschedule Date 
AND DEMOG_RESCHEDULE.DATA_SOURCE_CD = 1357 --AM
AND DEMOG_RESCHEDULE.CTL_ID = '004' --ALS
AND DEMOG_RESCHEDULE.ACCT_DEMOGRAPHIC_VAL <> '00000000' 
) AS  DEMOG_RESCHEDULE
ON ESL_AGMT.ACCOUNT_NUM = DEMOG_RESCHEDULE.ACCOUNT_NUM
AND ESL_AGMT.ACCOUNT_MODIFIER_NUM = DEMOG_RESCHEDULE.ACCOUNT_MODIFIER_NUM 
    
WHERE ACCDEMO_CTL3.ALS_CTL3  IN ('473','478','496') 
AND DEM_TDR_PDR.TDR_PDR_FLAG = 'RL'
AND DEMOG_RESCHEDULE.RESCHEDULE_DATE IS NOT NULL )

WHERE R = 1


UNION ALL 
  
  SELECT
  ACCOUNT_NUM
  ,ACCOUNT_MODIFIER_NUM
  ,RL_CHG_BRANCH --Support branch change case
  ,RESCHEDULE_DATE
  ,BASE_ACCT_NUM
  ,ALS_CTL3
  ,TDR_PDR_FLAG
  ,ACTION_CODE
  FROM
  (SELECT
     ESL_AGMT.ACCOUNT_NUM AS ACCOUNT_NUM
    ,ESL_AGMT.ACCOUNT_MODIFIER_NUM AS ACCOUNT_MODIFIER_NUM
    ,SUBSTR(ESL_AGMT.ACCOUNT_NUM,1,8)||SUBSTR(ESL_AGMT.ACCOUNT_NUM,13) AS RL_CHG_BRANCH --Support branch change case
 ,DATE_FORMAT(ACCT_FEAT.START_SKIP_DATE ,'yyyy-MM-dd') AS RESCHEDULE_DATE
    ,ESL_AGMT.BASE_ACCT_NUM AS BASE_ACCT_NUM
    ,ACCDEMO_CTL3.ALS_CTL3 AS ALS_CTL3
 ,DEM_TDR_PDR.TDR_PDR_FLAG AS TDR_PDR_FLAG
 ,ACCT_FEAT.ACTION_CODE  AS ACTION_CODE
 ,RANK () OVER (PARTITION BY ESL_AGMT.ACCOUNT_NUM ORDER BY ACCT_FEAT.START_SKIP_DATE  DESC) AS R

 FROM
 (
     SELECT 
  BD.BUSINESSDATE
     ,S_ESL_AGMT.ACCOUNT_NUM
     ,S_ESL_AGMT.ACCOUNT_MODIFIER_NUM
     ,S_ESL_AGMT.BASE_ACCT_NUM
     
     FROM P1VTTEDW.EDW_AGREEMENT_INFO AS S_ESL_AGMT
     
     INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
     ON S_ESL_AGMT.AS_OF_DT = BUSINESSDATE
     AND S_ESL_AGMT.AGMT_CTL_ID ='004'
     AND S_ESL_AGMT.AGMT_LEVEL_CD  IN (1,2,3) /* Consider only Master accounts (Refer CS001966) */
     AND S_ESL_AGMT.ACTIVE_IND = '01' /* Get only Active Account */
          
    ) AS ESL_AGMT

INNER  JOIN 
(
SELECT  ACCDEMO.ACCOUNT_NUM, ACCDEMO.ACCOUNT_MODIFIER_NUM,  ACCDEMO.ACCT_DEMOGRAPHIC_VAL AS ALS_CTL3
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS ACCDEMO
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
 ON BD.BUSINESSDATE BETWEEN ACCDEMO.START_DT AND ACCDEMO.END_DT
 AND ACCDEMO.RECORD_DELETED_FLAG = 0
 AND ACCDEMO.DEMOG_CD = 121 --ALS CTL3
 AND ACCDEMO.DATA_SOURCE_CD = 1357
 AND ACCDEMO.CTL_ID = '004'     
)
AS  ACCDEMO_CTL3
ON ACCDEMO_CTL3.ACCOUNT_NUM = ESL_AGMT.ACCOUNT_NUM
AND ACCDEMO_CTL3.ACCOUNT_MODIFIER_NUM = ESL_AGMT.ACCOUNT_MODIFIER_NUM
 
LEFT  JOIN 
(
SELECT  DEM_TDR_PDR.ACCOUNT_NUM , DEM_TDR_PDR.ACCOUNT_MODIFIER_NUM , M10704_01.SOURCE_KEY AS TDR_PDR_FLAG
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS DEM_TDR_PDR
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
 ON BD.BUSINESSDATE BETWEEN DEM_TDR_PDR.START_DT AND DEM_TDR_PDR.END_DT
 AND DEM_TDR_PDR.RECORD_DELETED_FLAG = 0
 AND DEM_TDR_PDR.DEMOG_CD = 287 --TDR FLAG
 AND DEM_TDR_PDR.CTL_ID = '004'     
  
 LEFT OUTER JOIN P1VUTEDW.M10704_AGREE_DEMOG_VAL AS  M10704_01
 ON DEM_TDR_PDR.DEMOG_VALUE_CD = M10704_01.EDW_CODE
 AND M10704_01.SRC_CTL_ID = '004'
 AND M10704_01.SOURCE_ID = '1'
 
 ) AS DEM_TDR_PDR
    ON ESL_AGMT.ACCOUNT_NUM = DEM_TDR_PDR.ACCOUNT_NUM
  AND ESL_AGMT.ACCOUNT_MODIFIER_NUM = DEM_TDR_PDR.ACCOUNT_MODIFIER_NUM
  
  LEFT OUTER JOIN 
   (
   SELECT 
   AF.ACCOUNT_NUM
   ,AF.ACCOUNT_MODIFIER_NUM
 ,AF.ACCOUNT_FEATURE_START_DT AS  START_SKIP_DATE
   ,AF.ACCOUNT_FEATURE_TXT AS ACTION_CODE

 FROM P1VTTEDW.ACCOUNT_FEATURE AS AF
 
  INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
  ON BD.BUSINESSDATE BETWEEN AF.START_DT AND AF.END_DT
   AND AF.RECORD_DELETED_FLAG = 0 
   AND AF.CTL_ID = '004'
   AND AF.ACCOUNT_FEATURE_ROLE_CD = 508        -- Action Code
  
 INNER JOIN P1VUTEDW.BKEY_FEATURE AS BK_FEAT
 ON BK_FEAT.EDW_KEY = AF.FEATURE_ID
  AND BK_FEAT.SOURCE_KEY = '3_1_Campaign Code_'  
  
) AS ACCT_FEAT
ON ACCT_FEAT.ACCOUNT_NUM = ESL_AGMT.ACCOUNT_NUM
AND ACCT_FEAT.ACCOUNT_MODIFIER_NUM = ESL_AGMT.ACCOUNT_MODIFIER_NUM

WHERE ACCDEMO_CTL3.ALS_CTL3 = '497'
AND  (DEM_TDR_PDR.TDR_PDR_FLAG IN ( 'RL' ,'R2' )   OR  substr(ACCT_FEAT.ACTION_CODE,1,3) = 'IRL' ) 
AND ACCT_FEAT.START_SKIP_DATE NOT IN (DATE '1000-01-01',DATE '1000-01-02',DATE '1000-01-03',DATE '1000-01-04')
AND ACCT_FEAT.START_SKIP_DATE IS NOT NULL )
WHERE R = 1

 
) AS MAIN_RL

 INNER JOIN 
  (
    SELECT 
    OLD_RL.RL_ACCOUNT_NUM AS RL_ACCOUNT_NUM
    ,OLD_RL.RL_ACCOUNT_MOD_NUM AS RL_ACCOUNT_MOD_NUM
    ,OLD_RL.BEF_ACCOUNT_NUM AS BEF_ACCOUNT_NUM 
    ,OLD_RL.BEF_ACCOUNT_MOD_NUM AS BEF_ACCOUNT_MOD_NUM
    ,ESL_AGMT.BASE_ACCT_NUM AS BEF_BASE_ACCT_NUM
    ,CASE WHEN OLD_RL.BEF_ACCOUNT_MOD_NUM LIKE 'TF%' THEN OLD_RL.BEF_ACCOUNT_NUM
      ELSE SUBSTR(OLD_RL.BEF_ACCOUNT_NUM,1,8)||SUBSTR(OLD_RL.BEF_ACCOUNT_NUM,13) END AS RL_CHG_BRANCH --Support branch change case 
    
    FROM P1DTPLLFP.TLLFP_BEFORE_RL_ACCT_M AS OLD_RL
    
    INNER JOIN 
    (
     SELECT 
     S_ESL_AGMT.ACCOUNT_NUM
     ,S_ESL_AGMT.ACCOUNT_MODIFIER_NUM
     ,S_ESL_AGMT.BASE_ACCT_NUM
    
     FROM P1VTTEDW.EDW_AGREEMENT_INFO AS S_ESL_AGMT 
     
     INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
     ON S_ESL_AGMT.AS_OF_DT = BD.BUSINESSDATE
     AND S_ESL_AGMT.AGMT_CTL_ID IN ('003','004','018')
     AND S_ESL_AGMT.AGMT_LEVEL_CD  IN (1,2,3)  /* Consider only Master accounts (Refer CS001966) */
     AND S_ESL_AGMT.BANK_CODE = '14'
       
    ) AS ESL_AGMT
    ON ESL_AGMT.ACCOUNT_NUM = OLD_RL.BEF_ACCOUNT_NUM
    AND ESL_AGMT.ACCOUNT_MODIFIER_NUM = OLD_RL.BEF_ACCOUNT_MOD_NUM
  
  ) AS SUB_BFR_AGING
  ON SUB_BFR_AGING.RL_ACCOUNT_NUM = MAIN_RL.ACCOUNT_NUM
  AND SUB_BFR_AGING.RL_ACCOUNT_MOD_NUM = MAIN_RL.ACCOUNT_MODIFIER_NUM
  
  --START : ADD  UNION   RL ON  OLD ACCOUNT---
  UNION
  
  SELECT
  MAIN_RL.BASE_ACCT_NUM AS RL_BASE_ACCT_NUM
  ,MAIN_RL.RL_CHG_BRANCH AS RL_ACCOUNT_NUM
  ,MAIN_RL.ACCOUNT_MODIFIER_NUM AS RL_ACCOUNT_MOD_NUM
  ,DATE_FORMAT(MAIN_RL.RESCHEDULE_DATE ,'yyyy-MM-dd') AS RESCHEDULE_DATE
  ,MAIN_RL.BASE_ACCT_NUM AS BEF_BASE_ACCT_NUM
  ,MAIN_RL.RL_CHG_BRANCH AS BEF_ACCOUNT_NUM
  ,MAIN_RL.ACCOUNT_MODIFIER_NUM AS BEF_ACCOUNT_MOD_NUM
  ,MAIN_RL.ALS_CTL3
  ,MAIN_RL.TDR_PDR_FLAG
  ,MAIN_RL.ACTION_CODE
 FROM
 (
 SELECT
 ACCOUNT_NUM
 ,ACCOUNT_MODIFIER_NUM
 ,RL_CHG_BRANCH --Support branch change case
 ,RESCHEDULE_DATE
 ,BASE_ACCT_NUM
 ,ALS_CTL3
 ,TDR_PDR_FLAG
 ,ACTION_CODE
 FROM
 (SELECT
     ESL_AGMT.ACCOUNT_NUM AS ACCOUNT_NUM
    ,ESL_AGMT.ACCOUNT_MODIFIER_NUM AS ACCOUNT_MODIFIER_NUM
    ,SUBSTR(ESL_AGMT.ACCOUNT_NUM,1,8)||SUBSTR(ESL_AGMT.ACCOUNT_NUM,13) AS RL_CHG_BRANCH --Support branch change case
    ,DEMOG_RESCHEDULE.RESCHEDULE_DATE AS  RESCHEDULE_DATE
    ,ESL_AGMT.BASE_ACCT_NUM AS  BASE_ACCT_NUM
    ,ACCDEMO_CTL3.ALS_CTL3 AS  ALS_CTL3
 ,DEM_TDR_PDR.TDR_PDR_FLAG AS TDR_PDR_FLAG
 , CAST(''  AS VARCHAR(20)) AS ACTION_CODE
 ,RANK () OVER (PARTITION BY ESL_AGMT.ACCOUNT_NUM ORDER BY DEMOG_RESCHEDULE.RESCHEDULE_DATE DESC) AS R
 
 FROM
 (
     SELECT 
  BD.BUSINESSDATE
     ,S_ESL_AGMT.ACCOUNT_NUM
     ,S_ESL_AGMT.ACCOUNT_MODIFIER_NUM
     ,S_ESL_AGMT.BASE_ACCT_NUM
     
     FROM P1VTTEDW.EDW_AGREEMENT_INFO AS S_ESL_AGMT
     
     INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
     ON S_ESL_AGMT.AS_OF_DT = BUSINESSDATE
     AND S_ESL_AGMT.AGMT_CTL_ID ='004'
     AND S_ESL_AGMT.AGMT_LEVEL_CD  IN (1,2,3) /* Consider only Master accounts (Refer CS001966) */
     AND S_ESL_AGMT.ACTIVE_IND = '01' /* Get only Active Account */
  ) AS ESL_AGMT

INNER  JOIN 
(
SELECT  ACCDEMO.ACCOUNT_NUM, ACCDEMO.ACCOUNT_MODIFIER_NUM,  ACCDEMO.ACCT_DEMOGRAPHIC_VAL AS ALS_CTL3
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS ACCDEMO
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
 ON BD.BUSINESSDATE BETWEEN ACCDEMO.START_DT AND ACCDEMO.END_DT
 AND ACCDEMO.RECORD_DELETED_FLAG = 0
 AND ACCDEMO.DEMOG_CD = 121 --ALS CTL3
 AND ACCDEMO.DATA_SOURCE_CD = 1357
 AND ACCDEMO.CTL_ID = '004'     
 
)
AS  ACCDEMO_CTL3
ON ACCDEMO_CTL3.ACCOUNT_NUM = ESL_AGMT.ACCOUNT_NUM
AND ACCDEMO_CTL3.ACCOUNT_MODIFIER_NUM = ESL_AGMT.ACCOUNT_MODIFIER_NUM
 
LEFT  JOIN 
(
SELECT  DEM_TDR_PDR.ACCOUNT_NUM , DEM_TDR_PDR.ACCOUNT_MODIFIER_NUM , M10704_01.SOURCE_KEY AS TDR_PDR_FLAG
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS DEM_TDR_PDR
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
 ON BD.BUSINESSDATE BETWEEN DEM_TDR_PDR.START_DT AND DEM_TDR_PDR.END_DT
 AND DEM_TDR_PDR.RECORD_DELETED_FLAG = 0
 AND DEM_TDR_PDR.DEMOG_CD = 287 --TDR FLAG
 AND DEM_TDR_PDR.CTL_ID = '004'
  
 LEFT OUTER JOIN P1VUTEDW.M10704_AGREE_DEMOG_VAL AS  M10704_01
 ON DEM_TDR_PDR.DEMOG_VALUE_CD = M10704_01.EDW_CODE
 AND M10704_01.SRC_CTL_ID = '004'
 AND M10704_01.SOURCE_ID = '1'
 
 
 ) AS DEM_TDR_PDR
    ON ESL_AGMT.ACCOUNT_NUM = DEM_TDR_PDR.ACCOUNT_NUM
  AND ESL_AGMT.ACCOUNT_MODIFIER_NUM = DEM_TDR_PDR.ACCOUNT_MODIFIER_NUM
  
LEFT JOIN 
(
SELECT  DEMOG_RESCHEDULE.ACCOUNT_NUM
,DEMOG_RESCHEDULE.ACCOUNT_MODIFIER_NUM
,DATE_FORMAT(DATE_FORMAT(DEMOG_RESCHEDULE.ACCT_DEMOGRAPHIC_VAL ,'yyyyMMdd') ,'yyyy-MM-dd') AS RESCHEDULE_DATE
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS DEMOG_RESCHEDULE
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
ON BD.BUSINESSDATE BETWEEN DEMOG_RESCHEDULE.START_DT AND DEMOG_RESCHEDULE.END_DT
AND DEMOG_RESCHEDULE.RECORD_DELETED_FLAG = 0
AND DEMOG_RESCHEDULE.DEMOG_CD = 4800  --Reschedule Date 
AND DEMOG_RESCHEDULE.DATA_SOURCE_CD = 1357 --AM 
AND DEMOG_RESCHEDULE.CTL_ID = '004' --ALS
AND DEMOG_RESCHEDULE.ACCT_DEMOGRAPHIC_VAL <> '00000000' 
) AS  DEMOG_RESCHEDULE
ON ESL_AGMT.ACCOUNT_NUM = DEMOG_RESCHEDULE.ACCOUNT_NUM
AND ESL_AGMT.ACCOUNT_MODIFIER_NUM = DEMOG_RESCHEDULE.ACCOUNT_MODIFIER_NUM 
    
WHERE ACCDEMO_CTL3.ALS_CTL3  IN ('473','478','496') 
AND DEM_TDR_PDR.TDR_PDR_FLAG = 'RL'
AND DEMOG_RESCHEDULE.RESCHEDULE_DATE IS NOT NULL)
WHERE R = 1


UNION ALL 
  
  SELECT
  ACCOUNT_NUM
  ,ACCOUNT_MODIFIER_NUM
  ,RL_CHG_BRANCH --Support branch change case
  ,RESCHEDULE_DATE
  ,BASE_ACCT_NUM
  ,ALS_CTL3
  ,TDR_PDR_FLAG
  ,ACTION_CODE
  FROM
  (SELECT
     ESL_AGMT.ACCOUNT_NUM AS ACCOUNT_NUM
    ,ESL_AGMT.ACCOUNT_MODIFIER_NUM AS ACCOUNT_MODIFIER_NUM
    ,SUBSTR(ESL_AGMT.ACCOUNT_NUM,1,8)||SUBSTR(ESL_AGMT.ACCOUNT_NUM,13) AS RL_CHG_BRANCH --Support branch change case
 ,DATE_FORMAT(ACCT_FEAT.START_SKIP_DATE ,'yyyy-MM-dd') AS RESCHEDULE_DATE
    ,ESL_AGMT.BASE_ACCT_NUM AS BASE_ACCT_NUM
    ,ACCDEMO_CTL3.ALS_CTL3 AS ALS_CTL3
 ,DEM_TDR_PDR.TDR_PDR_FLAG AS TDR_PDR_FLAG
 ,ACCT_FEAT.ACTION_CODE  AS ACTION_CODE
 ,RANK () OVER (PARTITION BY ESL_AGMT.ACCOUNT_NUM ORDER BY ACCT_FEAT.START_SKIP_DATE  DESC) AS R

 FROM
 (
     SELECT 
  BD.BUSINESSDATE
     ,S_ESL_AGMT.ACCOUNT_NUM
     ,S_ESL_AGMT.ACCOUNT_MODIFIER_NUM
     ,S_ESL_AGMT.BASE_ACCT_NUM
     
     FROM P1VTTEDW.EDW_AGREEMENT_INFO AS S_ESL_AGMT
     
     INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
     ON S_ESL_AGMT.AS_OF_DT = BUSINESSDATE
     AND S_ESL_AGMT.AGMT_CTL_ID ='004'
     AND S_ESL_AGMT.AGMT_LEVEL_CD  IN (1,2,3) /* Consider only Master accounts (Refer CS001966) */
     AND S_ESL_AGMT.ACTIVE_IND = '01' /* Get only Active Account */
 ) AS ESL_AGMT

INNER  JOIN 
(
SELECT  ACCDEMO.ACCOUNT_NUM, ACCDEMO.ACCOUNT_MODIFIER_NUM,  ACCDEMO.ACCT_DEMOGRAPHIC_VAL AS ALS_CTL3
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS ACCDEMO
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
 ON BD.BUSINESSDATE BETWEEN ACCDEMO.START_DT AND ACCDEMO.END_DT
 AND ACCDEMO.RECORD_DELETED_FLAG = 0
 AND ACCDEMO.DEMOG_CD = 121 --ALS CTL3
 AND ACCDEMO.DATA_SOURCE_CD = 1357
 AND ACCDEMO.CTL_ID = '004'     
)
AS  ACCDEMO_CTL3
ON ACCDEMO_CTL3.ACCOUNT_NUM = ESL_AGMT.ACCOUNT_NUM
AND ACCDEMO_CTL3.ACCOUNT_MODIFIER_NUM = ESL_AGMT.ACCOUNT_MODIFIER_NUM
 
LEFT  JOIN 
(
SELECT  DEM_TDR_PDR.ACCOUNT_NUM , DEM_TDR_PDR.ACCOUNT_MODIFIER_NUM , M10704_01.SOURCE_KEY AS TDR_PDR_FLAG
FROM P1VTTEDW.ACCOUNT_DEMOGRAPHIC AS DEM_TDR_PDR
INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
 ON BD.BUSINESSDATE BETWEEN DEM_TDR_PDR.START_DT AND DEM_TDR_PDR.END_DT
 AND DEM_TDR_PDR.RECORD_DELETED_FLAG = 0
 AND DEM_TDR_PDR.DEMOG_CD = 287 --TDR FLAG
 AND DEM_TDR_PDR.CTL_ID = '004'     
  
 LEFT OUTER JOIN P1VUTEDW.M10704_AGREE_DEMOG_VAL AS  M10704_01
 ON DEM_TDR_PDR.DEMOG_VALUE_CD = M10704_01.EDW_CODE
 AND M10704_01.SRC_CTL_ID = '004'
 AND M10704_01.SOURCE_ID = '1'
 
 ) AS DEM_TDR_PDR
    ON ESL_AGMT.ACCOUNT_NUM = DEM_TDR_PDR.ACCOUNT_NUM
  AND ESL_AGMT.ACCOUNT_MODIFIER_NUM = DEM_TDR_PDR.ACCOUNT_MODIFIER_NUM
  
  LEFT OUTER JOIN 
   (
   SELECT 
   AF.ACCOUNT_NUM
   ,AF.ACCOUNT_MODIFIER_NUM
 ,AF.ACCOUNT_FEATURE_START_DT AS  START_SKIP_DATE
   ,AF.ACCOUNT_FEATURE_TXT AS ACTION_CODE

 FROM P1VTTEDW.ACCOUNT_FEATURE AS AF
 
  INNER JOIN P1VTPLLFP.VLLFP_BUSINESSDATE_M AS BD
  ON BD.BUSINESSDATE BETWEEN AF.START_DT AND AF.END_DT
   AND AF.RECORD_DELETED_FLAG = 0 
   AND AF.CTL_ID = '004'
   AND AF.ACCOUNT_FEATURE_ROLE_CD = 508        -- Action Code
  
 INNER JOIN P1VUTEDW.BKEY_FEATURE AS BK_FEAT
 ON BK_FEAT.EDW_KEY = AF.FEATURE_ID
  AND BK_FEAT.SOURCE_KEY = '3_1_Campaign Code_'  
  
) AS ACCT_FEAT
ON ACCT_FEAT.ACCOUNT_NUM = ESL_AGMT.ACCOUNT_NUM
AND ACCT_FEAT.ACCOUNT_MODIFIER_NUM = ESL_AGMT.ACCOUNT_MODIFIER_NUM

WHERE ACCDEMO_CTL3.ALS_CTL3 = '497'
AND  (DEM_TDR_PDR.TDR_PDR_FLAG IN ( 'RL' ,'R2' )   OR  substr(ACCT_FEAT.ACTION_CODE,1,3) = 'IRL' ) 
AND ACCT_FEAT.START_SKIP_DATE NOT IN (DATE '1000-01-01',DATE '1000-01-02',DATE '1000-01-03',DATE '1000-01-04')
AND ACCT_FEAT.START_SKIP_DATE IS NOT NULL )
WHERE R = 1

 
) AS MAIN_RL

  --END : 

)AS FIN_RL
